// =============================================================
// allocMatrix.h — Fake R API: allocMatrix
// Original R header: Rinternals.h
// Category: C — Allocation or Memory Function
// Auto-generated by generate-r-extern-fake-header agent.
//
// allocMatrix is declared in Rinternals.h as:
//   SEXP Rf_allocMatrix(SEXPTYPE type, int nrow, int ncol);
// and exposed to package source via the macro alias (line 893):
//   #define allocMatrix    Rf_allocMatrix
//
// It allocates a two-dimensional R matrix object: a heap-managed SEXPREC
// node whose data field points to a flat, column-major buffer of
// nrow * ncol elements of the scalar type indicated by the SEXPTYPE
// argument (REALSXP => double, INTSXP => int).
//
// Observed usage in rpart source (all six CSV rows):
//
//   rpart.c:241  cptable3 = PROTECT(allocMatrix(REALSXP, xvals > 1 ? 5 : 3, rp.num_unique_cp));
//   rpart.c:261  dnode3   = PROTECT(allocMatrix(REALSXP, nodecount, (3 + rp.num_resp)));
//   rpart.c:269  dsplit3  = PROTECT(allocMatrix(REALSXP, splitcount, 3));
//   rpart.c:278  inode3   = PROTECT(allocMatrix(INTSXP,  nodecount, 6));
//   rpart.c:285  isplit3  = PROTECT(allocMatrix(INTSXP,  splitcount, 3));
//   rpart.c:293  csplit3  = PROTECT(allocMatrix(INTSXP,  catcount, maxcat));
//
// All six call sites are in the return-value construction block of rpart()
// (lines 239-305).  Each result is immediately passed to PROTECT (a no-op
// identity in the fake runtime) and then accessed via REAL() or INTEGER()
// for column-major pointer setup.
//
// The full implementation is provided by INTSXP.h (guard
// FAKE_ALLOCMATRIX_DEFINED), which also supplies:
//   - SEXPREC struct, SEXP typedef
//   - sexptype_element_size(SEXPTYPE)
//   - allocVector / Rf_allocVector
//   - allocMatrix / Rf_allocMatrix
//   - INTEGER / REAL / LOGICAL / RAW accessor inlines
//   - PROTECT / UNPROTECT / UNPROTECT_PTR no-ops
//   - LENGTH / nrows / ncols
//   - free_sexp()
//   - RError (C++ exception replacing longjmp)
//
// This header is a thin wrapper that (a) pulls in all dependencies in the
// correct order, (b) verifies the allocMatrix definitions are live, and
// (c) preserves the exact #define alias from the original Rinternals.h.
//
// Integration Requirements (allocMatrix.md Section 5):
//   - SEXP.h       : SEXPREC layout, free_sexp_deep, R_NilValue, etc.
//   - INTSXP.h     : SEXPTYPE block, allocVector, allocMatrix,
//                    INTEGER/REAL, PROTECT/UNPROTECT, sexptype_element_size
//   - REALSXP.h    : REALSXP==14 constant (3 of 6 call sites use REALSXP)
//   - PROTECT.h    : PROTECT_INDEX, R_ProtectWithIndex, R_Reprotect
//   - fake_arena.h : ArenaFrame RAII guard (not yet present in output_folder)
// =============================================================
#pragma once

#ifndef FAKE_ALLOCMATRIX_H
#define FAKE_ALLOCMATRIX_H

// --- Standard library includes ---
#include <stdlib.h>    // malloc, free, size_t
#include <string.h>    // memset
#include <stddef.h>    // NULL, size_t
#include <stdexcept>   // std::runtime_error
#include <string>      // std::string

// --- Fake R header dependencies ---
// (from Integration Requirements in allocMatrix.md)
//
// WARNING: dependency fake_arena.h not found in output_folder.
// The .Call wrapper for rpart() must declare `ArenaFrame _frame;` as its
// first statement once fake_arena.h is available — see ArenaFrame usage
// block at the bottom of this file.
//
// #include "fake_arena.h"

// INTSXP.h provides the complete foundation:
//   - SEXPTYPE typedef and full constant block (INTSXP=13, REALSXP=14, ...)
//   - SEXPREC struct and SEXP typedef
//   - sexptype_element_size(SEXPTYPE)
//   - allocVector / Rf_allocVector (FAKE_ALLOCVECTOR_DEFINED guard)
//   - allocMatrix / Rf_allocMatrix (FAKE_ALLOCMATRIX_DEFINED guard)
//   - INTEGER / REAL / LOGICAL / RAW accessors (FAKE_ACCESSORS_DEFINED guard)
//   - PROTECT / UNPROTECT / UNPROTECT_PTR no-ops (FAKE_PROTECT_DEFINED guard)
//   - LENGTH / Rf_length (FAKE_LENGTH_DEFINED guard)
//   - Rf_nrows / Rf_ncols (FAKE_NROWS_NCOLS_DEFINED guard)
//   - free_sexp() (FAKE_FREE_SEXP_DEFINED guard)
//   - RError (FAKE_R_RERROR_DEFINED guard)
#include "INTSXP.h"

// REALSXP.h: pulls in INTSXP.h transitively and adds a compile-time
// assertion that REALSXP==14.  Three of the six allocMatrix call sites
// pass REALSXP as the type argument.
#include "REALSXP.h"

// PROTECT.h: adds PROTECT_INDEX typedef and correct two-argument forms of
// PROTECT_WITH_INDEX(x,i) / REPROTECT(x,i) matching Rinternals.h lines
// 396-398.  The allocMatrix results at lines 241,261,269,278,285,293 are
// all wrapped in PROTECT; these macros must be in scope.
#include "PROTECT.h"

// SEXP.h: adds XLENGTH, TYPEOF, scalar coercions (asInteger/asReal),
// CHAR/mkChar, VECTOR_ELT/SET_VECTOR_ELT, type predicates (isReal/isInteger),
// R_NilValue, R_UnboundValue, R_NamesSymbol, PRINTNAME, setAttrib/getAttrib,
// free_sexp_deep, and R_ProtectWithIndex / R_Reprotect extended forms.
// Note: SEXP.h includes INTSXP.h internally, so there is no double-inclusion
// risk thanks to the FAKE_INTSXP_H and FAKE_SEXP_H include guards.
#include "SEXP.h"

// ---------------------------------------------------------------------------
// Core fake implementation — allocMatrix
//
// The implementation lives in INTSXP.h under the FAKE_ALLOCMATRIX_DEFINED
// guard.  It is reproduced here in comments for documentation and reference.
//
// Pattern 1: 2-D REALSXP matrix (rpart.c:241, 261, 269)
//   allocMatrix(REALSXP, nrow, ncol) produces SEXPREC with:
//     s->type   = REALSXP (14)
//     s->length = nrow * ncol
//     s->nrow   = nrow    (column j starts at REAL(s) + j * nrow)
//     s->ncol   = ncol
//     s->data   = double[nrow * ncol], zero-initialized via memset
//   REAL(s) returns (double *) s->data; pointer arithmetic dptr += nrow
//   advances one full column (column-major layout).
//
// Pattern 2: 2-D INTSXP matrix (rpart.c:278, 285, 293)
//   allocMatrix(INTSXP, nrow, ncol) produces SEXPREC with:
//     s->type   = INTSXP (13)
//     s->length = nrow * ncol
//     s->nrow   = nrow    (column j starts at INTEGER(s) + j * nrow)
//     s->ncol   = ncol
//     s->data   = int[nrow * ncol], zero-initialized via memset
//   INTEGER(s) returns (int *) s->data.  The zero-fill loop in rpart.c:299-300
//   is redundant with the memset but compiles and runs correctly.
//
// Both patterns share the same inline Rf_allocMatrix function (from INTSXP.h):
//
//   inline SEXP allocMatrix(SEXPTYPE type, int nrow, int ncol) {
//       SEXP s = allocVector(type, nrow * ncol);
//       s->nrow = nrow;
//       s->ncol = ncol;
//       return s;
//   }
//   inline SEXP Rf_allocMatrix(SEXPTYPE type, int nrow, int ncol) {
//       return allocMatrix(type, nrow, ncol);
//   }
//
// Invariant 1 (C++ exception-based errors): allocVector throws RError (a
// std::runtime_error subclass) on malloc failure.  If the SEXPREC node
// allocation fails, RError is thrown immediately.  If the data buffer
// allocation fails, the node is freed before RError is thrown.  No
// partial SEXP objects remain after a throw.
//
// Invariant 2 (arena-backed memory without source modification): The SEXPREC
// node and data buffer are heap-allocated via malloc() inside allocVector,
// NOT arena-managed.  This is correct because all six allocMatrix results in
// rpart() are output components packed into rlist via SET_VECTOR_ELT and
// returned to Python.  They must outlive the ArenaFrame RAII guard that
// governs ALLOC / R_alloc scratch arrays.  The ArenaFrame destructor at
// .Call wrapper return does not free heap-allocated SEXPs.
//
// Invariant 3 (Python function-pointer bridges): Not applicable.
// allocMatrix is not an R Interpreter Item.
//
// Memory lifecycle:
//   SEXPREC node + data buffer   malloc() in allocVector    Python: free_sexp()
//   Column-pointer scratch arrays arena via ALLOC/R_alloc   ArenaFrame destructor
//
// Source context note (rpart.c:292-301): csplit3 is conditionally allocated
// only when catcount > 0; it remains R_NilValue when catcount == 0.  The fake
// runtime handles this naturally — allocMatrix is simply not called.  If
// catcount > 0, allocMatrix(INTSXP, catcount, maxcat) allocates
// catcount * maxcat * sizeof(int) bytes.  The zero-fill at lines 299-300
// is safe (writes zeros into an already-zeroed buffer from memset).
// ---------------------------------------------------------------------------

// Compile-time verification: confirm that INTSXP.h's allocMatrix definitions
// are present.  If FAKE_ALLOCMATRIX_DEFINED is not set at this point,
// something went wrong with the include order.
#ifndef FAKE_ALLOCMATRIX_DEFINED
#error "allocMatrix.h: FAKE_ALLOCMATRIX_DEFINED not set after including INTSXP.h. \
Check that INTSXP.h was not stripped or conditionally excluded."
#endif

// --- Compatibility aliases (preserve original R API names) ---
//
// Original Rinternals.h aliases (confirmed from real header inspection):
//
//   Line 506:  SEXP Rf_allocMatrix(SEXPTYPE, int, int);
//   Line 893:  #define allocMatrix    Rf_allocMatrix
//
// Both names are already provided as inline functions in INTSXP.h:
//   inline SEXP allocMatrix(SEXPTYPE type, int nrow, int ncol) { ... }
//   inline SEXP Rf_allocMatrix(SEXPTYPE type, int nrow, int ncol) { ... }
//
// The #define alias below replicates line 893 of the original Rinternals.h
// and is guarded with #ifndef to avoid a macro-vs-inline redefinition
// diagnostic if the alias was already emitted by INTSXP.h.
#ifndef allocMatrix
#define allocMatrix    Rf_allocMatrix
#endif

// --- ArenaFrame usage (Category C) ---
//
// allocMatrix itself is heap-based and does NOT use the arena.  However,
// the functions in rpart.c that call allocMatrix also call ALLOC / R_alloc
// for scratch pointer arrays (ddnode, ddsplit, iinode, iisplit, ccsplit,
// savesort, etc.) in the same function body.  Those scratch allocations ARE
// arena-managed via fake_arena.h.
//
// Declare `ArenaFrame _frame;` as the FIRST statement of any .Call-entry
// wrapper function that enters rpart() or any other function that interleaves
// allocMatrix calls with ALLOC / R_alloc calls.  Example:
//
//   extern "C" SEXP rpart_entry(
//           SEXP ncat2, SEXP method2, SEXP opt2, SEXP parms2,
//           SEXP xvals2, SEXP xgrp2, SEXP ymat2, SEXP xmat2,
//           SEXP wt2, SEXP ny2, SEXP cost2) {
//       ArenaFrame _frame;   // frees ddnode, ddsplit, iinode, iisplit,
//                            // ccsplit, savesort, and all other R_alloc/ALLOC
//                            // scratch arrays when the wrapper returns.
//       try {
//           return rpart(ncat2, method2, opt2, parms2, xvals2, xgrp2,
//                        ymat2, xmat2, wt2, ny2, cost2);
//       } catch (const RError &e) {
//           set_python_error(e.what());
//           return R_NilValue;
//       }
//   }
//
// The six allocMatrix results (cptable3, dnode3, dsplit3, inode3, isplit3,
// csplit3) are heap-allocated via malloc() inside allocVector and survive
// ArenaFrame destruction.  Python extracts their data via REAL() / INTEGER()
// into numpy arrays and then calls free_sexp() or free_sexp_deep() on the
// enclosing VECSXP (rlist) to release all SEXP memory.

#endif // FAKE_ALLOCMATRIX_H
