// =============================================================
// error.h — Fake R API: error
// Original R header: R_ext/Error.h
// Category: D — error, warning, and print functions
// Auto-generated by generate-r-extern-fake-header agent.
// =============================================================
//
// This header is a drop-in replacement for R_ext/Error.h.
// It provides:
//   - RError   : C++ exception class thrown in place of longjmp.
//   - Rf_error : [[noreturn]] inline function that formats a printf-style
//                message and throws RError (Invariant 1: no longjmp/abort).
//   - Rf_warning : inline function that writes a formatted message to stderr.
//   - UNIMPLEMENTED, WrongArgCount : [[noreturn]] stubs that throw RError.
//   - #define error   Rf_error      (from original R_ext/Error.h)
//   - #define warning Rf_warning    (from original R_ext/Error.h)
//   - #define _(x) (x)              (gettext pass-through, guarded)
//
// Dependency: Rprintf.h (provides R_PRINTF_FORMAT).
//
// Usage pattern confirmed in source files:
//   rpart.c:91       error(_("Invalid value for 'method'"));
//   rpart.c:203      error("%s", errmsg);
//   rpart_callback.c:24   error(_("variable '%s' not found"), CHAR(PRINTNAME(sym)));
//   rpart_callback.c:114  error(_("return value not a vector"));
//   rpart_callback.c:116  error(_("returned value is the wrong length"));
//   rpart_callback.c:148  error(_("the expression expr1 did not return a vector!"));
//   xpred.c:89       error(_("Invalid value for 'method'"));
// All call sites use the short-form alias; no call site uses Rf_error directly.
// =============================================================

#pragma once

#ifndef FAKE_R_ERROR_H
#define FAKE_R_ERROR_H

// --- Standard library includes ---
#include <cstdarg>    // std::va_list, va_start, va_end
#include <cstdio>     // std::vsnprintf, std::fprintf, stderr
#include <stdexcept>  // std::runtime_error
#include <string>     // std::string

// --- Fake R header dependencies ---
// (from Integration Requirements in error.md)
// Rprintf.h provides R_PRINTF_FORMAT(M,N); must precede Rf_error declaration.
#include "Rprintf.h"

// --- RError exception class ---
//
// Defined once per translation unit; all Category D fakes that throw re-use
// this class. The guard prevents duplicate definitions when multiple fake
// headers are included in the same translation unit (e.g., via fake_R.h).
//
// All .Call boundary wrappers must catch (const RError &) and convert the
// message into a Python exception. Example boundary wrapper:
//
//   extern "C" int call_rpart(...) {
//       ArenaFrame _frame;
//       try {
//           rpart(...);
//           return 0;
//       } catch (const RError &e) {
//           set_last_error(e.what());
//           return -1;
//       }
//   }
#ifndef FAKE_R_RERROR_DEFINED
#define FAKE_R_RERROR_DEFINED
struct RError : public std::runtime_error {
    using std::runtime_error::runtime_error;
};
#endif /* FAKE_R_RERROR_DEFINED */

// --- Core fake implementation ---

// -----------------------------------------------------------------------
// Rf_error — formats a printf-style message, then throws RError.
//
// Covers patterns P1, P2, P3 from the Markdown guide:
//   P1: Literal string, no format arguments
//       error(_("Invalid value for 'method'"))      [rpart.c:91, xpred.c:89]
//       error(_("return value not a vector"))       [rpart_callback.c:114]
//       error(_("returned value is the wrong length")) [rpart_callback.c:116]
//       error(_("the expression expr1 did not return a vector!")) [rpart_callback.c:148]
//   P2: %s format with const char * argument
//       error("%s", errmsg)                         [rpart.c:203]
//       error(_("variable '%s' not found"), CHAR(PRINTNAME(sym))) [rpart_callback.c:24]
//   P3: Integer %d format arguments
//       error("... %d ... %d ...", j, 2*(n-1))      [rpart_callback.c:158]
//
// [[noreturn]] is preserved from the real R_ext/Error.h declaration. This
// attribute is load-bearing: call sites like:
//   } else
//       error(_("Invalid value for 'method'"));
// rely on the compiler knowing the else-branch never falls through, which
// suppresses spurious "control reaches end of non-void function" warnings.
//
// Buffer size: 4096 bytes is sufficient for all observed rpart messages.
// Messages exceeding 4095 bytes are silently truncated at the null terminator
// (std::vsnprintf guarantees null-termination within the buffer size).
// -----------------------------------------------------------------------
#ifndef FAKE_RF_ERROR_DEFINED
#define FAKE_RF_ERROR_DEFINED
[[noreturn]] inline void Rf_error(const char *fmt, ...) {
    char buf[4096];
    std::va_list args;
    va_start(args, fmt);
    std::vsnprintf(buf, sizeof(buf), fmt, args);
    va_end(args);
    throw RError(buf);
}
#endif // FAKE_RF_ERROR_DEFINED

// -----------------------------------------------------------------------
// Rf_warning — formats a printf-style message and writes to stderr.
//
// Per Invariant 1, warnings do NOT throw; they write to stderr only.
// This matches the behaviour of the original Rf_warning which routes to R's
// warning-message device. In the fake runtime, stderr is the substitute.
//
// Not directly called by rpart source files in the CSV, but declared in
// R_ext/Error.h and required to avoid link errors from translation units
// that include fake_R.h and use the warning() alias.
// -----------------------------------------------------------------------
inline void Rf_warning(const char *fmt, ...) {
    char buf[4096];
    std::va_list args;
    va_start(args, fmt);
    std::vsnprintf(buf, sizeof(buf), fmt, args);
    va_end(args);
    std::fprintf(stderr, "Warning: %s\n", buf);
}
#define FAKE_RF_WARNING_DEFINED

// -----------------------------------------------------------------------
// UNIMPLEMENTED — declared [[noreturn]] in R_ext/Error.h.
//
// In the real R runtime, calls R's error machinery with "not implemented".
// In the fake runtime, throws RError with a descriptive message.
// -----------------------------------------------------------------------
[[noreturn]] inline void UNIMPLEMENTED(const char *msg) {
    throw RError(std::string("UNIMPLEMENTED: ") + msg);
}

// -----------------------------------------------------------------------
// WrongArgCount — declared [[noreturn]] in R_ext/Error.h.
//
// In the real R runtime, signals a wrong-argument-count error.
// In the fake runtime, throws RError with a descriptive message.
// -----------------------------------------------------------------------
[[noreturn]] inline void WrongArgCount(const char *msg) {
    throw RError(std::string("WrongArgCount: ") + msg);
}

// --- Compatibility aliases (preserve original R API names) ---
//
// These aliases exactly reproduce the #define block in the original
// R_ext/Error.h (under the #ifndef R_NO_REMAP guard). Every call site in
// rpart source files uses the short form error(...) rather than Rf_error(...),
// so these aliases are required for all seven CSV call sites to compile.
//
// Original R_ext/Error.h:
//   #ifndef R_NO_REMAP
//   #define error   Rf_error
//   #define warning Rf_warning
//   #endif
#ifndef R_NO_REMAP
#  define error   Rf_error
#  define warning Rf_warning
#endif

// -----------------------------------------------------------------------
// _() — gettext pass-through macro.
//
// rpart.c and rpart_callback.c define the _() macro as:
//   #ifdef ENABLE_NLS
//   #  define _(String) dgettext("rpart", String)
//   #else
//   #  define _(String) (String)
//   #endif
//
// In a standalone fake build, ENABLE_NLS is not defined, so the source
// files already define _(x) as (x) before including any R headers. The
// guard below prevents a redefinition conflict in the event that this fake
// header is transitively included before the source file's own definition
// fires (e.g., when included via fake_R.h before the file-level #define).
//
// In an NLS-enabled build the dgettext definition takes precedence and the
// fake's definition is suppressed by the #ifndef guard.
// -----------------------------------------------------------------------
#ifndef _
#  define _(x) (x)
#endif

#endif /* FAKE_R_ERROR_H */
