// =============================================================
// fake_R.h — Master entry-point fake R API header
// Auto-generated by generate-r-extern-fake-headers skill.
//
// PURPOSE
// -------
// Drop-in replacement for all R C API headers used by the rpart package
// source files (init.c, rpart.c, xpred.c, pred_rpart.c, rpartexp2.c,
// rpart_callback.c, rundown.c, rundown2.c).  Enables the original C source
// files to compile and link WITHOUT linking against libR.so.
//
// REAL R HEADERS REPLACED
// -----------------------
//   Rinternals.h          — SEXP, SEXPREC, allocVector, allocMatrix,
//                           INTEGER, REAL, LOGICAL, RAW, LENGTH, nrows,
//                           ncols, CHAR, R_CHAR, mkChar, PRINTNAME,
//                           VECTOR_ELT, SET_VECTOR_ELT, STRING_ELT,
//                           SET_STRING_ELT, isReal, isInteger, isNull,
//                           asInteger, asReal, PROTECT, UNPROTECT,
//                           R_NilValue, R_UnboundValue, R_NamesSymbol,
//                           setAttrib, getAttrib, findVar, findVarInFrame,
//                           install, eval, FALSE, TRUE, Rboolean
//   R_ext/Rdynload.h      — DL_FUNC, DllInfo, R_CallMethodDef,
//                           R_registerRoutines, R_useDynamicSymbols,
//                           R_forceSymbols
//   R_ext/Error.h         — error/Rf_error (throws RError), warning,
//                           Rf_warning, _(x) NLS passthrough
//   R_ext/Memory.h        — R_alloc, S_alloc, S_realloc, vmaxget, vmaxset,
//                           R_gc, R_gc_running
//   R_ext/RS.h            — R_Calloc, R_Realloc, R_Free, R_chk_calloc,
//                           R_chk_realloc, R_chk_free, Memcpy, Memzero,
//                           CallocCharBuf
//   R_ext/Arith.h         — ISNAN, R_FINITE, R_IsNA, R_IsNaN, NA_REAL,
//                           R_isnancpp, R_INFINITE
//   R_ext/Utils.h         — R_CheckUserInterrupt
//   Rversion.h            — R_Version macro, R_VERSION (=R_Version(4,4,0)),
//                           R_MAJOR, R_MINOR, R_YEAR, R_SVN_REVISION
//   R_ext/Boolean.h       — Rboolean, FALSE=0, TRUE=1
//   R_ext/Print.h         — Rprintf, REprintf, Rvprintf, REvprintf
//
// USAGE
// -----
// In each rpart package C source file, replace all R header includes with:
//
//   #include "fake_R.h"
//
// fake_R.h must be the FIRST include in every source file (before any C
// standard headers) because it pulls in standard headers internally.
//
// PREREQUISITES
// -------------
// fake_arena.h  — Arena allocator (ArenaFrame RAII guard, arena_alloc,
//                 arena_calloc).  Must be present in the same directory as
//                 fake_R.h.  NOT auto-generated by this tool; provide it
//                 separately.  Required by R_alloc.h at runtime; fake_R.h
//                 includes it unconditionally so the build fails early if
//                 it is missing.
//
// PYTHON INTEGRATION (Category E items — R Interpreter stubs)
// -----------------------------------------------------------
// The following items require Python-registered function pointer callbacks
// before calling rpart source functions that use them (method=4 / user-
// defined splits only; standard rpart methods 1-3 do not need registration):
//
//   register_install_fn(fn)         — install() stub    (R_getVar.h)
//   register_findVar_fn(fn)         — findVar() stub    (R_getVar.h)
//   register_findVarInFrame_fn(fn)  — findVarInFrame()  (R_getVar.h)
//   register_eval_fn(fn)            — eval() stub       (eval.h)
//   request_user_interrupt()        — interrupt signal  (R_CheckUserInterrupt.h)
//   get_R_UnboundValue()            — unbound sentinel  (R_UnboundValue.h)
//
// VERSION
// -------
// R_VERSION is set to R_Version(4,4,0) = 263168.  This satisfies:
//   R_VERSION >= R_Version(2,16,0)  -> R_forceSymbols branch in init.c
//   R_VERSION <  R_Version(4, 5,0)  -> compat_getVar macro in rpart_callback.c
//
// KNOWN CONFLICTS / NOTES
// ----------------------
// - R_getVar.h is included before install.h so R_getVar.h's function pointer
//   bridge variant of Rf_install is active (throws if g_install_fn is null).
//   install.h's hash-map utilities (create_symbol, call_install) are still
//   available as parallel helpers for pre-populating _frame_registry.
//   To use the hash-map-primary Rf_install variant, include install.h first.
//
// =============================================================
#pragma once

#ifndef FAKE_R_H
#define FAKE_R_H

// --- Arena allocator (MUST be first) ---
//
// fake_arena.h provides:
//   - ArenaFrame  : RAII guard; declare at .Call boundary wrapper entry
//   - arena_alloc : replaces R_alloc / ALLOC in the fake runtime
//   - arena_calloc: zero-initialised arena allocation
//
// All .Call entry-point wrappers must begin with:
//   ArenaFrame _frame;
// to ensure that all arena-managed scratch memory (R_alloc / ALLOC) is
// freed when the wrapper returns or throws.
//
// NOTE: fake_arena.h is NOT auto-generated by this tool.  It must be
// present in the same directory as fake_R.h before compiling rpart sources.
#include "fake_arena.h"

// ============================================================
// FOUNDATIONAL TYPES AND CONSTANTS
// ============================================================

// DL_FUNC.h — function pointer typedef, Rboolean, R_CallMethodDef, DllInfo,
//              R_registerRoutines, R_useDynamicSymbols, R_forceSymbols no-ops
#include "DL_FUNC.h"

// DllInfo.h — C-compatible DllInfo typedef (thin wrapper over DL_FUNC.h)
#include "DllInfo.h"

// INTSXP.h — SEXPTYPE typedef, 25 SEXPTYPE constants (NILSXP=0..FUNSXP=99),
//             SEXPREC struct, SEXP typedef, allocVector/allocMatrix,
//             INTEGER/REAL/LOGICAL/RAW accessors, LENGTH, nrows/ncols,
//             PROTECT/UNPROTECT (no-ops), RError struct
#include "INTSXP.h"

// REALSXP.h — includes INTSXP.h; adds static_assert(REALSXP==14)
#include "REALSXP.h"

// R_CallMethodDef.h — includes DllInfo.h; adds Rversion.h fake inline
#include "R_CallMethodDef.h"

// Rboolean.h — #undef FALSE/TRUE; typedef enum {FALSE=0,TRUE=1} Rboolean
#include "Rboolean.h"

// ============================================================
// SEXP INFRASTRUCTURE AND STRING TYPES
// ============================================================

// SEXP.h — adds on top of INTSXP.h: asInteger, asReal, asLogical,
//           R_CHAR/CHAR, mkChar/Rf_mkChar, VECTOR_ELT, SET_VECTOR_ELT,
//           STRING_ELT, SET_STRING_ELT, isReal, isInteger, isNull,
//           R_NilValue, R_UnboundValue, R_NamesSymbol, PRINTNAME,
//           setAttrib/getAttrib (no-ops), free_sexp_deep
#include "SEXP.h"

// STRSXP.h — includes SEXP.h; adds R_BlankString/R_BlankScalarString,
//             mkCharCE/mkCharLen/mkCharLenCE/mkString, cetype_t typedef
#include "STRSXP.h"

// VECSXP.h — thin wrapper on STRSXP.h + REALSXP.h;
//             static_assert(VECSXP==19)
#include "VECSXP.h"

// ============================================================
// BOOLEAN ALIASES
// ============================================================

// FALSE.h — delegates to Rboolean.h
#include "FALSE.h"

// TRUE.h — delegates to Rboolean.h
#include "TRUE.h"

// ============================================================
// SENTINEL VALUES
// ============================================================

// R_NamesSymbol.h — includes SEXP.h; safety-net for R_NamesSymbol sentinel
#include "R_NamesSymbol.h"

// R_NilValue.h — includes SEXP.h; adds error_return/errorcall_return macros
#include "R_NilValue.h"

// R_UnboundValue.h — includes SEXP.h + R_NilValue.h;
//                    get_R_UnboundValue() C-linkage accessor for Python ctypes
#include "R_UnboundValue.h"

// ============================================================
// VERSION
// ============================================================

// R_VERSION.h — #define R_Version(v,p,s) and R_VERSION = R_Version(4,4,0)
#include "R_VERSION.h"

// ============================================================
// CHAR / STRING ACCESSORS
// ============================================================

// CHAR.h — R_CHAR inline + #define CHAR(x) R_CHAR(x);
//           translateChar/translateCharUTF8 stubs
#include "CHAR.h"

// PRINTNAME.h — safety-net fallback for PRINTNAME (already in SEXP.h)
#include "PRINTNAME.h"

// ============================================================
// VECTOR ACCESSORS
// ============================================================

// INTEGER.h — adds INTEGER_RO, INTEGER_OR_NULL
#include "INTEGER.h"

// REAL.h — adds REAL_RO, REAL0, REAL_ELT, SET_REAL_ELT
#include "REAL.h"

// LENGTH.h — adds R_xlen_t, XLENGTH, SETLENGTH, TRUELENGTH, LENGTH_EX
#include "LENGTH.h"

// ============================================================
// MEMORY PROTECTION
// ============================================================

// PROTECT.h — PROTECT_INDEX typedef, R_ProtectWithIndex/R_Reprotect (no-ops),
//              PROTECT_WITH_INDEX, REPROTECT macros
#include "PROTECT.h"

// UNPROTECT.h — adds unprotect/unprotect_ptr aliases
#include "UNPROTECT.h"

// ============================================================
// ARITHMETIC / NaN / FINITE CHECKS
// ============================================================

// ISNAN.h — R_isnancpp, R_FINITE, NA_REAL, R_IsNA, R_IsNaN, ISNAN macro
#include "ISNAN.h"

// R_FINITE.h — thin wrapper delegating to ISNAN.h
#include "R_FINITE.h"

// ============================================================
// USER INTERRUPT
// ============================================================

// R_CheckUserInterrupt.h — thread_local interrupt flag,
//                          request_user_interrupt(), R_CheckUserInterrupt()
#include "R_CheckUserInterrupt.h"

// ============================================================
// MEMORY MANAGEMENT (ARENA + HEAP)
// ============================================================

// R_Free.h — R_chk_calloc/realloc/free; #define R_Free(p) macro;
//             R_Calloc, R_Realloc, Memcpy, Memzero, CallocCharBuf
#include "R_Free.h"

// R_chk_calloc.h — thin wrapper delegating to R_Free.h
#include "R_chk_calloc.h"

// R_alloc.h — R_alloc (arena_alloc), S_alloc, S_realloc,
//              vmaxget/vmaxset (no-ops), R_gc/R_gc_running (no-ops)
//              WARNING: requires fake_arena.h (included above)
#include "R_alloc.h"

// ============================================================
// VERSION / DLL REGISTRATION
// ============================================================

// R_Version.h — #ifndef R_Version guard; includes R_VERSION.h, DllInfo.h
#include "R_Version.h"

// R_registerRoutines.h — R_registerRoutines no-op stub
#include "R_registerRoutines.h"

// R_useDynamicSymbols.h — R_useDynamicSymbols no-op stub
#include "R_useDynamicSymbols.h"

// R_forceSymbols.h — R_forceSymbols no-op stub
#include "R_forceSymbols.h"

// ============================================================
// PRINT FUNCTIONS
// ============================================================

// Rprintf.h — Rprintf/REprintf (delegate to std::vprintf/vfprintf);
//              Rvprintf/REvprintf; R_VA_LIST = std::va_list
#include "Rprintf.h"

// ============================================================
// ERROR / WARNING
// ============================================================

// error.h — RError struct, Rf_error (throws RError), Rf_warning (stderr),
//            #define _(x) (x) NLS passthrough,
//            #define error Rf_error, #define warning Rf_warning
#include "error.h"

// warning.h — safety-net wrapper; delegates to error.h for Rf_warning
#include "warning.h"

// ============================================================
// SET ELEMENT OPERATIONS
// ============================================================

// SET_STRING_ELT.h — safety-net for SET_STRING_ELT / STRING_ELT
#include "SET_STRING_ELT.h"

// SET_VECTOR_ELT.h — safety-net delegation
#include "SET_VECTOR_ELT.h"

// ============================================================
// ALLOCATION ALIASES
// ============================================================

// allocVector.h — adds Rf_allocVector3 stub; #define allocVector
#include "allocVector.h"

// allocMatrix.h — #define allocMatrix Rf_allocMatrix
#include "allocMatrix.h"

// ============================================================
// COERCION FUNCTIONS
// ============================================================

// asInteger.h — Rf_asInteger_coerce; #define asInteger
#include "asInteger.h"

// asReal.h — Rf_asReal_coerce; #define asReal
#include "asReal.h"

// ============================================================
// STRING / CHAR CONSTRUCTION
// ============================================================

// mkChar.h — safety-net fallbacks for Rf_mkChar family; includes STRSXP.h
#include "mkChar.h"

// ============================================================
// MATRIX DIMENSION ACCESSORS
// ============================================================

// ncols.h — safety-net for Rf_ncols/ncols
#include "ncols.h"

// nrows.h — includes ncols.h; safety-net for Rf_nrows/nrows
#include "nrows.h"

// ============================================================
// ATTRIBUTE OPERATIONS
// ============================================================

// setAttrib.h — safety-net for Rf_setAttrib/Rf_getAttrib (both no-ops)
#include "setAttrib.h"

// ============================================================
// TYPE PREDICATES
// ============================================================

// isReal.h — safety-net for Rf_isReal/isReal, Rf_isInteger/isInteger,
//             Rf_isNull/isNull
#include "isReal.h"

// ============================================================
// R INTERPRETER STUBS (CATEGORY E)
// ============================================================

// R_getVar.h — Category E: install/Rf_install (function pointer bridge),
//              findVar/Rf_findVar, findVarInFrame/Rf_findVarInFrame,
//              compat_getVar infrastructure, R_getVar stub (R>=4.5.0 path).
#include "R_getVar.h"

// findVar.h — Category E: delegates to R_getVar.h + Python registration guide
#include "findVar.h"

// findVarInFrame.h — Category E: delegates to findVar.h -> R_getVar.h
#include "findVarInFrame.h"

// install.h — Category E: includes R_getVar.h; adds hash-map symbol cache
//              utilities: create_symbol(), call_install(), clear_symbol_cache_c()
#include "install.h"

// eval.h — Category E: g_eval_fn pointer, register_eval_fn() extern "C",
//           Rf_eval stub (throws if callback not registered)
#include "eval.h"

// ============================================================
// SUMMARY
// ============================================================
//
// Original R headers replaced by fake_R.h:
//
//   Header                  External items faked
//   ─────────────────────── ────────────────────────────────────────
//   Rinternals.h            SEXP, SEXPREC, SEXPTYPE, INTSXP, REALSXP,
//                           VECSXP, STRSXP, CHARSXP, NILSXP, SYMSXP,
//                           allocVector, allocMatrix, INTEGER, REAL,
//                           LENGTH, nrows, ncols, CHAR, R_CHAR, mkChar
//                           (family), VECTOR_ELT, SET_VECTOR_ELT,
//                           STRING_ELT, SET_STRING_ELT, isReal, isInteger,
//                           isNull, asInteger, asReal, PROTECT, UNPROTECT,
//                           R_NilValue, R_UnboundValue, R_NamesSymbol,
//                           PRINTNAME, setAttrib, getAttrib, TYPEOF,
//                           eval, findVar, findVarInFrame, install,
//                           FALSE, TRUE, Rboolean
//   R_ext/Rdynload.h        DL_FUNC, DllInfo, R_CallMethodDef,
//                           R_registerRoutines, R_useDynamicSymbols,
//                           R_forceSymbols
//   R_ext/Error.h           error/Rf_error, warning/Rf_warning, _(x)
//   R_ext/Memory.h          R_alloc, S_alloc, S_realloc, vmaxget, vmaxset
//   R_ext/RS.h              R_Free, R_Calloc, R_Realloc, R_chk_calloc,
//                           Memcpy, Memzero, CallocCharBuf
//   R_ext/Arith.h           ISNAN, R_FINITE, R_IsNA, R_IsNaN, NA_REAL
//   R_ext/Utils.h           R_CheckUserInterrupt
//   Rversion.h              R_VERSION, R_Version macro
//   R_ext/Boolean.h         Rboolean, FALSE, TRUE
//   R_ext/Print.h           Rprintf, REprintf
//
// All 51 external items from r_extern_analysis/combined.csv were
// successfully generated.  No items were skipped.

#endif // FAKE_R_H
