// =============================================================
// findVarInFrame.h — Fake R API: findVarInFrame
// Original R header: Rinternals.h
// Category: E — R interpreter item
// Auto-generated by generate-r-extern-fake-header agent.
//
// findVarInFrame (Rf_findVarInFrame) requires a running R interpreter.
// It searches for a symbol binding in a single environment frame without
// walking parent frames.  Neither the environment frame data structure
// nor the symbol table exists outside of an initialized R runtime.
//
// In the fake build, findVarInFrame is implemented as a function pointer
// that Python registers via ctypes.CFUNCTYPE before invoking any .Call
// function that exercises the user-defined splitting code path (method=4).
//
// Original R declaration (Rinternals.h line 534):
//   SEXP Rf_findVarInFrame(SEXP, SEXP);
// Argument order: rho (environment) first, sym (symbol) second.
// This is the REVERSE of findVar(sym, rho) — argument order is load-bearing.
//
// Alias (Rinternals.h line 940):
//   #define findVarInFrame Rf_findVarInFrame
//
// Source usage context (rpart_callback.c:22):
//   SEXP val = inherits ? findVar(sym, rho) : findVarInFrame(rho, sym);
//   if (val == R_UnboundValue)
//     error(_("variable '%s' not found"), CHAR(PRINTNAME(sym)));
//
// Runtime note: In rpart source, all four R_getVar call sites in
// init_rpcallback (rpart_callback.c:59, 62, 65, 68) pass inherits=FALSE.
// Therefore findVarInFrame IS always called at runtime (critical path),
// while findVar (the inherits=TRUE branch) is NEVER reached.
// Registration of the Python callback for findVarInFrame is MANDATORY
// for the method=4 user-defined splits path to function.
//
// Co-implementation note (from findVarInFrame.md, Section 2):
//   findVar.md is the authoritative specification for findVar, and this
//   guide (findVarInFrame.md) is the authoritative specification for
//   findVarInFrame.  Because both names appear at the same call site
//   (rpart_callback.c:22), findVar.h co-implements both stubs together
//   under FAKE_FINDVAR_FN_DEFINED and FAKE_FINDVARINFRAME_FN_DEFINED guards.
//   This header delegates entirely to findVar.h rather than duplicating
//   the implementation, which would cause ODR violations and multiply-defined
//   symbol errors in a multi-translation-unit build.
//
// Dependency chain (findVarInFrame.md, Section 5):
//   SEXP.h (SEXPREC struct, SEXP typedef) — via findVar.h -> R_getVar.h
//   error.h (RError class, Rf_error) — via findVar.h -> R_getVar.h
//   R_UnboundValue.h (R_UnboundValue sentinel, get_R_UnboundValue) — via findVar.h
//   Rboolean.h (Rboolean, FALSE=0, TRUE=1) — via findVar.h -> R_getVar.h
//   CHAR.h (CHAR(SEXP) inline for compat_getVar error message) — via findVar.h
//   PRINTNAME.h (PRINTNAME(SEXP) inline) — via findVar.h
//   R_VERSION.h / R_Version.h (forces R_VERSION < R_Version(4,5,0)) — via findVar.h
//   findVar.h — provides Rf_findVarInFrame / g_findVarInFrame_fn /
//               register_findVarInFrame_fn and all parallel findVar stubs.
// =============================================================
#pragma once

#ifndef FAKE_R_FINDVARINFRAME_H
#define FAKE_R_FINDVARINFRAME_H

// --- Standard library includes ---
#include <stddef.h>    // NULL
#include <stdexcept>   // std::runtime_error (via RError, included through findVar.h)
#include <string>      // std::string (via RError)

// --- Fake R header dependencies ---
// (from Integration Requirements in findVarInFrame.md, Section 5)
//
// findVar.h is the authoritative provider of both the findVar and
// findVarInFrame stubs.  It includes R_getVar.h, which transitively pulls
// in SEXP.h, error.h, R_UnboundValue.h, Rboolean.h, CHAR.h, PRINTNAME.h,
// R_VERSION.h, and R_Version.h.
//
// The FAKE_FINDVARINFRAME_FN_DEFINED guard inside findVar.h ensures that
// Rf_findVarInFrame, g_findVarInFrame_fn, register_findVarInFrame_fn,
// findVarInFrame(), findVarInFrame3(), Rf_findVarInFrame3() are defined
// exactly once regardless of include order.
#include "findVar.h"

// *** R INTERPRETER ITEM — findVarInFrame ***
// A complete fake is impossible without an R interpreter.
// Register a Python callback via register_findVarInFrame_fn() before
// calling init_rpcallback() with method=4 (user-defined splits).
//
// Affected code paths:
//   rpart_callback.c:22 — false branch of:
//     SEXP val = inherits ? findVar(sym, rho) : findVarInFrame(rho, sym);
//   This branch is taken at ALL FOUR R_getVar call sites in init_rpcallback:
//     line 59: R_getVar(install("yback"), rho, FALSE)  -> ydata (double *)
//     line 62: R_getVar(install("wback"), rho, FALSE)  -> wdata (double *)
//     line 65: R_getVar(install("xback"), rho, FALSE)  -> xdata (double *)
//     line 68: R_getVar(install("nback"), rho, FALSE)  -> ndata (int *)
//
// The full implementation — Rf_findVarInFrame, findVarInFrame_fn_t,
// g_findVarInFrame_fn, register_findVarInFrame_fn, and the inline
// findVarInFrame() / findVarInFrame3() wrappers — is provided by
// findVar.h (included above) under the FAKE_FINDVARINFRAME_FN_DEFINED guard.
// No duplicate definitions are emitted here.

// --- Compatibility aliases (preserve original R API names) ---
//
// The following aliases from the original Rinternals.h are reproduced in
// findVar.h as inline wrapper functions (not macros):
//
//   Rinternals.h line 940: #define findVarInFrame  Rf_findVarInFrame
//   Rinternals.h line 941: #define findVarInFrame3 Rf_findVarInFrame3
//
// Both are satisfied by findVar.h's inline findVarInFrame() and
// findVarInFrame3() functions, which are defined inside
// FAKE_FINDVARINFRAME_FN_DEFINED and visible after including findVar.h.
// No additional #define macros are emitted here to avoid conflicts with
// the inline definitions already in scope.

// --- Python registration usage note (Category E) ---
//
// The Python-side ctypes registration workflow for findVarInFrame is
// documented in its entirety in findVar.h (the authoritative provider),
// which reproduces the full snippet from Section 4 of findVarInFrame.md.
//
// Summary of registration requirements for method=4:
//
//   1. register_install_fn(fn)          — mandatory; produces sym handles
//   2. register_findVarInFrame_fn(fn)   — MANDATORY; critical runtime path
//   3. register_findVar_fn(fn)          — optional (inherits=TRUE never reached)
//
// Argument order for the findVarInFrame callback (CFUNCTYPE argument 2 and 3):
//   ctypes.CFUNCTYPE(SEXP, SEXP, SEXP)   — return, rho, sym  (rho first)
//
// Argument order for the findVar callback (CFUNCTYPE argument 2 and 3):
//   ctypes.CFUNCTYPE(SEXP, SEXP, SEXP)   — return, sym, rho  (sym first)
//
// The reversed argument orders match Rinternals.h:533-534 and must not be
// confused.  See findVar.h for the full annotated ctypes code snippet.

// --- ArenaFrame usage ---
//
// findVarInFrame does not allocate arena memory.
// However, the .Call-entry wrapper for init_rpcallback (which calls
// compat_getVar, which calls findVarInFrame) must declare:
//
//   ArenaFrame _frame;
//
// as its first statement, because init_rpcallback shares its translation unit
// (rpart_callback.c) with rpart_callback1() and rpart_callback2(), which may
// invoke R_alloc / ALLOC (arena-backed by fake_arena.h).  The ArenaFrame guard
// is the standard Invariant 2 precaution for the entire callback subsystem.
//
// Example:
//   #include "findVarInFrame.h"    // pulls in fake_arena.h transitively
//   extern "C" SEXP init_rpcallback_wrapper(
//           SEXP rhox, SEXP ny, SEXP nr, SEXP expr1x, SEXP expr2x) {
//       ArenaFrame _frame;   // Invariant 2: frees all R_alloc/ALLOC on exit
//       try {
//           return init_rpcallback(rhox, ny, nr, expr1x, expr2x);
//       } catch (const RError &e) {
//           set_python_error(e.what());
//           return nullptr;
//       }
//   }

#endif // FAKE_R_FINDVARINFRAME_H
