// =============================================================
// ISNAN.h — Fake R API: ISNAN
// Original R header: R.h (transitively via R_ext/Arith.h)
// Category: B — Accessor Macro or Inline Function
// Auto-generated by generate-r-extern-fake-header agent.
// =============================================================
//
// Provides drop-in fake implementations of:
//   ISNAN, R_isnancpp, R_FINITE, R_finite, ISNA,
//   R_IsNA, R_IsNaN,
//   R_NaReal, R_NaN, R_PosInf, R_NegInf, R_NaInt,
//   NA_REAL, NA_INTEGER, NA_LOGICAL
//
// All items originate in R_ext/Arith.h (included by R.h at line 69).
// This header replaces that entire sub-header; no libR.so linkage
// is required.
//
// Usage note from source inspection:
//   rpart.h:27  #define RPARTNA(a) ISNAN(a)
//   branch.c:39, branch.c:59, nodesplit.c:107, rpart.c:154, xpred.c:153
//   all use R_FINITE().  RPARTNA is defined but has zero call sites in
//   the rpart source tree; ISNAN must still expand to a valid C++ expression.
// =============================================================

#pragma once
#ifndef FAKE_ISNAN_H
#define FAKE_ISNAN_H

// --- Standard library includes ---
#include <cmath>      // std::isnan, std::isfinite, std::isinf
#include <limits>     // std::numeric_limits
#include <climits>    // INT_MIN  (for NA_INTEGER / R_NaInt)
#include <cstdint>    // uint64_t (for NA_REAL bit-pattern reconstruction)
#include <cstring>    // std::memcpy (type-punning, avoids UB)

// --- Fake R header dependencies ---
// (Integration Requirements: none — this header depends only on the
//  C++ standard library.  No other fake header is needed beforehand.)

#ifdef __cplusplus
extern "C" {
#endif

// =============================================================
// Core fake implementation
// =============================================================

// --- Pattern P1: R_isnancpp ---
// Location: rpart.h:27 (#define RPARTNA(a) ISNAN(a))
//
// In the real R_ext/Arith.h (C++ branch):
//   int R_isnancpp(double);   /* implemented in libR.so arithmetic.c */
//   #define ISNAN(x) R_isnancpp(x)
//
// The fake replaces the libR.so function with an inline that delegates
// to std::isnan.  std::isnan returns true for every IEEE 754 NaN
// bit-pattern, including R's NA_REAL (0x7FF00000000007A2), which is a
// quiet NaN.  Therefore ISNAN(NA_REAL) == 1 and ISNAN(plain_NaN) == 1,
// exactly matching R's documented semantics.

#ifdef __cplusplus
} // end extern "C" — inline functions must be outside extern "C" in C++
#endif

inline int R_isnancpp(double x) {
    return std::isnan(x) ? 1 : 0;
}

// --- Pattern P2: R_finite ---
// Location: branch.c:39, branch.c:59, nodesplit.c:107, rpart.c:154,
//           xpred.c:153  (all via R_FINITE macro)
//
// In the real header:
//   int R_finite(double);     /* in libR.so */
//   #define R_FINITE(x) isfinite(x)   /* when HAVE_WORKING_ISFINITE */
//
// std::isfinite is false for NaN (including NA_REAL), +Inf, and -Inf,
// so R_finite(NA_REAL) == 0 — exactly what R documents.

inline int R_finite(double x) {
    return std::isfinite(x) ? 1 : 0;
}

// --- Pattern P3: NA_REAL bit-pattern constant (R_NaReal) ---
// R's NA_REAL is the specific quiet-NaN bit-pattern 0x7FF00000000007A2.
// std::isnan returns true for this pattern, so the ISNAN and R_FINITE
// macros work correctly on it without any special-casing.
// memcpy is used for type-punning to remain well-defined in C++.

namespace fake_r_arith_detail {
    inline double make_na_real() {
        // Bit pattern 0x7FF00000000007A2 — R's NA_REAL sentinel.
        // Confirmed by R source (main/arithmetic.c).
        const uint64_t kNaRealBits = UINT64_C(0x7FF00000000007A2);
        double v;
        std::memcpy(&v, &kNaRealBits, sizeof(v));
        return v;
    }
    inline double make_r_nan() {
        return std::numeric_limits<double>::quiet_NaN();
    }
    inline double make_pos_inf() {
        return std::numeric_limits<double>::infinity();
    }
    inline double make_neg_inf() {
        return -std::numeric_limits<double>::infinity();
    }
}

// Global constants matching LibExtern declarations in R_ext/Arith.h.
// In the real runtime these are external symbols in libR.so; here they
// are static const to avoid ODR violations across translation units.
static const double R_NaReal = fake_r_arith_detail::make_na_real();
static const double R_NaN    = fake_r_arith_detail::make_r_nan();
static const double R_PosInf = fake_r_arith_detail::make_pos_inf();
static const double R_NegInf = fake_r_arith_detail::make_neg_inf();
static const int    R_NaInt  = INT_MIN;  // R's NA_INTEGER

// --- Pattern P4: R_IsNA / R_IsNaN ---
// R_IsNA: true only for the specific NA_REAL bit-pattern, not plain NaN.
// R_IsNaN: true for IEEE NaN that is NOT R's NA.
// Neither is called directly in rpart source, but both are declared in
// R_ext/Arith.h and must be defined to satisfy translation units that
// include this header (e.g., via the ISNA macro).

inline int R_IsNA(double x) {
    if (!std::isnan(x)) return 0;
    uint64_t x_bits;
    const uint64_t kNaRealBits = UINT64_C(0x7FF00000000007A2);
    std::memcpy(&x_bits, &x, sizeof(x_bits));
    return (x_bits == kNaRealBits) ? 1 : 0;
}

inline int R_IsNaN(double x) {
    if (!std::isnan(x)) return 0;
    return R_IsNA(x) ? 0 : 1;
}

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} // end extern "C"
#endif

// =============================================================
// Compatibility aliases (preserve original R API names)
// From R_ext/Arith.h — these macros must exist so rpart source
// files compile without any textual modification.
// =============================================================

// ISNAN — C++ branch: delegates to the inline R_isnancpp above.
// Plain-C branch: falls back to ISO C isnan().
// rpart.h:27: #define RPARTNA(a) ISNAN(a)  — compiled unchanged.
#ifdef __cplusplus
#  define ISNAN(x)      R_isnancpp(x)
#else
#  define ISNAN(x)      (isnan(x) != 0)
#endif

// R_FINITE — used in branch.c, nodesplit.c, rpart.c, xpred.c.
// The real header uses isfinite() when HAVE_WORKING_ISFINITE is set
// (always true on Linux/glibc); the fake always uses std::isfinite.
#ifdef __cplusplus
#  define R_FINITE(x)   (std::isfinite(x) ? 1 : 0)
#else
#  define R_FINITE(x)   (isfinite(x) ? 1 : 0)
#endif

// ISNA — declared in R_ext/Arith.h as #define ISNA(x) R_IsNA(x)
#define ISNA(x)         R_IsNA(x)

// Scalar NA sentinel aliases declared in R_ext/Arith.h.
#define NA_REAL         R_NaReal
#define NA_INTEGER      R_NaInt
#define NA_LOGICAL      R_NaInt

#endif // FAKE_ISNAN_H
