// =============================================================
// ncols.h — Fake R API: ncols / Rf_ncols
// Original R header: Rinternals.h
// Category: B — Accessor / Inline Function
// Auto-generated by generate-r-extern-fake-header agent.
//
// ncols(SEXP s) returns the number of columns of a matrix SEXP.
// Original R declaration:
//   int Rf_ncols(SEXP);        (Rinternals.h)
//   #define ncols Rf_ncols     (Rinternals.h line 1027)
//
// Source usage context:
//   rpart.c:111   rp.nvar = ncols(xmat2);  — column count of predictor matrix
//   xpred.c:109   rp.nvar = ncols(xmat2);  — column count of predictor matrix
//
// Both call sites appear paired with nrows(xmat2) one line above.
// The result is stored in rp.nvar (int) and used as a loop bound
// (ALLOC(rp.nvar, ...) immediately follows).
//
// Implementation strategy (from ncols.md Section 3):
//   Read s->ncol directly from the SEXPREC struct.  allocMatrix sets ncol
//   when constructing a matrix SEXP.  Zero-cost accessor — no allocation,
//   no arena interaction, no interpreter required.
//
// Delegation: the authoritative implementation is in INTSXP.h under
// FAKE_NROWS_NCOLS_DEFINED (Rf_nrows and Rf_ncols, plus #define macros).
// =============================================================
#pragma once

#ifndef FAKE_R_NCOLS_H
#define FAKE_R_NCOLS_H

// --- Fake R header dependencies ---
//
// INTSXP.h provides:
//   - SEXPREC struct with nrow/ncol fields (set by allocMatrix)
//   - SEXP typedef
//   - Rf_ncols / Rf_nrows under FAKE_NROWS_NCOLS_DEFINED
//   - #define ncols(x) Rf_ncols(x)  and  #define nrows(x) Rf_nrows(x)
//   - allocMatrix / allocVector, INTEGER / REAL, LENGTH, PROTECT/UNPROTECT
#include "INTSXP.h"

// --- Safety-net fallback: Rf_ncols / Rf_nrows ---
//
// Skipped when INTSXP.h is already included (common case) because
// INTSXP.h sets FAKE_NROWS_NCOLS_DEFINED.  Present for standalone use.
#ifndef FAKE_NROWS_NCOLS_DEFINED
#define FAKE_NROWS_NCOLS_DEFINED

inline int Rf_nrows(SEXP s) { return s->nrow; }
inline int Rf_ncols(SEXP s) { return s->ncol; }

#ifndef nrows
#define nrows(x) Rf_nrows(x)
#endif
#ifndef ncols
#define ncols(x) Rf_ncols(x)
#endif

#endif // FAKE_NROWS_NCOLS_DEFINED

#endif // FAKE_R_NCOLS_H
