// =============================================================
// nrows.h — Fake R API: nrows / Rf_nrows
// Original R header: Rinternals.h
// Category: B — Accessor / Inline Function
// Auto-generated by generate-r-extern-fake-header agent.
//
// nrows(SEXP s) returns the number of rows of a matrix SEXP.
// Original R declaration:
//   int Rf_nrows(SEXP);        (Rinternals.h)
//   #define nrows Rf_nrows     (Rinternals.h line 1026)
//
// Source usage context:
//   rpart.c:108   rp.n = nrows(xmat2);  — row count of predictor matrix
//   xpred.c:106   rp.n = nrows(xmat2);  — row count of predictor matrix
//
// Both call sites appear immediately before ncols(xmat2) (one line below).
// The result is stored in rp.n (int) and used as the observation count
// throughout rpart() and xpred().
//
// Implementation strategy (from nrows.md Section 3):
//   Read s->nrow directly from the SEXPREC struct.  allocMatrix sets nrow
//   when constructing a matrix SEXP.  Zero-cost accessor — no allocation,
//   no arena interaction, no interpreter required.
//
// Delegation: the authoritative implementation is in INTSXP.h under
// FAKE_NROWS_NCOLS_DEFINED (Rf_nrows and Rf_ncols, plus #define macros).
// This header delegates to ncols.h which delegates to INTSXP.h, so
// including nrows.h always provides both Rf_nrows and Rf_ncols.
// =============================================================
#pragma once

#ifndef FAKE_R_NROWS_H
#define FAKE_R_NROWS_H

// ncols.h includes INTSXP.h and provides both Rf_nrows and Rf_ncols
// under FAKE_NROWS_NCOLS_DEFINED.
#include "ncols.h"

#endif // FAKE_R_NROWS_H
