// =============================================================
// R_Free.h — Fake R API: R_Free
// Original R header: R_ext/RS.h
// Category: C — Allocation or Memory Function
// Auto-generated by generate-r-extern-fake-header agent.
//
// R_Free is the deallocation macro defined in R_ext/RS.h as:
//   #define R_Free(p)  (R_chk_free( (void *)(p) ), (p) = NULL)
//
// It is the paired counterpart to R_Calloc / R_chk_calloc, releasing
// heap memory allocated by CALLOC (= R_chk_calloc) and nulling the
// pointer variable via the C comma operator.
//
// In rpart, the macro is used at six call sites across three files:
//
//   free_tree.c:13  — R_Free(spl)   frees a pSplit (Split *) node
//   free_tree.c:29  — R_Free(node)  frees a pNode  (Node  *) node
//   insert_split.c:36 — R_Free(s3)  frees a pSplit before realloc
//   insert_split.c:63 — R_Free(s4)  frees a pSplit before realloc
//   xval.c:178      — R_Free(savew) frees an int * scratch array
//   xval.c:179      — R_Free(xtemp) frees a double * scratch array
//
// All six call sites free CALLOC-allocated heap blocks.  They are
// NOT arena-managed and must NOT be touched by ArenaFrame destruction.
//
// This header also provides the full set of helpers from R_ext/RS.h:
//   R_chk_calloc, R_chk_realloc, R_chk_free, R_chk_memcpy, R_chk_memset,
//   R_Calloc, R_Realloc, Memcpy, Memzero, CallocCharBuf.
//
// Additional usage patterns noted from source inspection:
//   - insert_split.c:36: R_Free(s3) immediately followed by CALLOC(1, splitsize)
//     into the same variable; the NULL assignment from R_Free is overwritten.
//   - insert_split.c:63: identical pattern for s4.
//   - xval.c:179: R_Free(xtemp) releases the entire block; xpred and cp are
//     interior pointers into xtemp and become dangling after this call.
//     Neither is accessed again (xval.c ends at line 180).
//
// Integration Requirements (from R_Free.md Section 5):
//   - SEXP.h / INTSXP.h : provide RError (FAKE_R_RERROR_DEFINED guard).
//     R_chk_calloc throws RError on allocation failure (Invariant 1).
//   - fake_arena.h       : provides ArenaFrame.  R_Free itself does not use
//     the arena, but the .Call wrappers that surround CALLOC/R_Free code also
//     use ALLOC (= R_alloc, arena-backed).  fake_arena.h is included by
//     fake_R.h before this file and is therefore already available.
// =============================================================
#pragma once

#ifndef FAKE_R_FREE_H
#define FAKE_R_FREE_H

// --- Standard library includes ---
#include <stdlib.h>   // std::calloc, std::realloc, std::free, std::malloc
#include <string.h>   // std::memcpy, std::memset
#include <stddef.h>   // std::size_t, NULL

// --- Fake R header dependencies ---
// (from Integration Requirements in R_Free.md)
//
// fake_arena.h: provides ArenaFrame (included first by fake_R.h; listed here
// for documentation completeness — not re-included due to #pragma once).
// SEXP.h / INTSXP.h: provide RError under FAKE_R_RERROR_DEFINED.
// Both headers are pulled in transitively via fake_R.h before this file.
// A self-contained guard is provided below in case inclusion order varies.

// ---------------------------------------------------------------------------
// RError — C++ exception type replacing Rf_error in the fake runtime.
//
// The real RS.h does not define RError; it is introduced in fake_Rinternals.h
// (INTSXP.h in this project).  The guard FAKE_R_RERROR_DEFINED ensures exactly
// one definition exists regardless of include order.
// R_chk_calloc below throws RError on allocation failure (Invariant 1).
// ---------------------------------------------------------------------------
#ifndef FAKE_R_RERROR_DEFINED
#define FAKE_R_RERROR_DEFINED
#include <stdexcept>  // std::runtime_error
#include <string>     // std::string
struct RError : public std::runtime_error {
    using std::runtime_error::runtime_error;
};
#endif // FAKE_R_RERROR_DEFINED

// ---------------------------------------------------------------------------
// R_chk_calloc — zero-initialized heap allocation.
//
// Real RS.h definition:
//   void *(R_chk_calloc)(R_SIZE_T nmemb, size_t size);
//   (implementation calls calloc and error() on failure)
//
// Fake: calls std::calloc and throws RError on failure (Invariant 1).
//
// CRITICAL ALLOCATOR DISTINCTION:
//   R_chk_calloc allocates from the HEAP (std::calloc), NOT the arena.
//   Memory from this function persists across internal function calls within
//   a single .Call invocation (e.g., Split/Node nodes built in insert_split.c
//   and freed by free_tree.c/free_split).  It must be freed explicitly with
//   R_Free / R_chk_free.  It is NOT freed by ArenaFrame destruction.
//
// Contrast with R_alloc / ALLOC (= arena-managed, freed at ArenaFrame exit).
//
// Usage in rpart (via the CALLOC macro from rpart.h line 26):
//   insert_split.c:25  — CALLOC(1, splitsize)  -> pSplit node
//   insert_split.c:37  — CALLOC(1, splitsize)  -> pSplit node
//   insert_split.c:65  — CALLOC(1, splitsize)  -> pSplit node
//   insert_split.c:74  — CALLOC(1, splitsize)  -> pSplit node
//   xval.c:58          — CALLOC(3 * rp.num_unique_cp, sizeof(double)) -> double *
//   xval.c:61          — CALLOC(rp.n, sizeof(int))                    -> int *
//   xval.c:134         — CALLOC(1, nodesize)   -> pNode node
//   partition.c:98,113 — CALLOC(1, nodesize)   -> left/right son pNode
// ---------------------------------------------------------------------------
#ifndef FAKE_R_CHK_CALLOC_DEFINED
#define FAKE_R_CHK_CALLOC_DEFINED

inline void *R_chk_calloc(std::size_t nmemb, std::size_t size) {
    if (nmemb == 0 || size == 0) return nullptr;
    void *p = std::calloc(nmemb, size);
    if (!p) throw RError("R_chk_calloc: out of memory");
    return p;
}

#endif // FAKE_R_CHK_CALLOC_DEFINED

// ---------------------------------------------------------------------------
// R_chk_realloc — heap reallocation.
//
// Real RS.h definition:
//   void *(R_chk_realloc)(void *p, R_SIZE_T size);
//
// Fake: calls std::realloc and throws RError on failure (Invariant 1).
// Not called directly in rpart source (which uses CALLOC + R_Free for
// resize rather than Realloc; see insert_split.c FIXME comment at line 62).
// Required so that the R_Realloc macro below expands cleanly.
// ---------------------------------------------------------------------------
#ifndef FAKE_R_CHK_REALLOC_DEFINED
#define FAKE_R_CHK_REALLOC_DEFINED

inline void *R_chk_realloc(void *ptr, std::size_t size) {
    if (size == 0) { std::free(ptr); return nullptr; }
    void *p = std::realloc(ptr, size);
    if (!p) throw RError("R_chk_realloc: out of memory");
    return p;
}

#endif // FAKE_R_CHK_REALLOC_DEFINED

// ---------------------------------------------------------------------------
// R_chk_free — heap deallocation.
//
// Real RS.h definition:
//   void (R_chk_free)(void *p);
//   (implementation calls free with a null check)
//
// Fake: delegates directly to std::free.  std::free(nullptr) is a safe
// no-op per the C standard, so no null check is needed.
//
// NOT called directly by rpart source — called exclusively through R_Free.
// ---------------------------------------------------------------------------
#ifndef FAKE_R_CHK_FREE_DEFINED
#define FAKE_R_CHK_FREE_DEFINED

inline void R_chk_free(void *ptr) {
    std::free(ptr);
}

#endif // FAKE_R_CHK_FREE_DEFINED

// ---------------------------------------------------------------------------
// R_chk_memcpy — checked memcpy wrapper.
//
// Real RS.h definition:
//   void *(R_chk_memcpy)(void *dest, const void *src, R_SIZE_T n);
//
// Fake: delegates to std::memcpy.  Used by the Memcpy macro below.
// ---------------------------------------------------------------------------
#ifndef FAKE_R_CHK_MEMCPY_DEFINED
#define FAKE_R_CHK_MEMCPY_DEFINED

inline void *R_chk_memcpy(void *dest, const void *src, std::size_t n) {
    return std::memcpy(dest, src, n);
}

#endif // FAKE_R_CHK_MEMCPY_DEFINED

// ---------------------------------------------------------------------------
// R_chk_memset — checked memset wrapper.
//
// Real RS.h definition:
//   void *(R_chk_memset)(void *dest, int c, R_SIZE_T n);
//
// Fake: delegates to std::memset.  Used by the Memzero macro below.
// ---------------------------------------------------------------------------
#ifndef FAKE_R_CHK_MEMSET_DEFINED
#define FAKE_R_CHK_MEMSET_DEFINED

inline void *R_chk_memset(void *dest, int c, std::size_t n) {
    return std::memset(dest, c, n);
}

#endif // FAKE_R_CHK_MEMSET_DEFINED

// ---------------------------------------------------------------------------
// R_Free — the primary deallocation macro used by rpart source.
//
// WHY IT MUST REMAIN A MACRO:
//   The original source writes:
//       pSplit spl = ...;
//       R_Free(spl);          /* spl must equal nullptr after this */
//   The real macro achieves the null-out via the comma operator: (p) = NULL.
//   An inline function receives the pointer by value and cannot null the
//   caller's variable.  Therefore R_Free must be a macro, not an inline.
//
// WHY std::free AND NOT THE ARENA:
//   CALLOC(a, b) = R_chk_calloc(a, b) = std::calloc(a, b) — heap.
//   ALLOC(a, b)  = R_alloc(a, b)      = arena_alloc(...)  — arena.
//   The two allocators are completely orthogonal.  Calling arena functions
//   on a CALLOC block, or std::free on an arena block, would corrupt memory.
//   R_Free must call std::free (via R_chk_free) exclusively.
//
// USAGE PATTERNS COVERED:
//
//   Pattern A — Free and null a struct pointer
//     free_tree.c:13     R_Free(spl)   spl is pSplit (= Split *)
//     free_tree.c:29     R_Free(node)  node is pNode (= Node *)
//     insert_split.c:36  R_Free(s3)    s3 is pSplit; followed immediately
//                                      by CALLOC into s3 (null overwritten)
//     insert_split.c:63  R_Free(s4)    s4 is pSplit; same realloc pattern
//
//   Pattern B — Free and null a flat array pointer
//     xval.c:178  R_Free(savew)  savew is int *   (CALLOC(rp.n, sizeof(int)))
//     xval.c:179  R_Free(xtemp)  xtemp is double* (CALLOC(3*..., sizeof(double)))
//                                xpred and cp are interior pointers into xtemp;
//                                they become dangling but are not accessed after
//                                this line.
//
// Fake definition (functionally identical to the real RS.h macro with NULL
// replaced by nullptr for C++ idiom):
// ---------------------------------------------------------------------------
#ifndef R_Free
#define R_Free(p)  (R_chk_free( (void *)(p) ), (p) = nullptr)
#endif

// ---------------------------------------------------------------------------
// --- Compatibility aliases (preserve original R API names) ---
//
// The real R_ext/RS.h also defines these macros.  They are reproduced here
// so that any rpart source file that includes RS.h (or its fake replacement
// in the chain) compiles without modification.
//
// R_Calloc / R_Realloc: not used directly in rpart (rpart.h defines its own
//   CALLOC / ALLOC macros at lines 25-26), but required for completeness so
//   that the header chain compiles cleanly.
//
// Memcpy / Memzero / CallocCharBuf: utility macros; not observed in the CSV
//   usage set for rpart, but required to match the RS.h API surface.
// ---------------------------------------------------------------------------

// R_Calloc(n, t) — typed heap allocation; expands to a cast + R_chk_calloc.
// Real RS.h: #define R_Calloc(n, t)  (t *) R_chk_calloc( (R_SIZE_T) (n), sizeof(t) )
#ifndef R_Calloc
#define R_Calloc(n, t)    ((t *) R_chk_calloc( (std::size_t)(n), sizeof(t) ))
#endif

// R_Realloc(p, n, t) — typed heap reallocation.
// Real RS.h: #define R_Realloc(p,n,t) (t *) R_chk_realloc( (void *)(p), (R_SIZE_T)((n)*sizeof(t)) )
#ifndef R_Realloc
#define R_Realloc(p, n, t) \
    ((t *) R_chk_realloc( (void *)(p), (std::size_t)((n) * sizeof(t)) ))
#endif

// Memcpy(p, q, n) — type-aware memory copy (n elements of typeof(*p)).
// Real RS.h: #define Memcpy(p,q,n)  R_chk_memcpy( p, q, (R_SIZE_T)(n)*sizeof(*p) )
#ifndef Memcpy
#define Memcpy(p, q, n)  R_chk_memcpy((p), (q), (std::size_t)(n) * sizeof(*(p)))
#endif

// Memzero(p, n) — zero n elements of typeof(*p).
// Real RS.h: #define Memzero(p,n)   R_chk_memset(p, 0, (R_SIZE_T)(n)*sizeof(*p))
#ifndef Memzero
#define Memzero(p, n)    R_chk_memset((p), 0, (std::size_t)(n) * sizeof(*(p)))
#endif

// CallocCharBuf(n) — allocate a null-terminated char buffer of n+1 bytes.
// Real RS.h: #define CallocCharBuf(n) (char *) R_chk_calloc(((R_SIZE_T)(n))+1, sizeof(char))
#ifndef CallocCharBuf
#define CallocCharBuf(n) \
    ((char *) R_chk_calloc(((std::size_t)(n)) + 1, sizeof(char)))
#endif

// ---------------------------------------------------------------------------
// --- ArenaFrame usage (Category C) ---
//
// R_Free / R_chk_calloc govern HEAP memory only.  They have no interaction
// with the arena managed by fake_arena.h.  However, the three source files
// that call R_Free (free_tree.c, insert_split.c, xval.c) are themselves
// called from functions that also use ALLOC (= R_alloc, arena-managed).
//
// Every .Call-entry wrapper that (transitively) invokes any code in these
// files must declare an ArenaFrame as its first statement so that
// ALLOC-allocated scratch memory is freed on normal and exceptional exit.
//
// Example wrapper for the function that calls xval() (which uses both
// CALLOC/R_Free and ALLOC):
//
//   extern "C" SEXP rpart_entry(
//           SEXP ncat2, SEXP method2, SEXP opt2, SEXP parms2,
//           SEXP xvals2, SEXP xgrp2, SEXP ymat2, SEXP xmat2,
//           SEXP wt2, SEXP ny2, SEXP cost2) {
//       ArenaFrame _frame;    // frees ALLOC/R_alloc scratch on exit
//       try {
//           return rpart(ncat2, method2, opt2, parms2, xvals2, xgrp2,
//                        ymat2, xmat2, wt2, ny2, cost2);
//       } catch (const RError &e) {
//           // CALLOC-allocated pNode/pSplit/array blocks may be leaked if
//           // R_Free is not reached (e.g., OOM during tree build).  For
//           // the error path this is acceptable; the process typically
//           // exits or resets after an OOM condition.
//           set_python_error(e.what());
//           return R_NilValue;
//       }
//   }
//
// The CALLOC-allocated blocks freed by free_tree / free_split / R_Free at
// lines free_tree.c:13, free_tree.c:29, insert_split.c:36, insert_split.c:63,
// xval.c:178, and xval.c:179 are NOT freed by ArenaFrame — they are freed
// by the existing R_Free calls already present in the rpart source code.
// No source modification is needed.
// ---------------------------------------------------------------------------

#endif // FAKE_R_FREE_H
