// =============================================================
// R_NamesSymbol.h — Fake R API: R_NamesSymbol
// Original R header: Rinternals.h
// Category: E — R Interpreter Item (reduced to Category A static sentinel)
// Auto-generated by generate-r-extern-fake-header agent.
//
// R_NamesSymbol is a pre-interned SEXP of type SYMSXP declared in
// Rinternals.h at line 448:
//
//   LibExtern SEXP  R_NamesSymbol;    /* "names" */
//
// LibExtern expands to `extern` in translation units that link against
// libR.so.  In a standalone (no-libR.so) build, that extern declaration
// becomes an unresolved symbol at link time.  This header provides a
// self-contained definition so the rpart source files build and run
// without libR.so.
//
// Contextual usage in rpart source (from CSV):
//
//   rpart.c:329 — setAttrib(rlist, R_NamesSymbol, rname);
//
// R_NamesSymbol is passed as the second argument to setAttrib (which is
// itself a no-op in the fake runtime).  The pointer value is never
// dereferenced, never compared, and never passed to any accessor such as
// CHAR(), INTEGER(), or REAL().  The only requirement at the call site is
// that R_NamesSymbol evaluates to a valid (non-null) SEXP so the three-
// argument call compiles as valid C++.
//
// Because the sole usage reduces to an opaque no-op argument, a faithful
// replication of R's symbol-interning machinery (hash table, install(),
// PRINTNAME, identity comparison) is unnecessary.  A static SEXPREC
// sentinel with type=SYMSXP satisfies the contract exactly.
//
// Co-occurring items at rpart.c:327-349 (all covered by their own headers
// or by SEXP.h):
//   allocVector(VECSXP, nout)  — line 327 — VECSXP.h / SEXP.h
//   allocVector(STRSXP, nout)  — line 328 — STRSXP.h / SEXP.h
//   setAttrib                  — line 329 — SEXP.h (no-op)
//   SET_VECTOR_ELT             — lines 330-344 — SEXP.h
//   SET_STRING_ELT / mkChar    — lines 331-344 — SEXP.h
//   PROTECT / UNPROTECT        — lines 327, 347 — INTSXP.h (no-ops)
//
// *** R INTERPRETER ITEM — R_NamesSymbol ***
// A complete fake of R's symbol-interning semantics requires a live R
// interpreter.  However, because setAttrib is a no-op in the fake
// runtime, R_NamesSymbol's pointer value is never observed by any rpart
// code path.  No Python callback registration is required for this item.
// =============================================================
#pragma once

#ifndef FAKE_R_NAMESSYMBOL_H
#define FAKE_R_NAMESSYMBOL_H

// --- Standard library includes ---
// None required beyond what SEXP.h already includes.

// --- Fake R header dependencies ---
// (from Integration Requirements in R_NamesSymbol.md, Section 5)
//
// SEXP.h provides:
//   - struct SEXPREC layout (type, length, nrow, ncol, data fields)
//   - typedef SEXPREC *SEXP
//   - SYMSXP constant (via INTSXP.h which SEXP.h includes)
//   - R_NilValue singleton (NILSXP) — returned by getAttrib no-op
//   - R_NamesSymbol static sentinel (SYMSXP) — defined under
//     FAKE_R_NAMESSYMBOL_DEFINED guard
//   - Rf_setAttrib / setAttrib no-op (FAKE_ATTRIB_DEFINED guard)
//   - Rf_getAttrib / getAttrib no-op (FAKE_ATTRIB_DEFINED guard)
//   - make_names_symbol() factory function
#include "SEXP.h"

// ---------------------------------------------------------------------------
// R_NamesSymbol — static SYMSXP sentinel for the "names" attribute key.
//
// Real declaration in Rinternals.h line 448:
//   LibExtern SEXP  R_NamesSymbol;    /* "names" */
//
// The complete definition is provided by SEXP.h under the guard
// FAKE_R_NAMESSYMBOL_DEFINED.  It reads:
//
//   inline SEXP make_names_symbol() {
//       static SEXPREC names_sym = { SYMSXP, 0, 0, 0, NULL };
//       return &names_sym;
//   }
//   static SEXP R_NamesSymbol = make_names_symbol();
//
// Fields of the sentinel SEXPREC:
//   type   = SYMSXP (1) — consistent with a symbol node.
//   length = 0          — symbols are not vectors; length is irrelevant.
//   nrow   = 0          — not a matrix.
//   ncol   = 0          — not a matrix.
//   data   = NULL       — the symbol name string is not accessed anywhere
//                         in the rpart source; nullptr is safe.
//
// The function-static inside make_names_symbol() guarantees that a single
// SEXPREC object is allocated process-wide (first-call-wins).  The
// module-level `static SEXP R_NamesSymbol` in each translation unit stores
// the same address, so pointer equality holds across all .cpp files that
// include this header.
//
// No pointer dereference of R_NamesSymbol occurs at rpart.c:329 because
// setAttrib is defined as:
//   inline void Rf_setAttrib(SEXP /*x*/, SEXP /*name*/, SEXP /*val*/) {}
// All three pointer arguments are received and immediately discarded.
//
// If SEXP.h was not already included above, the guard below provides a
// fallback definition.  In normal include order (SEXP.h first), the guard
// body is skipped and the definition from SEXP.h is used.
// ---------------------------------------------------------------------------
#ifndef FAKE_R_NAMESSYMBOL_DEFINED
#define FAKE_R_NAMESSYMBOL_DEFINED

inline SEXP make_names_symbol() {
    static SEXPREC names_sym = { SYMSXP, 0, 0, 0, NULL };
    return &names_sym;
}

static SEXP R_NamesSymbol = make_names_symbol();

#endif // FAKE_R_NAMESSYMBOL_DEFINED

// ---------------------------------------------------------------------------
// Rf_setAttrib / setAttrib — attribute setter (no-op).
//
// Real declaration in Rinternals.h line 582:
//   SEXP Rf_setAttrib(SEXP, SEXP, SEXP);
// Real alias in Rinternals.h line 1048:
//   #define setAttrib  Rf_setAttrib
//
// In the fake runtime, R objects carry no attribute lists.  Python reads
// the output list (rlist) by positional slot index via VECTOR_ELT, not by
// name attribute lookup, so attaching the names vector via setAttrib has
// no observable effect and the function is a complete no-op.
//
// Note: the full definition lives in SEXP.h under FAKE_ATTRIB_DEFINED.
// The guard below is a safety net in case this header is included without
// SEXP.h.
// ---------------------------------------------------------------------------
#ifndef FAKE_ATTRIB_DEFINED
#define FAKE_ATTRIB_DEFINED

inline void Rf_setAttrib(SEXP /*x*/, SEXP /*name*/, SEXP /*val*/) {}
inline SEXP Rf_getAttrib(SEXP /*x*/, SEXP /*name*/) { return R_NilValue; }

// Short-name wrappers (inline functions, not macros, to avoid
// double-expansion and ensure argument types are checked).
inline void setAttrib(SEXP x, SEXP name, SEXP val) { Rf_setAttrib(x, name, val); }
inline SEXP getAttrib(SEXP x, SEXP name)           { return Rf_getAttrib(x, name); }

#endif // FAKE_ATTRIB_DEFINED

// --- Compatibility aliases (preserve original R API names) ---
//
// The real Rinternals.h defines the following aliases for the items
// documented in this header.  They are reproduced here so that the
// original rpart source files compile unchanged without any modification.
//
// From Rinternals.h line 1048:
//   #define setAttrib  Rf_setAttrib
// From Rinternals.h line 945:
//   #define getAttrib  Rf_getAttrib
//
// These macros are emitted conditionally so they do not conflict with the
// inline short-name functions already defined in FAKE_ATTRIB_DEFINED.
// Because SEXP.h provides the inline setAttrib / getAttrib functions
// (not macros), the #define aliases are intentionally omitted here to
// avoid redefinition warnings — the inline functions serve the same role
// and are already visible to the source files via SEXP.h.
//
// Usage of R_NamesSymbol in rpart source (from CSV, confirmed by source
// inspection at rpart.c:314-349):
//
//   rpart.c:329:  setAttrib(rlist, R_NamesSymbol, rname);
//                 ^-- resolves to: Rf_setAttrib(rlist, R_NamesSymbol, rname)
//                     which is: (void)(rlist, R_NamesSymbol, rname) — no-op.
//
// No other source files in the CSV reference R_NamesSymbol.

#endif // FAKE_R_NAMESSYMBOL_H
