// =============================================================
// R_useDynamicSymbols.h — Fake R API: R_useDynamicSymbols
// Original R header: R_ext/Rdynload.h
// Category: A — Type or Enum Constant (registration function variant)
// Auto-generated by generate-r-extern-fake-header agent.
//
// Original R API declaration (R_ext/Rdynload.h, line 85):
//   Rboolean R_useDynamicSymbols(DllInfo *info, Rboolean value);
//
// NOTE: The original header at
//   ~/.conda/envs/r-to-python/lib/R/include/R_ext/Rdynload.h
// was inaccessible (permission denied). Signature reproduced from
// the Markdown guide (R_useDynamicSymbols.md Section 1) which
// references line 85 of R_ext/Rdynload.h, and confirmed against
// the observed usage at init.c:26:
//   R_useDynamicSymbols(dll, FALSE);
//
// R_useDynamicSymbols is a library-registration function called inside
// R_init_rpart — the shared-library constructor that R's dynamic loader
// invokes when a package is loaded via dyn.load().  When called with
// value = FALSE, it instructs R's symbol resolver to forbid ad-hoc
// name-based symbol lookup (i.e., .Call("rpart", ...) where the string
// "rpart" is resolved dynamically from the package's exported symbol
// table).  The function returns the previous dynamic-lookup state
// (Rboolean), which is discarded at every rpart call site.
//
// In the standalone fake build there is no R dynamic loader, no R symbol
// table, and R_init_rpart is never invoked by a loader.
// R_useDynamicSymbols is therefore dead code at runtime; the stub exists
// solely to satisfy the linker and allow init.c to compile and link
// without any modification.
// =============================================================
#pragma once

#ifndef FAKE_R_USEDYNAMICSYMBOLS_H
#define FAKE_R_USEDYNAMICSYMBOLS_H

// --- Standard library includes ---
#include <stddef.h>   // NULL

// --- Fake R header dependencies ---
// (from Integration Requirements in R_useDynamicSymbols.md)
//
// DllInfo.h provides (transitively via DL_FUNC.h):
//   - DllInfo typedef (C-compatible two-step form:
//       typedef struct DllInfo_fake DllInfo; struct DllInfo_fake { int _unused; };)
//   - Rboolean enum (FALSE = 0, TRUE = 1) under FAKE_RBOOLEAN_DEFINED guard
//   - DL_FUNC typedef  (void * (*)(void))
//   - R_NativePrimitiveArgType typedef
//   - R_CMethodDef / R_FortranMethodDef structs
//   - R_CallMethodDef / R_ExternalMethodDef structs
//   - R_registerRoutines() no-op inline
//   - R_useDynamicSymbols() no-op inline  <-- the primary stub for this item
//   - R_forceSymbols() no-op inline
//   - R_getDllInfo() / R_getEmbeddingDllInfo() stubs
//   - R_RegisterCCallable() / R_GetCCallable() stubs
//
// Rboolean.h is also included directly to ensure FAKE_RBOOLEAN_DEFINED is
// set regardless of include order; both DL_FUNC.h and Rboolean.h guard
// their Rboolean typedef with matching #ifndef guards so there is no
// double-definition.
//
// R_VERSION.h provides R_Version(v, p, s) and R_VERSION so that the
// preprocessor gate at init.c:27 evaluates correctly:
//   #if defined(R_VERSION) && R_VERSION >= R_Version(2, 16, 0)
// With R_VERSION = R_Version(4, 4, 0) = 263168 >= R_Version(2, 16, 0) = 131584,
// the condition is TRUE and the R_forceSymbols call site (init.c:28,
// the call that immediately follows R_useDynamicSymbols) is compiled in.
// R_useDynamicSymbols itself is not gated by any version guard; it is
// always compiled from init.c regardless of R_VERSION.
#include "DllInfo.h"
#include "Rboolean.h"
#include "R_VERSION.h"

// --- Core fake implementation ---
//
// Pattern: No-Op Library Registration Call Disabling Dynamic Symbol Lookup
// Location: init.c:26 — `R_useDynamicSymbols(dll, FALSE);`
//            inside void R_init_rpart(DllInfo * dll), immediately after
//            R_registerRoutines(dll, NULL, CallEntries, NULL, NULL) at init.c:25
//            and before the R_VERSION-gated R_forceSymbols(dll, TRUE) at init.c:28.
//
// Argument and return-value types at the call site (init.c:26):
//
//   Position 1: dll   — DllInfo * (opaque handle from R_init_rpart parameter)
//   Position 2: FALSE — Rboolean enumerator (value = 0)
//   Return value: (discarded) — Rboolean (previous dynamic-lookup state)
//
// Purpose in real R: when value == FALSE, disables the ability to call
//   package C functions via .Call("symbol_name_string") dynamic lookup.
//   Only pre-registered entry points (registered by R_registerRoutines)
//   remain callable.  This is a security/robustness measure.  The function
//   returns the previous value of the dynamic-lookup flag for the DllInfo
//   handle; on a freshly loaded library the default is TRUE (dynamic lookup
//   enabled), so the first call R_useDynamicSymbols(dll, FALSE) would return
//   TRUE.  The rpart call site discards the return value; any Rboolean is
//   correct.  FALSE is returned here for consistency with the companion stubs
//   R_forceSymbols and R_registerRoutines established in DL_FUNC.h.
//
// In the standalone fake build: R's dynamic loader is absent; there is no
//   symbol table to configure.  R_init_rpart is never invoked by a loader;
//   R_useDynamicSymbols is dead code at runtime.  The stub accepts both
//   arguments, discards them via (void) casts to suppress -Wall -Wextra
//   unused-parameter warnings, and returns FALSE.
//
// Preprocessor note:
//   R_useDynamicSymbols at init.c:26 is NOT wrapped in any version guard.
//   It is always compiled.  This stub must therefore always be present;
//   it cannot be conditionally omitted based on any R_VERSION value.
//   Compare with R_forceSymbols at init.c:28, which IS version-gated.
//
// Implementation note:
//   The no-op inline stub for R_useDynamicSymbols is already emitted by
//   DL_FUNC.h (included above via DllInfo.h) as:
//     inline Rboolean R_useDynamicSymbols(DllInfo * /*info*/, Rboolean /*value*/)
//     { return FALSE; }
//   This header provides it additionally under a conflict-safe #ifndef guard
//   (FAKE_R_USEDYNAMICSYMBOLS_DEFINED) for translation units that include
//   R_useDynamicSymbols.h directly without going through DL_FUNC.h, and to
//   document the rationale as the canonical guide entry for this named item.
//   The #ifndef guard prevents a duplicate-definition error when both DL_FUNC.h
//   and this header are included in the same translation unit.
//
// Invariants:
//   - Invariant 1 (C++ exception-based errors): not triggered.
//     R_useDynamicSymbols does not call Rf_error, Rf_warning, or any error
//     mechanism in either the real or fake implementation.
//   - Invariant 2 (arena memory): not triggered.
//     R_useDynamicSymbols neither allocates nor frees any memory.  The
//     DllInfo * pointer is received opaquely and immediately discarded.
//     No heap or arena involvement.
//   - Invariant 3 (R Interpreter Items): not triggered.
//     R_useDynamicSymbols is a dynamic-loader configuration function with
//     no interaction with the R interpreter.  No Python callback registration
//     is required.
#ifndef FAKE_R_USEDYNAMICSYMBOLS_DEFINED
#define FAKE_R_USEDYNAMICSYMBOLS_DEFINED

// R_useDynamicSymbols — primary subject of this guide.
//
// Signature confirmed against R_ext/Rdynload.h line 85 (from guide):
//   Rboolean R_useDynamicSymbols(DllInfo *info, Rboolean value);
//
// Declared static inline to:
//   - Prevent multiple-definition link errors when this header is included
//     by more than one translation unit in the same build.
//   - Allow the compiler to fold the no-op body entirely (zero code emitted),
//     eliminating any runtime overhead.
//
// The (void) casts suppress -Wall -Wextra unused-parameter warnings without
// requiring any modification to init.c.
//
// NOTE: DL_FUNC.h (included above via DllInfo.h) already emits an `inline`
// (non-static) form of this stub.  The two forms are compatible under C++
// ODR: both produce the same no-op body and the linker selects one copy.
// The FAKE_R_USEDYNAMICSYMBOLS_DEFINED guard below ensures this block is
// skipped if DL_FUNC.h was already included, avoiding any redeclaration
// diagnostic.
//
// Returns FALSE: represents "dynamic lookup was previously not restricted."
// The rpart call site at init.c:26 discards this value entirely, so any
// Rboolean return is correct.  FALSE (value 0) is chosen for consistency
// with the companion stubs R_forceSymbols and R_registerRoutines.
static inline Rboolean R_useDynamicSymbols(DllInfo *info, Rboolean value)
{
    (void)info;   // DllInfo * — opaque handle; never dereferenced in standalone build
    (void)value;  // FALSE received here; has no effect in fake build
    return FALSE;
}

#endif /* FAKE_R_USEDYNAMICSYMBOLS_DEFINED */

// --- Compatibility aliases (preserve original R API names) ---
//
// R_ext/Rdynload.h defines no preprocessor aliases for R_useDynamicSymbols.
// The function name is used directly at the call site (init.c:26):
//   R_useDynamicSymbols(dll, FALSE);
// No #define remapping macros are needed or present in the original R header
// for this item.
//
// All other aliases needed by the surrounding init.c context are provided by
// DL_FUNC.h (via DllInfo.h, included above):
//   - FALSE / TRUE          : Rboolean enum enumerators (not preprocessor macros)
//   - R_registerRoutines()  : companion no-op stub (init.c:25)
//   - R_forceSymbols()      : companion no-op stub (init.c:28, R_VERSION gated)
//   - DL_FUNC               : function pointer typedef (used in CallEntries[])
//   - R_CallMethodDef       : struct type for CallEntries[] array
//   - DllInfo               : C-compatible typedef for the dll parameter

// --- Usage note for callers ---
//
// To compile init.c without libR.so, the shadow include tree must resolve:
//
//   #include "R_ext/Rdynload.h"  ->  fake_R.h (or direct) which includes
//                                    DllInfo.h -> DL_FUNC.h
//                                    (R_useDynamicSymbols stub already present there)
//
//   #include <Rversion.h>        ->  R_VERSION.h
//                                    (R_VERSION and R_Version macros)
//
// If this header (R_useDynamicSymbols.h) is included directly instead of
// going through DL_FUNC.h, it is self-contained: DllInfo.h, Rboolean.h,
// and R_VERSION.h are all pulled in above, and the stub is present under
// FAKE_R_USEDYNAMICSYMBOLS_DEFINED.  If DL_FUNC.h was already included
// first (the common case via fake_R.h), both FAKE_R_USEDYNAMICSYMBOLS_DEFINED
// and the stub in DL_FUNC.h are active; the #ifndef guard here prevents
// any redeclaration conflict.
//
// R_useDynamicSymbols is declared static inline.  The compiler resolves
// the call at init.c:26 directly to the no-op body and optimises it away
// entirely.  No external symbol reference is emitted and libR.so is not
// needed at link time for this symbol.

#endif /* FAKE_R_USEDYNAMICSYMBOLS_H */
