// =============================================================
// Rprintf.h — Fake R API: Rprintf
// Original R header: R_ext/Print.h
// Category: D — Print Function
// Auto-generated by generate-r-extern-fake-header agent.
// =============================================================
#pragma once

#ifndef FAKE_R_EXT_PRINT_H_
#define FAKE_R_EXT_PRINT_H_

// --- Standard library includes ---
#include <cstdarg>   // std::va_list, va_start, va_end
#include <cstdio>    // std::vprintf, std::vfprintf, stderr

// --- Fake R header dependencies ---
// (from Integration Requirements in Rprintf.md)
// None: Rprintf and its companions (REprintf, Rvprintf, REvprintf) have no
// dependencies on other fake headers. Only <cstdarg> and <cstdio> are needed.

// --- Compatibility attribute macros (from original R_ext/Print.h) ---
//
// The real R_ext/Print.h defines R_PRINTF_FORMAT as a GCC
// __attribute__((format(printf,M,N))) decorator that enables compile-time
// format-string checking and is applied to every declaration of Rprintf and
// REprintf.  In a fake build there is no point enabling the attribute (the
// inline definitions below already satisfy format checking), so we suppress it
// by defining R_PRINTF_FORMAT as an empty macro.  Any translation unit that
// re-declares one of these functions with R_PRINTF_FORMAT still compiles.
//
// R_VA_LIST is a portability alias for va_list / std::va_list.  The real
// header sets it to std::va_list under C++11 with R_USE_C99_IN_CXX.  We
// define it here unconditionally so any code that references R_VA_LIST
// outside the conditional guards of the original header still compiles.

#ifndef R_PRINTF_FORMAT
#  define R_PRINTF_FORMAT(M, N)
#endif

#ifndef R_VA_LIST
#  define R_VA_LIST std::va_list
#endif

// --- Core fake implementation ---

// -----------------------------------------------------------------------
// Pattern: Formatted Output to Standard Output
//
// Covers all 29 CSV rows:
//   print_tree.c:59-146  — printme() static helper, all 26 calls.
//     Argument types observed: const char* fmt, followed by zero to four
//     arguments of type int (%d) or double (%f, %5g, %5.3f).
//     No SEXP interactions, no arena, no PROTECT/UNPROTECT in this file.
//   xval.c:151, 161      — inside #if DEBUG > 1 blocks in xval().
//     Default build defines DEBUG 0, so these two calls are dead code
//     in a standard build.  Active only with -DDEBUG=2 or higher.
//
// The real Rprintf routes output through R's Rconnection infrastructure
// so that sink() and textConnection() can intercept it.  In the fake
// runtime there is no R session and no connection stack; direct delegation
// to std::vprintf (which writes to stdout) is the correct substitute.
// -----------------------------------------------------------------------

// Rprintf — formatted output to stdout.
//
// Accepts a printf-style format string and a variadic argument list.
// Captures the variadic tail with va_start/va_end and forwards the entire
// argument pack to std::vprintf, preserving all format-string semantics
// (%d, %f, %5g, %5.3f, etc.) without reimplementing the formatter.
//
// The original R_ext/Print.h declares this with extern "C" linkage when
// compiled as C++.  The inline definition here has external linkage by
// default; because it appears in every translation unit that includes this
// header the linker merges the definitions (standard inline semantics).
// No ODR violation arises from multiple-inclusion scenarios.
inline void Rprintf(const char *fmt, ...) {
    std::va_list args;
    va_start(args, fmt);
    std::vprintf(fmt, args);
    va_end(args);
}

// REprintf — formatted output to stderr.
//
// The real REprintf is the error-output variant of Rprintf: it routes
// through R's warning/message output device rather than the standard
// output device.  In the fake runtime, delegation to std::vfprintf(stderr)
// is the correct substitute.
//
// Not called by rpart source files directly (no CSV rows for REprintf), but
// declared in R_ext/Print.h and must be provided to avoid link errors from
// any translation unit that includes the master fake_R.h and calls REprintf.
inline void REprintf(const char *fmt, ...) {
    std::va_list args;
    va_start(args, fmt);
    std::vfprintf(stderr, fmt, args);
    va_end(args);
}

// Rvprintf — va_list variant of Rprintf.
//
// The real R_ext/Print.h declares Rvprintf only when __cplusplus is not
// defined or when R_USE_C99_IN_CXX is defined (C++11 and later).  In the
// fake header we always provide it because the inline definition is
// unconditionally safe under C++11 and later (which is the minimum standard
// for this fake build).  Accepts a pre-constructed va_list; delegates
// directly to std::vprintf.
//
// Not called by rpart source files but must be linkable.
inline void Rvprintf(const char *fmt, std::va_list ap) {
    std::vprintf(fmt, ap);
}

// REvprintf — va_list variant of REprintf.
//
// Mirrors Rvprintf for the stderr output device.
// Not called by rpart source files but must be linkable.
inline void REvprintf(const char *fmt, std::va_list ap) {
    std::vfprintf(stderr, fmt, ap);
}

// --- Compatibility aliases (preserve original R API names) ---
//
// The original R_ext/Print.h does NOT define any #define aliases that
// remap the public names Rprintf / REprintf / Rvprintf / REvprintf to
// internal Rf_* names (unlike R_ext/Error.h which remaps error -> Rf_error).
// Therefore no #define aliases are required here.
//
// The only macros from the original header that affect callers are
// R_PRINTF_FORMAT and R_VA_LIST, both of which are handled above.

#endif /* FAKE_R_EXT_PRINT_H_ */
