// =============================================================
// allocVector.h — Fake R API: allocVector
// Original R header: Rinternals.h
// Category: C — Allocation or Memory Function
// Auto-generated by generate-r-extern-fake-header agent.
//
// allocVector is declared in Rinternals.h as:
//   SEXP Rf_allocVector(SEXPTYPE type, R_xlen_t length);
// and exposed to package source via the macro alias (line 896):
//   #define allocVector    Rf_allocVector
//
// It allocates a one-dimensional R vector object: a heap-managed SEXPREC
// node whose data field points to a flat, contiguous buffer of `length`
// elements of the scalar type indicated by the SEXPTYPE argument:
//   INTSXP  (13) => int[]        accessed via INTEGER(s)
//   REALSXP (14) => double[]     accessed via REAL(s)
//   STRSXP  (16) => SEXP[]       accessed via STRING_ELT(s, i)
//   VECSXP  (19) => SEXP[]       accessed via VECTOR_ELT(s, i)
//
// In the fake runtime, allocVector is an inline C++ function
// (Rf_allocVector) that:
//   1. Allocates the SEXPREC node via std::malloc(sizeof(SEXPREC)).
//   2. Sets s->type = type, s->length = length, s->nrow = length, s->ncol = 1.
//   3. Computes data buffer bytes = length * sexptype_element_size(type).
//   4. Allocates and zero-initializes the data buffer via std::malloc + std::memset.
//   5. Returns the SEXP.
// No garbage collector, no R runtime, and no libR.so are involved.
//
// Observed usage patterns in rpart source (all six CSV rows):
//
//   Pattern P1: 1-D INTSXP vector
//     pred_rpart.c:139   SEXP where = PROTECT(allocVector(INTSXP, n));
//     rpart.c:194        which3 = PROTECT(allocVector(INTSXP, n));
//     rpartexp2.c:47     SEXP keep = PROTECT(allocVector(INTSXP, n));
//     Accessor: INTEGER(s)  — returns int * into the data buffer.
//
//   Pattern P2: 1-D REALSXP vector
//     xpred.c:209        predict2 = PROTECT(allocVector(REALSXP, n * ncp * nresp));
//     Accessor: REAL(s)  — returns double * into the data buffer.
//
//   Pattern P3: 1-D VECSXP generic list
//     rpart.c:327        SEXP rlist = PROTECT(allocVector(VECSXP, nout));
//     Accessor: SET_VECTOR_ELT / VECTOR_ELT — writes/reads SEXP slot pointers.
//
//   Pattern P4: 1-D STRSXP string vector (no PROTECT)
//     rpart.c:328        SEXP rname = allocVector(STRSXP, nout);
//     Accessor: SET_STRING_ELT / STRING_ELT — writes/reads CHARSXP slot pointers.
//
// Memory allocation model:
//   Both the SEXPREC node and the element data buffer are heap-allocated via
//   std::malloc — they are NOT arena-managed.  Every allocVector result in the
//   rpart source is either a .Call return value (which must outlive the call
//   frame) or a component packed into the returned VECSXP list.  Arena memory
//   (via ALLOC / R_alloc) is used only for scratch arrays in the same
//   function bodies; ArenaFrame governs only those.
//
// Failure handling (Invariant 1):
//   If std::malloc fails for the SEXPREC node, RError is thrown immediately.
//   If std::malloc fails for the data buffer, the SEXPREC node is freed before
//   throwing.  No longjmp, setjmp, abort(), or Rf_error() is used.
//
// ArenaFrame requirement (Invariant 2):
//   All four rpart entry points that call allocVector (pred_rpart, rpart,
//   rpartexp2, xpred) also call ALLOC / R_alloc for scratch arrays.  The
//   .Call wrapper for each must declare `ArenaFrame _frame;` at entry.
//
// Integration Requirements (allocVector.md Section 5):
//   - INTSXP.h    : SEXPTYPE constant block, SEXPREC/SEXP typedef,
//                   sexptype_element_size, allocVector / Rf_allocVector
//                   (FAKE_ALLOCVECTOR_DEFINED), allocMatrix / Rf_allocMatrix,
//                   INTEGER / REAL / LOGICAL / RAW accessors,
//                   PROTECT / UNPROTECT no-ops, LENGTH, nrows/ncols,
//                   free_sexp, RError.
//   - REALSXP.h   : REALSXP==14 constant; used by xpred.c:209.
//   - STRSXP.h    : STRSXP==16 constant; used by rpart.c:328.
//   - VECSXP.h    : VECSXP==19 constant; used by rpart.c:327.
//   - PROTECT.h   : PROTECT_INDEX, R_ProtectWithIndex, R_Reprotect; correct
//                   two-argument PROTECT_WITH_INDEX / REPROTECT aliases.
//   - SEXP.h      : XLENGTH, TYPEOF, asInteger/asReal, CHAR/mkChar,
//                   VECTOR_ELT/SET_VECTOR_ELT, STRING_ELT/SET_STRING_ELT,
//                   setAttrib/getAttrib, R_NilValue, R_NamesSymbol,
//                   free_sexp_deep for recursive VECSXP freeing.
//   - fake_arena.h: ArenaFrame RAII guard (not yet present in output_folder).
// =============================================================
#pragma once

#ifndef FAKE_R_ALLOCVECTOR_H
#define FAKE_R_ALLOCVECTOR_H

// --- Standard library includes ---
#include <stdlib.h>    // malloc, free, size_t
#include <string.h>    // memset
#include <stddef.h>    // NULL, size_t
#include <stdarg.h>    // va_list, vsnprintf
#include <stdio.h>     // fprintf, stderr
#include <stdexcept>   // std::runtime_error
#include <string>      // std::string

// --- Fake R header dependencies ---
// (from Integration Requirements in allocVector.md, Section 5)
//
// WARNING: dependency fake_arena.h not found in output_folder.
// The .Call wrapper for every entry point that calls allocVector alongside
// ALLOC / R_alloc (pred_rpart, rpart, rpartexp2, xpred) must declare
// `ArenaFrame _frame;` as its first statement once fake_arena.h is available.
// See the ArenaFrame usage block at the bottom of this file.
//
// #include "fake_arena.h"

// INTSXP.h provides the complete foundation:
//   - RError (FAKE_R_RERROR_DEFINED guard)
//   - SEXPTYPE typedef and full constant block: INTSXP=13, REALSXP=14,
//     STRSXP=16, VECSXP=19, CHARSXP=9, NILSXP=0, etc.
//   - SEXPREC struct and SEXP typedef (FAKE_SEXPREC_DEFINED guard)
//   - sexptype_element_size(SEXPTYPE) (FAKE_SEXPTYPE_ELEMENT_SIZE_DEFINED)
//   - allocVector / Rf_allocVector (FAKE_ALLOCVECTOR_DEFINED guard) — the
//     core implementation targeted by this header
//   - allocMatrix / Rf_allocMatrix (FAKE_ALLOCMATRIX_DEFINED guard)
//   - INTEGER / REAL / LOGICAL / RAW accessors (FAKE_ACCESSORS_DEFINED guard)
//   - LENGTH / Rf_length (FAKE_LENGTH_DEFINED guard)
//   - Rf_nrows / Rf_ncols (FAKE_NROWS_NCOLS_DEFINED guard)
//   - Rf_protect / Rf_unprotect / Rf_unprotect_ptr (FAKE_PROTECT_DEFINED guard)
//   - free_sexp() — basic form (FAKE_FREE_SEXP_DEFINED guard)
//   - #define aliases: PROTECT, UNPROTECT, UNPROTECT_PTR, nrows, ncols,
//     allocVector, allocMatrix (emitted under #ifndef guards)
#include "INTSXP.h"

// REALSXP.h: confirms REALSXP==14 via static_assert; required by xpred.c:209
//   predict2 = PROTECT(allocVector(REALSXP, n * ncp * nresp));
// sexptype_element_size(REALSXP) must return sizeof(double) = 8.
#include "REALSXP.h"

// STRSXP.h: confirms STRSXP==16; required by rpart.c:328
//   SEXP rname = allocVector(STRSXP, nout);
// sexptype_element_size(STRSXP) must return sizeof(SEXP) (pointer size).
#include "STRSXP.h"

// VECSXP.h: confirms VECSXP==19; required by rpart.c:327
//   SEXP rlist = PROTECT(allocVector(VECSXP, nout));
// sexptype_element_size(VECSXP) must return sizeof(SEXP) (pointer size).
#include "VECSXP.h"

// PROTECT.h: adds PROTECT_INDEX typedef, R_ProtectWithIndex / R_Reprotect
// no-ops, and the correct two-argument PROTECT_WITH_INDEX(x,i) /
// REPROTECT(x,i) #define aliases matching Rinternals.h lines 396-398.
// Five of the six allocVector call sites are wrapped in PROTECT; these
// macros must be in scope for the rpart source to compile unchanged.
#include "PROTECT.h"

// SEXP.h: adds XLENGTH, TYPEOF, asInteger/asReal/asLogical, R_CHAR/CHAR,
// mkChar/Rf_mkChar, VECTOR_ELT/SET_VECTOR_ELT, STRING_ELT/SET_STRING_ELT,
// type predicates (isReal/isInteger/isNull), R_NilValue, R_UnboundValue,
// R_NamesSymbol, PRINTNAME, setAttrib/getAttrib, R_ProtectWithIndex /
// R_Reprotect extended forms, NA_STRING, and free_sexp_deep() for recursive
// VECSXP / STRSXP tree freeing.
// Note: SEXP.h includes INTSXP.h and Rboolean.h internally; all guards
// prevent double-definition conflicts.
#include "SEXP.h"

// ---------------------------------------------------------------------------
// Core fake implementation — allocVector
//
// The implementation lives entirely in INTSXP.h under the
// FAKE_ALLOCVECTOR_DEFINED include guard.  It is reproduced here in
// comments for documentation and cross-reference.
//
// Signature (fake, matching the real Rinternals.h line 1085 intent):
//   inline SEXP Rf_allocVector(SEXPTYPE type, int length);
//   inline SEXP allocVector(SEXPTYPE type, int length);
//
// Real Rinternals.h (line 1085):
//   SEXP Rf_allocVector(SEXPTYPE, R_xlen_t);
// where R_xlen_t is ptrdiff_t on 64-bit and int on 32-bit.
// All rpart call sites pass a plain int length; the fake uses int directly.
//
// Pattern P1 — INTSXP (pred_rpart.c:139, rpart.c:194, rpartexp2.c:47):
//   SEXP where = PROTECT(allocVector(INTSXP, n));
//   ->  Rf_allocVector(INTSXP, n)
//       s->type=13, s->length=n, s->nrow=n, s->ncol=1
//       s->data = int[n], zero-initialized
//   INTEGER(where) returns (int *)where->data
//
// Pattern P2 — REALSXP (xpred.c:209):
//   predict2 = PROTECT(allocVector(REALSXP, n * ncp * nresp));
//   ->  Rf_allocVector(REALSXP, n*ncp*nresp)
//       s->type=14, s->length=n*ncp*nresp, s->nrow=n*ncp*nresp, s->ncol=1
//       s->data = double[n*ncp*nresp], zero-initialized
//   REAL(predict2) returns (double *)predict2->data
//
// Pattern P3 — VECSXP (rpart.c:327):
//   SEXP rlist = PROTECT(allocVector(VECSXP, nout));
//   ->  Rf_allocVector(VECSXP, nout)
//       s->type=19, s->length=nout, s->nrow=nout, s->ncol=1
//       s->data = SEXP[nout], all slots zeroed (nullptr)
//   SET_VECTOR_ELT(rlist, i, child) writes child into ((SEXP*)rlist->data)[i]
//   Python calls free_sexp_deep(rlist) to recursively free child SEXPs.
//
// Pattern P4 — STRSXP (rpart.c:328, no PROTECT):
//   SEXP rname = allocVector(STRSXP, nout);
//   ->  Rf_allocVector(STRSXP, nout)
//       s->type=16, s->length=nout, s->nrow=nout, s->ncol=1
//       s->data = SEXP[nout], all slots zeroed (nullptr, CHARSXP pointers)
//   SET_STRING_ELT(rname, i, mkChar("...")) writes a CHARSXP into each slot.
//   Note: rname is not PROTECT'd in the original source (safe because
//   setAttrib is a no-op in the fake runtime and no GC exists).
//
// Memory lifecycle for all patterns:
//   SEXPREC node   malloc() in Rf_allocVector   Python: free_sexp / free_sexp_deep
//   element buffer malloc() in Rf_allocVector   Python: free_sexp / free_sexp_deep
//   R_alloc scratch arena via ALLOC/R_alloc     ArenaFrame destructor at .Call exit
//
// Invariant 1 (C++ exception-based errors):
//   SEXPREC malloc failure: throw RError("allocVector: out of memory (SEXPREC)")
//   data buffer malloc failure: free SEXPREC node, then throw RError(...)
//   No longjmp, setjmp, abort(), or Rf_error() is used.
//
// Invariant 2 (arena-backed memory without source modification):
//   Rf_allocVector does NOT use the arena.  ArenaFrame at the .Call wrapper
//   boundary governs only ALLOC / R_alloc scratch arrays called in the same
//   function bodies (rp.csplit, rp.lwt, rp.sorts, savesort, etc.).
//
// Invariant 3 (Python function-pointer bridges):
//   Not applicable — allocVector is not an R interpreter item.
// ---------------------------------------------------------------------------

// Compile-time verification: confirm that INTSXP.h's allocVector definition
// is present after the include chain above.  If FAKE_ALLOCVECTOR_DEFINED is
// not set at this point, the include order or guards have been disrupted.
#ifndef FAKE_ALLOCVECTOR_DEFINED
#error "allocVector.h: FAKE_ALLOCVECTOR_DEFINED not set after including INTSXP.h. \
Check that INTSXP.h was not stripped or conditionally excluded."
#endif

// --- Compatibility aliases (preserve original R API names) ---
//
// Original Rinternals.h aliases confirmed from real header inspection:
//
//   Line 1085:  SEXP Rf_allocVector(SEXPTYPE, R_xlen_t);   -- canonical decl
//   Line  896:  #define allocVector    Rf_allocVector       -- user-facing alias
//   Line  897:  #define allocVector3   Rf_allocVector3      -- not used by rpart
//
// INTSXP.h provides both names as inline functions and emits the #define
// alias under an #ifndef guard.  The guard below reproduces the exact alias
// from line 896 of the original header so that any translation unit that
// includes allocVector.h directly (bypassing INTSXP.h) also gets the alias.
//
// Note: because INTSXP.h already defines both inline SEXP allocVector(...)
// and inline SEXP Rf_allocVector(...), and emits:
//   #ifndef allocVector
//   #define allocVector Rf_allocVector
//   #endif
// the #define below will be a no-op in the normal include flow where
// INTSXP.h is already processed.  It is provided for documentation
// completeness and to satisfy the specification requirement of Rule 4.
#ifndef allocVector
#define allocVector    Rf_allocVector
#endif

// allocVector3 — extended form accepting a custom allocator.
// Declared in Rinternals.h line 512 / alias line 897.
// Not used by any rpart source file; provided as a compile-time stub so
// that source files that forward-declare it (e.g., via R.h) still compile.
#ifndef FAKE_ALLOCVECTOR3_DEFINED
#define FAKE_ALLOCVECTOR3_DEFINED
// R_allocator_t is not defined in the fake runtime; provide a minimal
// forward typedef so that Rf_allocVector3 can be declared without error.
#ifndef R_ALLOCATOR_T_DEFINED
#define R_ALLOCATOR_T_DEFINED
typedef struct R_allocator R_allocator_t;
#endif // R_ALLOCATOR_T_DEFINED

// Rf_allocVector3: ignores the custom allocator argument and delegates
// to the standard heap-based Rf_allocVector.  This matches the comment
// in Rinternals.h line 511 ("next is not documented but generated by
// inlined calls to Rf_allocVector").
inline SEXP Rf_allocVector3(SEXPTYPE type, int length,
                             R_allocator_t * /*alloc*/) {
    return Rf_allocVector(type, length);
}

#ifndef allocVector3
#define allocVector3    Rf_allocVector3
#endif
#endif // FAKE_ALLOCVECTOR3_DEFINED

// --- ArenaFrame usage (Category C) ---
//
// allocVector itself is heap-based and does NOT use the arena.  However,
// the four rpart entry points that call allocVector (pred_rpart, rpart,
// rpartexp2, xpred) also call ALLOC / R_alloc for scratch arrays in the
// same function body.  Those scratch allocations ARE arena-managed via
// fake_arena.h.
//
// Declare `ArenaFrame _frame;` as the FIRST statement of any .Call-entry
// wrapper function that enters a function body that calls allocVector
// alongside ALLOC / R_alloc.  The SEXP results of allocVector are
// heap-allocated and survive ArenaFrame destruction; only the scratch
// arrays are freed by the ArenaFrame destructor.
//
// Example wrappers:
//
//   // pred_rpart — Pattern P1 representative
//   extern "C" SEXP pred_rpart_entry(
//           SEXP dimx, SEXP nnode, SEXP nsplit, SEXP dimc,
//           SEXP nnum, SEXP nodes2, SEXP vnum, SEXP split2,
//           SEXP csplit2, SEXP usesur, SEXP xdata2, SEXP xmiss2) {
//       ArenaFrame _frame;   // frees all R_alloc/ALLOC scratch on exit
//       try {
//           return pred_rpart(dimx, nnode, nsplit, dimc, nnum, nodes2,
//                             vnum, split2, csplit2, usesur, xdata2, xmiss2);
//       } catch (const RError &e) {
//           set_python_error(e.what());
//           return R_NilValue;
//       }
//   }
//
//   // rpartexp2 — Pattern P1 representative
//   extern "C" SEXP rpartexp2_entry(SEXP dtimes, SEXP eps) {
//       ArenaFrame _frame;
//       try {
//           return rpartexp2(dtimes, eps);
//       } catch (const RError &e) {
//           set_python_error(e.what());
//           return R_NilValue;
//       }
//   }
//
//   // xpred — Pattern P2 representative
//   extern "C" SEXP xpred_entry(
//           SEXP ncat2, SEXP method2, SEXP opt2, SEXP parms2,
//           SEXP xvals2, SEXP xgrp2, SEXP ymat2, SEXP xmat2,
//           SEXP wt2, SEXP ny2, SEXP cost2, SEXP all2, SEXP cp2,
//           SEXP toprisk2, SEXP nresp2) {
//       ArenaFrame _frame;   // frees rp.sorts, rp.csplit, savesort, etc.
//       try {
//           return xpred(ncat2, method2, opt2, parms2, xvals2, xgrp2,
//                        ymat2, xmat2, wt2, ny2, cost2, all2, cp2,
//                        toprisk2, nresp2);
//       } catch (const RError &e) {
//           set_python_error(e.what());
//           return R_NilValue;
//       }
//   }
//
//   // rpart — Patterns P1, P3, P4 all present in same function body
//   extern "C" SEXP rpart_entry(
//           SEXP ncat2, SEXP method2, SEXP opt2, SEXP parms2,
//           SEXP xvals2, SEXP xgrp2, SEXP ymat2, SEXP xmat2,
//           SEXP wt2, SEXP ny2, SEXP cost2) {
//       ArenaFrame _frame;   // frees ALLOC/R_alloc scratch on exit;
//                            // does NOT free rlist (heap-allocated SEXP)
//       try {
//           return rpart(ncat2, method2, opt2, parms2, xvals2, xgrp2,
//                        ymat2, xmat2, wt2, ny2, cost2);
//       } catch (const RError &e) {
//           set_python_error(e.what());
//           return R_NilValue;
//       }
//   }
//
// SEXP return values (where, keep, predict2, rlist, rname) are all
// heap-allocated via malloc() inside Rf_allocVector and survive ArenaFrame
// destruction.  Python extracts data via INTEGER()/REAL()/VECTOR_ELT() into
// numpy arrays or Python lists, then calls free_sexp_deep() on the top-level
// SEXP (rlist for the rpart() entry point) to release all SEXP memory.
// For simple 1-D vectors (where, keep, predict2), free_sexp() is sufficient.

#endif // FAKE_R_ALLOCVECTOR_H
