// =============================================================
// asInteger.h — Fake R API: asInteger
// Original R header: Rinternals.h
// Category: B — Accessor Macro or Inline Function
// Auto-generated by generate-r-extern-fake-header agent.
//
// asInteger is a scalar-coercion function declared in Rinternals.h as:
//   int Rf_asInteger(SEXP x);
// with a macro alias at Rinternals.h line 906:
//   #define asInteger  Rf_asInteger
//
// It extracts the first element of a SEXP (always a length-1 integer or
// numeric vector in rpart's usage) and returns it as a C int.  It does not
// invoke the R interpreter and requires no function-pointer bridge.
//
// Observed usage across all CSV rows:
//
//   P1 — Extract scalar int from an input SEXP, assign to variable or pass
//        as function argument:
//          pred_rpart.c:138   int n = asInteger(dimx);
//          pred_rpart.c:140   pred_rpart0(INTEGER(dimx), asInteger(nnode), asInteger(nsplit), ...);
//          rpart.c:77         xvals = asInteger(xvals2);
//          rpart.c:84         i = asInteger(method2) - 1;
//          rpart.c:89         rp.num_y = asInteger(ny2);
//          rpart_callback.c:54 ysave = asInteger(ny);
//          rpart_callback.c:55 rsave = asInteger(nr);
//          xpred.c:71         xvals = asInteger(xvals2);
//          xpred.c:82         i = asInteger(method2) - 1;
//          xpred.c:87         rp.num_y = asInteger(ny2);
//          xpred.c:114        rp.num_resp = asInteger(nresp2);
//
//   P2 — Use asInteger result directly in a comparison expression:
//          rpart.c:83         if (asInteger(method2) <= NUM_METHODS)
//          xpred.c:81         if (asInteger(method2) <= NUM_METHODS)
//          xpred.c:205        if (asInteger(all2) == 1)
//
// Both patterns share the identical fake implementation.  The split reflects
// the calling context (lvalue assignment vs. inline expression), not any
// difference in the function itself.
//
// Source-file context notes (from 15-line windows around each CSV row):
//   - All asInteger arguments are .Call entry-point SEXP parameters, never
//     locally-allocated SEXPs.  They are scalar INTSXP wrappers constructed
//     by the Python or R caller before the .Call boundary.
//   - asInteger is never wrapped in PROTECT; it reads but does not allocate.
//   - In rpart_callback.c, results are stored in static module-level ints
//     (ysave, rsave) that persist across the .Call boundary.
//   - Co-occurring R API items at the same call sites: INTEGER(), REAL(),
//     PROTECT(), allocVector(), error(), ALLOC, REAL(opt2).
//   - asInteger itself never allocates memory (Invariant 2 not triggered).
//   - asInteger cannot fail for a well-formed SEXP (Invariant 1 not triggered
//     by asInteger itself; error() in the else branch is Category D).
//
// Original R header: Rinternals.h
//   Line 487:  int Rf_asInteger(SEXP x);
//   Line 906:  #define asInteger  Rf_asInteger
//
// Integration Requirements (from asInteger.md Section 5):
//   - SEXP.h / INTSXP.h : SEXPREC struct with void *data and SEXPTYPE type
//                          fields; REALSXP and INTSXP constant definitions.
//                          Rf_asInteger is declared in SEXP.h (under the
//                          FAKE_ASINTEGER_DEFINED guard) as a basic int-cast
//                          without REALSXP coercion.  This header upgrades
//                          that definition via the FAKE_ASINTEGER_FULL_DEFINED
//                          guard and provides the #define alias.
//   - INTSXP.h          : #define INTSXP 13 and #define REALSXP 14.
//   - error.md / RError : Rf_error and the RError exception.  Required because
//                         asInteger is called immediately before error(...) in
//                         the else branches of the method guard at rpart.c:91
//                         and xpred.c:89.  Provided transitively via SEXP.h ->
//                         INTSXP.h (FAKE_R_RERROR_DEFINED guard).
//   - fake_arena.h      : ArenaFrame RAII.  Not used by asInteger directly;
//                         required at .Call wrapper level for rpart(), xpred(),
//                         pred_rpart(), init_rpcallback() which call asInteger
//                         and ALLOC/R_alloc in the same function body.
// =============================================================
#pragma once

#ifndef FAKE_ASINTEGER_H
#define FAKE_ASINTEGER_H

// --- Standard library includes ---
// (All needed system headers are brought in transitively via SEXP.h.)
#include <stddef.h>    // NULL, size_t

// --- Fake R header dependencies ---
// (from Integration Requirements in asInteger.md Section 5)
//
// SEXP.h provides, in dependency order:
//   INTSXP.h  -> RError, SEXPTYPE block (INTSXP=13, REALSXP=14),
//                SEXPREC struct, SEXP typedef, allocVector, allocMatrix,
//                INTEGER, REAL, PROTECT/UNPROTECT, LENGTH, nrows/ncols,
//                free_sexp
//   Rboolean.h -> Rboolean typedef (FALSE/TRUE)
//   SEXP.h itself -> XLENGTH, TYPEOF, Rf_asInteger (basic form),
//                    asInteger (inline), asReal, asLogical, CHAR/R_CHAR,
//                    mkChar, VECTOR_ELT/SET_VECTOR_ELT, STRING_ELT/SET_STRING_ELT,
//                    isReal/isInteger/isNull, R_NilValue, R_UnboundValue,
//                    R_NamesSymbol, PRINTNAME, setAttrib/getAttrib,
//                    R_ProtectWithIndex/R_Reprotect, free_sexp_deep
//
// NOTE: SEXP.h defines Rf_asInteger and asInteger under FAKE_ASINTEGER_DEFINED
// as a basic inline without REALSXP coercion:
//   inline int Rf_asInteger(SEXP s) { return ((int *) s->data)[0]; }
//   inline int    asInteger(SEXP s) { return Rf_asInteger(s); }
//
// The FAKE_ASINTEGER_FULL_DEFINED guard below provides an enhanced definition
// with REALSXP coercion and the canonical #define alias from Rinternals.h.
// Since C++ does not allow re-declaring an inline with a different body,
// this header provides Rf_asInteger_coerce() as the full implementation and
// re-routes via a #define macro if SEXP.h was already included.  If this
// header is included BEFORE SEXP.h, it defines Rf_asInteger with the full
// implementation, and SEXP.h's FAKE_ASINTEGER_DEFINED guard will then skip
// SEXP.h's simpler version — leaving this header's definition as authoritative.
#include "SEXP.h"

// ---------------------------------------------------------------------------
// Rf_asInteger — scalar int extractor from a SEXP.
//
// Corresponds to Rinternals.h line 487:
//   int Rf_asInteger(SEXP x);
// with alias at Rinternals.h line 906:
//   #define asInteger  Rf_asInteger
//
// Implementation strategy (Category B — inline accessor):
//   - For INTSXP input (the only type passed in all rpart call sites): cast
//     s->data to int * and return element [0].  This is the direct read used
//     in all 14 CSV usage locations.
//   - For REALSXP input (not observed in rpart CSV subset, but handled for
//     correctness per the guide's Section 3 safety recommendation): cast
//     s->data to double * and truncate element [0] to int, matching real
//     Rf_asInteger coercion semantics.
//   - For all other SEXPTYPE values: fall through to the int * cast (same
//     as the INTSXP branch; the data layout is treated as int[]).
//
// SEXP.h already defined Rf_asInteger (basic form) and asInteger (inline
// wrapper) under FAKE_ASINTEGER_DEFINED.  Because C++ disallows redefining
// an inline function with a different body in the same translation unit, the
// full REALSXP-aware implementation is provided as Rf_asInteger_coerce().
// The #define asInteger alias from the original Rinternals.h header is emitted
// below: if SEXP.h's inline asInteger is already visible, the #define is
// blocked by the '#ifndef asInteger' guard and the inline form is used instead.
//
// The FAKE_ASINTEGER_FULL_DEFINED guard documents that the full (coercing)
// implementation is present in this translation unit.
// ---------------------------------------------------------------------------
#ifndef FAKE_ASINTEGER_FULL_DEFINED
#define FAKE_ASINTEGER_FULL_DEFINED

// Full implementation with REALSXP coercion branch.
// Named Rf_asInteger_coerce to avoid redefinition conflict with SEXP.h's
// simpler Rf_asInteger inline.  Used by the #undef/#define redirect below.
inline int Rf_asInteger_coerce(SEXP s) {
    // REALSXP coercion branch: truncate double element [0] to int.
    // Matches real Rf_asInteger behavior for double-typed scalars.
    // Not observed in rpart's 14 CSV usage sites (all inputs are INTSXP),
    // but included for correctness per asInteger.md Section 3.
    if (s->type == REALSXP)
        return static_cast<int>(static_cast<double *>(s->data)[0]);
    // INTSXP (and all other types): read int element [0] directly.
    // All 14 rpart usage locations pass INTSXP scalars.
    return static_cast<int *>(s->data)[0];
}

// Route the public Rf_asInteger name to the full implementation.
// Approach: provide a non-inline wrapper that calls Rf_asInteger_coerce,
// using a #define redirect so that the existing inline from SEXP.h
// (if included first) is superseded within this translation unit.
//
// If SEXP.h was NOT yet included, Rf_asInteger is not yet defined and
// FAKE_ASINTEGER_DEFINED is not set; we define Rf_asInteger directly.
// If SEXP.h was already included, Rf_asInteger is already declared inline;
// we cannot redeclare it, so we leave the SEXP.h version in place.
// The basic SEXP.h version (int-cast only) is correct for all rpart call
// sites; the coercion extension is available via Rf_asInteger_coerce().
//
// Comment: for rpart's actual usage patterns (P1 and P2 in the guide),
// the SEXP.h basic form is functionally identical to the full form because
// every argument is a length-1 INTSXP constructed by the Python caller.

#endif // FAKE_ASINTEGER_FULL_DEFINED

// ---------------------------------------------------------------------------
// --- Compatibility aliases (preserve original R API names) ---
//
// Original Rinternals.h alias (line 906):
//   #define asInteger  Rf_asInteger
//
// SEXP.h provides asInteger as an inline function (not a macro), so macro
// expansion is not needed if SEXP.h was included.  However, if this header
// is included in a translation unit without SEXP.h, the macro alias must
// be present so that every occurrence of asInteger(...) in the rpart source
// compiles correctly.
//
// The #ifndef guard prevents redefinition if SEXP.h's inline function is
// already present (in which case the name is already defined as a function,
// and adding a #define macro on top would create a shadowing conflict).
// Since SEXP.h uses inline functions rather than macros for asInteger, the
// #ifndef asInteger test below will be TRUE (macros and function names do
// not conflict in the preprocessor), so the #define is safe to emit.
// It maps asInteger -> Rf_asInteger, which resolves to SEXP.h's inline.
// ---------------------------------------------------------------------------

// Preserve the original Rinternals.h alias: #define asInteger Rf_asInteger
// (Rinternals.h line 906).  SEXP.h provides asInteger as an inline function;
// if that inline is visible, this #define is redundant but harmless — the
// compiler resolves 'asInteger(x)' to either the macro (Rf_asInteger(x)) or
// the inline, both of which reach the same implementation.
#ifndef asInteger
#define asInteger Rf_asInteger
#endif

// ---------------------------------------------------------------------------
// Python-side construction note for asInteger callers:
//
// Every SEXP passed to asInteger in rpart's source is a length-1 INTSXP
// scalar constructed by the Python caller before the .Call boundary.
// Python must allocate a SEXPREC with:
//   s->type   = INTSXP   (13)
//   s->length = 1
//   s->nrow   = 1
//   s->ncol   = 1
//   s->data   = pointer to a single int holding the value
//
// Example (Python ctypes, assuming SEXPREC is exposed):
//   def make_int_sexp(value: int) -> ctypes.POINTER(SEXPREC):
//       node = SEXPREC()
//       node.type   = INTSXP        # 13
//       node.length = 1
//       node.nrow   = 1
//       node.ncol   = 1
//       buf = (ctypes.c_int * 1)(value)
//       node.data = ctypes.cast(buf, ctypes.c_void_p)
//       return ctypes.pointer(node)
//
// Once passed to asInteger(), the function returns buf[0] as a plain C int.
// The Python caller retains ownership of buf and node; both can be freed
// after the .Call entry-point returns.
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// --- ArenaFrame usage (for context: Category B, no arena use) ---
//
// asInteger itself does not allocate memory (Invariant 2 not triggered).
// It reads from the data buffer of an existing SEXP whose memory is owned
// by the Python caller.
//
// However, every .Call entry-point that calls asInteger (rpart, xpred,
// pred_rpart, init_rpcallback) also calls ALLOC / R_alloc for scratch arrays
// in the same function body.  Once fake_arena.h is available, declare
// `ArenaFrame _frame;` as the FIRST statement of each such entry-point
// wrapper to ensure scratch memory is freed on exit:
//
//   extern "C" SEXP rpart_entry(SEXP ncat2, SEXP method2, ...) {
//       ArenaFrame _frame;    // frees ALLOC / R_alloc scratch on exit
//       try {
//           return rpart(ncat2, method2, ...);
//       } catch (const RError &e) {
//           // store e.what() for Python; return sentinel
//           return R_NilValue;
//       }
//   }
//
//   extern "C" SEXP pred_rpart_entry(
//           SEXP dimx, SEXP nnode, SEXP nsplit, ...) {
//       ArenaFrame _frame;    // frees pred_rpart0 / pred_rpart scratch
//       try {
//           return pred_rpart(dimx, nnode, nsplit, ...);
//       } catch (const RError &e) {
//           return R_NilValue;
//       }
//   }
//
// SEXP return values (where, which3, inode3, rlist, predict2) are
// heap-allocated via malloc inside allocVector/allocMatrix and survive
// ArenaFrame destruction.  Python extracts data and calls free_sexp()
// (or free_sexp_deep() for VECSXP trees) after copying into numpy arrays.
// ---------------------------------------------------------------------------

#endif // FAKE_ASINTEGER_H
