// =============================================================
// asReal.h — Fake R API: asReal
// Original R header: Rinternals.h
// Category: B — Accessor Macro or Inline Function
// Auto-generated by generate-r-extern-fake-header agent.
//
// asReal is a scalar-coercion function declared in Rinternals.h as:
//   double Rf_asReal(SEXP x);
// with a macro alias at Rinternals.h line 910:
//   #define asReal  Rf_asReal
//
// It accepts a single SEXP argument — typically a length-1 real or
// integer vector — and returns the C double value of its first element.
// Unlike REAL(x), which returns a pointer to the entire element buffer,
// asReal extracts and returns only the first element as a scalar double,
// performing a coercion if necessary (e.g., from INTSXP to double).
//
// In rpart's source files, asReal is used exclusively to extract scalar
// floating-point configuration parameters from .Call input arguments,
// converting single-element SEXP wrappers into plain double values for
// use as function arguments or local variable initializers.
//
// asReal is not an R Interpreter Item; it requires no running R
// interpreter and no function-pointer bridge.
//
// Observed usage across all CSV rows:
//
//   P1 — Pass scalar double as a direct function argument:
//          rpartexp2.c:48  Rpartexp2(n, REAL(dtimes), asReal(eps), INTEGER(keep));
//          asReal(eps) converts a length-1 REALSXP to double and passes it as
//          the third positional argument to Rpartexp2 (declared double eps).
//          No intermediate variable is used; the compiler loads the double
//          directly from eps->data[0] into the argument slot.
//
//   P2 — Assign scalar double to a local variable:
//          xpred.c:76  toprisk = asReal(toprisk2);
//          toprisk is declared 'double toprisk;' earlier in xpred().
//          toprisk2 is a .Call input parameter (length-1 REALSXP).
//          The double result is stored in toprisk for later use in the
//          function body.
//
// Both patterns share the identical fake implementation.  The split
// reflects the calling context (direct argument vs. local-variable
// assignment), not any difference in the function itself.
//
// Source-file context notes (from 15-line windows around each CSV row):
//   - rpartexp2.c:48: asReal(eps) co-occurs with REAL(dtimes) and
//     INTEGER(keep) in the same call.  eps is a .Call parameter never
//     wrapped in PROTECT; it is read-only for the duration of the call.
//   - xpred.c:76: asReal(toprisk2) follows six other scalar/vector
//     extractions (INTEGER, asInteger, REAL) on the same input SEXPs.
//     An error() call appears at xpred.c:89 in a subsequent else-branch;
//     the RError exception thrown there propagates through xpred() to
//     the .Call entry-point wrapper's try/catch block.
//   - asReal itself never allocates memory (Invariant 2 not triggered).
//   - asReal cannot fail for a well-formed SEXP (Invariant 1 not
//     triggered by asReal itself; error() at xpred.c:89 is Category D).
//   - asReal is never wrapped in PROTECT.
//   - All SEXP arguments are .Call entry-point parameters (scalar REALSXP
//     wrappers) constructed by the Python caller before the .Call boundary.
//
// Original R header: Rinternals.h
//   Line 488:  double Rf_asReal(SEXP x);
//   Line 910:  #define asReal  Rf_asReal
//
// Integration Requirements (from asReal.md Section 5):
//   - SEXP.h / INTSXP.h : SEXPREC struct with void *data and SEXPTYPE
//                          type fields; INTSXP=13 and REALSXP=14 constants.
//                          SEXP.h already defines Rf_asReal and asReal
//                          (as inline functions, not macros) under the
//                          FAKE_ASINTEGER_DEFINED guard:
//                            inline double Rf_asReal(SEXP s)
//                                { return ((double *) s->data)[0]; }
//                            inline double asReal(SEXP s)
//                                { return Rf_asReal(s); }
//                          This header includes SEXP.h, upgrades the
//                          INTSXP coercion branch via FAKE_ASREAL_FULL_DEFINED,
//                          and emits the #define alias from Rinternals.h.
//   - INTSXP.h          : #define INTSXP 13 and #define REALSXP 14.
//                          Provided transitively via SEXP.h.
//   - asInteger.h       : Rf_asInteger / asInteger parallel accessor.
//                          asReal and asInteger are symmetric functions;
//                          both appear together at xpred.c:71–76.  Both
//                          are already defined in SEXP.h (same guard block).
//   - error.md / RError : Rf_error and the RError exception.  Required
//                         because asReal is called at xpred.c:76 immediately
//                         before the method guard at xpred.c:81–89 which
//                         may invoke error(...) in its else branch.
//                         RError is provided transitively via INTSXP.h.
//   - REAL.h            : The REAL inline accessor.  Used at the same call
//                         site as asReal in rpartexp2.c:48 (REAL(dtimes))
//                         and at nearby lines in xpred.c:72–75 (REAL(wt2),
//                         REAL(parms2), REAL(cp2)).  Both REAL and asReal
//                         cast sexp->data to double *; REAL returns the
//                         pointer, asReal dereferences element [0].
//   - INTEGER.h         : The INTEGER inline accessor.  Used at the same
//                         call site as asReal in rpartexp2.c:48
//                         (INTEGER(keep)) and at nearby lines in
//                         xpred.c:69–70 (INTEGER(ncat2), INTEGER(xgrp2)).
//   - fake_arena.h (not used by asReal directly): ArenaFrame RAII guard;
//                         required at the .Call wrapper level for xpred()
//                         and rpartexp2(), which call asReal and also
//                         invoke arena-backed functions.
// =============================================================
#pragma once

#ifndef FAKE_ASREAL_H
#define FAKE_ASREAL_H

// --- Standard library includes ---
// (All needed system headers are brought in transitively via SEXP.h.)
#include <stddef.h>    // NULL, size_t

// --- Fake R header dependencies ---
// (from Integration Requirements in asReal.md Section 5)
//
// SEXP.h provides, in dependency order:
//   INTSXP.h  -> RError, SEXPTYPE block (INTSXP=13, REALSXP=14),
//                SEXPREC struct, SEXP typedef, allocVector, allocMatrix,
//                INTEGER, REAL, PROTECT/UNPROTECT, LENGTH, nrows/ncols,
//                free_sexp
//   Rboolean.h -> Rboolean typedef (FALSE/TRUE)
//   SEXP.h itself -> XLENGTH, TYPEOF, Rf_asInteger (basic form),
//                    asInteger (inline), Rf_asReal (basic form),
//                    asReal (inline), asLogical, CHAR/R_CHAR, mkChar,
//                    VECTOR_ELT/SET_VECTOR_ELT, STRING_ELT/SET_STRING_ELT,
//                    isReal/isInteger/isNull, R_NilValue, R_UnboundValue,
//                    R_NamesSymbol, PRINTNAME, setAttrib/getAttrib,
//                    R_ProtectWithIndex/R_Reprotect, free_sexp_deep
//
// NOTE: SEXP.h defines Rf_asReal and asReal under FAKE_ASINTEGER_DEFINED
// as basic inline functions without INTSXP coercion:
//   inline double Rf_asReal(SEXP s) { return ((double *) s->data)[0]; }
//   inline double    asReal(SEXP s) { return Rf_asReal(s); }
//
// The FAKE_ASREAL_FULL_DEFINED guard below documents that the full
// INTSXP-aware implementation is intended for this translation unit.
// Since C++ disallows re-declaring an inline with a different body,
// the coercion extension is provided as Rf_asReal_coerce() and the
// basic SEXP.h form remains authoritative for rpart's actual call sites
// (all of which pass REALSXP scalars, so the INTSXP branch is a safety
// measure only).
#include "SEXP.h"

// ---------------------------------------------------------------------------
// Rf_asReal — scalar double extractor from a SEXP.
//
// Corresponds to Rinternals.h line 488:
//   double Rf_asReal(SEXP x);
// with alias at Rinternals.h line 910:
//   #define asReal  Rf_asReal
//
// Implementation strategy (Category B — inline accessor):
//   - For REALSXP input (the primary type for all rpart call sites):
//     cast s->data to double * and return element [0].  This is the
//     direct read used in both CSV usage locations.
//   - For INTSXP input (not observed in rpart CSV subset, but handled
//     for correctness per asReal.md Section 3 safety recommendation):
//     cast s->data to int * and widen element [0] to double, matching
//     real Rf_asReal coercion semantics for integer scalars.
//   - For all other SEXPTYPE values: fall through to the double * cast.
//
// SEXP.h already defined Rf_asReal (basic form, double-cast only) and
// asReal (inline wrapper) under FAKE_ASINTEGER_DEFINED.  Because C++
// disallows redefining an inline function with a different body in the
// same translation unit, the INTSXP-coercing implementation is provided
// as Rf_asReal_coerce() for completeness.  The SEXP.h basic form is
// functionally correct for all rpart call sites (all arguments are
// length-1 REALSXP constructed by the Python caller).
//
// Pattern P1 coverage (rpartexp2.c:48):
//   Rpartexp2(n, REAL(dtimes), asReal(eps), INTEGER(keep));
//   asReal(eps) expands to Rf_asReal(eps), which returns:
//     static_cast<double *>(eps->data)[0]
//   The result is the first (and only) element of the eps REALSXP,
//   passed directly as the third argument to Rpartexp2(int n,
//   double *y, double eps, int *keep).
//
// Pattern P2 coverage (xpred.c:76):
//   toprisk = asReal(toprisk2);
//   asReal(toprisk2) expands to Rf_asReal(toprisk2), which returns:
//     static_cast<double *>(toprisk2->data)[0]
//   The result is assigned to the local variable 'double toprisk'
//   declared earlier in xpred().  toprisk is used in subsequent
//   computation in the xpred function body.
// ---------------------------------------------------------------------------
#ifndef FAKE_ASREAL_FULL_DEFINED
#define FAKE_ASREAL_FULL_DEFINED

// Full implementation with INTSXP coercion branch.
// Named Rf_asReal_coerce to avoid redefinition conflict with SEXP.h's
// simpler Rf_asReal inline.  Provides explicit INTSXP->double widening
// for callers that need the full coercion semantics (not used by rpart).
inline double Rf_asReal_coerce(SEXP s) {
    // INTSXP coercion branch: widen int element [0] to double.
    // Matches real Rf_asReal behavior for integer-typed scalars.
    // Not observed in rpart's CSV usage sites (all inputs are REALSXP),
    // but included for correctness per asReal.md Section 3.
    if (s->type == INTSXP)
        return static_cast<double>(static_cast<int *>(s->data)[0]);
    // REALSXP (and all other types): read double element [0] directly.
    // Both rpart usage locations (rpartexp2.c:48, xpred.c:76) pass
    // REALSXP scalars; this is the primary execution path.
    return static_cast<double *>(s->data)[0];
}

// Note: Rf_asReal (the canonical name) is already defined as an inline
// by SEXP.h under the FAKE_ASINTEGER_DEFINED guard:
//   inline double Rf_asReal(SEXP s) { return ((double *) s->data)[0]; }
// The basic form is correct for all rpart call sites.  Rf_asReal_coerce
// is available for use cases requiring the INTSXP safety branch.

#endif // FAKE_ASREAL_FULL_DEFINED

// ---------------------------------------------------------------------------
// --- Compatibility aliases (preserve original R API names) ---
//
// Original Rinternals.h alias (line 910):
//   #define asReal  Rf_asReal
//
// SEXP.h provides asReal as an inline function (not a macro), so macro
// expansion is not strictly needed if SEXP.h was included first.
// However, if this header is included in a translation unit without
// SEXP.h, the macro alias must be present so that every occurrence of
// asReal(...) in the rpart source compiles correctly.
//
// The #ifndef guard prevents redefinition if SEXP.h's inline function
// is already present.  Since SEXP.h uses inline functions rather than
// macros for asReal, the #ifndef asReal test will be TRUE (macros and
// function names do not conflict in the preprocessor), so the #define
// is safe to emit.  It maps asReal -> Rf_asReal, which resolves to
// SEXP.h's inline function (double-cast, correct for REALSXP scalars).
// ---------------------------------------------------------------------------

// Preserve the original Rinternals.h alias: #define asReal Rf_asReal
// (Rinternals.h line 910).  SEXP.h provides asReal as an inline function;
// if that inline is visible, this #define is redundant but harmless — the
// compiler resolves 'asReal(x)' to either the macro (Rf_asReal(x)) or
// the inline, both of which reach the same implementation.
#ifndef asReal
#define asReal Rf_asReal
#endif

// ---------------------------------------------------------------------------
// Python-side construction note for asReal callers:
//
// Every SEXP passed to asReal in rpart's source is a length-1 REALSXP
// scalar constructed by the Python caller before the .Call boundary.
// Python must allocate a SEXPREC with:
//   s->type   = REALSXP  (14)
//   s->length = 1
//   s->nrow   = 1
//   s->ncol   = 1
//   s->data   = pointer to a single double holding the value
//
// Example (Python ctypes, assuming SEXPREC is exposed):
//   def make_real_sexp(value: float) -> ctypes.POINTER(SEXPREC):
//       node = SEXPREC()
//       node.type   = REALSXP       # 14
//       node.length = 1
//       node.nrow   = 1
//       node.ncol   = 1
//       buf = (ctypes.c_double * 1)(value)
//       node.data = ctypes.cast(buf, ctypes.c_void_p)
//       return ctypes.pointer(node)
//
// Usage at rpartexp2.c:48 (Pattern P1):
//   eps_sexp = make_real_sexp(1e-6)
//   # asReal(eps_sexp) -> Rf_asReal(eps_sexp) -> eps_sexp->data[0] == 1e-6
//   # passed as third argument to Rpartexp2(..., 1e-6, ...)
//
// Usage at xpred.c:76 (Pattern P2):
//   toprisk2_sexp = make_real_sexp(0.05)
//   # toprisk = asReal(toprisk2_sexp) -> toprisk2_sexp->data[0] == 0.05
//   # stored in local variable toprisk for later computation in xpred()
//
// Once passed to asReal(), the function returns buf[0] as a plain C double.
// The Python caller retains ownership of buf and node; both can be freed
// after the .Call entry-point returns.
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// --- ArenaFrame usage (for context: Category B, no arena use) ---
//
// asReal itself does not allocate memory (Invariant 2 not triggered).
// It reads from the data buffer of an existing SEXP whose memory is owned
// by the Python caller.
//
// However, every .Call entry-point that calls asReal (rpartexp2, xpred)
// also calls ALLOC / R_alloc for scratch arrays in the same function body.
// Once fake_arena.h is available, declare `ArenaFrame _frame;` as the
// FIRST statement of each such entry-point wrapper to ensure scratch
// memory is freed on exit:
//
//   #include "fake_arena.h"
//   extern "C" SEXP rpartexp2_entry(SEXP dtimes, SEXP eps) {
//       ArenaFrame _frame;    // frees any R_alloc/ALLOC scratch on exit
//       try {
//           return rpartexp2(dtimes, eps);
//           // Inside rpartexp2.c:48: Rpartexp2(n, REAL(dtimes),
//           //                                    asReal(eps), INTEGER(keep));
//           // asReal(eps) -> Rf_asReal(eps) -> ((double *) eps->data)[0]
//       } catch (const RError &e) {
//           set_python_error(e.what());
//           return nullptr;
//       }
//   }
//
//   extern "C" SEXP xpred_entry(
//           SEXP ncat2, SEXP method2, SEXP opt2,
//           SEXP parms2, SEXP xvals2, SEXP xgrp2,
//           SEXP ymat2, SEXP xmat2, SEXP wt2,
//           SEXP ny2, SEXP cost2, SEXP all2, SEXP cp2,
//           SEXP toprisk2, SEXP nresp2) {
//       ArenaFrame _frame;    // frees ALLOC/R_alloc scratch arrays on exit
//       try {
//           return xpred(ncat2, method2, opt2, parms2, xvals2, xgrp2,
//                        ymat2, xmat2, wt2, ny2, cost2, all2, cp2,
//                        toprisk2, nresp2);
//           // Inside xpred.c:76: toprisk = asReal(toprisk2);
//           // asReal(toprisk2) -> ((double *) toprisk2->data)[0]
//       } catch (const RError &e) {
//           set_python_error(e.what());    // store for Python to read
//           return nullptr;
//       }
//   }
//
// The error() call at xpred.c:89 (in the else branch of the method guard
// at lines 81–89) throws RError via Rf_error.  The try/catch in
// xpred_entry() catches it and converts it to a Python-side error.
// asReal at xpred.c:76 executes before the method guard, so it always
// succeeds regardless of whether the guard later throws.
//
// SEXP return values are heap-allocated via malloc inside allocVector /
// allocMatrix and survive ArenaFrame destruction.  Python extracts data
// and calls free_sexp() (or free_sexp_deep() for VECSXP trees) after
// copying into numpy arrays.
// ---------------------------------------------------------------------------

#endif // FAKE_ASREAL_H
