// =============================================================
// CHAR.h — Fake R API: CHAR
// Original R header: Rinternals.h
// Category: B — Accessor Macro or Inline Function
// Auto-generated by generate-r-extern-fake-header agent.
//
// CHAR is a macro defined in Rinternals.h line 203 as:
//
//   #define CHAR(x)  R_CHAR(x)
//   const char *(R_CHAR)(SEXP x);          // line 204
//
// It accepts a single SEXP of type CHARSXP (SEXPTYPE = 9) and returns
// a const char * pointer to the null-terminated C string stored in the
// node's data field.  CHAR is a pure read accessor — it performs no
// allocation, contacts no R interpreter, and does not depend on libR.so.
//
// Observed usage in rpart source (from CSV):
//
//   rpart_callback.c:24
//     error(_("variable '%s' not found"), CHAR(PRINTNAME(sym)));
//     Pattern P1: Extract const char* from a symbol's name CHARSXP for use
//     in an error message.  sym is a SYMSXP; PRINTNAME(sym) returns the child
//     CHARSXP; CHAR converts that node's data field to const char*.
//     The entire expression is the %s argument to error() / Rf_error().
//
// Additional R API items in the same context window (rpart_callback.c:18-28):
//   PRINTNAME(sym)         — extracts name CHARSXP from a SYMSXP
//   error(fmt, ...)        — #define error Rf_error; throws RError
//   findVar / findVarInFrame — Category E stubs producing the val compared
//                              against R_UnboundValue at line 23
//   R_UnboundValue         — sentinel SEXP for "variable not found"
//   Rboolean inherits      — controls which find* function is called
//
// Original R header verified at:
//   ~/.conda/envs/r-to-python/lib/R/include/Rinternals.h
//   Line 203:  #define CHAR(x)  R_CHAR(x)
//   Line 204:  const char *(R_CHAR)(SEXP x);
//   Line 588:  const char * Rf_translateChar(SEXP);
//   Line 589:  const char * Rf_translateCharUTF8(SEXP);
//   Line 1058: #define translateChar     Rf_translateChar
//   Line 1060: #define translateCharUTF8 Rf_translateCharUTF8
//
// New symbols added by this header (not already present in SEXP.h):
//   - Rf_translateChar / translateChar
//   - Rf_translateCharUTF8 / translateCharUTF8
//
// Symbols defined in SEXP.h (under their own guards, reused here):
//   - R_CHAR (FAKE_CHAR_DEFINED in SEXP.h lines 188-200)
//   - #define CHAR(x) R_CHAR(x) (same guard)
//   - PRINTNAME (FAKE_PRINTNAME_DEFINED in SEXP.h)
//   - mkChar / Rf_mkChar (FAKE_MKCHAR_DEFINED in SEXP.h)
//
// Invariant applicability:
//   Invariant 1 (C++ exception errors): not triggered by CHAR itself.
//     error() at line 24 consumes the const char* returned by CHAR;
//     Rf_error is governed by the error/Rf_error fake guide and SEXP.h.
//   Invariant 2 (arena memory): not triggered. CHAR / R_CHAR is a pure
//     read accessor; it neither allocates nor frees any memory.
//   Invariant 3 (R Interpreter Items): not triggered by CHAR itself.
//     The surrounding compat_getVar function uses findVar / findVarInFrame
//     (Category E), but CHAR operates on an already-constructed SEXP.
//
// Integration Requirements (from CHAR.md Section 5):
//   SEXP.h         — SEXPREC struct (data field as void*), SEXP typedef,
//                    CHARSXP = 9, SYMSXP = 1, R_CHAR + #define CHAR,
//                    PRINTNAME, mkChar, R_NilValue, R_UnboundValue,
//                    R_NamesSymbol, RError, Rf_error, setAttrib, getAttrib,
//                    VECTOR_ELT, SET_VECTOR_ELT, STRING_ELT, SET_STRING_ELT,
//                    free_sexp_deep.
//   INTSXP.h       — (included transitively via SEXP.h) provides SEXPTYPE
//                    constant block (CHARSXP = 9), allocVector, allocMatrix,
//                    INTEGER, REAL, PROTECT, UNPROTECT, LENGTH, nrows, ncols.
//   R_UnboundValue.h — (listed as dependency in guide) provides guarded
//                    fallback for R_UnboundValue, get_R_UnboundValue(), and
//                    the #define error Rf_error alias via R_NilValue.h.
//   R_VERSION.h    — provides R_VERSION macro and R_Version(major,minor,patch)
//                    so that #if R_VERSION < R_Version(4, 5, 0) in
//                    rpart_callback.c evaluates to true, compiling
//                    compat_getVar and the CHAR(PRINTNAME(sym)) expression.
// =============================================================
#pragma once

#ifndef FAKE_CHAR_H
#define FAKE_CHAR_H

// --- Standard library includes ---
#include <stddef.h>    // NULL, size_t

// --- Fake R header dependencies ---
// (from Integration Requirements in CHAR.md Section 5, in dependency order)
//
// SEXP.h provides (transitively via INTSXP.h and Rboolean.h):
//   - RError C++ exception struct (FAKE_R_RERROR_DEFINED)
//   - SEXPTYPE typedef + full constant block: NILSXP=0, SYMSXP=1, CHARSXP=9,
//     INTSXP=13, REALSXP=14, STRSXP=16, VECSXP=19, EXPRSXP=20, etc.
//   - struct SEXPREC { SEXPTYPE type; int length; int nrow; int ncol; void *data; }
//   - typedef SEXPREC *SEXP
//   - allocVector, allocMatrix, Rf_allocVector, Rf_allocMatrix
//   - INTEGER, REAL, LOGICAL, RAW, Rf_INTEGER, Rf_REAL
//   - LENGTH, Rf_length, Rf_nrows, Rf_ncols
//   - PROTECT, UNPROTECT, UNPROTECT_PTR, PROTECT_WITH_INDEX, REPROTECT
//   - Rboolean (FALSE=0, TRUE=1)
//   - R_NilValue singleton (NILSXP)
//   - R_UnboundValue sentinel (SYMSXP) — primary definition
//   - R_NamesSymbol sentinel (SYMSXP)
//   - TYPEOF, isReal, isInteger, isNull, asInteger, asReal, asLogical
//   - R_CHAR inline function + #define CHAR(x) R_CHAR(x)   <-- primary def.
//   - PRINTNAME inline function
//   - mkChar / Rf_mkChar
//   - VECTOR_ELT, SET_VECTOR_ELT, STRING_ELT, SET_STRING_ELT
//   - setAttrib / getAttrib no-op stubs
//   - R_ProtectWithIndex, R_Reprotect no-ops
//   - free_sexp_deep and the free_sexp macro redirect
//   - XLENGTH / Rf_xlength
//   - NA_STRING / R_NaString
//   - Rf_error (via transitively included R_NilValue.h)
//   - #define error Rf_error (via R_NilValue.h)
#include "SEXP.h"

// R_UnboundValue.h provides:
//   - Guarded fallback definition of R_UnboundValue (if SEXP.h was not
//     already included; the guard prevents double definition).
//   - get_R_UnboundValue() extern "C" accessor for Python ctypes interop.
//   - Transitively re-includes R_NilValue.h (Rf_error, #define error, etc.).
// Required because CHAR(PRINTNAME(sym)) at rpart_callback.c:24 is inside the
// if (val == R_UnboundValue) branch; R_UnboundValue must be defined in the
// same translation unit.
#include "R_UnboundValue.h"

// R_VERSION.h provides:
//   - R_VERSION macro (e.g., #define R_VERSION 0x040400) set to a value
//     below R_Version(4, 5, 0) in the fake build, so that the preprocessor
//     condition #if R_VERSION < R_Version(4, 5, 0) in rpart_callback.c
//     evaluates to true, compiling compat_getVar and the R_getVar shim.
//   - R_Version(major, minor, patch) macro for the comparison.
// Without this header, the entire compat_getVar function (and the
// CHAR(PRINTNAME(sym)) expression at line 24) would be compiled out.
#include "R_VERSION.h"

// ---------------------------------------------------------------------------
// R_CHAR / CHAR — Category B: accessor macro / inline function.
//
// Pattern P1: Extract const char* from a symbol's name CHARSXP.
// Location: rpart_callback.c:24
//
//   error(_("variable '%s' not found"), CHAR(PRINTNAME(sym)));
//
// Original Rinternals.h declarations (lines 203-204):
//   #define CHAR(x)  R_CHAR(x)
//   const char *(R_CHAR)(SEXP x);
//
// The parentheses around R_CHAR in the declaration suppress macro expansion
// in the declaration itself (standard C/C++ convention for functions that
// have a macro alias).
//
// Fake implementation: R_CHAR casts s->data (void*) to const char*.
// In the fake SEXPREC (from INTSXP.h / SEXP.h), a CHARSXP node stores its
// string in the void* data field as a char* to a null-terminated buffer
// allocated by mkChar() via malloc().  The cast is the complete
// implementation; no allocation, no interpreter interaction.
//
// For the specific usage at line 24:
//   sym                   — SYMSXP; sym->data points to a child CHARSXP node
//   PRINTNAME(sym)        — returns static_cast<SEXP>(sym->data)  (CHARSXP)
//   CHAR(PRINTNAME(sym))  — R_CHAR(charsxp)
//                         — static_cast<const char*>(charsxp->data)
//                         — the null-terminated symbol name string
//
// Precondition: s must be non-null and s->data must point to a valid
// null-terminated string.  For CHARSXP nodes produced by mkChar() or
// by the install() stub, this is always satisfied.
//
// NOTE: The primary definition of R_CHAR and #define CHAR(x) R_CHAR(x)
// lives in SEXP.h under the FAKE_CHAR_DEFINED guard (included above).
// The block below is a guarded fallback for translation units that include
// CHAR.h without having previously included SEXP.h.  In practice, the
// include of SEXP.h above always fires first, making this block a no-op.
// It is retained so CHAR.h is self-contained when included standalone.
// ---------------------------------------------------------------------------
#ifndef FAKE_CHAR_DEFINED
#define FAKE_CHAR_DEFINED

// R_CHAR — inline function matching the real Rinternals.h declaration.
// The const char* cast reads the data field of any SEXPREC node.
// When called on a CHARSXP (type==9), data holds a malloc'd C string buffer.
inline const char *R_CHAR(SEXP s) {
    return static_cast<const char *>(s->data);
}

// Preserve the original Rinternals.h alias verbatim (line 203):
//   #define CHAR(x)  R_CHAR(x)
// This ensures every occurrence of CHAR(...) in the rpart source files
// expands to a call to the inline R_CHAR function without any source
// modification.
#ifndef CHAR
#define CHAR(x) R_CHAR(x)
#endif

#endif // FAKE_CHAR_DEFINED

// ---------------------------------------------------------------------------
// translateChar / translateCharUTF8 — re-encoding helpers.
//
// Original Rinternals.h declarations and aliases:
//   Line 588:  const char * Rf_translateChar(SEXP);
//   Line 589:  const char * Rf_translateCharUTF8(SEXP);
//   Line 1058: #define translateChar      Rf_translateChar
//   Line 1059: #define translateChar0     Rf_translateChar0     (not aliased here)
//   Line 1060: #define translateCharUTF8  Rf_translateCharUTF8
//
// The real implementations consult R's internal encoding infrastructure
// (locale, CE_UTF8, CE_LATIN1 flags on the CHARSXP node) to return a
// re-encoded string in the requested encoding.  The fake runtime has no
// encoding infrastructure; all strings are assumed to be plain ASCII or
// the system locale encoding.  The raw data pointer from R_CHAR is returned
// unchanged — this is the correct behaviour for ASCII symbols (the only
// strings that appear in rpart source files via PRINTNAME / mkChar).
//
// These aliases are required so that any transitively included header or
// source file that calls translateChar() compiles without modification.
// rpart does not call translateChar directly in the CSV usage set, but
// the declarations are unconditionally present in Rinternals.h and must
// therefore be present in the fake header set.
//
// Guarded by FAKE_TRANSLATECHAR_DEFINED to prevent redefinition if a future
// combined fake_Rinternals.hpp also provides these functions.
// ---------------------------------------------------------------------------
#ifndef FAKE_TRANSLATECHAR_DEFINED
#define FAKE_TRANSLATECHAR_DEFINED

// Rf_translateChar — returns raw C string from any CHARSXP-like SEXP.
// No encoding conversion in the fake runtime (no locale support).
inline const char *Rf_translateChar(SEXP s) {
    return R_CHAR(s);
}

// Rf_translateCharUTF8 — returns raw C string, nominally as UTF-8.
// In the fake runtime: identical to Rf_translateChar (no conversion).
inline const char *Rf_translateCharUTF8(SEXP s) {
    return R_CHAR(s);
}

// Preserve the original Rinternals.h #define aliases (lines 1058, 1060):
//   #define translateChar      Rf_translateChar
//   #define translateCharUTF8  Rf_translateCharUTF8
#ifndef translateChar
#define translateChar      Rf_translateChar
#endif

#ifndef translateCharUTF8
#define translateCharUTF8  Rf_translateCharUTF8
#endif

#endif // FAKE_TRANSLATECHAR_DEFINED

// ---------------------------------------------------------------------------
// --- Compatibility aliases (preserve original R API names) ---
//
// Primary aliases already emitted above under their respective guards:
//   #define CHAR(x) R_CHAR(x)          — in FAKE_CHAR_DEFINED block
//   #define translateChar      Rf_translateChar      — in FAKE_TRANSLATECHAR_DEFINED
//   #define translateCharUTF8  Rf_translateCharUTF8  — in FAKE_TRANSLATECHAR_DEFINED
//
// Aliases provided by SEXP.h (included above) and therefore already visible
// in any translation unit that includes CHAR.h:
//   #define error   Rf_error            (via R_NilValue.h, included by SEXP.h)
//   #define PROTECT(s)  Rf_protect(s)   (via INTSXP.h, included by SEXP.h)
//   #define UNPROTECT(n) Rf_unprotect(n)
//   #define nrows(x) Rf_nrows(x)
//   #define ncols(x) Rf_ncols(x)
//   #define NA_STRING  R_NaString
//
// No additional aliases are required for CHAR itself beyond those listed.
// The real Rinternals.h defines no other #define for CHAR or R_CHAR.
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Composition note: CHAR(PRINTNAME(sym)) — full call chain
// (rpart_callback.c line 24, inside compat_getVar compiled when
//  R_VERSION < R_Version(4, 5, 0))
//
//   sym                         // SYMSXP: sym->data == &charsxp_node
//   PRINTNAME(sym)              // returns static_cast<SEXP>(sym->data)
//                               //   == &charsxp_node  (type CHARSXP, =9)
//   CHAR(PRINTNAME(sym))        // R_CHAR(&charsxp_node)
//                               //   == static_cast<const char*>(charsxp_node.data)
//                               //   == "yback" (or whatever symbol name)
//
// The const char* is passed as the %s argument to:
//   error(_("variable '%s' not found"), CHAR(PRINTNAME(sym)));
// which expands (via #define error Rf_error and #define _(s) (s)) to:
//   Rf_error("variable '%s' not found", <symbol_name>)
// Rf_error formats the message via vsnprintf and throws RError (Invariant 1).
//
// For correctness:
//   - The install() fake stub (Category E) must construct the sym SYMSXP with
//     sym->data pointing to a valid CHARSXP child node produced by mkChar().
//   - If sym->data is NULL (as it is for R_UnboundValue), PRINTNAME returns
//     R_NilValue (NILSXP, data=NULL).  R_CHAR on R_NilValue returns NULL,
//     which would produce undefined behavior in the vsnprintf %s format.
//     This situation cannot arise in practice because CHAR(PRINTNAME(sym))
//     is only reached with the sym argument passed into compat_getVar, which
//     originates from install("yback") etc. — always a well-formed SYMSXP.
// ---------------------------------------------------------------------------

#endif // FAKE_CHAR_H
