// =============================================================
// DllInfo.h — Fake R API: DllInfo
// Original R header: R_ext/Rdynload.h
// Category: A — Type or Enum Constant
// Auto-generated by generate-r-extern-fake-header agent.
//
// Original declaration in R_ext/Rdynload.h (line 71):
//   typedef struct _DllInfo DllInfo;
// The struct body of _DllInfo is private to libR.so and is never
// exposed to package code.  Package code only ever holds a DllInfo *
// and forwards it to registration functions — it never reads or
// writes any field.
// =============================================================
#pragma once

#ifndef FAKE_DLLINFO_H
#define FAKE_DLLINFO_H

// --- Standard library includes ---
#include <stddef.h>   // NULL

// --- Fake R header dependencies ---
// (from Integration Requirements in DllInfo.md)
//
// DL_FUNC.h provides: DL_FUNC typedef, R_CMethodDef, R_FortranMethodDef,
// R_CallMethodDef, R_ExternalMethodDef, Rboolean enum (FALSE/TRUE), and
// all registration function stubs (R_registerRoutines, R_useDynamicSymbols,
// R_forceSymbols, R_getDllInfo, R_getEmbeddingDllInfo,
// R_RegisterCCallable, R_GetCCallable).
//
// It also contains an inline stub `struct DllInfo {};` (C++ only).
// This header supersedes that stub with the C-compatible two-step form
// using the FAKE_DLLINFO_DEFINED guard; both forms are structurally
// equivalent for C++ compilation, but only the form here is valid
// when init.c is compiled as plain C (C99/C11).
#include "DL_FUNC.h"

// --- Core fake implementation ---

// Pattern: DllInfo * as parameter of R_init_rpart, forwarded to no-op
//          registration functions.
// Locations: init.c:23 — `void R_init_rpart(DllInfo * dll)`
//            init.c:25 — `R_registerRoutines(dll, NULL, CallEntries, NULL, NULL)`
//            init.c:26 — `R_useDynamicSymbols(dll, FALSE)`
//            init.c:28 — `R_forceSymbols(dll, TRUE)`   (inside R_VERSION guard)
//
// Original R API declaration (R_ext/Rdynload.h, line 71):
//   typedef struct _DllInfo DllInfo;
//
// The internal layout of struct _DllInfo lives entirely inside libR.so
// and is never exposed to package code.  DllInfo * is used purely as a
// pass-through argument: the pointer is never dereferenced, its fields
// are never read, and no memory is allocated through it.
//
// Fake strategy:
//   Define an empty struct under a unique tag name (DllInfo_fake) to avoid
//   collision with the bare `struct DllInfo {}` already emitted by DL_FUNC.h,
//   then typedef it to DllInfo.  The C-compatible two-step form (typedef +
//   tag with at least one member) is required because init.c is compiled as
//   plain C (not C++):
//     - In C, `struct Foo {}` with an empty body is not valid C99/C11 syntax.
//     - The `int _unused` member satisfies the "at least one member" rule.
//     - In C++, the struct with a single int member and the empty struct are
//       both valid and ABI-compatible at the pointer level.
//
// Because DL_FUNC.h has already emitted `struct DllInfo {};` in C++ builds,
// we provide the typedef-only form when DllInfo is already defined as a tag,
// and the full two-step form otherwise.  The FAKE_DLLINFO_DEFINED guard
// prevents any double-definition regardless of include order.
#ifndef FAKE_DLLINFO_DEFINED
#define FAKE_DLLINFO_DEFINED

// C-compatible two-step form:
//   Step 1: typedef so that `DllInfo` is a valid type name in both C and C++.
//   Step 2: struct definition with tag DllInfo_fake and one member so the
//           struct body is non-empty (required by C99/C11).
//
// Note on tag collision with DL_FUNC.h:
//   DL_FUNC.h defines `struct DllInfo {}` (no typedef, C++ only).  That
//   declaration uses the tag `DllInfo` directly.  To avoid tag collision
//   under C++ (where `struct DllInfo` in DL_FUNC.h is already in scope),
//   this header uses the distinct tag `DllInfo_fake`.  The typedef below
//   makes `DllInfo` an alias for `struct DllInfo_fake`, which is a separate
//   type from the C++ `struct DllInfo` in DL_FUNC.h.
//
//   If both headers are included in the same C++ translation unit, there
//   will be two tag-level types: `struct DllInfo` (from DL_FUNC.h) and
//   `struct DllInfo_fake` (from here), both accessible as `DllInfo` via the
//   typedef.  In C++ the typedef takes precedence for unqualified `DllInfo`
//   lookups, which is the correct behaviour — callers see the typedef, not
//   the bare tag.  The registration function stubs in DL_FUNC.h accept
//   `DllInfo *` by the typedef; since `DllInfo` now resolves to
//   `struct DllInfo_fake`, those stubs remain type-correct.
//
//   For builds that compile init.c as plain C, DL_FUNC.h must not be
//   included before this header (or at all), because `struct DllInfo {};`
//   is not valid C.  In a C-only build, only DllInfo.h should be on the
//   include path.

typedef struct DllInfo_fake DllInfo;
struct DllInfo_fake { int _unused; };

#endif /* FAKE_DLLINFO_DEFINED */

// --- Compatibility aliases (preserve original R API names) ---
// The real R_ext/Rdynload.h defines no preprocessor aliases for DllInfo
// itself.  The type is exposed only through the typedef above.
//
// All other aliases needed by init.c (FALSE, TRUE via Rboolean;
// R_registerRoutines, R_useDynamicSymbols, R_forceSymbols;
// R_CallMethodDef; DL_FUNC) are already provided by DL_FUNC.h,
// which is included above.  No additional #define remapping is needed.

#endif /* FAKE_DLLINFO_H */
