// =============================================================
// FALSE.h — Fake R API: FALSE
// Original R header: R_ext/Boolean.h
// Category: A — Type or Enum Constant (enumerator of Rboolean)
// Auto-generated by generate-r-extern-fake-header agent.
//
// NOTE: The original R header at
//   ~/.conda/envs/r-to-python/lib/R/include/R_ext/Boolean.h
// could not be found at that path; the definition below is
// reproduced from the authoritative Markdown guide (FALSE.md).
//
// `FALSE` is enumerator `0` of the `Rboolean` typedef enum defined in
// R_ext/Boolean.h.  Its integer value is 0.  The real R header issues
// `#undef FALSE` before the enum declaration so that any prior macro
// definition (e.g., from <stdbool.h> or <cstdbool>) is replaced by
// the enumerator.  FALSE is NOT a macro in the compiled program; it is
// a named constant of type Rboolean.
//
// Observed usage in rpart source:
//
//   init.c:26
//     R_useDynamicSymbols(dll, FALSE);
//       -- second argument type: Rboolean
//          (no-op in the fake build; FALSE must be integer-compatible)
//
//   rpart_callback.c:59,62,65,68
//     stemp = R_getVar(install("yback"), rho, FALSE);
//       -- third argument `inherits` declared as Rboolean in
//          compat_getVar (the compatibility shim compiled when
//          R_VERSION < R_Version(4, 5, 0)).
//          Passing FALSE (== 0) causes the ternary
//            inherits ? findVar(sym,rho) : findVarInFrame(rho,sym)
//          to take the findVarInFrame branch.
//
// Implementation strategy (FALSE.md Section 3):
//   FALSE is produced as a side effect of the Rboolean enum declaration.
//   This guide does not introduce a new enum; it delegates entirely to
//   Rboolean.h (already present in the output folder), which issues
//   `#undef FALSE`, `#undef TRUE`, and then:
//     typedef enum { FALSE = 0, TRUE = 1 } Rboolean;
//   Including Rboolean.h is therefore sufficient to make FALSE visible.
//
// Integration Requirements satisfied here (FALSE.md Section 5):
//   - Rboolean.h : present in output folder — provides the enum definition
//                  that places FALSE = 0 in enclosing scope.
//   - DllInfo.h, R_CallMethodDef.h, DL_FUNC.h : required by init.c (same
//     translation unit), NOT by FALSE itself; included by fake_R.h.
//   - SEXP.h / INTSXP.h / REALSXP.h : required by rpart_callback.c,
//     NOT by FALSE itself; included by fake_R.h.
//   - fake_Rversion.h (not yet generated) : must define R_VERSION to a
//     value < R_Version(4, 5, 0) so compat_getVar is compiled.
//   - install.h, R_getVar.h, findVar.h, findVarInFrame.h (Category E) :
//     required by rpart_callback.c call sites, NOT by FALSE itself.
//   - error.h / Rf_error.h (Category D) : required by compat_getVar's
//     "variable not found" path, NOT by FALSE itself.
//   - fake_arena.h : required at .Call entry points in the same TU,
//     NOT by FALSE itself.
// =============================================================
#pragma once

#ifndef FAKE_R_FALSE_H
#define FAKE_R_FALSE_H

// --- Standard library includes ---
// None required: FALSE is a plain enum enumerator with no runtime
// dependencies.

// --- Fake R header dependencies ---
// (from Integration Requirements in FALSE.md Section 5)
//
// Rboolean.h is the sole dependency: it declares
//   typedef enum { FALSE = 0, TRUE = 1 } Rboolean;
// after issuing #undef FALSE / #undef TRUE.  Including it here
// makes the enumerator FALSE available to every translation unit
// that includes FALSE.h (or fake_R.h, which includes this file).
#include "Rboolean.h"

// --- Core fake implementation ---
//
// Pattern 1: No-op Registration Argument (init.c:26)
// -------------------------------------------------------
// R_useDynamicSymbols(dll, FALSE) passes FALSE as the second argument
// of type Rboolean.  In the standalone fake build R_useDynamicSymbols
// is a no-op inline function (provided by DllInfo.h / fake_Rdynload
// headers).  FALSE needs only to exist as an integer-compatible constant
// of type Rboolean — satisfied by the Rboolean enum from Rboolean.h
// included above.  No additional definition is required here.
//
// Pattern 2: Boolean Inherits Flag to R_getVar (rpart_callback.c:59,62,65,68)
// -------------------------------------------------------
// compat_getVar(SEXP sym, SEXP rho, Rboolean inherits) is compiled under
//   #if R_VERSION < R_Version(4, 5, 0)
// (fake_Rversion.h must satisfy this condition).
// At each call site, FALSE (== 0) is passed as `inherits`, causing the
// ternary
//   SEXP val = inherits ? findVar(sym, rho) : findVarInFrame(rho, sym);
// to evaluate as false and select findVarInFrame.
// FALSE is an enumerator (value 0) of Rboolean; the C++ compiler accepts
// the integer constant 0 implicitly where a Rboolean is expected.
// No additional definition is required beyond the Rboolean enum.
//
// Both patterns share the same fake strategy: the Rboolean enum from
// Rboolean.h (included above) is the complete fake implementation of FALSE.
//
// Invariant applicability:
//   - Invariant 1 (C++ exception-based errors): not triggered by FALSE itself.
//   - Invariant 2 (arena memory): not triggered; FALSE is a scalar constant.
//   - Invariant 3 (R Interpreter Items): not triggered by FALSE itself.

// --- Compatibility aliases (preserve original R API names) ---
//
// R_ext/Boolean.h introduces no #define aliases for FALSE.  The only
// preprocessor directive the original header uses for FALSE is `#undef FALSE`
// before the enum declaration — that #undef is already issued inside
// Rboolean.h (included above).  After the enum declaration, FALSE is an
// enumerator, not a macro.  No additional #define wrapper is required
// or present in the original header.

#endif // FAKE_R_FALSE_H
