// =============================================================
// findVar.h — Fake R API: findVar
// Original R header: Rinternals.h
// Category: E — R interpreter item
// Auto-generated by generate-r-extern-fake-header agent.
//
// findVar (Rf_findVar) requires a running R interpreter to function.
// It traverses an R environment's frame chain, consulting R's internal
// symbol table and binding records at each level.  None of these data
// structures exist outside of an initialized R runtime.
//
// In the fake build, findVar is implemented as a function pointer that
// Python registers via ctypes.CFUNCTYPE before invoking any .Call function
// that exercises the user-defined splitting code path (method=4).
//
// Original R declaration (Rinternals.h line 533):
//   SEXP Rf_findVar(SEXP, SEXP);
// Alias (Rinternals.h line 939):
//   #define findVar Rf_findVar
//
// Co-implemented in this header: findVarInFrame / Rf_findVarInFrame
// Original declaration (Rinternals.h line 534):
//   SEXP Rf_findVarInFrame(SEXP, SEXP);
// Alias (Rinternals.h line 940):
//   #define findVarInFrame Rf_findVarInFrame
//
// Source usage context (rpart_callback.c:22):
//   SEXP val = inherits ? findVar(sym, rho) : findVarInFrame(rho, sym);
//   if (val == R_UnboundValue)
//     error(_("variable '%s' not found"), CHAR(PRINTNAME(sym)));
//
// Argument order note:
//   findVar(sym, rho)           — symbol first, environment second
//   findVarInFrame(rho, sym)    — environment first, symbol second
//   Both match the real Rinternals.h declarations.
//
// Runtime note: In rpart source, all four R_getVar call sites in
// init_rpcallback (rpart_callback.c:59,62,65,68) pass inherits=FALSE,
// so findVarInFrame is always called and findVar is NEVER reached at
// runtime.  Both stubs must compile and link correctly; findVar must
// additionally provide a safe failure path in case inherits=TRUE is
// ever passed.
// =============================================================
#pragma once

#ifndef FAKE_R_FINDVAR_H
#define FAKE_R_FINDVAR_H

// --- Standard library includes ---
#include <stddef.h>    // NULL
#include <stdexcept>   // std::runtime_error (via RError)
#include <string>      // std::string (via RError)

// --- Fake R header dependencies ---
// (from Integration Requirements in findVar.md, Section 5)
//
// R_getVar.h provides the full dependency chain:
//   SEXP.h (via R_UnboundValue.h) ->
//     INTSXP.h: RError, SEXPREC struct, SEXP typedef, SEXPTYPE constants,
//               allocVector, allocMatrix, INTEGER, REAL, LENGTH,
//               PROTECT, UNPROTECT
//     Rboolean.h: Rboolean (FALSE=0, TRUE=1) — required by compat_getVar
//                 parameter (rpart_callback.c:20)
//   R_NilValue.h: Rf_error (throws RError), #define error Rf_error
//   R_UnboundValue.h: R_UnboundValue sentinel, get_R_UnboundValue() accessor
//   R_VERSION.h: R_VERSION = R_Version(4,4,0), forces R_VERSION < R_Version(4,5,0)
//                so compat_getVar and the R_getVar macro are compiled
//
// R_getVar.h also provides the authoritative stub definitions for:
//   - install / Rf_install (Category E, register_install_fn)
//   - findVar / Rf_findVar (Category E, register_findVar_fn)
//   - findVarInFrame / Rf_findVarInFrame (Category E, register_findVarInFrame_fn)
//   - findVarInFrame3 / Rf_findVarInFrame3
//   - Optional R_getVar function pointer (compiled out for R < 4.5.0)
//
// The stubs below (FAKE_FINDVAR_FN_DEFINED / FAKE_FINDVARINFRAME_FN_DEFINED)
// are guarded: they become no-ops when R_getVar.h is included first, and
// provide the full implementation when findVar.h is included standalone.
#include "R_getVar.h"

// *** R INTERPRETER ITEM — findVar ***
// A complete fake is impossible without an R interpreter.
// Register a Python callback via register_findVar_fn() before calling any
// function that exercises the inherits=TRUE branch of compat_getVar.
// Affected code paths: rpart_callback.c:22 (true branch of the ternary —
//   never reached by standard rpart calls; inherits=FALSE at all four
//   R_getVar call sites in init_rpcallback: lines 59, 62, 65, 68).

// --- Core fake implementation: findVar / Rf_findVar ---
//
// Pattern: Conditional Environment Lookup — findVar Branch (Compile-and-Link Target)
// Location: rpart_callback.c:22 (true branch of inherits ? findVar(sym, rho) : ...)
//
// The FAKE_FINDVAR_FN_DEFINED guard ensures this block is skipped if
// R_getVar.h (which provides the authoritative definition) was included
// first in the same translation unit.  When findVar.h is included
// standalone (before R_getVar.h), this block provides the full
// implementation.
#ifndef FAKE_FINDVAR_FN_DEFINED
#define FAKE_FINDVAR_FN_DEFINED

// findVar_fn_t — function pointer type for the Python-registered callback.
//
// Signature: SEXP callback(SEXP sym, SEXP rho)
//   sym: a SYMSXP produced by install(name); carries the interned symbol name.
//   rho: an ENVSXP; the starting frame for the parent-chain search.
//   return: the SEXP value bound to sym in rho or any parent; R_UnboundValue
//           if not found.
//
// Argument order: symbol first, environment second.
// This matches the real Rinternals.h:533 declaration and the call site at
// rpart_callback.c:22: findVar(sym, rho).
typedef SEXP (*findVar_fn_t)(SEXP sym, SEXP rho);
static findVar_fn_t g_findVar_fn = nullptr;

// register_findVar_fn — registers the Python-provided callback.
//
// Call this from Python via ctypes before invoking any code path that
// passes inherits=TRUE to compat_getVar.  For standard rpart methods
// (anova, poisson, class, exp), this function never needs to be called
// because inherits is always FALSE at the four R_getVar call sites in
// init_rpcallback.  Registration is required for correctness if a future
// call site passes inherits=TRUE.
extern "C" inline void register_findVar_fn(findVar_fn_t fn) {
    g_findVar_fn = fn;
}

// Rf_findVar — the fake stub (Category E, Invariant 3).
//
// When the callback is registered, delegates to the Python function.
// When the callback is null:
//   - Returns R_UnboundValue as a conservative fallback so that
//     compat_getVar at rpart_callback.c:23 sees the "not found" sentinel
//     and calls error(...), which throws RError (Invariant 1).
//   - This is safe for rpart because findVar is never actually called
//     at runtime (inherits=FALSE everywhere); if it somehow were called
//     with a null pointer, an RError with an informative message would
//     surface rather than a segfault.
//
// NOTE: The guide's Section 3 and Section 4 both allow either approach
// (throw immediately vs. return R_UnboundValue) for the null-callback case.
// Returning R_UnboundValue is the safer choice: it lets the existing
// compat_getVar error-handling path at line 23-24 fire through the standard
// Rf_error -> RError chain, producing a legible Python-facing error message
// that includes the symbol name.
inline SEXP Rf_findVar(SEXP sym, SEXP rho) {
    if (!g_findVar_fn) {
        // Conservative fallback: inherits=TRUE path is never reached by rpart.
        // Return R_UnboundValue so compat_getVar's error(...) fires via the
        // standard path (Invariant 1), rather than crashing with a null dereference.
        return R_UnboundValue;
    }
    return g_findVar_fn(sym, rho);
}

// Short-form alias matching Rinternals.h line 939: #define findVar Rf_findVar
// Provided as an inline function to avoid macro-expansion conflicts when
// findVar appears as both an identifier and a parameter name in complex sites.
inline SEXP findVar(SEXP sym, SEXP rho) { return Rf_findVar(sym, rho); }

#endif // FAKE_FINDVAR_FN_DEFINED

// *** R INTERPRETER ITEM — findVarInFrame ***
// A complete fake is impossible without an R interpreter.
// Register a Python callback via register_findVarInFrame_fn() before calling
// init_rpcallback() with method=4 (user-defined splits).
// Affected code paths: rpart_callback.c:22 (false branch of the ternary —
//   reached at ALL FOUR R_getVar call sites in init_rpcallback:
//   lines 59 (yback), 62 (wback), 65 (xback), 68 (nback)).

// --- Core fake implementation: findVarInFrame / Rf_findVarInFrame ---
//
// Pattern: Conditional Environment Lookup — findVarInFrame Branch (Critical Path)
// Location: rpart_callback.c:22 (false branch: findVarInFrame(rho, sym))
//
// CRITICAL: findVarInFrame IS called at runtime for method=4.  Python MUST
// register a callback that returns the correct SEXP for each of the four
// expected variable names (yback, wback, xback, nback).
//
// The FAKE_FINDVARINFRAME_FN_DEFINED guard ensures this block is skipped if
// R_getVar.h was already included (which provides the same definition).
#ifndef FAKE_FINDVARINFRAME_FN_DEFINED
#define FAKE_FINDVARINFRAME_FN_DEFINED

// findVarInFrame_fn_t — function pointer type for the Python-registered callback.
//
// Signature: SEXP callback(SEXP rho, SEXP sym)
//   rho: an ENVSXP; only its immediate frame is searched (no parent walk).
//   sym: a SYMSXP produced by install(name).
//   return: the SEXP value bound to sym in rho; R_UnboundValue if not found.
//
// Argument order: environment first, symbol second — the REVERSE of findVar.
// This matches the real Rinternals.h:534 declaration and the call site at
// rpart_callback.c:22: findVarInFrame(rho, sym).
//
// Expected return values by variable:
//   install("yback") -> REALSXP (double *); REAL(stemp) at line 60
//   install("wback") -> REALSXP (double *); REAL(stemp) at line 63
//   install("xback") -> REALSXP (double *); REAL(stemp) at line 66
//   install("nback") -> INTSXP  (int *);    INTEGER(stemp) at line 69
typedef SEXP (*findVarInFrame_fn_t)(SEXP rho, SEXP sym);
static findVarInFrame_fn_t g_findVarInFrame_fn = nullptr;

// register_findVarInFrame_fn — registers the Python-provided callback.
//
// This MUST be called from Python before init_rpcallback_wrapper() is
// invoked for method=4 (user-defined splits).  Failure to register will
// cause Rf_findVarInFrame to throw RError with an informative message,
// which will propagate back to Python as a RuntimeError.
extern "C" inline void register_findVarInFrame_fn(findVarInFrame_fn_t fn) {
    g_findVarInFrame_fn = fn;
}

// Rf_findVarInFrame — the fake stub (Category E, Invariant 3).
//
// This is on the critical path: every R_getVar(install(name), rho, FALSE)
// call in init_rpcallback resolves via compat_getVar to findVarInFrame(rho, sym).
// If the callback is null, throws RError immediately (rather than returning
// R_UnboundValue) because the caller cannot recover: the error would simply
// propagate through compat_getVar's R_UnboundValue check and throw the same
// RError anyway, but the immediate throw provides a clearer error message.
inline SEXP Rf_findVarInFrame(SEXP rho, SEXP sym) {
    if (!g_findVarInFrame_fn)
        throw RError(
            "findVarInFrame: Python callback not registered. "
            "init_rpcallback() requires registration via "
            "register_findVarInFrame_fn() before R_getVar calls at "
            "rpart_callback.c lines 59, 62, 65, 68 (yback, wback, xback, nback).");
    return g_findVarInFrame_fn(rho, sym);
}

// Short-form alias matching Rinternals.h line 940: #define findVarInFrame Rf_findVarInFrame
inline SEXP findVarInFrame(SEXP rho, SEXP sym) {
    return Rf_findVarInFrame(rho, sym);
}

// Rf_findVarInFrame3 — three-argument form (Rinternals.h line 535).
// Not called by rpart; provided for compilation completeness.
// Dispatches to Rf_findVar (parent-chain walk) or Rf_findVarInFrame
// (single frame) based on the inherits flag, mirroring compat_getVar logic.
inline SEXP Rf_findVarInFrame3(SEXP rho, SEXP sym, Rboolean inherits) {
    if (inherits) return Rf_findVar(sym, rho);
    return Rf_findVarInFrame(rho, sym);
}

// Short-form alias matching Rinternals.h line 941: #define findVarInFrame3 Rf_findVarInFrame3
inline SEXP findVarInFrame3(SEXP rho, SEXP sym, Rboolean inherits) {
    return Rf_findVarInFrame3(rho, sym, inherits);
}

#endif // FAKE_FINDVARINFRAME_FN_DEFINED

// --- Compatibility aliases (preserve original R API names) ---
//
// The following aliases from the original Rinternals.h are preserved above
// as inline wrapper functions (not macros, to avoid double-expansion):
//
//   Rinternals.h line 939:  #define findVar          Rf_findVar
//   Rinternals.h line 940:  #define findVarInFrame   Rf_findVarInFrame
//   Rinternals.h line 941:  #define findVarInFrame3  Rf_findVarInFrame3
//
// These inline functions are defined in the FAKE_FINDVAR_FN_DEFINED and
// FAKE_FINDVARINFRAME_FN_DEFINED blocks above.  No additional #define macros
// are emitted to avoid conflicts with the inline definitions already visible.
//
// The #define error Rf_error alias (needed for rpart_callback.c:24) is
// provided by R_NilValue.h, which is included transitively through R_getVar.h
// -> R_UnboundValue.h -> SEXP.h -> R_NilValue.h.

// --- Python registration usage note (Category E) ---
//
// The full ctypes integration workflow for findVar, findVarInFrame, and the
// surrounding call chain (install, compat_getVar, init_rpcallback) is
// documented below.  This snippet is derived from the guide's Section 4
// "Python Interop Notes" and is the authoritative registration guide for
// the findVar / findVarInFrame pair.
//
// NOTE: Registration is ONLY required for method=4 (user-defined splits).
// Standard rpart() calls (anova, poisson, class, exp; methods 1-3) never
// invoke init_rpcallback() and therefore never call findVar or findVarInFrame.
// For standard use, none of these callbacks need to be registered.
//
/*
import ctypes
import numpy as np

# Load the shared library built from the fake-header rpart source.
lib = ctypes.CDLL("./librpart_fake.so")

# SEXP is an opaque pointer in Python; c_void_p maps cleanly.
SEXP = ctypes.c_void_p

# ----------------------------------------------------------------
# Step 1: Retrieve the R_UnboundValue sentinel pointer.
#
# get_R_UnboundValue() is a C-linkage accessor defined in R_UnboundValue.h
# (included transitively via R_getVar.h).  Python must obtain this address
# BEFORE registering any callbacks so that py_findVarInFrame and py_findVar
# can return the correct sentinel on lookup failure.
# ----------------------------------------------------------------
lib.get_R_UnboundValue.restype  = SEXP
lib.get_R_UnboundValue.argtypes = []
R_UNBOUND = lib.get_R_UnboundValue()   # integer address of unbound_rec

# ----------------------------------------------------------------
# Step 2: Register the install() stub.
#
# install(name) interns a C string as a symbol SEXP (SYMSXP).
# Python maintains a string->c_void_p dict so each name always maps
# to the same stable pointer address (symbol interning invariant).
# This invariant is REQUIRED for the _frame_registry lookup to work:
# the sym pointer produced by install("yback") inside C code must match
# the sym pointer used as the dict key in _frame_registry.
# ----------------------------------------------------------------
_symbol_handles: dict = {}   # {name_str: int pointer value}
_symbol_nodes:   dict = {}   # keep SEXP node objects alive; prevent GC

InstallFnType = ctypes.CFUNCTYPE(SEXP, ctypes.c_char_p)

def py_install(name_bytes: bytes) -> int:
    name = name_bytes.decode()
    if name not in _symbol_handles:
        node = (ctypes.c_char * 1)()   # 1-byte placeholder; address is the handle
        _symbol_nodes[name]   = node
        _symbol_handles[name] = ctypes.cast(node, ctypes.c_void_p).value
    return _symbol_handles[name]

_install_cb = InstallFnType(py_install)

lib.register_install_fn.restype  = None
lib.register_install_fn.argtypes = [InstallFnType]
lib.register_install_fn(_install_cb)

# ----------------------------------------------------------------
# Step 3: Register the findVarInFrame() stub.
#
# findVarInFrame(rho, sym) looks up sym in the single frame rho.
# Argument order: rho first, sym second (matches Rinternals.h:534).
#
# Python maintains a nested registry:
#   _frame_registry[rho_ptr][sym_ptr] = sexp_value_ptr
#
# Before calling init_rpcallback_wrapper, Python populates this
# registry with the four "back" array SEXPs.
# ----------------------------------------------------------------
_frame_registry: dict = {}   # {rho_ptr: {sym_ptr: sexp_ptr}}

FindVarInFrameFnType = ctypes.CFUNCTYPE(SEXP, SEXP, SEXP)

def py_findVarInFrame(rho: int, sym: int) -> int:
    """Look up sym in the frame keyed by rho.
    Returns R_UnboundValue if the (rho, sym) pair is not registered.
    Returning R_UNBOUND causes compat_getVar at rpart_callback.c:23 to
    call error("variable '%s' not found"), which throws RError (Invariant 1).
    """
    frame = _frame_registry.get(rho, {})
    val = frame.get(sym)
    if val is None:
        return R_UNBOUND
    return val

_findVarInFrame_cb = FindVarInFrameFnType(py_findVarInFrame)

lib.register_findVarInFrame_fn.restype  = None
lib.register_findVarInFrame_fn.argtypes = [FindVarInFrameFnType]
lib.register_findVarInFrame_fn(_findVarInFrame_cb)

# ----------------------------------------------------------------
# Step 4: Register the findVar() stub (inherits=TRUE branch).
#
# findVar(sym, rho) walks rho and all parent environments.
# Argument order: sym first, rho second (matches Rinternals.h:533).
# Note the reversed argument order vs. findVarInFrame.
#
# This branch is NEVER reached by rpart (inherits=FALSE everywhere),
# but should be registered to avoid the null-pointer fallback path in
# the C stub (which returns R_UnboundValue conservatively).
# A minimal implementation that always returns R_UnboundValue is safe.
# ----------------------------------------------------------------
FindVarFnType = ctypes.CFUNCTYPE(SEXP, SEXP, SEXP)

def py_findVar(sym: int, rho: int) -> int:
    """Walk rho's parent chain looking for sym.
    For rpart, this path is never reached (inherits=FALSE always).
    Returns R_UnboundValue conservatively; triggers RError in compat_getVar
    if somehow called, producing a legible error rather than a crash.
    """
    # Attempt a direct frame lookup as a minimal fallback.
    frame = _frame_registry.get(rho, {})
    val = frame.get(sym)
    if val is not None:
        return val
    return R_UNBOUND   # "not found" in any known frame

_findVar_cb = FindVarFnType(py_findVar)

lib.register_findVar_fn.restype  = None
lib.register_findVar_fn.argtypes = [FindVarFnType]
lib.register_findVar_fn(_findVar_cb)

# ----------------------------------------------------------------
# Step 5: Build fake SEXPs for the four "back" arrays and populate
# the frame registry.
#
# Expected by init_rpcallback (rpart_callback.c:59-69):
#   yback: REALSXP, length = n_obs * n_resp;  REAL(stemp)    -> ydata
#   wback: REALSXP, length = n_obs;           REAL(stemp)    -> wdata
#   xback: REALSXP, length = n_obs * n_xcols; REAL(stemp)    -> xdata
#   nback: INTSXP,  length = 1;               INTEGER(stemp) -> ndata
# ----------------------------------------------------------------
n_obs    = 100
n_resp   = 1
n_x_cols = 10

yback_arr = np.zeros(n_obs * n_resp,   dtype=np.float64)
wback_arr = np.ones(n_obs,             dtype=np.float64)
xback_arr = np.zeros(n_obs * n_x_cols, dtype=np.float64)
nback_arr = np.array([n_resp],         dtype=np.int32)

lib.make_real_sexp.restype  = SEXP
lib.make_real_sexp.argtypes = [ctypes.c_void_p, ctypes.c_int]
lib.make_int_sexp.restype   = SEXP
lib.make_int_sexp.argtypes  = [ctypes.c_void_p, ctypes.c_int]

sexp_y = lib.make_real_sexp(yback_arr.ctypes.data_as(ctypes.c_void_p), yback_arr.size)
sexp_w = lib.make_real_sexp(wback_arr.ctypes.data_as(ctypes.c_void_p), wback_arr.size)
sexp_x = lib.make_real_sexp(xback_arr.ctypes.data_as(ctypes.c_void_p), xback_arr.size)
sexp_n = lib.make_int_sexp(nback_arr.ctypes.data_as(ctypes.c_void_p),  nback_arr.size)

# Create an ENVSXP handle that serves as the rho key.
lib.make_env_sexp.restype  = SEXP
lib.make_env_sexp.argtypes = []
rho_handle = lib.make_env_sexp()

# Use py_install to produce the same stable sym handles that the C code
# receives when it calls install("yback") etc. inside init_rpcallback.
_frame_registry[rho_handle] = {
    py_install(b"yback"): sexp_y,
    py_install(b"wback"): sexp_w,
    py_install(b"xback"): sexp_x,
    py_install(b"nback"): sexp_n,
}

# ----------------------------------------------------------------
# Step 6: Call init_rpcallback_wrapper.
#
# init_rpcallback sets up the static globals (rho, ysave, rsave, expr1,
# expr2, ydata, wdata, xdata, ndata) used by rpart_callback1/2.
# ny and nr are scalar INTSXP SEXPs (1-element int32 arrays).
# expr1 and expr2 are R language SEXPs; pass None (nullptr) if the
# eval() stub is not registered (i.e., no custom split expressions).
# ----------------------------------------------------------------
lib.init_rpcallback_wrapper.restype  = SEXP
lib.init_rpcallback_wrapper.argtypes = [SEXP, SEXP, SEXP, SEXP, SEXP]

ny_arr = np.array([n_resp], dtype=np.int32)
nr_arr = np.array([n_resp], dtype=np.int32)
sexp_ny = lib.make_int_sexp(ny_arr.ctypes.data_as(ctypes.c_void_p), 1)
sexp_nr = lib.make_int_sexp(nr_arr.ctypes.data_as(ctypes.c_void_p), 1)

result = lib.init_rpcallback_wrapper(
    rho_handle,   # rhox:   the environment frame SEXP
    sexp_ny,      # ny:     number of response columns (scalar INTSXP)
    sexp_nr,      # nr:     length of user eval return vector (scalar INTSXP)
    None,         # expr1x: R split expression SEXP (None if eval not needed)
    None,         # expr2x: R value expression SEXP (None if eval not needed)
)

# ----------------------------------------------------------------
# Step 7: Check for errors raised by Rf_error (Invariant 1).
# ----------------------------------------------------------------
lib.get_last_rerror_message.restype  = ctypes.c_char_p
lib.get_last_rerror_message.argtypes = []
msg = lib.get_last_rerror_message()
if msg:
    raise RuntimeError(f"init_rpcallback failed: {msg.decode()}")
*/

// --- ArenaFrame usage ---
//
// findVar and findVarInFrame themselves do not allocate arena memory.
// However, the .Call-entry wrapper for init_rpcallback (which calls
// compat_getVar which calls findVarInFrame) must declare:
//
//   ArenaFrame _frame;
//
// as its first statement, because init_rpcallback is compiled in the same
// translation unit (rpart_callback.c) as rpart_callback1() and
// rpart_callback2(), which may use R_alloc / ALLOC (arena-backed).
// The ArenaFrame guard is a standard precautionary measure for the entire
// callback subsystem.
//
// Once fake_arena.h is available:
//
//   #include "fake_arena.h"
//   extern "C" SEXP init_rpcallback_wrapper(
//           SEXP rhox, SEXP ny, SEXP nr, SEXP expr1x, SEXP expr2x) {
//       ArenaFrame _frame;   // Invariant 2: frees all R_alloc/ALLOC on exit
//       try {
//           return init_rpcallback(rhox, ny, nr, expr1x, expr2x);
//       } catch (const RError &e) {
//           // Invariant 1: translate C++ exception to a Python-readable message.
//           set_python_error(e.what());
//           return nullptr;   // signals failure to the Python caller
//       }
//   }
//
// Static SEXP singletons (R_NilValue, R_UnboundValue, R_NamesSymbol) survive
// ArenaFrame destruction — they live in the BSS segment, not on the arena.
// Heap SEXPs produced by allocVector / allocMatrix survive too (they use
// std::malloc, not the arena); Python must call free_sexp() or free_sexp_deep()
// after extracting data from returned SEXP values.

#endif // FAKE_R_FINDVAR_H
