// =============================================================
// install.h — Fake R API: install / Rf_install
// Original R header: Rinternals.h
// Category: E — R Interpreter Item (best-effort fakeable)
// Auto-generated by generate-r-extern-fake-header agent.
//
// install(const char *name)  (Rinternals.h line 956: #define install Rf_install)
// Rf_install(const char *)   (Rinternals.h, declared as SEXP Rf_install(const char *))
//
// Interns a C string as a symbol SEXP (SYMSXP).  In the real R runtime,
// install() looks up name in R's global symbol table (a hash structure
// managed by the interpreter at startup), creating a new SYMSXP node if
// the name is not already present.  The same SEXPREC* pointer is returned
// for a given name on every call in every translation unit for the lifetime
// of the R session.
//
// In the fake build, install() is used exclusively inside init_rpcallback
// (rpart_callback.c:59,62,65,68) to produce the 'sym' SEXP argument passed
// to R_getVar / compat_getVar / findVarInFrame.  The only requirements on
// the returned SEXP are:
//   1. Stable pointer identity: install(name) must return the same pointer
//      on every call within a process (needed by findVarInFrame's lookup).
//   2. Readable PRINTNAME: sym->data must be a CHARSXP node so that
//      CHAR(PRINTNAME(sym)) works on the error path in compat_getVar:24.
//
// Both requirements are satisfied by either:
//   (A) Thread-local hash-map symbol cache (preferred — no Python registration
//       required; works out of the box for standard rpart use)
//   (B) Python function pointer bridge (optional — Python calls
//       register_install_fn() before init_rpcallback(); overrides the cache)
//
// The authoritative stub (function pointer bridge, approach B) was already
// provided in R_getVar.h under FAKE_INSTALL_FN_DEFINED, because R_getVar.h
// was generated before this header and included the install stub as part of
// its comprehensive compat_getVar / R_getVar implementation.
//
// This header:
//   1. Pulls in R_getVar.h for the complete dependency chain and the
//      function pointer bridge stub.
//   2. Adds the thread-local hash-map symbol cache (approach A) under a
//      separate guard FAKE_INSTALL_HASHMAP_DEFINED, so both mechanisms coexist.
//   3. Documents why approach A from the guide is superior for rpart
//      (install never needs Python registration for standard rpart methods).
//
// Usage in rpart:
//   install("yback") / install("wback") / install("xback") / install("nback")
//   are the only call sites (init_rpcallback, rpart_callback.c:59,62,65,68).
//   All four call sites pass inherits=FALSE to R_getVar, so findVarInFrame
//   (not findVar) is always invoked.  Standard rpart methods (anova, poisson,
//   class, exp) never call init_rpcallback at all, so install is never
//   invoked at runtime for the common case.
//
// Design note on R_getVar.h vs. install.h function pointer behavior:
//   R_getVar.h's Rf_install throws RError if g_install_fn is null.
//   The guide (install.md Section 3) recommends the hash-map approach where
//   Rf_install falls back to the hash-map when g_install_fn is null, so
//   it never throws under normal operation.  The hash-map utilities in this
//   header (gSymbolCache, create_symbol, clear_symbol_cache) implement that
//   strategy.  When Python registers g_install_fn before calling
//   init_rpcallback_wrapper, the registered callback takes precedence (as
//   documented in R_getVar.h); the hash-map utilities are then unused.
//
// Source file context (rpart_callback.c:44-72):
//   SEXP init_rpcallback(SEXP rhox, SEXP ny, SEXP nr, SEXP expr1x, SEXP expr2x)
//   {
//       SEXP stemp;
//       rho = rhox; ysave = asInteger(ny); rsave = asInteger(nr);
//       expr1 = expr1x; expr2 = expr2x;
//       stemp = R_getVar(install("yback"), rho, FALSE);  ydata = REAL(stemp);
//       stemp = R_getVar(install("wback"), rho, FALSE);  wdata = REAL(stemp);
//       stemp = R_getVar(install("xback"), rho, FALSE);  xdata = REAL(stemp);
//       stemp = R_getVar(install("nback"), rho, FALSE);  ndata = INTEGER(stemp);
//       return R_NilValue;
//   }
// =============================================================
#pragma once

#ifndef FAKE_R_INSTALL_H
#define FAKE_R_INSTALL_H

// --- Standard library includes ---
#include <stddef.h>    // NULL, size_t
#include <stdlib.h>    // std::malloc, std::free
#include <string.h>    // strlen, strcpy
#include <string>      // std::string (for gSymbolCache key type)
#include <unordered_map> // std::unordered_map (for gSymbolCache)

// --- Fake R header dependencies ---
//
// R_getVar.h provides the authoritative stub for install / Rf_install
// (under FAKE_INSTALL_FN_DEFINED) via a Python function pointer bridge,
// plus findVar / findVarInFrame stubs (under FAKE_FINDVAR_FN_DEFINED /
// FAKE_FINDVARINFRAME_FN_DEFINED), and transitively pulls in:
//   SEXP.h (SEXPREC struct, SEXP typedef, SYMSXP/CHARSXP/NILSXP constants,
//            mkChar, PRINTNAME, R_CHAR, R_NilValue, R_UnboundValue,
//            R_NamesSymbol, asInteger, asReal, setAttrib, getAttrib,
//            VECTOR_ELT, SET_VECTOR_ELT, isReal, isInteger, isNull,
//            free_sexp_deep, RError)
//   INTSXP.h (SEXPTYPE constant block, allocVector, allocMatrix,
//              INTEGER, REAL, LENGTH, PROTECT, UNPROTECT)
//   R_NilValue.h (Rf_error, #define error Rf_error, error_return macros)
//   R_UnboundValue.h (R_UnboundValue sentinel, get_R_UnboundValue())
//   R_VERSION.h (R_VERSION = R_Version(4,4,0) = 263168, R_Version macro;
//                ensures R_VERSION < R_Version(4,5,0) so compat_getVar and
//                the R_getVar macro in rpart_callback.c are compiled)
//   Rboolean.h (Rboolean, FALSE=0, TRUE=1)
#include "R_getVar.h"

// *** R INTERPRETER ITEM — install / Rf_install ***
// A complete fake is impossible without an R interpreter (global symbol table).
// Best-effort fake: thread-local hash-map symbol cache satisfies the two
// requirements of rpart's usage (stable identity + readable PRINTNAME).
// Affected code paths: rpart_callback.c:59, 62, 65, 68.
// For method=4 (user-defined splits) ONLY — standard methods never call this.

// --- Core fake implementation: install hash-map cache ---
//
// DESIGN: The authoritative Rf_install definition (function pointer bridge)
// is already provided by R_getVar.h under FAKE_INSTALL_FN_DEFINED.  This
// block adds the thread-local hash-map symbol cache and its utilities under
// a separate guard FAKE_INSTALL_HASHMAP_DEFINED.
//
// When g_install_fn is registered by Python (via register_install_fn()),
// R_getVar.h's Rf_install delegates to the Python callback immediately and
// the hash-map is bypassed.
//
// When g_install_fn is null (i.e., Python did NOT register a callback),
// R_getVar.h's Rf_install throws RError.  In that case, Python MUST register
// g_install_fn before calling init_rpcallback_wrapper.
//
// The hash-map utilities below (create_symbol, gSymbolCache,
// clear_symbol_cache, call_install) are provided as a self-contained
// alternative that does NOT require Python registration.  They are
// accessible from Python as C-linkage helpers for pre-populating symbol
// handles that can then be used to build _frame_registry for findVarInFrame.

#ifndef FAKE_INSTALL_HASHMAP_DEFINED
#define FAKE_INSTALL_HASHMAP_DEFINED

// Thread-local symbol cache: maps string name -> interned SYMSXP pointer.
//
// Each distinct name receives exactly one SYMSXP node per thread.  Subsequent
// calls to create_symbol(name) for the same name return the same SEXPREC*
// pointer, satisfying the idempotency invariant required by findVarInFrame.
//
// Symbol nodes (SYMSXP + their CHARSXP children) are heap-allocated once
// and stored indefinitely for the thread lifetime.  They are NOT arena-managed
// because the ArenaFrame at the .Call boundary must not free them: their
// pointer values must remain stable as _frame_registry lookup keys across
// multiple .Call invocations.
//
// Call clear_symbol_cache() from Python between independent test runs.
inline thread_local std::unordered_map<std::string, SEXP> gSymbolCache;

// create_symbol — allocates or retrieves a SYMSXP for the given name.
//
// This is the standalone hash-map implementation of the install() semantic.
// It does NOT depend on g_install_fn.  If mkChar or std::malloc fails, it
// throws RError (Invariant 1).
//
// SYMSXP node layout (from install.md Section 3):
//   sym->type   = SYMSXP (1)
//   sym->length = 0        (symbols have no element count)
//   sym->nrow   = 0, sym->ncol = 0
//   sym->data   = charsxp_node   (PRINTNAME reads this as the CHARSXP child)
//
// After create_symbol("yback"), CHAR(PRINTNAME(sym)) == "yback" because:
//   PRINTNAME(sym) returns static_cast<SEXP>(sym->data)  -> the CHARSXP node
//   R_CHAR(charnode) returns static_cast<const char*>(charnode->data) -> "yback"
inline SEXP create_symbol(const char *name) {
    std::string key(name);
    auto it = gSymbolCache.find(key);
    if (it != gSymbolCache.end())
        return it->second;

    // Cache miss: build a new SYMSXP + CHARSXP pair.
    SEXP charnode = mkChar(name);  // allocates CHARSXP; throws RError on OOM

    SEXPREC *sym = static_cast<SEXPREC *>(std::malloc(sizeof(SEXPREC)));
    if (!sym) {
        std::free(charnode->data);
        std::free(charnode);
        throw RError("install: out of memory allocating SYMSXP node");
    }

    sym->type   = SYMSXP;
    sym->length = 0;
    sym->nrow   = 0;
    sym->ncol   = 0;
    sym->data   = charnode;

    gSymbolCache[key] = sym;
    return sym;
}

// clear_symbol_cache — releases all symbol nodes allocated by create_symbol.
//
// Call from Python (via ctypes) between independent test runs to avoid
// accumulating stale SYMSXP nodes from previous fittings.
// After calling this, any _frame_registry entries keyed on old symbol
// pointers become dangling; rebuild _frame_registry after the call.
inline void clear_symbol_cache() {
    for (auto &kv : gSymbolCache) {
        SEXP sym = kv.second;
        if (sym) {
            SEXP charnode = static_cast<SEXP>(sym->data);
            if (charnode) {
                std::free(charnode->data);
                std::free(charnode);
            }
            std::free(sym);
        }
    }
    gSymbolCache.clear();
}

// call_install — C-linkage wrapper that exposes create_symbol() to Python.
//
// Python uses this to discover the SEXP pointer that the C++ hash-map
// assigns to a given name, so that _frame_registry can be populated with
// the matching keys BEFORE findVarInFrame is called by compat_getVar.
//
// Usage from Python (when using the built-in hash-map path):
//
//   lib.call_install.restype  = ctypes.c_void_p   # SEXP = void*
//   lib.call_install.argtypes = [ctypes.c_char_p]
//
//   sym_yback = lib.call_install(b"yback")
//   sym_wback = lib.call_install(b"wback")
//   sym_xback = lib.call_install(b"xback")
//   sym_nback = lib.call_install(b"nback")
//
//   # These four values are then used as keys in _frame_registry:
//   _frame_registry[rho_handle] = {
//       sym_yback: sexp_y,
//       sym_wback: sexp_w,
//       sym_xback: sexp_x,
//       sym_nback: sexp_n,
//   }
//
// Note: call_install delegates to create_symbol (hash-map path), NOT to
// g_install_fn.  If Python has registered g_install_fn, call_install still
// uses the hash-map — which means the _frame_registry keys from call_install
// would NOT match the symbols produced by Rf_install (which uses g_install_fn
// when registered).  In that case, Python must populate _frame_registry using
// the py_install callback instead, as documented in R_getVar.h.
extern "C" inline SEXP call_install(const char *name) {
    return create_symbol(name);
}

// clear_symbol_cache_c — C-linkage wrapper for Python:
//   lib.clear_symbol_cache_c.restype  = None
//   lib.clear_symbol_cache_c.argtypes = []
//   lib.clear_symbol_cache_c()
extern "C" inline void clear_symbol_cache_c() {
    clear_symbol_cache();
}

#endif // FAKE_INSTALL_HASHMAP_DEFINED

// --- Fallback definition for FAKE_INSTALL_FN_DEFINED ---
//
// This block is skipped when R_getVar.h is included first (common case),
// because R_getVar.h already sets FAKE_INSTALL_FN_DEFINED.  It is present
// so that install.h can be included standalone (before R_getVar.h) and still
// provide a complete Rf_install implementation using the hash-map.
//
// When this block IS active (standalone inclusion):
//   - Rf_install uses create_symbol (hash-map path) when g_install_fn is null.
//   - Rf_install uses g_install_fn when registered.
//   - The stub never throws RError under normal operation (unlike R_getVar.h's
//     version, which throws when g_install_fn is null).
//
// When this block is SKIPPED (R_getVar.h included first):
//   - R_getVar.h's Rf_install is used (throws if g_install_fn is null).
//   - Python MUST register g_install_fn before calling init_rpcallback_wrapper.
//   - The create_symbol / call_install utilities above are still available as
//     a parallel path for pre-computing symbol pointer values for _frame_registry.

#ifndef FAKE_INSTALL_FN_DEFINED
#define FAKE_INSTALL_FN_DEFINED

// install_fn_t — function pointer type for Python-registered symbol factory.
typedef SEXP (*install_fn_t)(const char *name);
static install_fn_t g_install_fn = nullptr;

// register_install_fn — registers the Python-provided callback.
// When registered, takes precedence over create_symbol (hash-map path).
extern "C" inline void register_install_fn(install_fn_t fn) {
    g_install_fn = fn;
}

// Rf_install — hash-map-primary, function-pointer-optional implementation.
//
// Lookup order:
//   1. g_install_fn is registered -> delegate to Python callback.
//   2. Otherwise -> create_symbol() (thread-local hash-map; never throws
//      RError under normal operation; only throws on std::malloc failure).
//
// This is the preferred implementation per install.md Section 3.
// When R_getVar.h is included first, this block is skipped; the function
// pointer bridge version from R_getVar.h is used instead.
inline SEXP Rf_install(const char *name) {
    if (g_install_fn)
        return g_install_fn(name);
    return create_symbol(name);
}

// Short-form alias matching Rinternals.h line 956: #define install Rf_install
// Provided as an inline function to match the alias pattern used by other
// Category E stubs; avoids macro double-expansion in complex call sites.
inline SEXP install(const char *name) { return Rf_install(name); }

// Rf_installChar — extracts char* from a CHARSXP and delegates to Rf_install.
inline SEXP Rf_installChar(SEXP charsxp) {
    return Rf_install(R_CHAR(charsxp));
}

// Rinternals.h aliases (lines 957-960):
//   #define installChar       Rf_installTrChar
//   #define installNoTrChar   Rf_installNoTrChar
//   #define installTrChar     Rf_installTrChar
inline SEXP Rf_installNoTrChar(SEXP c) { return Rf_installChar(c); }
inline SEXP Rf_installTrChar(SEXP c)   { return Rf_installChar(c); }
inline SEXP installChar(SEXP c)        { return Rf_installTrChar(c); }
inline SEXP installNoTrChar(SEXP c)    { return Rf_installNoTrChar(c); }
inline SEXP installTrChar(SEXP c)      { return Rf_installTrChar(c); }

#endif // FAKE_INSTALL_FN_DEFINED

// --- Compatibility aliases (preserve original R API names) ---
//
// Regardless of which path defines Rf_install (R_getVar.h or this file),
// the following Rinternals.h aliases are provided via inline functions
// (not #define macros) to avoid macro-expansion conflicts.  The inline
// wrappers above or in R_getVar.h cover all required aliases:
//
//   Rinternals.h line 956:  #define install          Rf_install
//   Rinternals.h line 957:  #define installChar      Rf_installTrChar
//   Rinternals.h line 958:  #define installNoTrChar  Rf_installNoTrChar
//   Rinternals.h line 959:  #define installTrChar    Rf_installTrChar

// --- ArenaFrame usage ---
//
// install / Rf_install / create_symbol do NOT use arena memory.
// Symbol nodes are heap-allocated (std::malloc) and stored in gSymbolCache
// for the thread lifetime.  They must NOT be freed by ArenaFrame at the
// .Call boundary because their pointer values are used as _frame_registry
// keys across multiple init_rpcallback_wrapper invocations.
//
// The .Call boundary wrapper for init_rpcallback must still declare:
//   ArenaFrame _frame;
// as its first statement, because rpart_callback1/2 (compiled in the same
// translation unit) use R_alloc / ALLOC (arena-backed).  See R_getVar.h
// for the full init_rpcallback_wrapper template.

#endif // FAKE_R_INSTALL_H
