// =============================================================
// INTSXP.h — Fake R API: INTSXP
// Original R header: Rinternals.h
// Category: A — Type or Enum Constant
// Auto-generated by generate-r-extern-fake-header agent.
//
// INTSXP is the SEXPTYPE tag (value 13) that identifies integer
// vector objects in R's C API.  It is used as the first argument
// to allocVector(INTSXP, n) and allocMatrix(INTSXP, nrow, ncol)
// in six locations across the rpart package source:
//
//   pred_rpart.c:139  allocVector(INTSXP, n)
//   rpart.c:194       allocVector(INTSXP, n)
//   rpart.c:278       allocMatrix(INTSXP, nodecount, 6)
//   rpart.c:285       allocMatrix(INTSXP, splitcount, 3)
//   rpart.c:293       allocMatrix(INTSXP, catcount, maxcat)
//   rpartexp2.c:47    allocVector(INTSXP, n)
//
// Original R header definition (Rinternals.h, non-enum_SEXPTYPE branch):
//   typedef unsigned int SEXPTYPE;
//   #define INTSXP  13   /* integer vectors */
//
// This header also provides:
//   - SEXPTYPE typedef and the full SEXPTYPE constant block
//   - SEXPREC struct and SEXP typedef
//   - allocVector / allocMatrix / sexptype_element_size inline functions
//   - INTEGER / REAL / LOGICAL / RAW accessor inline functions
//   - LENGTH / Rf_length accessors
//   - PROTECT / UNPROTECT / UNPROTECT_PTR no-op stubs
//   - nrows / ncols / Rf_nrows / Rf_ncols accessors
//   - free_sexp() helper for Python-side cleanup
//   - RError struct (guarded) for C++ exception-based error signalling
//
// Integration Requirements (from INTSXP.md Section 5):
//   - fake_arena.h  : ArenaFrame RAII guard for R_alloc / ALLOC scratch
//   - RError        : defined inline here, guarded by FAKE_R_RERROR_DEFINED
//   - SEXP/SEXPREC  : defined inline here (no separate SEXP.h exists yet)
//
// Note: fake_arena.h is listed as a dependency but does not yet exist in
// the output folder.  A WARNING comment is emitted at the include site below.
// The ArenaFrame usage pattern is documented in the ArenaFrame usage block
// at the bottom of this file.
// =============================================================

#pragma once

#ifndef FAKE_INTSXP_H
#define FAKE_INTSXP_H

// --- Standard library includes ---
#include <stdlib.h>    // malloc, free, size_t
#include <string.h>    // memset
#include <stddef.h>    // NULL, size_t
#include <stdarg.h>    // va_list, vsnprintf
#include <stdio.h>     // fprintf, stderr
#include <stdexcept>   // std::runtime_error
#include <string>      // std::string

// --- Fake R header dependencies ---
// (from Integration Requirements in INTSXP.md)
//
// WARNING: dependency fake_arena.h not found in output_folder.
// Any .Call-entry function that calls R_alloc / ALLOC in the same
// function body as allocVector(INTSXP,...) / allocMatrix(INTSXP,...)
// must declare `ArenaFrame _frame;` as its first statement once
// fake_arena.h is available.  See the ArenaFrame usage block below.
//
// #include "fake_arena.h"

// ---------------------------------------------------------------------------
// RError — C++ exception replacing Rf_error / longjmp.
// Defined once; subsequent includes of this header are no-ops thanks to the
// FAKE_INTSXP_H guard.  If another fake header already defines RError, the
// FAKE_R_RERROR_DEFINED guard prevents redefinition.
// ---------------------------------------------------------------------------
#ifndef FAKE_R_RERROR_DEFINED
#define FAKE_R_RERROR_DEFINED
struct RError : public std::runtime_error {
    explicit RError(const std::string &msg) : std::runtime_error(msg) {}
    explicit RError(const char *msg)        : std::runtime_error(msg) {}
};
#endif // FAKE_R_RERROR_DEFINED

// ---------------------------------------------------------------------------
// SEXPTYPE — unsigned int tag identifying the content type of a SEXPREC node.
//
// Source: Rinternals.h lines 109-144 (non-enum_SEXPTYPE branch, active by
// default when the compiler does not define enum_SEXPTYPE).
//
// The original header comment notes that slots 11 and 12 were used for
// factors in the 1990s and are now intentionally unassigned.
// ---------------------------------------------------------------------------
#ifndef FAKE_SEXPTYPE_DEFINED
#define FAKE_SEXPTYPE_DEFINED

typedef unsigned int SEXPTYPE;

#define NILSXP       0    /* nil = NULL */
#define SYMSXP       1    /* symbols */
#define LISTSXP      2    /* lists of dotted pairs */
#define CLOSXP       3    /* closures */
#define ENVSXP       4    /* environments */
#define PROMSXP      5    /* promises: [un]evaluated closure arguments */
#define LANGSXP      6    /* language constructs (special lists) */
#define SPECIALSXP   7    /* special forms */
#define BUILTINSXP   8    /* builtin non-special forms */
#define CHARSXP      9    /* "scalar" string type (internal only) */
#define LGLSXP      10    /* logical vectors */
/* 11 and 12 were used for factors in the 1990s — intentionally unassigned */
#define INTSXP      13    /* integer vectors */
#define REALSXP     14    /* real (double) variables */
#define CPLXSXP     15    /* complex variables */
#define STRSXP      16    /* string vectors */
#define DOTSXP      17    /* dot-dot-dot object */
#define ANYSXP      18    /* make "any" args work */
#define VECSXP      19    /* generic vectors */
#define EXPRSXP     20    /* expressions vectors */
#define BCODESXP    21    /* byte code */
#define EXTPTRSXP   22    /* external pointer */
#define WEAKREFSXP  23    /* weak reference */
#define RAWSXP      24    /* raw bytes */
#define OBJSXP      25    /* object, non-vector (S4) */
#define S4SXP       25    /* same as OBJSXP, retained for back compatibility */
#define NEWSXP      30    /* fresh node created in new page */
#define FREESXP     31    /* node released by GC */
#define FUNSXP      99    /* Closure or Builtin or Special */

#endif // FAKE_SEXPTYPE_DEFINED

// ---------------------------------------------------------------------------
// SEXPREC and SEXP — minimal fake matching the observable C API contract.
//
// Fields derived from the usage patterns in the rpart source:
//   type   — stores the SEXPTYPE tag; set by allocVector/allocMatrix.
//   length — total element count; returned by LENGTH().
//   nrow   — row count for matrices; returned by nrows() / Rf_nrows().
//   ncol   — column count for matrices; returned by ncols() / Rf_ncols().
//   data   — void * to the heap-allocated element buffer; cast by INTEGER(),
//            REAL(), LOGICAL(), RAW() to their respective pointer types.
//
// Both the SEXPREC node and its data buffer are heap-allocated via malloc().
// They are NOT arena-managed: returned SEXPs must outlive the function frame
// (they are the .Call return values consumed by Python).  See Arena/Memory
// Notes in the guide (Section 4) for the distinction between SEXP allocations
// and R_alloc / ALLOC scratch allocations.
// ---------------------------------------------------------------------------
#ifndef FAKE_SEXPREC_DEFINED
#define FAKE_SEXPREC_DEFINED

struct SEXPREC {
    SEXPTYPE  type;    /* one of the SEXPTYPE tags above */
    int       length;  /* total element count (used by LENGTH()) */
    int       nrow;    /* row count for matrices (used by nrows()) */
    int       ncol;    /* column count for matrices (used by ncols()) */
    void     *data;    /* pointer to the element buffer (heap-allocated) */
};

typedef SEXPREC *SEXP;

#endif // FAKE_SEXPREC_DEFINED

// ---------------------------------------------------------------------------
// sexptype_element_size — returns sizeof(element) for a given SEXPTYPE.
// Used by allocVector and allocMatrix to size the data buffer correctly.
// INTSXP and LGLSXP both use int; REALSXP uses double; etc.
// ---------------------------------------------------------------------------
#ifndef FAKE_SEXPTYPE_ELEMENT_SIZE_DEFINED
#define FAKE_SEXPTYPE_ELEMENT_SIZE_DEFINED

inline size_t sexptype_element_size(SEXPTYPE type) {
    switch (type) {
        case INTSXP:
        case LGLSXP:    return sizeof(int);
        case REALSXP:   return sizeof(double);
        case CPLXSXP:   return 2 * sizeof(double);
        case RAWSXP:    return sizeof(unsigned char);
        case STRSXP:
        case VECSXP:
        case EXPRSXP:   return sizeof(SEXP);
        default:        return sizeof(int);
    }
}

#endif // FAKE_SEXPTYPE_ELEMENT_SIZE_DEFINED

// ---------------------------------------------------------------------------
// Core fake implementation — allocVector
//
// Pattern: 1-D integer vector allocation
// Locations: pred_rpart.c:139, rpart.c:194, rpartexp2.c:47
//   SEXP where = PROTECT(allocVector(INTSXP, n));
//   SEXP which3 = PROTECT(allocVector(INTSXP, n));
//   SEXP keep  = PROTECT(allocVector(INTSXP, n));
//
// When type == INTSXP, data holds int[length], zero-initialised.
// INTEGER(sexp) returns int * into this buffer.
//
// The SEXPREC node and its data buffer are both heap-allocated via malloc().
// On failure, RError is thrown (Invariant 1: C++ exception-based errors).
// ---------------------------------------------------------------------------
#ifndef FAKE_ALLOCVECTOR_DEFINED
#define FAKE_ALLOCVECTOR_DEFINED

inline SEXP allocVector(SEXPTYPE type, int length) {
    SEXPREC *s = (SEXPREC *) malloc(sizeof(SEXPREC));
    if (!s) throw RError("allocVector: out of memory allocating SEXPREC node");
    s->type   = type;
    s->length = length;
    s->nrow   = length;
    s->ncol   = 1;
    size_t bytes = (size_t) length * sexptype_element_size(type);
    s->data = malloc(bytes);
    if (!s->data) {
        free(s);
        throw RError("allocVector: out of memory allocating data buffer");
    }
    memset(s->data, 0, bytes);
    return s;
}

/* Rf_allocVector — canonical name in Rinternals.h; alias to allocVector. */
inline SEXP Rf_allocVector(SEXPTYPE type, int length) {
    return allocVector(type, length);
}

#endif // FAKE_ALLOCVECTOR_DEFINED

// ---------------------------------------------------------------------------
// Core fake implementation — allocMatrix
//
// Pattern: 2-D integer matrix allocation
// Locations: rpart.c:278, rpart.c:285, rpart.c:293
//   inode3  = PROTECT(allocMatrix(INTSXP, nodecount, 6));
//   isplit3 = PROTECT(allocMatrix(INTSXP, splitcount, 3));
//   csplit3 = PROTECT(allocMatrix(INTSXP, catcount, maxcat));
//
// Stores a flat column-major int[nrow * ncol] buffer.
// Column j starts at INTEGER(s) + j * nrow.
// The rpart source advances iptr by nrow per column:
//   for (i = 0; i < 6; i++) { iinode[i] = iptr; iptr += nodecount; }
// This is correct for column-major layout over a flat buffer.
// ---------------------------------------------------------------------------
#ifndef FAKE_ALLOCMATRIX_DEFINED
#define FAKE_ALLOCMATRIX_DEFINED

inline SEXP allocMatrix(SEXPTYPE type, int nrow, int ncol) {
    /* Delegate to allocVector for the flat buffer, then fix up dimensions. */
    SEXP s = allocVector(type, nrow * ncol);
    s->nrow = nrow;
    s->ncol = ncol;
    return s;
}

/* Rf_allocMatrix — canonical name in Rinternals.h; alias to allocMatrix. */
inline SEXP Rf_allocMatrix(SEXPTYPE type, int nrow, int ncol) {
    return allocMatrix(type, nrow, ncol);
}

#endif // FAKE_ALLOCMATRIX_DEFINED

// ---------------------------------------------------------------------------
// Accessor functions — cast sexp->data to the element pointer type.
//
// INTEGER(s): used directly after allocVector(INTSXP, n) in all six CSV rows
//             to obtain the writable int * array.
// REAL(s)   : used at rpart.c:243,263,270 for REALSXP matrices / vectors.
// LOGICAL(s): provided for completeness; not observed in the CSV subset.
// RAW(s)    : provided for completeness.
// ---------------------------------------------------------------------------
#ifndef FAKE_ACCESSORS_DEFINED
#define FAKE_ACCESSORS_DEFINED

inline int           *INTEGER(SEXP s) { return (int *)            s->data; }
inline double        *REAL(SEXP s)    { return (double *)         s->data; }
inline int           *LOGICAL(SEXP s) { return (int *)            s->data; }
inline unsigned char *RAW(SEXP s)     { return (unsigned char *)  s->data; }

/* Rf_* canonical forms — aliases for the accessor inline functions. */
inline int           *Rf_INTEGER(SEXP s) { return INTEGER(s); }
inline double        *Rf_REAL(SEXP s)    { return REAL(s);    }
inline int           *Rf_LOGICAL(SEXP s) { return LOGICAL(s); }

#endif // FAKE_ACCESSORS_DEFINED

// ---------------------------------------------------------------------------
// LENGTH / Rf_length — return the total element count stored in sexp->length.
//
// Usage observed: rpartexp2.c:46  int n = LENGTH(dtimes);
// ---------------------------------------------------------------------------
#ifndef FAKE_LENGTH_DEFINED
#define FAKE_LENGTH_DEFINED

inline int LENGTH(SEXP s)    { return s->length; }
inline int Rf_length(SEXP s) { return s->length; }

#endif // FAKE_LENGTH_DEFINED

// ---------------------------------------------------------------------------
// nrows / ncols — return matrix dimensions stored in sexp->nrow / sexp->ncol.
//
// The real R API provides these as Rf_nrows / Rf_ncols (declared in
// Rinternals.h and defined in matrix.c).  Aliases match the names used
// by the rpart source via the #define compatibility block below.
// ---------------------------------------------------------------------------
#ifndef FAKE_NROWS_NCOLS_DEFINED
#define FAKE_NROWS_NCOLS_DEFINED

inline int Rf_nrows(SEXP s) { return s->nrow; }
inline int Rf_ncols(SEXP s) { return s->ncol; }

#endif // FAKE_NROWS_NCOLS_DEFINED

// ---------------------------------------------------------------------------
// PROTECT / UNPROTECT — no-ops in the fake runtime (no garbage collector).
//
// PROTECT(expr) must return the SEXP produced by expr, identical to the real
// R API.  The inline Rf_protect(SEXP) wrapper achieves this: the compiler
// sees a function call whose return value is the same SEXP passed in.
//
// Usage in every CSV row:
//   SEXP where = PROTECT(allocVector(INTSXP, n));   // pred_rpart.c:139
//   which3 = PROTECT(allocVector(INTSXP, n));        // rpart.c:194
//   inode3 = PROTECT(allocMatrix(INTSXP, ...));      // rpart.c:278
//   ...
//   UNPROTECT(1);                                    // after each .Call entry
// ---------------------------------------------------------------------------
#ifndef FAKE_PROTECT_DEFINED
#define FAKE_PROTECT_DEFINED

inline SEXP Rf_protect(SEXP s)           { return s; }
inline void Rf_unprotect(int /*n*/)      {}
inline void Rf_unprotect_ptr(SEXP /*s*/) {}

#endif // FAKE_PROTECT_DEFINED

// ---------------------------------------------------------------------------
// free_sexp — releases the heap memory for a SEXP and its data buffer.
// Python-side wrappers must call this after extracting element data into
// numpy arrays (or equivalent), to avoid leaking the malloc'd SEXPREC node.
// This function has no counterpart in the real R API (GC handles cleanup).
// ---------------------------------------------------------------------------
#ifndef FAKE_FREE_SEXP_DEFINED
#define FAKE_FREE_SEXP_DEFINED

inline void free_sexp(SEXP s) {
    if (s) {
        free(s->data);
        free(s);
    }
}

#endif // FAKE_FREE_SEXP_DEFINED

// ---------------------------------------------------------------------------
// --- Compatibility aliases (preserve original R API names) ---
//
// The original Rinternals.h (non-enum_SEXPTYPE branch, lines 111-144)
// defines INTSXP as a plain preprocessor constant.  The definitions above
// already emit #define INTSXP 13, which is the canonical alias.
//
// Additional aliases from Rinternals.h that the rpart source uses:
//   - allocVector / allocMatrix are called without the Rf_ prefix in source;
//     the originals are declared as Rf_allocVector / Rf_allocMatrix and
//     aliased via #define allocVector Rf_allocVector.  Here both names are
//     provided as inline functions and the #define alias is added below for
//     safety if any source file includes only this header.
//   - nrows / ncols: original header maps these to Rf_nrows / Rf_ncols.
//   - PROTECT / UNPROTECT: original header maps these to Rf_protect /
//     Rf_unprotect.  The macros below replicate those mappings exactly.
// ---------------------------------------------------------------------------

/* SEXPTYPE tag aliases — already defined above as #define; listed here for
   documentation clarity.  No redefinition needed. */
/* #define INTSXP 13 — defined in the SEXPTYPE block above */

/* allocVector / allocMatrix: both names are inline functions above.
   If source was compiled against a header that defines these as macros
   mapping to Rf_* names, reproduce that aliasing here. */
#ifndef allocVector
#define allocVector Rf_allocVector
#endif
#ifndef allocMatrix
#define allocMatrix Rf_allocMatrix
#endif

/* nrows / ncols aliases: original Rinternals.h maps these to Rf_nrows / Rf_ncols. */
#ifndef nrows
#define nrows(x) Rf_nrows(x)
#endif
#ifndef ncols
#define ncols(x) Rf_ncols(x)
#endif

/* PROTECT / UNPROTECT aliases: original Rinternals.h maps to Rf_protect / Rf_unprotect. */
#ifndef PROTECT
#define PROTECT(s)            Rf_protect(s)
#endif
#ifndef UNPROTECT
#define UNPROTECT(n)          Rf_unprotect(n)
#endif
#ifndef UNPROTECT_PTR
#define UNPROTECT_PTR(s)      Rf_unprotect_ptr(s)
#endif
#ifndef PROTECT_WITH_INDEX
#define PROTECT_WITH_INDEX(s, i) Rf_protect(s)
#endif
#ifndef REPROTECT
#define REPROTECT(s, i)       Rf_protect(s)
#endif

// ---------------------------------------------------------------------------
// --- ArenaFrame usage (Category A with arena-adjacent context) ---
//
// INTSXP itself is a compile-time constant and does not trigger arena use.
// However, the functions that call allocVector(INTSXP,...) and
// allocMatrix(INTSXP,...) (namely rpart() in rpart.c and rpartexp2() in
// rpartexp2.c) also call ALLOC / R_alloc for scratch arrays in the same
// function body.  Those scratch allocations ARE arena-managed via fake_arena.h.
//
// Once fake_arena.h is available, declare `ArenaFrame _frame;` as the FIRST
// statement of every .Call-entry wrapper function that invokes arena-backed
// functions.  Example:
//
//   extern "C" SEXP rpart_entry(SEXP ncat, SEXP method, ...) {
//       ArenaFrame _frame;    // <-- frees all R_alloc/ALLOC scratch on exit
//       try {
//           return rpart(ncat, method, ...);
//       } catch (const RError &e) {
//           set_python_error(e.what());
//           return nullptr;
//       }
//   }
//
//   extern "C" SEXP pred_rpart_entry(SEXP dimx, ...) {
//       ArenaFrame _frame;    // needed only if pred_rpart calls R_alloc
//       try {
//           return pred_rpart(dimx, ...);
//       } catch (const RError &e) {
//           set_python_error(e.what());
//           return nullptr;
//       }
//   }
//
// The SEXP return values (where, which3, inode3, isplit3, csplit3, keep)
// are heap-allocated and survive the ArenaFrame destruction.  They must
// be passed back to Python, which calls free_sexp() after copying data.
// ---------------------------------------------------------------------------

#endif // FAKE_INTSXP_H
