// =============================================================
// isReal.h — Fake R API: isReal / Rf_isReal
// Original R header: Rinternals.h
// Category: B — Accessor / Inline Function (type predicate)
// Auto-generated by generate-r-extern-fake-header agent.
//
// isReal(s) returns TRUE if the SEXP s has type REALSXP (14).
// Original R declaration:
//   Rboolean (Rf_isReal)(SEXP s);   (Rinternals.h:210)
//   #define isReal Rf_isReal        (Rinternals.h:986)
//
// Source usage context:
//   rpart_callback.c:113  if (!isReal(value))   error(_("return value not a vector"))
//   rpart_callback.c:147  if (!isReal(goodness)) error(_("the expression expr1..."))
//
// Both call sites receive the return value of eval() (Category E) and guard
// it before calling REAL() on the same SEXP.  isReal itself needs only the
// SEXPREC->type field — no interpreter, no arena, no function pointer bridge.
//
// Delegation: the authoritative implementation of Rf_isReal (and the
// companion predicates Rf_isInteger and Rf_isNull) is already provided by
// SEXP.h under the FAKE_ISPREDICATES_DEFINED guard as inline functions.
// This header pulls in SEXP.h to ensure those definitions are available, and
// adds a safety-net fallback block (skipped when SEXP.h is already included).
//
// Dependency chain: SEXP.h -> INTSXP.h (SEXPREC struct, REALSXP/INTSXP/NILSXP)
// =============================================================
#pragma once

#ifndef FAKE_R_ISREAL_H
#define FAKE_R_ISREAL_H

// --- Standard library includes ---
#include <stddef.h>   // NULL

// --- Fake R header dependencies ---
//
// SEXP.h provides the authoritative implementation of isReal / Rf_isReal,
// isInteger / Rf_isInteger, and isNull / Rf_isNull under FAKE_ISPREDICATES_DEFINED.
// It also provides (transitively via INTSXP.h) the SEXPREC struct, SEXP typedef,
// and the SEXPTYPE constant block (REALSXP=14, INTSXP=13, NILSXP=0).
#include "SEXP.h"

// --- Safety-net fallback: isReal / isInteger / isNull ---
//
// This block is skipped when SEXP.h is included first (the common case),
// because SEXP.h already sets FAKE_ISPREDICATES_DEFINED.  It is present so
// that isReal.h can be included standalone (before SEXP.h) and still compile.
//
// Implementation strategy (from isReal.md Section 3):
//   Return int rather than Rboolean to avoid a forward-reference on Rboolean.
//   All call sites in rpart use the result in !isReal(...) boolean tests —
//   int (1 or 0) is fully compatible.
#ifndef FAKE_ISPREDICATES_DEFINED
#define FAKE_ISPREDICATES_DEFINED

inline int Rf_isReal(SEXP s)    { return s->type == REALSXP; }
inline int Rf_isInteger(SEXP s) { return s->type == INTSXP;  }
inline int Rf_isNull(SEXP s)    { return s->type == NILSXP;  }

// Short-form aliases: Rinternals.h lines 986-988.
// Provided as inline functions (not #define macros) to avoid
// double-expansion if isReal / isInteger / isNull appear as identifiers
// in complex call sites.
inline int isReal(SEXP s)    { return Rf_isReal(s);    }
inline int isInteger(SEXP s) { return Rf_isInteger(s); }
inline int isNull(SEXP s)    { return Rf_isNull(s);    }

#endif // FAKE_ISPREDICATES_DEFINED

// --- Compatibility aliases ---
//
// Whether the definitions came from SEXP.h or the fallback block above,
// the following Rinternals.h aliases are covered:
//
//   Rinternals.h line 986: #define isReal    Rf_isReal
//   Rinternals.h line 987: #define isInteger Rf_isInteger
//   Rinternals.h line 988: #define isNull    Rf_isNull
//
// Provided as inline wrapper functions in both paths; no additional
// #define macros are emitted here to avoid conflicts.

#endif // FAKE_R_ISREAL_H
