// =============================================================
// LENGTH.h — Fake R API: LENGTH
// Original R header: Rinternals.h
// Category: B — Accessor Macro or Inline Function
// Auto-generated by generate-r-extern-fake-header agent.
//
// LENGTH is declared in Rinternals.h at line 279 as:
//   int (LENGTH)(SEXP x);
// The parenthesised form prevents the compiler treating the declaration
// as a macro invocation if a #define LENGTH is in scope.  It returns the
// total element count of any SEXP vector or matrix as a plain C int.
//
// The core LENGTH and Rf_length definitions live in INTSXP.h
// (guard: FAKE_LENGTH_DEFINED).  This header:
//   (a) re-exports those definitions via the INTSXP.h dependency,
//   (b) provides the typedef R_xlen_t (needed by XLENGTH and other
//       Rinternals.h items that use the 64-bit-safe length type), and
//   (c) provides the full family of length accessors declared in
//       Rinternals.h lines 279-281 and 1137-1141 and 1263-1264:
//         LENGTH / Rf_length         — int,       already in INTSXP.h
//         XLENGTH / Rf_xlength       — R_xlen_t,  already in SEXP.h (macro)
//         TRUELENGTH / XTRUELENGTH   — R_xlen_t,  added here
//         LENGTH_EX / XLENGTH_EX     — debug variants, added here
//         SETLENGTH / SET_TRUELENGTH — setters,    added here
//
// Observed rpart usage (all four CSV rows):
//   rpart_callback.c:115  if (LENGTH(value) != (1 + rsave))
//   rpart_callback.c:149  j = LENGTH(goodness);
//   rpartexp2.c:46        int n = LENGTH(dtimes);
//   xpred.c:74            ncp = LENGTH(cp2);
//
// In every case the return type is used as a plain C int.  All rpart
// usage fits within 32-bit int bounds; R_xlen_t == int in the fake build.
//
// Integration Requirements (from LENGTH.md Section 5):
//   - INTSXP.h : struct SEXPREC with int length field; LENGTH / Rf_length.
//   - SEXP.h   : XLENGTH macro and Rf_xlength inline (FAKE_XLENGTH_DEFINED).
//   - fake_arena.h : ArenaFrame; required by .Call wrappers that enclose the
//                    LENGTH call sites.  LENGTH itself does not use the arena.
//   - error.md : RError / Rf_error — required by rpart_callback.c:116/158
//                immediately after the LENGTH comparisons.  Provided by
//                INTSXP.h (transitive through the include chain).
// =============================================================
#pragma once

#ifndef FAKE_LENGTH_H
#define FAKE_LENGTH_H

// --- Standard library includes ---
#include <stddef.h>   // ptrdiff_t, size_t

// --- Fake R header dependencies ---
// (from Integration Requirements in LENGTH.md)
//
// INTSXP.h provides: struct SEXPREC, typedef SEXP, LENGTH, Rf_length,
// allocVector, INTEGER, REAL, PROTECT/UNPROTECT, RError, and the full
// SEXPTYPE constant block.
#include "INTSXP.h"

// SEXP.h provides: XLENGTH macro (FAKE_XLENGTH_DEFINED), Rf_xlength,
// TYPEOF, asInteger/asReal, isReal/isInteger/isNull, mkChar, CHAR,
// VECTOR_ELT/SET_VECTOR_ELT, STRING_ELT/SET_STRING_ELT,
// R_NilValue/R_UnboundValue/R_NamesSymbol, setAttrib/getAttrib,
// and the extended free_sexp_deep helper.
#include "SEXP.h"

// ---------------------------------------------------------------------------
// R_xlen_t — the 64-bit-safe length type used throughout Rinternals.h.
//
// The real Rinternals.h (lines 75 / 80):
//   #ifdef __LP64__
//     typedef ptrdiff_t R_xlen_t;    // 64-bit platforms
//   #else
//     typedef int       R_xlen_t;    // 32-bit platforms
//   #endif
//
// rpart operates only on lengths that fit in a 32-bit int; every
// LENGTH() result in the CSV is stored into a plain int variable.
// Typedef to int is therefore safe for the fake build and avoids
// introducing ptrdiff_t mismatch warnings.
//
// Guard: FAKE_R_XLEN_T_DEFINED prevents redefinition if a future
// header also provides this typedef.
// ---------------------------------------------------------------------------
#ifndef FAKE_R_XLEN_T_DEFINED
#define FAKE_R_XLEN_T_DEFINED

typedef int R_xlen_t;

#endif // FAKE_R_XLEN_T_DEFINED

// ---------------------------------------------------------------------------
// TRUELENGTH / XTRUELENGTH — allocated-capacity accessors.
//
// The real Rinternals.h (lines 281 / 1139):
//   R_xlen_t (TRUELENGTH)(SEXP x);
//   R_xlen_t (XTRUELENGTH)(SEXP x);
//
// These return the allocated capacity, which may exceed the logical
// length for growable vectors.  The fake SEXPREC has no separate
// "true length" field; allocVector always allocates exactly length
// elements, so TRUELENGTH == LENGTH in the fake build.
//
// None of the four rpart CSV rows call TRUELENGTH.  It is included
// because some R macro paths (e.g. PROTECT internals in newer R builds)
// may reference it when Rinternals.h is transitively processed.
// ---------------------------------------------------------------------------
#ifndef FAKE_TRUELENGTH_DEFINED
#define FAKE_TRUELENGTH_DEFINED

// Pattern P1/P2 — read the allocated capacity (same as length in fake).
inline R_xlen_t TRUELENGTH(SEXP s)  { return (R_xlen_t) s->length; }
inline R_xlen_t XTRUELENGTH(SEXP s) { return (R_xlen_t) s->length; }

#endif // FAKE_TRUELENGTH_DEFINED

// ---------------------------------------------------------------------------
// LENGTH_EX / XLENGTH_EX — debug-variant accessors (Rinternals.h:1140-1141).
//
// The real Rinternals.h (lines 1140-1141):
//   int      LENGTH_EX(SEXP x, const char *file, int line);
//   R_xlen_t XLENGTH_EX(SEXP x);
//
// LENGTH_EX is the bounds-checked debug form activated when R is built
// with STRICT_R_HEADERS or via the USE_RINTERNALS macro path.  rpart
// does not define USE_RINTERNALS, so the non-gated function declarations
// at lines 279-280 are resolved by the compiler instead.  The _EX
// variants are provided here in case a transitive include (e.g. from a
// system R header wrapper) references them.
//
// Note from guide Section 3: "In modern R builds (R >= 4.5) a
// USE_RINTERNALS-gated macro path may redirect LENGTH through
// LENGTH_EX(x, __FILE__, __LINE__), but rpart does not define
// USE_RINTERNALS, so the non-gated function declaration at line 279
// is the one resolved by the compiler."
// ---------------------------------------------------------------------------
#ifndef FAKE_LENGTH_EX_DEFINED
#define FAKE_LENGTH_EX_DEFINED

// LENGTH_EX — debug variant; ignores file/line arguments; delegates to LENGTH.
inline int LENGTH_EX(SEXP s, const char * /*file*/, int /*line*/) {
    return s->length;
}

// XLENGTH_EX — 64-bit debug variant; ignores file/line (not in signature
// per Rinternals.h:1141); delegates to XLENGTH via the int fake type.
inline R_xlen_t XLENGTH_EX(SEXP s) {
    return (R_xlen_t) s->length;
}

#endif // FAKE_LENGTH_EX_DEFINED

// ---------------------------------------------------------------------------
// SETLENGTH / SET_TRUELENGTH — length setters (Rinternals.h:1263-1264).
//
// The real Rinternals.h (lines 1263-1264):
//   void (SETLENGTH)(SEXP x, R_xlen_t v);        // used by many packages
//   void (SET_TRUELENGTH)(SEXP x, R_xlen_t v);   // used by many packages
//
// These allow packages to resize a vector in-place (a pattern used by
// growable-vector code).  None of the rpart CSV usage rows call these
// setters, but they are declared in Rinternals.h alongside LENGTH and
// are provided to avoid linker or compilation errors if any rpart source
// file (or a transitively included header) references them.
//
// Fake strategy: write the value directly into s->length.  No realloc
// of the data buffer is performed; the caller is responsible for
// ensuring the data buffer is large enough.  This is consistent with
// the "no runtime R linkage" invariant — fake SEXP objects are
// heap-allocated with a fixed-size data buffer matching the original
// length argument to allocVector / allocMatrix.
// ---------------------------------------------------------------------------
#ifndef FAKE_SETLENGTH_DEFINED
#define FAKE_SETLENGTH_DEFINED

inline void SETLENGTH(SEXP s, R_xlen_t v) {
    s->length = (int) v;
}

inline void SET_TRUELENGTH(SEXP s, R_xlen_t v) {
    s->length = (int) v;
}

#endif // FAKE_SETLENGTH_DEFINED

// ---------------------------------------------------------------------------
// --- Compatibility aliases (preserve original R API names) ---
//
// Original Rinternals.h aliases for LENGTH-family items.
//
// LENGTH / Rf_length    — already defined as inline functions in INTSXP.h
//                         (guard: FAKE_LENGTH_DEFINED).  No alias needed
//                         because the real Rinternals.h does NOT define a
//                         #define LENGTH macro in the non-USE_RINTERNALS path.
//                         The parenthesised function declaration
//                         `int (LENGTH)(SEXP x)` suppresses macro
//                         interpretation.  The inline function suffices.
//
// XLENGTH               — already defined as a macro in SEXP.h:
//                         #define XLENGTH(x) Rf_xlength(x)
//                         The real Rinternals.h uses the same parenthesised
//                         declaration form as LENGTH; the macro form in SEXP.h
//                         is compatible because rpart never calls XLENGTH.
//
// Rf_xlength            — already defined as an inline in SEXP.h.
//
// R_xlen_t              — typedef int, defined above.
// TRUELENGTH            — inline function defined above.
// XTRUELENGTH           — inline function defined above.
// LENGTH_EX             — inline function defined above.
// XLENGTH_EX            — inline function defined above.
// SETLENGTH             — inline function defined above.
// SET_TRUELENGTH        — inline function defined above.
// ---------------------------------------------------------------------------

// --- ArenaFrame usage ---
// LENGTH itself performs no allocation and does not interact with the arena.
// The .Call-entry wrappers that enclose the LENGTH call sites DO require an
// ArenaFrame guard because the surrounding rpart/rpartexp2/xpred functions
// call ALLOC / R_alloc scratch allocations.
//
// Declare `ArenaFrame _frame;` as the first statement of any .Call-entry
// function whose body (directly or transitively) invokes arena-backed
// functions such as R_alloc or ALLOC from rpart's internal memory layer.
//
// Example for rpartexp2 (the simplest case):
//
//   #include "fake_arena.h"
//   extern "C" SEXP rpartexp2_entry(SEXP dtimes, SEXP eps) {
//       ArenaFrame _frame;   // arena scratch freed on exit (Invariant 2)
//       try {
//           return rpartexp2(dtimes, eps);
//           // Inside rpartexp2:
//           //   int n = LENGTH(dtimes);        => dtimes->length
//           //   SEXP keep = PROTECT(allocVector(INTSXP, n));  => heap
//           //   Rpartexp2(n, REAL(dtimes), asReal(eps), INTEGER(keep));
//           //   UNPROTECT(1);                  => no-op
//           //   return keep;                   => heap SEXP; outlives frame
//       } catch (const RError &e) {
//           set_python_error(e.what());
//           return nullptr;
//       }
//   }
//
// The SEXP return value (keep) is heap-allocated via malloc() inside
// allocVector and survives ArenaFrame destruction.  Python extracts data
// via INTEGER(keep) and calls free_sexp(keep) after copying into a numpy
// array.

#endif // FAKE_LENGTH_H
