// =============================================================
// mkChar.h — Fake R API: mkChar / Rf_mkChar and the mkChar family
// Original R header: Rinternals.h
// Category: C — Allocation / Memory Function
// Auto-generated by generate-r-extern-fake-header agent.
//
// mkChar(const char *str) allocates a CHARSXP node from a null-terminated
// C string.  The resulting SEXP has type CHARSXP (9) and its data field
// holds a heap-allocated copy of the input string.  In R's C API:
//   SEXP Rf_mkChar(const char *);        (Rinternals.h line 564)
//   #define mkChar Rf_mkChar             (Rinternals.h line 1020)
//
// Source usage context — rpart.c lines 327-344:
//   SEXP rname = allocVector(STRSXP, nout);
//   setAttrib(rlist, R_NamesSymbol, rname);
//   SET_STRING_ELT(rname, 0, mkChar("which"));
//   SET_STRING_ELT(rname, 1, mkChar("cptable"));
//   SET_STRING_ELT(rname, 2, mkChar("dsplit"));
//   SET_STRING_ELT(rname, 3, mkChar("isplit"));
//   SET_STRING_ELT(rname, 4, mkChar("dnode"));
//   SET_STRING_ELT(rname, 5, mkChar("inode"));
//   SET_STRING_ELT(rname, 6, mkChar("csplit"));   // when catcount > 0
//
// Implementation strategy (from mkChar.md Section 3):
//   Heap-allocate (std::malloc) a SEXPREC node with type=CHARSXP and a
//   separate string buffer.  Both allocations outlive the ArenaFrame at the
//   .Call boundary because the CHARSXP is stored as a STRSXP element and
//   must survive until Python calls free_sexp(rname).
//   Throws RError on std::malloc failure (Invariant 1).
//
// Delegation: the authoritative implementations are provided by:
//   SEXP.h     — Rf_mkChar under FAKE_MKCHAR_DEFINED
//   STRSXP.h   — Rf_mkCharCE, Rf_mkCharLen, Rf_mkCharLenCE, Rf_mkString
//                under FAKE_MKCHARCEFAMILY_DEFINED; also cetype_t typedef
//                under FAKE_CETYPE_T_DEFINED
//
// This header includes STRSXP.h (which pulls in SEXP.h transitively) and
// adds safety-net fallback blocks under the same guards, so that mkChar.h
// can also be used standalone.
// =============================================================
#pragma once

#ifndef FAKE_R_MKCHAR_H
#define FAKE_R_MKCHAR_H

// --- Standard library includes ---
#include <stddef.h>   // size_t, NULL
#include <stdlib.h>   // std::malloc, std::free
#include <string.h>   // std::strlen, std::strcpy, std::memcpy

// --- Fake R header dependencies ---
//
// STRSXP.h provides:
//   - Rf_mkChar / mkChar (FAKE_MKCHAR_DEFINED, via SEXP.h)
//   - cetype_t typedef (FAKE_CETYPE_T_DEFINED)
//   - Rf_mkCharCE / mkCharCE, Rf_mkCharLen / mkCharLen,
//     Rf_mkCharLenCE / mkCharLenCE, Rf_mkString / mkString
//     (FAKE_MKCHARCEFAMILY_DEFINED)
//   - R_BlankString, R_BlankScalarString sentinels
//   - STRSXP allocations (allocVector(STRSXP,...), STRING_ELT,
//     SET_STRING_ELT — the direct consumers of mkChar's return value)
//
// Transitively provides (via SEXP.h -> INTSXP.h):
//   SEXPREC struct, SEXP typedef, CHARSXP/STRSXP/REALSXP/INTSXP/NILSXP
//   constants, RError, R_CHAR / CHAR, PRINTNAME, mkChar (primary stub),
//   allocVector, LENGTH, PROTECT, UNPROTECT, R_NilValue, etc.
#include "STRSXP.h"

// --- Safety-net fallback: Rf_mkChar ---
//
// This block is skipped when SEXP.h (or STRSXP.h) is included first,
// because SEXP.h already sets FAKE_MKCHAR_DEFINED.  It is present so
// that mkChar.h can be included standalone and still compile.
//
// Implementation per mkChar.md Section 3:
//   - Allocate SEXPREC (sizeof(SEXPREC) bytes) via std::malloc.
//   - Set type=CHARSXP, length=len, nrow=len, ncol=1.
//   - Allocate string buffer (len+1 bytes) via std::malloc.
//   - Copy string into buffer via std::strcpy.
//   - Return SEXP.  Throws RError on std::malloc failure (Invariant 1).
#ifndef FAKE_MKCHAR_DEFINED
#define FAKE_MKCHAR_DEFINED

inline SEXP Rf_mkChar(const char *str) {
    std::size_t len = std::strlen(str);
    SEXPREC *s = static_cast<SEXPREC *>(std::malloc(sizeof(SEXPREC)));
    if (!s) throw RError("mkChar: out of memory (SEXPREC)");
    s->type   = CHARSXP;
    s->length = static_cast<int>(len);
    s->nrow   = static_cast<int>(len);
    s->ncol   = 1;
    s->data   = std::malloc(len + 1);
    if (!s->data) {
        std::free(s);
        throw RError("mkChar: out of memory (string buffer)");
    }
    std::strcpy(static_cast<char *>(s->data), str);
    return s;
}

// Short-form alias: Rinternals.h line 1020.
// Provided as an inline function wrapper (not a #define macro) to avoid
// double-expansion, consistent with the alias pattern used throughout
// these fake headers.
inline SEXP mkChar(const char *str) { return Rf_mkChar(str); }

#endif // FAKE_MKCHAR_DEFINED

// --- Safety-net fallback: cetype_t ---
#ifndef FAKE_CETYPE_T_DEFINED
#define FAKE_CETYPE_T_DEFINED
typedef enum {
    CE_NATIVE = 0,
    CE_UTF8   = 1,
    CE_LATIN1 = 2,
    CE_BYTES  = 3,
    CE_SYMBOL = 5,
    CE_ANY    = 99
} cetype_t;
#endif // FAKE_CETYPE_T_DEFINED

// --- Safety-net fallback: mkChar family ---
#ifndef FAKE_MKCHARCEFAMILY_DEFINED
#define FAKE_MKCHARCEFAMILY_DEFINED

inline SEXP Rf_mkCharLen(const char *str, int len) {
    SEXPREC *s = static_cast<SEXPREC *>(std::malloc(sizeof(SEXPREC)));
    if (!s) throw RError("mkCharLen: out of memory (SEXPREC)");
    s->type   = CHARSXP;
    s->length = len;
    s->nrow   = len;
    s->ncol   = 1;
    s->data   = std::malloc(static_cast<std::size_t>(len) + 1);
    if (!s->data) { std::free(s); throw RError("mkCharLen: out of memory (buffer)"); }
    std::memcpy(s->data, str, static_cast<std::size_t>(len));
    static_cast<char *>(s->data)[len] = '\0';
    return s;
}
inline SEXP mkCharLen(const char *str, int len) { return Rf_mkCharLen(str, len); }

inline SEXP Rf_mkCharCE(const char *str, cetype_t /*enc*/) { return Rf_mkChar(str); }
inline SEXP mkCharCE(const char *str, cetype_t enc) { return Rf_mkCharCE(str, enc); }

inline SEXP Rf_mkCharLenCE(const char *str, int len, cetype_t /*enc*/) {
    return Rf_mkCharLen(str, len);
}
inline SEXP mkCharLenCE(const char *str, int len, cetype_t enc) {
    return Rf_mkCharLenCE(str, len, enc);
}

inline SEXP Rf_mkString(const char *str) {
    SEXP charsxp = Rf_mkChar(str);
    SEXPREC *s = static_cast<SEXPREC *>(std::malloc(sizeof(SEXPREC)));
    if (!s) throw RError("mkString: out of memory (SEXPREC)");
    s->type   = STRSXP;
    s->length = 1;
    s->nrow   = 1;
    s->ncol   = 1;
    s->data   = std::malloc(sizeof(SEXP));
    if (!s->data) { std::free(s); throw RError("mkString: out of memory (data)"); }
    static_cast<SEXP *>(s->data)[0] = charsxp;
    return s;
}
inline SEXP mkString(const char *str) { return Rf_mkString(str); }

#endif // FAKE_MKCHARCEFAMILY_DEFINED

// --- Compatibility aliases (from Rinternals.h) ---
//
// Whether provided by STRSXP.h or the fallback blocks above, the following
// Rinternals.h aliases are present:
//
//   Rinternals.h line 1020: #define mkChar       Rf_mkChar
//   Rinternals.h line 1021: #define mkCharCE     Rf_mkCharCE
//   Rinternals.h line 1022: #define mkCharLen    Rf_mkCharLen
//   Rinternals.h line 1023: #define mkCharLenCE  Rf_mkCharLenCE
//   Rinternals.h line 1025: #define mkString     Rf_mkString
//
// All are provided as inline wrapper functions rather than #define macros
// to avoid macro double-expansion conflicts.

// --- Arena / Memory Notes ---
//
// mkChar and all family members use std::malloc (NOT arena) for all
// allocations.  CHARSXP nodes must survive the ArenaFrame RAII guard at
// the .Call boundary because they are embedded in the rname STRSXP that is
// part of the function return value.
//
// Memory is reclaimed by free_sexp_deep(rname) or free_sexp(rname) after
// the Python caller extracts the named list fields from the returned VECSXP.
// The STRSXP-recursive branch in free_sexp (defined in SEXP.h / STRSXP.h)
// walks the STRSXP's data[] slot array and calls free_sexp on each CHARSXP
// child, freeing both charnode->data (the string buffer) and charnode itself.

#endif // FAKE_R_MKCHAR_H
