// =============================================================
// R_chk_calloc.h — Fake R API: R_chk_calloc
// Original R header: R.h (transitively via R_ext/RS.h)
// Category: C — Allocation or Memory Function
// Auto-generated by generate-r-extern-fake-header agent.
//
// R_chk_calloc is R's checked, zero-initializing heap allocator declared
// in R_ext/RS.h (confirmed at
//   ~/.conda/envs/r-to-python/lib/R/include/R_ext/RS.h) as:
//
//   extern void *R_chk_calloc(R_SIZE_T nmemb, R_SIZE_T size);
//
// where R_SIZE_T resolves to std::size_t in C++ builds.
//
// In rpart, R_chk_calloc is referenced at exactly one location in the
// package source:
//
//   rpart.h:26  #define CALLOC(a,b)  R_chk_calloc((size_t)(a), b)
//
// Every actual allocation call goes through the CALLOC macro.  The nine
// call sites and their allocated types are:
//
//   insert_split.c:25,37,65,74 — CALLOC(1, splitsize)  -> pSplit
//   partition.c:98,113         — CALLOC(1, nodesize)   -> pNode (left/right son)
//   xval.c:58                  — CALLOC(3*rp.num_unique_cp, sizeof(double)) -> double *
//   xval.c:61                  — CALLOC(rp.n, sizeof(int))                  -> int *
//   xval.c:134                 — CALLOC(1, nodesize)   -> pNode (xtree root)
//
// CRITICAL ALLOCATOR DISTINCTION (from rpart.h:19-23 comment):
//   "Memory defined with R_alloc is removed automatically.
//    That with CALLOC I have to remove myself."
//
//   ALLOC(a,b)  = R_alloc(a,b)                    -> ARENA (ArenaFrame-managed)
//   CALLOC(a,b) = R_chk_calloc((size_t)(a), b)    -> HEAP  (freed via R_Free)
//
// R_chk_calloc uses std::calloc (heap), NOT the arena.  This is intentional:
// Node and Split structs allocated during recursive tree construction in
// partition.c and insert_split.c must survive across multiple nested function
// calls within a single .Call invocation.  They are freed explicitly by
// free_tree() / free_split() (which call R_Free internally) before the .Call
// returns.  Using the arena here would be incorrect because the ArenaFrame
// destructor fires at .Call exit, which is after the nodes have already been
// recursively freed — double-free territory.
//
// IMPLEMENTATION LOCATION:
//   The full implementation of R_chk_calloc, R_chk_realloc, R_chk_free,
//   R_chk_memcpy, R_chk_memset, and all related RS.h macros (R_Free,
//   R_Calloc, R_Realloc, Memcpy, Memzero, CallocCharBuf) is in R_Free.h.
//   This header is a forwarding wrapper that includes R_Free.h.
//   All definitions are guarded with FAKE_R_CHK_CALLOC_DEFINED (and
//   their respective per-function guards) so including both this header
//   and R_Free.h is safe and idempotent.
//
// Integration Requirements (from R_chk_calloc.md Section 5):
//   - fake_arena.h  : ArenaFrame for ALLOC/R_alloc scratch in the same .Call
//                     wrappers.  R_chk_calloc itself does not call arena
//                     functions, but .Call wrappers covering both allocators
//                     need ArenaFrame.  Included transitively via fake_R.h.
//   - SEXP.h / INTSXP.h : provide RError (FAKE_R_RERROR_DEFINED guard).
//                     R_chk_calloc throws RError on OOM (Invariant 1).
//                     Included transitively via R_Free.h.
//   - R_alloc.h     : documents the arena side (R_alloc / ALLOC macro).
//                     Included transitively via fake_R.h; no explicit
//                     dependency from this file.
//   - R_Free.h      : provides the shared implementation of R_chk_calloc
//                     and all paired helpers.  THIS is the authoritative
//                     definition file.
//
// Additional usage patterns found in source inspection (not in CSV):
//   - Every CALLOC call site also has a co-located R_Free call (either
//     directly or via free_tree / free_split recursion) — the fake
//     preserves this invariant because R_chk_calloc returns heap memory
//     that R_Free / R_chk_free correctly releases with std::free.
//   - xval.c assigns interior pointers (xpred, cp) into the xtemp block
//     allocated at xval.c:58.  R_Free(xtemp) at xval.c:179 frees the
//     entire block; xpred and cp become dangling but are not accessed
//     afterwards.  The fake reproduces this exactly because std::calloc
//     guarantees a single contiguous block for the full nmemb*size bytes.
//   - splitsize at insert_split.c:20 may exceed sizeof(Split) when ncat > 20
//     (variable-length csplit tail).  nodesize at rpart.c exceeds sizeof(Node)
//     by (num_resp-1)*sizeof(double).  std::calloc zero-initializes the
//     entire allocation including the variable-length tail, matching
//     R's R_chk_calloc behaviour exactly.
// =============================================================
#pragma once

#ifndef FAKE_R_CHK_CALLOC_H
#define FAKE_R_CHK_CALLOC_H

// --- Standard library includes ---
// (Provided transitively by R_Free.h; listed here for documentation.)
// #include <stdlib.h>   // std::calloc, std::free
// #include <stddef.h>   // std::size_t

// --- Fake R header dependencies ---
// (from Integration Requirements in R_chk_calloc.md)
//
// R_Free.h is the shared implementation file for all of R_ext/RS.h.
// It provides under their respective FAKE_R_*_DEFINED guards:
//
//   FAKE_R_RERROR_DEFINED      — struct RError : public std::runtime_error
//   FAKE_R_CHK_CALLOC_DEFINED  — inline void *R_chk_calloc(size_t, size_t)
//   FAKE_R_CHK_REALLOC_DEFINED — inline void *R_chk_realloc(void *, size_t)
//   FAKE_R_CHK_FREE_DEFINED    — inline void  R_chk_free(void *)
//   FAKE_R_CHK_MEMCPY_DEFINED  — inline void *R_chk_memcpy(void *, const void *, size_t)
//   FAKE_R_CHK_MEMSET_DEFINED  — inline void *R_chk_memset(void *, int, size_t)
//   R_Free(p)                  — macro: (R_chk_free((void*)(p)), (p) = nullptr)
//   R_Calloc(n, t)             — macro: typed heap allocation via R_chk_calloc
//   R_Realloc(p, n, t)         — macro: typed heap reallocation
//   Memcpy(p, q, n)            — macro: type-aware memcpy
//   Memzero(p, n)              — macro: type-aware memset to zero
//   CallocCharBuf(n)           — macro: char buffer allocation (n+1 bytes)
//
// Including R_Free.h here is safe and idempotent due to its own
// #pragma once and FAKE_R_FREE_H include guard.
#include "R_Free.h"

// --- Compatibility aliases (preserve original R API names) ---
//
// The original R_ext/RS.h declares R_chk_calloc with extern linkage:
//   extern void *R_chk_calloc(R_SIZE_T nmemb, R_SIZE_T size);
//
// No remapping #define alias exists in the real RS.h for R_chk_calloc itself
// (unlike Rf_error -> error).  The function is consumed by:
//   (a) the CALLOC macro in rpart.h:26 (unchanged original source), and
//   (b) the R_Calloc / CallocCharBuf macros from RS.h (in R_Free.h above).
//
// R_SIZE_T must be defined for R_chk_calloc's documented signature to match:
//   extern void *R_chk_calloc(R_SIZE_T nmemb, R_SIZE_T size);
// The original RS.h defines R_SIZE_T as std::size_t in C++ builds.
// Provide the same mapping here under a guard so CALLOC(a, b) expands
// with correct types when only this header (not the full fake_R.h chain)
// is included.
#ifndef R_SIZE_T
#  if defined(__cplusplus)
#    include <cstddef>
#    define R_SIZE_T std::size_t
#  else
#    include <stddef.h>
#    define R_SIZE_T size_t
#  endif
#endif

// --- ArenaFrame usage (Category C) ---
//
// R_chk_calloc allocates from the HEAP (std::calloc).  It is NOT governed
// by ArenaFrame.  However, every .Call-entry wrapper that (transitively)
// invokes any function using CALLOC also uses ALLOC (= R_alloc, arena-
// backed) in the same call tree.  Therefore, every such wrapper must
// declare `ArenaFrame _frame;` as its first statement so that the
// ALLOC-based scratch memory is freed on both normal and exceptional exit.
//
// CALLOC-allocated blocks (Node, Split structs; flat arrays xtemp, savew)
// are NOT freed by ArenaFrame.  They are freed by the existing R_Free calls
// already present in the rpart source (free_tree.c:13,29; insert_split.c:36,63;
// xval.c:178-179).  No source modification is needed.
//
// Representative .Call wrapper showing coexistence of both allocators:
//
//   #include "fake_arena.h"    // provides ArenaFrame
//   #include "fake_R.h"        // provides R_chk_calloc (via R_Free.h),
//                              // R_alloc (via R_alloc.h), RError, SEXP, etc.
//
//   extern "C" SEXP rpart_entry(
//           SEXP ncat2, SEXP method2, SEXP opt2, SEXP parms2,
//           SEXP xvals2, SEXP xgrp2, SEXP ymat2, SEXP xmat2,
//           SEXP wt2, SEXP ny2, SEXP cost2) {
//       ArenaFrame _frame;   // <-- frees ALLOC/R_alloc arena scratch on exit
//       try {
//           return rpart(ncat2, method2, opt2, parms2, xvals2, xgrp2,
//                        ymat2, xmat2, wt2, ny2, cost2);
//           // On normal return:
//           //   _frame destructs: all ALLOC'd arena blocks freed.
//           //   All CALLOC'd Node/Split/array blocks freed by free_tree /
//           //   free_split / R_Free calls inside xval() and rpart().
//       } catch (const RError &e) {
//           // _frame destructs: ALLOC arena blocks freed.
//           // CALLOC blocks not yet freed by R_Free will leak on this path.
//           // In practice RError is thrown only on OOM or bad inputs, so
//           // the process is about to signal a Python exception; a leak
//           // is acceptable on the fatal-error path.
//           set_python_error(e.what());
//           return R_NilValue;
//       } catch (const std::bad_alloc &) {
//           set_python_error("R_chk_calloc: out of memory");
//           return R_NilValue;
//       }
//   }   // _frame destructs here on normal return

#endif // FAKE_R_CHK_CALLOC_H
