// =============================================================
// R_CheckUserInterrupt.h — Fake R API: R_CheckUserInterrupt
// Original R header: R_ext/Utils.h
// Category: D — Error, Warning, or Print Function
//   (aborts execution via longjmp in the real R runtime;
//    replaced here by a C++ throw, per Invariant 1)
// Auto-generated by generate-r-extern-fake-header agent.
//
// Original R declaration (from ~/.conda/envs/r-to-python/lib/R/include/R_ext/Utils.h):
//   void R_CheckUserInterrupt(void);
//   void R_CheckStack(void);
//   void R_CheckStack2(R_SIZE_T);
// No #define aliases are defined for R_CheckUserInterrupt in the original header.
//
// Observed usage in rpart source:
//
//   Pattern: Bare interrupt check at bottom of cross-validation loop.
//     xpred.c:291 — bottom of for(xgroup=0;xgroup<xvals;xgroup++) after free_tree(xtree,0)
//     xval.c:168  — bottom of for(xgroup=0;xgroup<n_xval;xgroup++) after free_tree(xtree,1)
//
//   In both cases the call is a bare `R_CheckUserInterrupt();` with no
//   surrounding PROTECT/UNPROTECT or allocation calls at the exact check point.
//   free_tree() has already released the per-fold tree before the check fires,
//   so throwing here leaves no pending per-fold cleanup obligations.
//
// Integration Requirements (from R_CheckUserInterrupt.md Section 5):
//   - SEXP.h (which pulls in INTSXP.h): provides the RError struct.
//     If SEXP.h is included before this header, RError is already defined.
//     If this header is included standalone, a minimal RError is defined below.
//   - fake_arena.h: required by .Call boundary wrappers that call functions
//     containing R_CheckUserInterrupt, but not by this header itself.
//     See the ArenaFrame usage block at the bottom.
// =============================================================
#pragma once

#ifndef FAKE_R_CHECKUSERINTERRUPT_H
#define FAKE_R_CHECKUSERINTERRUPT_H

// --- Standard library includes ---
#include <atomic>      // std::atomic
#include <cstddef>     // std::size_t
#include <cstdio>      // std::fprintf
#include <stdexcept>   // std::runtime_error
#include <string>      // std::string

// --- Fake R header dependencies ---
// (from Integration Requirements in R_CheckUserInterrupt.md)
//
// SEXP.h provides the RError struct (via INTSXP.h).  Include it if the full
// fake runtime is being assembled.  The #ifndef guard below ensures that if
// SEXP.h has already been included (which defines FAKE_SEXP_H and, transitively,
// FAKE_R_RERROR_DEFINED via INTSXP.h), we skip the minimal fallback definition.
#ifdef FAKE_SEXP_H
// SEXP.h was included before this header — RError is already defined.
#else
// SEXP.h not yet included.  Attempt to include it first for a full build.
// If this header is being used standalone, the fallback RError below will fire.
#include "SEXP.h"
#endif

// WARNING: dependency fake_arena.h not found in output_folder.
// ArenaFrame is required by every .Call boundary wrapper whose call graph
// reaches R_CheckUserInterrupt (i.e., xpred_wrapper and rpart_wrapper).
// Once fake_arena.h is present in the output folder, add:
//   #include "fake_arena.h"
// to the .Call entry-point source, not here.  R_CheckUserInterrupt itself
// performs no arena allocation.

// ---------------------------------------------------------------------------
// Minimal RError fallback — only active if SEXP.h (and thereby INTSXP.h) was
// not included before this header.  In a complete build, INTSXP.h defines
// RError under FAKE_R_RERROR_DEFINED; this block is a safety net for
// standalone compilation only.
// ---------------------------------------------------------------------------
#ifndef FAKE_R_RERROR_DEFINED
#define FAKE_R_RERROR_DEFINED

struct RError : public std::runtime_error {
    using std::runtime_error::runtime_error;
};

#endif // FAKE_R_RERROR_DEFINED

// ---------------------------------------------------------------------------
// Interrupt flag.
//
// thread_local: each worker thread has its own independent flag, consistent
//   with the thread_local arena stack in fake_arena.h.  A cross-validation
//   loop running in one thread cannot accidentally observe an interrupt flag
//   meant for a different thread.
//
// std::atomic<bool>: a Python SIGINT handler may run in a different OS thread
//   (e.g., the main Python thread) while the computation thread is inside the
//   cross-validation loop.  The atomic type prevents data races on the flag.
//
// Initialized to false: no interrupt pending at program start or at the
//   beginning of any new thread.
//
// Note on thread_local + inline:
//   C++17 inline variables with thread_local storage are legal; each
//   translation unit that includes this header shares the same variable
//   definition (one per thread per process).  The `inline` keyword suppresses
//   the ODR violation that would arise from multiple definitions across TUs.
// ---------------------------------------------------------------------------
inline thread_local std::atomic<bool> g_interrupt_requested{false};

// ---------------------------------------------------------------------------
// request_user_interrupt — C-linkage entry point callable from Python via
// ctypes.  Sets the interrupt flag so that the next R_CheckUserInterrupt()
// call in any C code running on this thread will throw RError("UserInterrupt").
//
// memory_order_relaxed is sufficient for the store: the flag is read with
// relaxed order on the same thread (after the Python signal handler has
// returned), and correctness requires only that the flag eventually becomes
// visible — no cross-thread ordering guarantee is needed here because the
// check and the set are separated by at least one OS-level signal boundary.
//
// Python SIGINT handler setup:
//
//   import ctypes, signal
//   lib = ctypes.CDLL("/path/to/librpart_fake.so")
//   lib.request_user_interrupt.restype  = None
//   lib.request_user_interrupt.argtypes = []
//
//   def _sigint_handler(signum, frame):
//       lib.request_user_interrupt()
//
//   signal.signal(signal.SIGINT, _sigint_handler)
//
// After installation, pressing Ctrl+C while rpart's cross-validation is
// running will set the flag; the next R_CheckUserInterrupt() call (i.e., the
// next loop iteration in xpred.c or xval.c) will throw RError("UserInterrupt"),
// which propagates to the .Call boundary wrapper and is converted to a Python
// exception (KeyboardInterrupt or RuntimeError).
// ---------------------------------------------------------------------------
extern "C" inline void request_user_interrupt() {
    g_interrupt_requested.store(true, std::memory_order_relaxed);
}

// ---------------------------------------------------------------------------
// Core fake implementation: R_CheckUserInterrupt
//
// Pattern: Bare interrupt check at bottom of cross-validation loop.
// Locations: xpred.c:291, xval.c:168
//
// Behavior:
//   - Flag is false (common case): returns immediately.  A single relaxed
//     atomic load on x86-64 compiles to one register read; overhead is
//     negligible relative to the tree-building work in the surrounding loop.
//   - Flag is true (interrupt requested): clears the flag (so a second call
//     does not re-throw), then throws RError("UserInterrupt").  The C++
//     exception unwinds the call stack through xpred.c / xval.c (all
//     intermediate frames use only automatic-storage or arena-managed
//     variables — no longjmp-unsafe state) up to the .Call boundary wrapper,
//     where it is caught and converted to a Python exception.
//
// Resource safety at throw time:
//   - xpred.c:290: free_tree(xtree, 0) is called BEFORE R_CheckUserInterrupt(),
//     so the per-fold Calloc-allocated tree nodes are already released.
//   - xval.c:167:  free_tree(xtree, 1) is called BEFORE R_CheckUserInterrupt(),
//     same guarantee.
//   - predict2 (xpred.c): a heap-allocated SEXP that is UNPROTECT-ed and
//     returned after the loop.  If the throw fires before the loop completes,
//     predict2 is allocated but not returned; the .Call boundary wrapper should
//     call free_sexp(predict2) in its catch block if predict2 was allocated.
//     Accepting this minor leak on the interrupt path is consistent with the
//     fake runtime's simplified lifetime model (per the guide's analysis).
//   - xval.c is a void function called internally (not a direct .Call entry
//     point); RError propagates upward through xpred.c or rpart.c to the
//     outermost .Call boundary wrapper.
//
// The real R_CheckUserInterrupt() exits via longjmp to R's evaluation loop.
// The fake exits via throw — Invariant 1 compliance.
// No memory allocation is performed — Invariant 2 is not applicable.
// No R interpreter is required — Invariant 3 is not applicable.
// ---------------------------------------------------------------------------
inline void R_CheckUserInterrupt(void) {
    if (g_interrupt_requested.load(std::memory_order_relaxed)) {
        g_interrupt_requested.store(false, std::memory_order_relaxed);
        throw RError("UserInterrupt");
    }
}

// ---------------------------------------------------------------------------
// R_CheckStack / R_CheckStack2 — no-ops in the fake runtime.
//
// The real R_ext/Utils.h declares these alongside R_CheckUserInterrupt.
// They check whether the C call stack is close to overflowing and call
// error() if so.  In the fake runtime there is no R stack limit to enforce;
// both are safe no-ops.  Providing them here avoids link errors if rpart
// source files ever call them (none do in the current CSV set, but the
// original header declares them in the same block as R_CheckUserInterrupt).
//
// R_SIZE_T is defined in the original R_ext/Utils.h as either std::size_t
// (C++) or size_t (C).  We use std::size_t directly to avoid pulling in
// the R-defined macro.
// ---------------------------------------------------------------------------
inline void R_CheckStack(void) {}
inline void R_CheckStack2(std::size_t /*extra*/) {}

// ---------------------------------------------------------------------------
// --- Compatibility aliases (preserve original R API names) ---
//
// The original R_ext/Utils.h does NOT define any #define alias for
// R_CheckUserInterrupt, R_CheckStack, or R_CheckStack2.  Both rpart source
// files (xpred.c:291, xval.c:168) call R_CheckUserInterrupt() by its
// canonical name with no remapping.  No alias block is required.
//
// Other symbols declared in the original R_ext/Utils.h (revsort, iPsort,
// rPsort, R_isort, R_rsort, R_qsort, etc.) are not used by rpart's
// cross-validation paths and are not faked here.  They are listed in the
// original header under the alias block:
//   #define revsort    Rf_revsort
//   #define iPsort     Rf_iPsort
//   #define rPsort     Rf_rPsort
//   #define cPsort     Rf_cPsort
//   #define IndexWidth Rf_IndexWidth
//   #define StringFalse Rf_StringFalse
//   #define StringTrue  Rf_StringTrue
//   #define isBlankString Rf_isBlankString
// If any of these are needed, add them to a future Utils_extras.h.
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// --- ArenaFrame usage ---
//
// R_CheckUserInterrupt itself performs no arena allocation.  However, every
// .Call-entry wrapper whose call graph reaches R_CheckUserInterrupt must
// declare `ArenaFrame _frame;` as its first statement to ensure that all
// R_alloc / ALLOC scratch allocations made during tree building are freed
// when the wrapper exits — whether normally or via a caught RError.
//
// Representative xpred wrapper pattern:
//
//   #include "fake_arena.h"   // provides ArenaFrame
//   #include "SEXP.h"         // provides SEXP, RError, free_sexp
//   #include "R_CheckUserInterrupt.h"
//
//   extern "C" SEXP xpred_wrapper(
//           SEXP ncat2, SEXP method2, SEXP opt2,
//           SEXP parms2, SEXP xvals2, SEXP xgrp2,
//           SEXP ymat2, SEXP xmat2, SEXP wt2,
//           SEXP ny2, SEXP cost2, SEXP all2,
//           SEXP cp2, SEXP toprisk2, SEXP nresp2) {
//       ArenaFrame _frame;      // frees R_alloc/ALLOC scratch on scope exit
//       SEXP predict2 = nullptr; // track for cleanup on interrupt path
//       try {
//           return xpred(ncat2, method2, opt2, parms2, xvals2, xgrp2,
//                        ymat2, xmat2, wt2, ny2, cost2, all2,
//                        cp2, toprisk2, nresp2);
//       } catch (const RError &e) {
//           bool is_interrupt = (std::string(e.what()) == "UserInterrupt");
//           // store e.what() for Python-side exception raising
//           // free predict2 if it was allocated before the throw
//           return R_NilValue;
//       }
//   }
//
// The same pattern applies to any wrapper that calls xval() transitively
// (e.g., rpart_wrapper).  xval() is a void function; RError propagates from
// it through xpred.c or rpart.c to the outermost .Call wrapper.
// ---------------------------------------------------------------------------

#endif // FAKE_R_CHECKUSERINTERRUPT_H
