// =============================================================
// R_FINITE.h — Fake R API: R_FINITE
// Original R header: R_ext/Arith.h
// Category: B — Accessor Macro or Inline Function
// Auto-generated by generate-r-extern-fake-header agent.
// =============================================================
//
// NOTE: The original R_ext/Arith.h defines R_FINITE, R_finite,
// ISNAN, R_isnancpp, ISNA, R_IsNA, R_IsNaN, R_NaReal, R_NaN,
// R_PosInf, R_NegInf, R_NaInt, NA_REAL, NA_INTEGER, and NA_LOGICAL
// all in a single header.  The fake implementation of the entire
// Arith.h surface lives in ISNAN.h (which was generated first and
// serves as the authoritative fake_Arith replacement).
// This file exists so that any code that #includes "R_FINITE.h"
// directly also obtains the full Arith.h surface — it is a thin
// forwarding wrapper around ISNAN.h and adds no new definitions.
//
// Original R_ext/Arith.h macro for R_FINITE (Linux/glibc path):
//   #ifdef HAVE_WORKING_ISFINITE
//   # define R_FINITE(x)    isfinite(x)
//   #else
//   # define R_FINITE(x)    R_finite(x)
//   #endif
//
// The fake replaces isfinite(x) with (std::isfinite(x) ? 1 : 0) to
// avoid the unqualified-isfinite lookup ambiguity in C++ (where
// <cmath> may #undef the C99 macro form on some platforms) and to
// guarantee an explicit int 0/1 return matching R's documented
// R_finite() contract.
//
// Correctness for R's missing-value semantics:
//   R_FINITE(NA_REAL)  == 0   (NA_REAL is a quiet NaN)
//   R_FINITE(NaN)      == 0
//   R_FINITE(+Inf)     == 0
//   R_FINITE(-Inf)     == 0
//   R_FINITE(0.0)      == 1
//   R_FINITE(1.5)      == 1
// std::isfinite satisfies all five without special bit-pattern logic.
//
// Call sites covered (all Pattern P1 — finite-value guard on double):
//   branch.c:39    if (R_FINITE(xdata[j][obs]))
//   branch.c:59    if (R_FINITE(xdata[j][obs]))    /* not missing */
//   nodesplit.c:107 if (!R_FINITE(xdata[var][j]))  continue;
//   rpart.c:154    if (!R_FINITE(rp.xdata[i][k]))
//   xpred.c:153    if (!R_FINITE(rp.xdata[i][k]))
// All five sites pass a double element of a double** predictor matrix.
// No SEXP, PROTECT, allocVector, or interpreter items appear adjacent.
// =============================================================

#pragma once
#ifndef FAKE_R_FINITE_H
#define FAKE_R_FINITE_H

// --- Standard library includes ---
// (Pulled in transitively through ISNAN.h; listed here for clarity.)
#include <cmath>      // std::isfinite
#include <climits>    // INT_MIN
#include <cstdint>    // uint64_t
#include <cstring>    // std::memcpy

// --- Fake R header dependencies ---
// (from Integration Requirements in R_FINITE.md)
// R_FINITE depends only on standard library headers; the one fake
// dependency is ISNAN.h, which provides the complete fake_Arith.h
// surface (including R_FINITE itself, R_finite, ISNAN, NA_REAL, etc.).
// Including ISNAN.h here is sufficient to satisfy every call site.
#include "ISNAN.h"

// =============================================================
// Core fake implementation
// =============================================================
//
// Pattern P1: Finite-value guard on double element of double**
// Locations: branch.c:39, branch.c:59, nodesplit.c:107,
//            rpart.c:154, xpred.c:153
//
// R_FINITE and R_finite are defined in ISNAN.h (the authoritative
// fake replacement for R_ext/Arith.h).  Definitions are NOT repeated
// here to avoid ODR violations; the #ifndef guards in ISNAN.h protect
// against double-inclusion.
//
// If ISNAN.h were absent (e.g., missing from output_folder), the
// definitions below would be the fallback.  Because ISNAN.h exists
// and is included above, these are conditionally suppressed.

#ifndef FAKE_ISNAN_H
// --- Fallback: define R_finite and R_FINITE if ISNAN.h was not found ---
// WARNING: This path should never be reached in a correct build.
// If reached, it means ISNAN.h is missing from the output folder.

inline int R_finite(double x) {
    return std::isfinite(x) ? 1 : 0;
}

// R_FINITE macro — preserves exact name from R_ext/Arith.h.
// Uses std::isfinite (from <cmath>) rather than bare isfinite (from
// <math.h>) to avoid macro-vs-function ambiguity in C++ builds.
#ifdef __cplusplus
#  define R_FINITE(x)  (std::isfinite(x) ? 1 : 0)
#else
#  define R_FINITE(x)  (isfinite(x) ? 1 : 0)
#endif

#endif // !FAKE_ISNAN_H

// =============================================================
// Compatibility aliases (preserve original R API names)
// From R_ext/Arith.h — all aliases are already emitted by ISNAN.h.
// Listed here as documentation of what ISNAN.h provides on behalf
// of this item; no new #define directives are added to avoid
// redefinition warnings.
// =============================================================
//
// #define R_FINITE(x)   (std::isfinite(x) ? 1 : 0)  — in ISNAN.h
// int R_finite(double x)  { ... }                     — in ISNAN.h
// #define ISNAN(x)      R_isnancpp(x)                 — in ISNAN.h
// #define ISNA(x)       R_IsNA(x)                     — in ISNAN.h
// #define NA_REAL       R_NaReal                       — in ISNAN.h
// #define NA_INTEGER    R_NaInt                        — in ISNAN.h
// #define NA_LOGICAL    R_NaInt                        — in ISNAN.h

#endif // FAKE_R_FINITE_H
