// =============================================================
// R_forceSymbols.h — Fake R API: R_forceSymbols
// Original R header: R_ext/Rdynload.h
// Category: A — Type or Enum Constant (registration function variant)
// Auto-generated by generate-r-extern-fake-header agent.
//
// Original R API declaration (R_ext/Rdynload.h, line 86):
//   Rboolean R_forceSymbols(DllInfo *info, Rboolean value);
//
// NOTE: The original header at
//   ~/.conda/envs/r-to-python/lib/R/include/R_ext/Rdynload.h
// was inaccessible (permission denied). Signature reproduced from
// the Markdown guide (R_forceSymbols.md Section 1) and confirmed
// against the observed usage in rpart/src/init.c.
// =============================================================
#pragma once

#ifndef FAKE_R_FORCESYMBOLS_H
#define FAKE_R_FORCESYMBOLS_H

// --- Standard library includes ---
#include <stddef.h>   // NULL

// --- Fake R header dependencies ---
// (from Integration Requirements in R_forceSymbols.md)
//
// DllInfo.h provides (transitively via DL_FUNC.h):
//   - DllInfo typedef (C-compatible two-step form: typedef struct DllInfo_fake DllInfo)
//   - Rboolean enum (FALSE = 0, TRUE = 1) under FAKE_RBOOLEAN_DEFINED guard
//   - DL_FUNC typedef
//   - R_CMethodDef / R_FortranMethodDef / R_CallMethodDef / R_ExternalMethodDef
//   - R_registerRoutines() no-op inline
//   - R_useDynamicSymbols() no-op inline
//   - R_forceSymbols() no-op inline  <-- the primary stub for this item
//   - R_getDllInfo() / R_getEmbeddingDllInfo() stubs
//   - R_RegisterCCallable() / R_GetCCallable() stubs
//
// Rboolean.h is also included directly to ensure FAKE_RBOOLEAN_DEFINED
// is set regardless of include order; both DL_FUNC.h and Rboolean.h
// guard their Rboolean typedef with matching #ifndef guards so there
// is no double-definition.
//
// R_VERSION.h provides R_Version(v, p, s) and R_VERSION so that the
// preprocessor gate at init.c:27 evaluates correctly:
//   #if defined(R_VERSION) && R_VERSION >= R_Version(2, 16, 0)
// With R_VERSION = R_Version(4, 4, 0) = 263168 >= R_Version(2, 16, 0) = 131584,
// the condition is TRUE and the R_forceSymbols call site is compiled in.
// The stub must therefore be present to avoid an undefined-reference link error.
#include "DllInfo.h"
#include "Rboolean.h"
#include "R_VERSION.h"

// --- Core fake implementation ---
//
// Pattern: No-op Library Registration Call Gated by Version Preprocessor Guard
// Location: init.c:28 — `R_forceSymbols(dll, TRUE);`
//            inside `#if defined(R_VERSION) && R_VERSION >= R_Version(2, 16, 0)`
//
// Call site arguments:
//   First argument  : dll          — DllInfo * (opaque handle from R_init_rpart parameter)
//   Second argument : TRUE         — Rboolean enumerator (value = 1)
//   Return value    : discarded    — Rboolean (previous enforcement state)
//
// Purpose in real R: when value == TRUE, instructs R's dynamic loader to
//   reject ad-hoc name-based .Call("symbol") lookups and require callers to
//   use the pre-registered table set up by R_registerRoutines.
//
// In the standalone fake build: R's dynamic loader is absent; R_init_rpart
//   is never invoked by a loader; the function has nothing to configure.
//   The stub accepts both arguments, discards them, and returns FALSE
//   (representing "symbol forcing was previously not active"), which is the
//   plausible first-call return value of the real function and is safe
//   because the return value is discarded at init.c:28.
//
// Preprocessor gate interaction:
//   R_forceSymbols is compiled into init.c only when the gate is true.
//   R_VERSION.h (included above) defines R_Version(4, 4, 0) = 263168.
//   263168 >= R_Version(2, 16, 0) = 131584 -> TRUE.
//   The stub must therefore be present; without it the compiler would
//   produce an undefined reference at the link step.
//
// Implementation note:
//   The no-op inline stub for R_forceSymbols is already emitted by DL_FUNC.h
//   (included above via DllInfo.h) at line 153 of that header.  This header
//   provides it additionally under a conflict-safe #ifndef guard
//   (FAKE_R_FORCESYMBOLS_DEFINED) for translation units that include
//   R_forceSymbols.h directly without going through DL_FUNC.h, and to
//   document the rationale as the canonical guide entry for this item.
//   The #ifndef guard prevents a duplicate-definition error when both
//   DL_FUNC.h and this header are included in the same translation unit.
//
// Invariants:
//   - Invariant 1 (C++ exception-based errors): not triggered.
//     R_forceSymbols does not call Rf_error, Rf_warning, or any error mechanism.
//   - Invariant 2 (arena memory): not triggered.
//     R_forceSymbols neither allocates nor frees any memory.
//   - Invariant 3 (R Interpreter Items): not triggered.
//     R_forceSymbols is a loader-configuration function with no interpreter
//     interaction; no Python callback registration is required.
#ifndef FAKE_R_FORCESYMBOLS_DEFINED
#define FAKE_R_FORCESYMBOLS_DEFINED

// R_forceSymbols — primary subject of this guide.
//
// Signature matches the authoritative R_ext/Rdynload.h line 86 declaration:
//   Rboolean R_forceSymbols(DllInfo *info, Rboolean value);
//
// The static inline qualifier:
//   - Prevents multiple-definition errors when this header is included by
//     more than one translation unit in the same build.
//   - Allows the compiler to fold the no-op body entirely (zero code emitted),
//     eliminating any runtime overhead.
//
// The (void) casts suppress -Wall -Wextra unused-parameter warnings without
// modifying init.c in any way.
//
// Returns FALSE: the plausible prior-state value ("symbol forcing was not
// previously active").  The return value is discarded at init.c:28.
static inline Rboolean R_forceSymbols(DllInfo *info, Rboolean value)
{
    (void)info;   // DllInfo * — opaque, never dereferenced in standalone build
    (void)value;  // TRUE received here; has no effect in fake build
    return FALSE;
}

#endif /* FAKE_R_FORCESYMBOLS_DEFINED */

// --- Compatibility aliases (preserve original R API names) ---
//
// R_ext/Rdynload.h defines no preprocessor aliases for R_forceSymbols.
// The function name is used directly at every call site in the package source
// (init.c:28: `R_forceSymbols(dll, TRUE);`).  No #define remapping macros
// are needed or present in the original R header for this item.
//
// All other aliases needed by init.c are provided by DL_FUNC.h (via DllInfo.h):
//   - FALSE / TRUE  : Rboolean enum enumerators (not preprocessor macros)
//   - R_registerRoutines, R_useDynamicSymbols : companion registration no-ops
//   - DL_FUNC, R_CallMethodDef : types used in CallEntries[] table

// --- Usage note for callers ---
//
// To compile init.c without libR.so, the shadow include tree must resolve:
//
//   #include "R_ext/Rdynload.h"  ->  fake_R.h (or direct) which includes
//                                    DllInfo.h -> DL_FUNC.h
//                                    (R_forceSymbols stub already present there)
//
//   #include <Rversion.h>        ->  R_VERSION.h or R_CallMethodDef.h
//                                    (R_VERSION and R_Version macros)
//
// If this header (R_forceSymbols.h) is included directly instead of going
// through DL_FUNC.h, it is self-contained: DllInfo.h, Rboolean.h, and
// R_VERSION.h are all pulled in above, and the stub below is present under
// FAKE_R_FORCESYMBOLS_DEFINED.  If DL_FUNC.h was already included first
// (the common case via fake_R.h), both FAKE_R_FORCESYMBOLS_DEFINED and the
// stub in DL_FUNC.h are active; the #ifndef guard here prevents any conflict.

#endif /* FAKE_R_FORCESYMBOLS_H */
