// =============================================================
// R_getVar.h — Fake R API: R_getVar
// Original R header: Rinternals.h
// Category: E — R Interpreter Item (environment variable lookup)
// Auto-generated by generate-r-extern-fake-header agent.
// =============================================================
//
// R_getVar(SEXP symbol, SEXP rho, Rboolean inherits) looks up a variable
// named 'symbol' in the R environment 'rho'.  When inherits=TRUE it walks
// the parent chain (findVar); when inherits=FALSE it searches only the
// immediate frame (findVarInFrame).
//
// Original declaration in Rinternals.h (line 537):
//   SEXP R_getVar(SEXP, SEXP, Rboolean);   // envir.c   (R >= 4.5.0 only)
//
// CRITICAL DESIGN NOTE — R_getVar is a SOURCE-LEVEL MACRO under R < 4.5.0.
//
// rpart_callback.c lines 18-28 define:
//
//   #if R_VERSION < R_Version(4, 5, 0)
//   static SEXP compat_getVar(SEXP sym, SEXP rho, Rboolean inherits)
//   {
//     SEXP val = inherits ? findVar(sym, rho) : findVarInFrame(rho, sym);
//     if (val == R_UnboundValue)
//       error(_("variable '%s' not found"), CHAR(PRINTNAME(sym)));
//     return val;
//   }
//   #define R_getVar(sym, rho, inherits) compat_getVar(sym, rho, inherits)
//   #endif
//
// R_VERSION.h (already in output_folder) forces R_VERSION = R_Version(4,4,0),
// which satisfies R_VERSION < R_Version(4,5,0) = TRUE.  Therefore:
//   - compat_getVar is compiled as a static C function inside rpart_callback.c.
//   - The macro #define R_getVar(...) compat_getVar(...) is active.
//   - No library symbol 'R_getVar' is ever referenced by the linker.
//   - This header does NOT need to define R_getVar as a C function.
//
// What this header DOES provide:
//   1. install(const char *) — Category E stub; produces the 'sym' SEXP
//      argument passed to compat_getVar at all four call sites (lines 59-68).
//   2. findVar(SEXP, SEXP) — Category E stub; the inherits=TRUE branch inside
//      compat_getVar; never reached by rpart (inherits=FALSE everywhere), but
//      must compile and link.
//   3. findVarInFrame(SEXP, SEXP) — Category E stub; the inherits=FALSE branch;
//      called at all four rpart R_getVar call sites.
//   4. An optional R_getVar function pointer stub for a hypothetical future
//      R >= 4.5.0 build path (NOT used by current rpart code; guarded by
//      #if R_VERSION >= R_Version(4, 5, 0) so it is compiled out by default).
//
// Call chain for R_getVar(install("yback"), rho, FALSE) at rpart_callback.c:59:
//
//   R_getVar("yback", rho, FALSE)         [macro -> compat_getVar, rpart_callback.c:27]
//     -> install("yback")                 [evaluated first; Category E, g_install_fn]
//     -> compat_getVar(sym, rho, FALSE)   [static C function, rpart_callback.c:20]
//          -> findVarInFrame(rho, sym)    [Category E stub, g_findVarInFrame_fn]
//          -> if (val == R_UnboundValue)  [pointer equality; throws RError if true]
//          -> return val                  [SEXP for "yback" / "wback" / "xback" / "nback"]
//
// All four call sites in init_rpcallback are structurally identical; only the
// variable name and downstream accessor (REAL vs. INTEGER) differ.
//
// Source file context (rpart_callback.c:47-72):
//   SEXP init_rpcallback(SEXP rhox, SEXP ny, SEXP nr, SEXP expr1x, SEXP expr2x)
//   {
//       SEXP stemp;
//       rho = rhox; ysave = asInteger(ny); rsave = asInteger(nr);
//       expr1 = expr1x; expr2 = expr2x;
//       stemp = R_getVar(install("yback"), rho, FALSE);  ydata = REAL(stemp);
//       stemp = R_getVar(install("wback"), rho, FALSE);  wdata = REAL(stemp);
//       stemp = R_getVar(install("xback"), rho, FALSE);  xdata = REAL(stemp);
//       stemp = R_getVar(install("nback"), rho, FALSE);  ndata = INTEGER(stemp);
//       return R_NilValue;
//   }
//
// Invariant applicability:
//   Invariant 1 (C++ exception errors): triggered by error(...) inside
//     compat_getVar (rpart_callback.c:24) when val == R_UnboundValue.
//     error() expands to Rf_error() which throws RError (provided by SEXP.h
//     transitively through R_NilValue.h).
//   Invariant 2 (arena memory): not directly triggered by R_getVar /
//     compat_getVar.  An ArenaFrame guard is required at the .Call boundary
//     wrapper for init_rpcallback as a standard precaution.
//   Invariant 3 (R Interpreter Items): fully applicable.  install(),
//     findVarInFrame(), and findVar() all require Python-registered function
//     pointer bridges before init_rpcallback() can be called.
//
// Integration Requirements (from R_getVar.md Section 5):
//   SEXP.h         — SEXPREC struct, SEXP typedef, SYMSXP/NILSXP constants,
//                    TYPEOF, CHAR, PRINTNAME, R_NilValue, R_UnboundValue,
//                    R_NamesSymbol, isReal, isInteger, asInteger, mkChar,
//                    VECTOR_ELT, SET_VECTOR_ELT, free_sexp_deep.
//                    Also pulls in INTSXP.h (allocVector, INTEGER, REAL,
//                    PROTECT/UNPROTECT, LENGTH, RError) and Rboolean.h
//                    (Rboolean, FALSE, TRUE).
//   R_NilValue.h   — Rf_error/Rf_warning/#define error Rf_error; RError.
//   R_UnboundValue.h — R_UnboundValue sentinel, get_R_UnboundValue().
//   R_VERSION.h    — R_VERSION = R_Version(4,4,0), R_Version macro; forces
//                    R_VERSION < R_Version(4,5,0) = TRUE so compat_getVar
//                    and the R_getVar macro in rpart_callback.c are compiled.
//   Rboolean.h     — Rboolean, FALSE=0, TRUE=1; used as third argument type
//                    of compat_getVar and in the ternary inside it.
// =============================================================
#pragma once

#ifndef FAKE_R_GETVAR_H
#define FAKE_R_GETVAR_H

// --- Standard library includes ---
#include <stddef.h>    // NULL, size_t
#include <stdlib.h>    // malloc, free
#include <string.h>    // strlen, strcpy
#include <stdexcept>   // std::runtime_error (via RError)
#include <string>      // std::string (via RError)

// --- Fake R header dependencies ---
// (from Integration Requirements in R_getVar.md, Section 5)
//
// SEXP.h provides (pulling in INTSXP.h and Rboolean.h transitively):
//   RError, SEXPREC struct, SEXP typedef, SEXPTYPE constants
//   (SYMSXP=1, NILSXP=0, CHARSXP=9, REALSXP=14, INTSXP=13, ...),
//   allocVector, allocMatrix, INTEGER, REAL, LOGICAL, RAW,
//   LENGTH, nrows, ncols, PROTECT, UNPROTECT,
//   TYPEOF, CHAR, R_CHAR, mkChar, PRINTNAME,
//   VECTOR_ELT, SET_VECTOR_ELT, STRING_ELT, SET_STRING_ELT,
//   isReal, isInteger, isNull, asInteger, asReal,
//   setAttrib, getAttrib, R_ProtectWithIndex, R_Reprotect,
//   R_NilValue, R_UnboundValue, R_NamesSymbol, free_sexp_deep.
//   Also Rboolean (FALSE=0, TRUE=1) from Rboolean.h.
#include "SEXP.h"

// R_NilValue.h provides:
//   Rf_error (throws RError), Rf_warning, Rf_errorcall,
//   #define error Rf_error, #define warning Rf_warning,
//   error_return / errorcall_return compatibility macros.
// Required because compat_getVar in rpart_callback.c:24 calls
//   error(_("variable '%s' not found"), CHAR(PRINTNAME(sym)));
// which expands to Rf_error(...) and throws RError (Invariant 1).
#include "R_NilValue.h"

// R_UnboundValue.h provides:
//   make_unbound_value(), static SEXP R_UnboundValue (SYMSXP sentinel),
//   get_R_UnboundValue() C-linkage accessor for Python ctypes interop.
// Required because compat_getVar compares the findVarInFrame return value
// against R_UnboundValue (rpart_callback.c:23).
#include "R_UnboundValue.h"

// R_VERSION.h provides:
//   #define R_Version(v,p,s) (((v)*65536)+((p)*256)+(s))
//   #define R_VERSION  R_Version(4,4,0)   /* 263168 */
// Required because rpart_callback.c:19 gates compat_getVar on:
//   #if R_VERSION < R_Version(4, 5, 0)
// Without this header the compat_getVar shim and the R_getVar macro are
// suppressed, leaving all four call sites as unresolved identifiers.
#include "R_VERSION.h"

// Rboolean.h provides:
//   typedef enum { FALSE = 0, TRUE = 1 } Rboolean;
//   (also #undef FALSE before the enum to avoid conflicts)
// Required because compat_getVar takes 'Rboolean inherits' as its third
// parameter, and all four call sites pass 'FALSE' as the inherits argument.
// (Rboolean.h is pulled in transitively by SEXP.h -> INTSXP.h, but is
// listed here explicitly to document the dependency.)
#include "Rboolean.h"

// WARNING: dependency fake_arena.h not found in output_folder.
// fake_arena.h (ArenaFrame, arena_alloc, arena_calloc) is not present
// in the output folder at the time this header was generated.
// The .Call boundary wrapper for init_rpcallback (see ArenaFrame usage
// section below) requires ArenaFrame _frame for Invariant 2.
// Once fake_arena.h is available, add:
//   #include "fake_arena.h"
// to the wrapper source file and declare `ArenaFrame _frame;` as the
// first statement of any .Call-entry function that calls arena-backed
// functions from any fake header.
//
// #include "fake_arena.h"

// NOTE: install.md, findVar.md, findVarInFrame.md are listed in the
// guide's Integration Requirements as "not yet generated — Category E".
// Since those headers do not yet exist in the output_folder, this
// header provides the authoritative stub definitions for all three
// items, guarded by #ifndef so they can be consolidated later without
// conflicts.

// =============================================================
// *** R INTERPRETER ITEM — install ***
// A complete fake is impossible without an R interpreter.
// Register a Python callback via register_install_fn() before
// calling init_rpcallback() with method=4 (user-defined splits).
// Affected code paths: rpart_callback.c:59, 62, 65, 68
//   (install("yback"), install("wback"), install("xback"), install("nback"))
// =============================================================

// WARNING: dependency install.h not found in output_folder.
// Providing authoritative stub definition here under FAKE_INSTALL_FN_DEFINED.

#ifndef FAKE_INSTALL_FN_DEFINED
#define FAKE_INSTALL_FN_DEFINED

// install(const char *name) interns a C string as a symbol SEXP (SYMSXP).
// In the real R runtime it looks up or creates an entry in R's global symbol
// table (a hash table of SYMSXP nodes, each with a print name CHARSXP).
//
// In the fake build, install() is a Python-registered function pointer.
// Python maintains a string->SEXP dict so each name always maps to the same
// stable pointer address.  The returned SEXP is a fake SEXPREC of type SYMSXP
// with its data field pointing to a CHARSXP node holding the name string.
// This layout satisfies PRINTNAME(sym) at rpart_callback.c:24 (error path).
//
// Function pointer type:
//   SEXP install_fn_t(const char *name)
typedef SEXP (*install_fn_t)(const char *name);
inline install_fn_t g_install_fn = nullptr;

// register_install_fn — called once from Python before init_rpcallback().
extern "C" inline void register_install_fn(install_fn_t fn) {
    g_install_fn = fn;
}

// install — the fake stub.
// If g_install_fn is null, throws RError explaining what registration is
// needed.  This path is only reached if the caller invokes init_rpcallback()
// (method=4) without registering the callback first.
inline SEXP Rf_install(const char *name) {
    if (!g_install_fn)
        throw RError("install: Python callback not registered. "
                     "init_rpcallback() and user-defined splits (method=4) "
                     "require registration via register_install_fn() before "
                     "any R_getVar call.");
    return g_install_fn(name);
}

// Short-form alias matching Rinternals.h line 956:
//   #define install Rf_install
// Provided as an inline function (not a macro) to avoid double-expansion
// and to preserve type checking.
inline SEXP install(const char *name) { return Rf_install(name); }

// Rf_installChar — provided for completeness (not called by rpart).
// Extracts the char* from a CHARSXP and delegates to Rf_install.
inline SEXP Rf_installChar(SEXP charsxp) {
    return Rf_install(R_CHAR(charsxp));
}

// Rf_installNoTrChar / Rf_installTrChar — thin wrappers (not called by rpart).
inline SEXP Rf_installNoTrChar(SEXP charsxp) { return Rf_installChar(charsxp); }
inline SEXP Rf_installTrChar(SEXP charsxp)   { return Rf_installChar(charsxp); }

// Preserve Rinternals.h alias block (lines 957-960):
//   #define installChar       Rf_installTrChar
//   #define installNoTrChar   Rf_installNoTrChar
//   #define installTrChar     Rf_installTrChar
// Provided as inline functions rather than macros (see note above).
inline SEXP installChar(SEXP c)       { return Rf_installTrChar(c); }
inline SEXP installNoTrChar(SEXP c)   { return Rf_installNoTrChar(c); }
inline SEXP installTrChar(SEXP c)     { return Rf_installTrChar(c); }

#endif // FAKE_INSTALL_FN_DEFINED

// =============================================================
// *** R INTERPRETER ITEM — findVar ***
// A complete fake is impossible without an R interpreter.
// Register a Python callback via register_findVar_fn() before
// calling init_rpcallback() with method=4.
// Affected code paths: rpart_callback.c:22 (inherits=TRUE branch of
//   compat_getVar — never reached by rpart call sites where inherits
//   is always FALSE, but must compile and link without error).
// =============================================================

// WARNING: dependency findVar.h not found in output_folder.
// Providing authoritative stub definition here under FAKE_FINDVAR_FN_DEFINED.

#ifndef FAKE_FINDVAR_FN_DEFINED
#define FAKE_FINDVAR_FN_DEFINED

// findVar(SEXP sym, SEXP rho) searches rho and its entire parent-chain
// environment for the variable named by sym.  Returns R_UnboundValue if not
// found.  In R's C API declared as:
//   SEXP Rf_findVar(SEXP, SEXP);   (Rinternals.h line 533)
//   #define findVar Rf_findVar      (Rinternals.h line 939)
//
// The inherits=TRUE branch of compat_getVar calls findVar(sym, rho).
// Since all four rpart R_getVar call sites pass inherits=FALSE, this branch
// is dead code for the current rpart build.  The stub must still be present
// so that the compiler can resolve the symbol in compat_getVar's body and
// the linker can produce a complete shared library.
typedef SEXP (*findVar_fn_t)(SEXP sym, SEXP rho);
inline findVar_fn_t g_findVar_fn = nullptr;

// register_findVar_fn — called from Python to install the callback.
extern "C" inline void register_findVar_fn(findVar_fn_t fn) {
    g_findVar_fn = fn;
}

// Rf_findVar — the fake stub.
// Delegates to the registered Python callback; returns R_UnboundValue if the
// callback is null (conservative: treats every lookup as "not found").
inline SEXP Rf_findVar(SEXP sym, SEXP rho) {
    if (!g_findVar_fn) {
        // Conservative fallback: inherits=TRUE path is never reached by rpart.
        // Return R_UnboundValue so that compat_getVar throws RError if it is
        // somehow reached; this surfaces as a Python-readable error rather than
        // a segfault.
        return R_UnboundValue;
    }
    return g_findVar_fn(sym, rho);
}

// Short-form alias matching Rinternals.h line 939:
//   #define findVar Rf_findVar
// Provided as an inline function to avoid macro / inline conflicts.
inline SEXP findVar(SEXP sym, SEXP rho) { return Rf_findVar(sym, rho); }

#endif // FAKE_FINDVAR_FN_DEFINED

// =============================================================
// *** R INTERPRETER ITEM — findVarInFrame ***
// A complete fake is impossible without an R interpreter.
// Register a Python callback via register_findVarInFrame_fn() before
// calling init_rpcallback() with method=4.
// Affected code paths: rpart_callback.c:22 (inherits=FALSE branch of
//   compat_getVar — reached at ALL FOUR R_getVar call sites in
//   init_rpcallback: lines 59, 62, 65, 68).
// =============================================================

// WARNING: dependency findVarInFrame.h not found in output_folder.
// Providing authoritative stub definition here under
// FAKE_FINDVARINFRAME_FN_DEFINED.

#ifndef FAKE_FINDVARINFRAME_FN_DEFINED
#define FAKE_FINDVARINFRAME_FN_DEFINED

// findVarInFrame(SEXP rho, SEXP sym) searches only the immediate frame of rho
// (no parent walk).  Returns R_UnboundValue if sym is not bound in rho.
// In R's C API declared as:
//   SEXP Rf_findVarInFrame(SEXP, SEXP);   (Rinternals.h line 534)
//   #define findVarInFrame Rf_findVarInFrame  (Rinternals.h line 940)
//
// This is the CRITICAL stub for the rpart fake build: all four R_getVar calls
// in init_rpcallback pass inherits=FALSE, so compat_getVar always calls
// findVarInFrame(rho, sym).  Python must register a callback that:
//   - Accepts (rho_ptr: int, sym_ptr: int)
//   - Returns the SEXP pointer bound to sym in the rho frame, or
//     get_R_UnboundValue() if the symbol is not present.
//
// The return values for the four variables expected by rpart:
//   "yback"  -> REALSXP SEXP (double *); accessed via REAL(stemp)   line 60
//   "wback"  -> REALSXP SEXP (double *); accessed via REAL(stemp)   line 63
//   "xback"  -> REALSXP SEXP (double *); accessed via REAL(stemp)   line 66
//   "nback"  -> INTSXP  SEXP (int *);   accessed via INTEGER(stemp) line 69
typedef SEXP (*findVarInFrame_fn_t)(SEXP rho, SEXP sym);
inline findVarInFrame_fn_t g_findVarInFrame_fn = nullptr;

// register_findVarInFrame_fn — called from Python before init_rpcallback().
extern "C" inline void register_findVarInFrame_fn(findVarInFrame_fn_t fn) {
    g_findVarInFrame_fn = fn;
}

// Rf_findVarInFrame — the fake stub.
// Delegates to the Python callback; throws RError if callback is null.
// Throwing is appropriate here because findVarInFrame is on the critical
// path of every R_getVar call in init_rpcallback.
inline SEXP Rf_findVarInFrame(SEXP rho, SEXP sym) {
    if (!g_findVarInFrame_fn)
        throw RError("findVarInFrame: Python callback not registered. "
                     "init_rpcallback() requires registration via "
                     "register_findVarInFrame_fn() before R_getVar calls at "
                     "rpart_callback.c lines 59, 62, 65, 68.");
    return g_findVarInFrame_fn(rho, sym);
}

// Short-form alias matching Rinternals.h line 940:
//   #define findVarInFrame Rf_findVarInFrame
// Provided as an inline function to avoid macro / inline conflicts.
inline SEXP findVarInFrame(SEXP rho, SEXP sym) {
    return Rf_findVarInFrame(rho, sym);
}

// Rf_findVarInFrame3 — three-argument form (Rinternals.h line 535).
// Not called by rpart; provided for compilation completeness.
// The third argument (Rboolean) mirrors the inherits flag.
inline SEXP Rf_findVarInFrame3(SEXP rho, SEXP sym, Rboolean inherits) {
    if (inherits) return Rf_findVar(sym, rho);
    return Rf_findVarInFrame(rho, sym);
}

// #define findVarInFrame3 Rf_findVarInFrame3   (Rinternals.h line 941)
inline SEXP findVarInFrame3(SEXP rho, SEXP sym, Rboolean inherits) {
    return Rf_findVarInFrame3(rho, sym, inherits);
}

#endif // FAKE_FINDVARINFRAME_FN_DEFINED

// =============================================================
// *** R INTERPRETER ITEM — R_getVar (optional stub for R >= 4.5.0) ***
//
// Under the fake build, R_VERSION = R_Version(4,4,0) < R_Version(4,5,0),
// so rpart_callback.c defines R_getVar as a macro expanding to compat_getVar.
// The function pointer stub below is COMPILED OUT by the #if guard and is
// NEVER CALLED by the current rpart code.
//
// It is provided here to:
//   (a) document the R >= 4.5.0 semantics precisely,
//   (b) enable a future build that sets R_VERSION >= R_Version(4,5,0)
//       without modifying any rpart source file.
//
// If such a future build is needed, remove the #if guard in R_VERSION.h
// (or change R_VERSION to R_Version(4,5,0) or higher) and the block below
// will automatically compile in, providing the required library symbol.
// =============================================================

#if R_VERSION >= R_Version(4, 5, 0)

#ifndef FAKE_R_GETVAR_FN_DEFINED
#define FAKE_R_GETVAR_FN_DEFINED

// R_getVar(SEXP sym, SEXP rho, Rboolean inherits)
// In R >= 4.5.0 this is a real library function (envir.c).
// The fake implementation mirrors compat_getVar from rpart_callback.c exactly:
//   if (inherits) use findVar; else use findVarInFrame.
//   if result == R_UnboundValue, throw RError (Invariant 1).
typedef SEXP (*R_getVar_fn_t)(SEXP sym, SEXP rho, Rboolean inherits);
static R_getVar_fn_t g_R_getVar_fn = nullptr;

// register_R_getVar_fn — optional; if null, the inline below uses the
// findVar / findVarInFrame stubs directly, which is equivalent.
extern "C" inline void register_R_getVar_fn(R_getVar_fn_t fn) {
    g_R_getVar_fn = fn;
}

inline SEXP R_getVar(SEXP sym, SEXP rho, Rboolean inherits) {
    if (g_R_getVar_fn)
        return g_R_getVar_fn(sym, rho, inherits);
    // Fall back to the component stubs (mirrors compat_getVar semantics).
    SEXP val = inherits ? Rf_findVar(sym, rho) : Rf_findVarInFrame(rho, sym);
    if (val == R_UnboundValue)
        throw RError("R_getVar: variable not found in environment");
    return val;
}

#endif // FAKE_R_GETVAR_FN_DEFINED

#endif // R_VERSION >= R_Version(4, 5, 0)

// --- Compatibility aliases (preserve original R API names) ---
//
// The fake header provides inline functions rather than #define macros for
// all short-form aliases.  This avoids macro expansion problems when the same
// name appears as both an argument and a function name in complex call sites.
//
// The following aliases from the original Rinternals.h are preserved above
// as inline wrappers:
//
//   Rinternals.h line 939:  #define findVar          Rf_findVar
//   Rinternals.h line 940:  #define findVarInFrame   Rf_findVarInFrame
//   Rinternals.h line 941:  #define findVarInFrame3  Rf_findVarInFrame3
//   Rinternals.h line 956:  #define install          Rf_install
//   Rinternals.h line 957:  #define installChar      Rf_installTrChar
//   Rinternals.h line 958:  #define installNoTrChar  Rf_installNoTrChar
//   Rinternals.h line 959:  #define installTrChar    Rf_installTrChar
//
// The macro #define R_getVar(sym, rho, inherits) compat_getVar(sym, rho, inherits)
// is defined in rpart_callback.c line 27 (not in any R header) and does NOT
// need to be reproduced in this fake header.  It is active automatically
// because R_VERSION < R_Version(4,5,0) (enforced by R_VERSION.h).
//
// The #define error Rf_error alias that makes rpart_callback.c:24 compile is
// provided by R_NilValue.h (included above transitively via SEXP.h).

// --- Python-side usage note (Category E) ---
//
// The ctypes registration snippet below is the authoritative guide for
// integrating R_getVar / compat_getVar with Python.  It covers all five
// steps: install stub registration, findVarInFrame stub registration,
// findVar stub registration, frame-registry population, and the
// init_rpcallback_wrapper call.
//
// NOTE: init_rpcallback() is only needed for method=4 (user-defined splits).
// Standard rpart() calls (anova, poisson, class, exp) never invoke it.
// For standard use, none of these stubs need to be registered.
//
/*
import ctypes
import numpy as np

# Load the shared library built from the fake-header rpart source.
lib = ctypes.CDLL("./librpart_fake.so")

# SEXP is an opaque pointer in Python.
SEXP = ctypes.c_void_p

# ----------------------------------------------------------------
# Step 1: Retrieve the R_UnboundValue sentinel pointer.
#
# get_R_UnboundValue() is a C-linkage accessor defined in R_UnboundValue.h.
# Python must obtain this address BEFORE registering any callbacks so that
# py_findVarInFrame can return the correct sentinel on lookup failure.
# ----------------------------------------------------------------
lib.get_R_UnboundValue.restype  = SEXP
lib.get_R_UnboundValue.argtypes = []
R_UNBOUND = lib.get_R_UnboundValue()    # integer address of unbound_rec

# ----------------------------------------------------------------
# Step 2: Register the install() stub.
#
# install(name) interns a C string as a symbol SEXP (SYMSXP).
# Python maintains a string->c_void_p dict so each name always maps
# to the same stable pointer address.
# ----------------------------------------------------------------
_symbol_handles: dict = {}    # {name_str: c_void_p integer address}
_symbol_nodes:   dict = {}    # keep SEXP nodes alive (prevent GC)

InstallFnType = ctypes.CFUNCTYPE(SEXP, ctypes.c_char_p)

def py_install(name_bytes: bytes) -> int:
    name = name_bytes.decode()
    if name not in _symbol_handles:
        # Allocate a 1-byte placeholder as a stable identity for the symbol.
        node = (ctypes.c_char * 1)()
        _symbol_handles[name] = ctypes.cast(node, ctypes.c_void_p).value
        _symbol_nodes[name] = node          # keep alive
    return _symbol_handles[name]

_install_cb = InstallFnType(py_install)

lib.register_install_fn.restype  = None
lib.register_install_fn.argtypes = [InstallFnType]
lib.register_install_fn(_install_cb)

# ----------------------------------------------------------------
# Step 3: Register the findVarInFrame() stub.
#
# findVarInFrame(rho, sym) looks up sym in the frame identified by rho.
# Python maintains a nested registry:
#   _frame_registry[rho_ptr][sym_ptr] = sexp_value_ptr
#
# Before calling init_rpcallback_wrapper, Python populates
# _frame_registry with the four "back" variable SEXPs.
# ----------------------------------------------------------------
_frame_registry: dict = {}    # {rho_ptr: {sym_ptr: val_ptr}}

FindVarInFrameFnType = ctypes.CFUNCTYPE(SEXP, SEXP, SEXP)

def py_findVarInFrame(rho: int, sym: int) -> int:
    """
    Look up sym in the frame keyed by rho.
    Return the registered value SEXP, or R_UnboundValue on failure.
    Returning R_UNBOUND causes compat_getVar to call error(), which
    throws RError and surfaces as a Python RuntimeError.
    """
    frame = _frame_registry.get(rho, {})
    val = frame.get(sym)
    if val is None:
        return R_UNBOUND
    return val

_findVarInFrame_cb = FindVarInFrameFnType(py_findVarInFrame)

lib.register_findVarInFrame_fn.restype  = None
lib.register_findVarInFrame_fn.argtypes = [FindVarInFrameFnType]
lib.register_findVarInFrame_fn(_findVarInFrame_cb)

# ----------------------------------------------------------------
# Step 4: Register the findVar() stub (inherits=TRUE branch).
# Not reached by rpart call sites (inherits=FALSE everywhere),
# but must be registered so the stub does not crash if called.
# Conservative: always returns R_UnboundValue ("not found").
# ----------------------------------------------------------------
FindVarFnType = ctypes.CFUNCTYPE(SEXP, SEXP, SEXP)

def py_findVar(sym: int, rho: int) -> int:
    # Conservative fallback — inherits=TRUE is dead code for rpart.
    return R_UNBOUND

_findVar_cb = FindVarFnType(py_findVar)

lib.register_findVar_fn.restype  = None
lib.register_findVar_fn.argtypes = [FindVarFnType]
lib.register_findVar_fn(_findVar_cb)

# ----------------------------------------------------------------
# Step 5: Build fake SEXPs for the four "back" arrays and populate
# the frame registry.
#
# The four arrays expected by init_rpcallback:
#   yback: float64 array of shape (n_obs * n_resp,)  -> REALSXP
#   wback: float64 array of shape (n_obs,)            -> REALSXP
#   xback: float64 array of shape (n_obs * n_x_cols,) -> REALSXP
#   nback: int32   array of shape (1,)               -> INTSXP
# ----------------------------------------------------------------
n_obs    = 100
n_resp   = 1
n_x_cols = 10

yback_arr = np.zeros(n_obs * n_resp, dtype=np.float64)
wback_arr = np.ones(n_obs,           dtype=np.float64)
xback_arr = np.zeros(n_obs * n_x_cols, dtype=np.float64)
nback_arr = np.array([n_resp],       dtype=np.int32)

# make_real_sexp / make_int_sexp: build a fake SEXPREC pointing into
# a numpy buffer.  These helpers are assumed to be exported by the
# fake header build infrastructure (e.g., via a utility source file).
lib.make_real_sexp.restype  = SEXP
lib.make_real_sexp.argtypes = [ctypes.c_void_p, ctypes.c_int]
lib.make_int_sexp.restype   = SEXP
lib.make_int_sexp.argtypes  = [ctypes.c_void_p, ctypes.c_int]

sexp_y = lib.make_real_sexp(
    yback_arr.ctypes.data_as(ctypes.c_void_p), yback_arr.size)
sexp_w = lib.make_real_sexp(
    wback_arr.ctypes.data_as(ctypes.c_void_p), wback_arr.size)
sexp_x = lib.make_real_sexp(
    xback_arr.ctypes.data_as(ctypes.c_void_p), xback_arr.size)
sexp_n = lib.make_int_sexp(
    nback_arr.ctypes.data_as(ctypes.c_void_p), nback_arr.size)

# Create an environment SEXP (opaque handle serving as the dict key).
lib.make_env_sexp.restype  = SEXP
lib.make_env_sexp.argtypes = []
rho_handle = lib.make_env_sexp()

# Populate the frame registry for rho_handle.
_frame_registry[rho_handle] = {
    py_install(b"yback"): sexp_y,
    py_install(b"wback"): sexp_w,
    py_install(b"xback"): sexp_x,
    py_install(b"nback"): sexp_n,
}

# ----------------------------------------------------------------
# Step 6: Call init_rpcallback_wrapper.
#
# ny and nr are scalar INTSXP SEXPs wrapping 1-element int32 arrays.
# expr1 and expr2 are R language object SEXPs; pass None (nullptr) if
# the eval() stub is not registered (standard methods only).
# ----------------------------------------------------------------
lib.init_rpcallback_wrapper.restype  = SEXP
lib.init_rpcallback_wrapper.argtypes = [SEXP, SEXP, SEXP, SEXP, SEXP]

ny_arr = np.array([n_resp], dtype=np.int32)
nr_arr = np.array([n_resp], dtype=np.int32)
sexp_ny = lib.make_int_sexp(ny_arr.ctypes.data_as(ctypes.c_void_p), 1)
sexp_nr = lib.make_int_sexp(nr_arr.ctypes.data_as(ctypes.c_void_p), 1)

result = lib.init_rpcallback_wrapper(
    rho_handle,   # rhox:   environment frame SEXP
    sexp_ny,      # ny:     number of response columns
    sexp_nr,      # nr:     length of user eval return vector
    None,         # expr1x: R language expression SEXP (nullptr = not needed)
    None,         # expr2x: R language expression SEXP (nullptr = not needed)
)

# ----------------------------------------------------------------
# Step 7: Check for errors.
# ----------------------------------------------------------------
lib.get_last_rerror_message.restype  = ctypes.c_char_p
lib.get_last_rerror_message.argtypes = []
msg = lib.get_last_rerror_message()
if msg:
    raise RuntimeError(f"init_rpcallback failed: {msg.decode()}")
*/

// --- ArenaFrame usage ---
//
// Declare `ArenaFrame _frame;` as the first statement of any .Call-entry
// function that invokes arena-backed functions transitively through
// R_getVar / compat_getVar or any other rpart callback.
//
// init_rpcallback() itself does not perform arena allocations, but it is
// compiled in the same translation unit (rpart_callback.c) as
// rpart_callback1() and rpart_callback2(), which may use ALLOC / R_alloc.
// The ArenaFrame guard at the init_rpcallback wrapper is a precautionary
// standard measure for the entire callback subsystem.
//
// Once fake_arena.h is available:
//
//   #include "fake_arena.h"
//   extern "C" SEXP init_rpcallback_wrapper(
//           SEXP rhox, SEXP ny, SEXP nr, SEXP expr1x, SEXP expr2x)
//   {
//       ArenaFrame _frame;   // Invariant 2: frees all R_alloc/ALLOC on exit
//       try {
//           return init_rpcallback(rhox, ny, nr, expr1x, expr2x);
//       } catch (const RError &e) {
//           // Invariant 1: translate C++ exception to Python-readable error.
//           set_python_error(e.what());
//           return nullptr;   // signals failure; Python checks for nullptr
//       }
//   }
//
// SEXP sentinels (R_NilValue, R_UnboundValue, R_NamesSymbol) are
// function-static; they survive ArenaFrame destruction.
// SEXP heap allocations produced by allocVector / allocMatrix survive too
// (they use std::malloc, not the arena).  Python must call free_sexp() or
// free_sexp_deep() after extracting data from returned SEXP values.

#endif // FAKE_R_GETVAR_H
