// =============================================================
// R_NilValue.h — Fake R API: R_NilValue
// Original R header: Rinternals.h
// Category: A — Type or Enum Constant (global constant SEXP sentinel)
// Auto-generated by generate-r-extern-fake-header agent.
//
// R_NilValue is the canonical NULL singleton in R's C API.
// Original declaration in Rinternals.h (line 412):
//
//   LibExtern SEXP R_NilValue;    /* The nil object */
//
// LibExtern expands to `extern` in translation units that link against
// libR.so.  In a standalone (no-libR.so) build, that extern declaration
// becomes an unresolved symbol at link time.  This header provides a
// self-contained definition so the rpart source files build and run
// without libR.so.
//
// Contextual usage in rpart source (from CSV):
//
//   rpart.c:64
//     SEXP which3, cptable3, dsplit3, isplit3, csplit3 = R_NilValue, ...;
//     Pattern P1: default initializer for a SEXP local variable that may
//     be conditionally overwritten by allocMatrix(INTSXP, catcount, maxcat)
//     at rpart.c:293 when catcount > 0.  The /* -Wall */ comment confirms
//     the intent: suppress gcc -Wall "used uninitialized" warnings.
//
//   rpart_callback.c:71
//     return R_NilValue;
//     Pattern P2: side-effect-only .Call entry-point that performs no
//     useful computation and returns NULL as a conventional sentinel.
//
// Both patterns require R_NilValue to be a valid, non-null SEXP pointer
// to a NILSXP node (type=0).  A null pointer (nullptr) would satisfy the
// syntactic type requirement but would break any code that calls
// TYPEOF(R_NilValue) or isNull(R_NilValue), both of which dereference
// the pointer.  The fake provides a static SEXPREC sentinel instead.
//
// SEXP.h (which includes INTSXP.h) already provides:
//   - struct SEXPREC layout
//   - SEXP typedef
//   - NILSXP constant (#define NILSXP 0)
//   - R_NilValue singleton under FAKE_R_NILVALUE_DEFINED guard
//   - R_NaString / NA_STRING under FAKE_NA_STRING_DEFINED guard
//   - R_UnboundValue and R_NamesSymbol sentinels
//   - RError C++ exception struct under FAKE_R_RERROR_DEFINED guard
//
// This header is a lightweight wrapper that:
//   (a) includes SEXP.h to pull in all the above definitions,
//   (b) emits guarded fallback definitions of R_NilValue and R_NaString
//       for the case where this header is included standalone (without
//       SEXP.h having been included first in the same TU), and
//   (c) defines the error_return / errorcall_return compatibility macros
//       from Rinternals.h lines 1260-1261, which are not defined anywhere
//       else in the output folder.
// =============================================================
#pragma once

#ifndef FAKE_R_NILVALUE_H
#define FAKE_R_NILVALUE_H

// --- Standard library includes ---
#include <stdlib.h>    // malloc, free, size_t
#include <stddef.h>    // NULL, size_t
#include <stdarg.h>    // va_list, vsnprintf
#include <stdio.h>     // fprintf, stderr, vsnprintf
#include <stdexcept>   // std::runtime_error
#include <string>      // std::string

// --- Fake R header dependencies ---
// (from Integration Requirements in R_NilValue.md, Section 5)
//
// SEXP.h provides:
//   - RError C++ exception struct (via INTSXP.h under FAKE_R_RERROR_DEFINED)
//   - SEXPTYPE typedef and the full SEXPTYPE constant block including NILSXP=0,
//     SYMSXP=1, CHARSXP=9 (via INTSXP.h under FAKE_SEXPTYPE_DEFINED)
//   - struct SEXPREC { SEXPTYPE type; int length; int nrow; int ncol; void *data; }
//     (via INTSXP.h under FAKE_SEXPREC_DEFINED)
//   - typedef SEXPREC *SEXP (via INTSXP.h under FAKE_SEXPREC_DEFINED)
//   - allocVector / allocMatrix / INTEGER / REAL / PROTECT / UNPROTECT
//     (via INTSXP.h)
//   - Rboolean (via Rboolean.h)
//   - R_NilValue singleton under FAKE_R_NILVALUE_DEFINED
//   - R_NaString / NA_STRING under FAKE_NA_STRING_DEFINED
//   - R_UnboundValue sentinel under FAKE_R_UNBOUNDVALUE_DEFINED
//   - R_NamesSymbol sentinel under FAKE_R_NAMESSYMBOL_DEFINED
//   - TYPEOF, isNull, asInteger, asReal, mkChar, VECTOR_ELT, SET_VECTOR_ELT,
//     STRING_ELT, SET_STRING_ELT, setAttrib, getAttrib, XLENGTH, PRINTNAME,
//     R_ProtectWithIndex, R_Reprotect, free_sexp_deep
//
// NOTE: fake_arena.h is listed in R_NilValue.md as a dependency of the
// .Call boundary wrapper for init_rpcallback.  R_NilValue itself does not
// use the arena; fake_arena.h is not required by this header.
//
// WARNING: dependency fake_arena.h not found in output_folder.
// The ArenaFrame guard (ArenaFrame _frame;) must be added to any .Call-entry
// wrapper that calls rpart / init_rpcallback / pred_rpart / xpred / rpartexp2,
// once fake_arena.h is available.  See the ArenaFrame usage block at the
// bottom of SEXP.h.
#include "SEXP.h"

// ---------------------------------------------------------------------------
// R_NilValue — the NULL singleton (NILSXP, type=0, length=0, data=NULL).
//
// Real declaration in Rinternals.h line 412:
//   LibExtern SEXP R_NilValue;    /* The nil object */
//
// The primary definition lives in SEXP.h under FAKE_R_NILVALUE_DEFINED.
// The block below is a guarded fallback definition for the case where
// this header is included into a translation unit without SEXP.h having
// been included first.
//
// Implementation mechanism: a function-local static SEXPREC (guaranteed
// to be initialized exactly once by the C++ runtime, before first use,
// regardless of static-initialization order across translation units).
// A module-level `static SEXP R_NilValue` stores the resulting pointer.
//
// Observable properties (consistent with the real R runtime):
//   TYPEOF(R_NilValue)  == NILSXP  (0)
//   LENGTH(R_NilValue)  == 0
//   isNull(R_NilValue)  == 1 (true — s->type == NILSXP)
//   R_NilValue          != nullptr (safe to dereference in TYPEOF / isNull)
//
// Usage patterns satisfied:
//   P1 (rpart.c:64):
//     SEXP csplit3 = R_NilValue;   // pointer assignment — SEXP = SEXP, OK
//   P2 (rpart_callback.c:71):
//     return R_NilValue;            // returning a SEXP from SEXP function, OK
// ---------------------------------------------------------------------------
#ifndef FAKE_R_NILVALUE_DEFINED
#define FAKE_R_NILVALUE_DEFINED

inline SEXP make_nil_value() {
    static SEXPREC nil_rec = { NILSXP, 0, 0, 0, NULL };
    return &nil_rec;
}

/* Every translation unit that includes this header gets its own static
   SEXP R_NilValue variable; all point to the same SEXPREC because
   make_nil_value() uses a function-local static (initialized once). */
static SEXP R_NilValue = make_nil_value();

#endif // FAKE_R_NILVALUE_DEFINED

// ---------------------------------------------------------------------------
// R_NaString — NA_STRING as a CHARSXP (type=9) sentinel.
//
// Real declaration in Rinternals.h line 469:
//   LibExtern SEXP R_NaString;    /* NA_STRING as a CHARSXP */
// Real alias in Rinternals.h line 468:
//   #define NA_STRING  R_NaString
//
// The primary definition lives in SEXP.h under FAKE_NA_STRING_DEFINED.
// The block below is a guarded fallback definition.
//
// rpart source does not reference NA_STRING or R_NaString directly.
// The alias is required for completeness: any code that includes a real
// R header transitively (which the fake headers replace) may use NA_STRING.
//
// The CHARSXP sentinel fields:
//   type   = CHARSXP (9)
//   length = 2  (strlen("NA"))
//   nrow   = 2
//   ncol   = 1
//   data   = pointer to static "NA" string literal
// ---------------------------------------------------------------------------
#ifndef FAKE_NA_STRING_DEFINED
#define FAKE_NA_STRING_DEFINED

inline SEXP make_na_string() {
    static SEXPREC na_str_rec = { CHARSXP, 2, 2, 1, (void *) "NA" };
    return &na_str_rec;
}

static SEXP R_NaString = make_na_string();

/* Original Rinternals.h alias (line 468): #define NA_STRING R_NaString */
#ifndef NA_STRING
#define NA_STRING R_NaString
#endif

#endif // FAKE_NA_STRING_DEFINED

// ---------------------------------------------------------------------------
// RError — C++ exception struct replacing Rf_error / longjmp.
//
// Guarded fallback definition for the case where this header is included
// without INTSXP.h / SEXP.h.  The primary definition lives in INTSXP.h
// under FAKE_R_RERROR_DEFINED.
//
// Required here because error_return (see below) expands to a call to
// Rf_error, which throws RError.  The error_return macro must compile in
// any translation unit that includes this header, regardless of include order.
// ---------------------------------------------------------------------------
#ifndef FAKE_R_RERROR_DEFINED
#define FAKE_R_RERROR_DEFINED
struct RError : public std::runtime_error {
    explicit RError(const std::string &msg) : std::runtime_error(msg) {}
    explicit RError(const char *msg)        : std::runtime_error(msg) {}
};
#endif // FAKE_R_RERROR_DEFINED

// ---------------------------------------------------------------------------
// Rf_error — [[noreturn]] variadic function that formats a message and
// throws RError (Invariant 1: C++ exception-based error signalling).
//
// Guarded fallback definition for translation units that include this
// header without having already pulled in the Rf_error definition from
// another fake header.  The primary definition is expected in a dedicated
// error/warning fake header (Category D); this fallback ensures that the
// error_return macro compiles even when that header is absent.
//
// The real Rinternals.h declares:
//   void Rf_error(const char *, ...);   // line in R_ext/Error.h
// and aliases it:
//   #define error Rf_error              // in Rinternals.h
//
// In the fake, Rf_error throws RError so that C++ callers (and .Call-entry
// wrappers) can catch it at the boundary rather than relying on longjmp.
// ---------------------------------------------------------------------------
#ifndef FAKE_RF_ERROR_DEFINED
#define FAKE_RF_ERROR_DEFINED

[[noreturn]] inline void Rf_error(const char *fmt, ...) {
    char buf[1024];
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(buf, sizeof(buf), fmt, ap);
    va_end(ap);
    throw RError(buf);
}

#ifndef error
#define error Rf_error
#endif

#endif // FAKE_RF_ERROR_DEFINED

// ---------------------------------------------------------------------------
// Rf_errorcall — errorcall variant (call object ignored in fake runtime).
//
// The real Rinternals.h declares:
//   void Rf_errorcall(SEXP, const char *, ...);
//
// Needed for errorcall_return macro (see compatibility aliases below).
// The call argument is silently dropped; the message is thrown as RError.
// ---------------------------------------------------------------------------
#ifndef FAKE_RF_ERRORCALL_DEFINED
#define FAKE_RF_ERRORCALL_DEFINED

[[noreturn]] inline void Rf_errorcall(SEXP /*call*/, const char *fmt, ...) {
    char buf[1024];
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(buf, sizeof(buf), fmt, ap);
    va_end(ap);
    throw RError(buf);
}

#ifndef errorcall
#define errorcall Rf_errorcall
#endif

#endif // FAKE_RF_ERRORCALL_DEFINED

// --- Compatibility aliases (preserve original R API names) ---
//
// The following macros are defined by the real Rinternals.h at lines
// 1260-1261 and depend on both R_NilValue and Rf_error / Rf_errorcall.
// They are reproduced here because no other fake header in the output
// folder defines them.
//
// From Rinternals.h line 1260:
//   #define error_return(msg)          { Rf_error(msg); return R_NilValue; }
// From Rinternals.h line 1261:
//   #define errorcall_return(cl,msg)   { Rf_errorcall(cl, msg); return R_NilValue; }
//
// Semantics in the fake runtime:
//   Rf_error(msg)       throws RError — the "return R_NilValue" is unreachable
//   Rf_errorcall(cl,msg) throws RError — same
// Both are syntactically valid because R_NilValue is a SEXP expression.
//
// The macros are guarded to avoid conflicts if another fake header (e.g., a
// future dedicated error fake header) defines them first.
//
// Note: rpart source files do not use error_return or errorcall_return
// directly (confirmed by CSV context inspection).  These macros are provided
// for completeness so that any rpart-adjacent code using them compiles.
#ifndef error_return
#define error_return(msg)          { Rf_error(msg); return R_NilValue; }
#endif

#ifndef errorcall_return
#define errorcall_return(cl, msg)  { Rf_errorcall(cl, msg); return R_NilValue; }
#endif

// NA_STRING alias — already emitted above in FAKE_NA_STRING_DEFINED block.
// #define NA_STRING R_NaString    (already present if guard body was executed)

#endif // FAKE_R_NILVALUE_H
