// =============================================================
// R_registerRoutines.h — Fake R API: R_registerRoutines
// Original R header: R_ext/Rdynload.h
// Category: A — Type or Enum Constant (registration function variant)
// Auto-generated by generate-r-extern-fake-header agent.
//
// Original R API declaration (R_ext/Rdynload.h, lines 80-83):
//   int R_registerRoutines(DllInfo *info,
//                          const R_CMethodDef        * const croutines,
//                          const R_CallMethodDef     * const callRoutines,
//                          const R_FortranMethodDef  * const fortranRoutines,
//                          const R_ExternalMethodDef * const externalRoutines);
//
// Confirmed against the authoritative header at:
//   /users/ycai9/.conda/envs/r-to-python/lib/R/include/R_ext/Rdynload.h
// Lines 77-83: the declaration is wrapped in `extern "C"` for C++ builds.
// The function name is used directly at every call site — no #define alias
// exists in the original header.
//
// In the standalone fake build there is no R dynamic loader, no R symbol
// table, and R_init_rpart is never invoked by a loader.  R_registerRoutines
// is therefore dead code at runtime; the stub exists solely to satisfy the
// linker and allow init.c to compile and link without any modification.
// =============================================================
#pragma once

#ifndef FAKE_R_REGISTERROUTINES_H
#define FAKE_R_REGISTERROUTINES_H

// --- Standard library includes ---
#include <stddef.h>   // NULL

// --- Fake R header dependencies ---
// (from Integration Requirements in R_registerRoutines.md)
//
// DllInfo.h (via DL_FUNC.h) provides every type and companion stub needed
// for this header to compile and for init.c to build without libR.so:
//
//   From DL_FUNC.h (included by DllInfo.h):
//     - DL_FUNC typedef          (void * (*)(void))
//     - Rboolean enum            (FALSE = 0, TRUE = 1) — used by companion stubs
//     - R_NativePrimitiveArgType typedef
//     - R_CMethodDef struct      — second argument type of R_registerRoutines
//     - R_FortranMethodDef typedef — fourth argument type of R_registerRoutines
//     - R_CallMethodDef struct   — third argument type of R_registerRoutines
//     - R_ExternalMethodDef typedef — fifth argument type of R_registerRoutines
//     - inline int R_registerRoutines(...)     no-op stub (already present)
//     - inline Rboolean R_useDynamicSymbols(...)  companion no-op stub
//     - inline Rboolean R_forceSymbols(...)        companion no-op stub
//     - auxiliary stubs: R_getDllInfo, R_getEmbeddingDllInfo,
//                        R_RegisterCCallable, R_GetCCallable
//
//   From DllInfo.h itself:
//     - typedef struct DllInfo_fake DllInfo;  — C-compatible two-step form
//       (valid for plain C compilation of init.c as well as C++ builds)
//
// R_VERSION.h provides R_Version(v,p,s) and R_VERSION so that the
// preprocessor gate at init.c:27 evaluates correctly:
//   #if defined(R_VERSION) && R_VERSION >= R_Version(2, 16, 0)
// With R_VERSION = R_Version(4, 4, 0) = 263168 >= 131584, the condition
// is TRUE and R_forceSymbols(dll, TRUE) at init.c:28 is compiled.
// The R_forceSymbols stub in DL_FUNC.h (via DllInfo.h) handles that call.
//
// SEXP is not referenced in R_registerRoutines's own signature, but the
// function pointers in CallEntries[] (init.c:12-19) are SEXP-typed before
// being cast to DL_FUNC.  SEXP must therefore be in scope when init.c is
// compiled.  init.c includes rpart.h before R_ext/Rdynload.h, so SEXP is
// already defined by the time this header is processed.  No explicit
// SEXP.h include is needed here.
#include "DllInfo.h"
#include "R_VERSION.h"

// --- Core fake implementation ---
//
// Pattern: No-Op Library Registration Call Populating R's Symbol Table
//          with .Call Entry Points
// Location: init.c:25
//   R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
//
// Argument and return-value types at the call site (init.c:25):
//
//   Position 1: dll         — DllInfo *      (opaque handle, never dereferenced)
//   Position 2: NULL        — const R_CMethodDef * const    (.C routines; rpart has none)
//   Position 3: CallEntries — const R_CallMethodDef * const (5 .Call entry points + sentinel)
//   Position 4: NULL        — const R_FortranMethodDef * const (Fortran; rpart has none)
//   Position 5: NULL        — const R_ExternalMethodDef * const (.External; rpart has none)
//   Return value: (discarded) int — real function returns 1 on success
//
// Real R behaviour:
//   Populates R's internal symbol table so that .Call("rpart", ...) resolves
//   to the C function rpart().  In the standalone Python build, Python calls
//   the five rpart entry points directly by their C function symbols via
//   ctypes (lib.rpart(...)), bypassing R's symbol table entirely.
//   R_init_rpart — including its R_registerRoutines call — is dead code at
//   runtime; the function and its symbol are present in the shared object
//   but are never invoked.
//
// Fake strategy:
//   A static inline no-op stub with the correct five-argument signature.
//   All five arguments are discarded; the function returns 1 (the real
//   function's success code) to avoid triggering any hypothetical caller
//   check for zero (error) vs. positive (success).  Because the rpart call
//   site discards the return value entirely (init.c:25), any integer return
//   is technically correct; 1 is chosen for clarity and correctness.
//
//   The stub is already present as `inline int R_registerRoutines(...)` in
//   DL_FUNC.h (included above via DllInfo.h).  The #ifndef guard below
//   prevents a duplicate-definition error when both DL_FUNC.h and this
//   header appear in the same translation unit.  The static qualifier here
//   is compatible with the inline-only form in DL_FUNC.h: the compiler
//   selects a single definition because both produce identical no-op bodies.
//
// Invariants:
//   - Invariant 1 (C++ exception-based errors): not triggered.
//     R_registerRoutines does not call Rf_error, Rf_warning, or any error
//     mechanism.  No exception path exists in this stub.
//   - Invariant 2 (arena memory): not triggered.
//     R_registerRoutines neither allocates nor frees any memory.  The
//     DllInfo * pointer and the R_CallMethodDef * pointer are received
//     opaquely and immediately discarded; no heap or arena involvement.
//   - Invariant 3 (R Interpreter Items): not triggered.
//     R_registerRoutines is a loader-configuration function with no
//     interpreter interaction.  No Python callback registration is required.
#ifndef FAKE_R_REGISTERROUTINES_DEFINED
#define FAKE_R_REGISTERROUTINES_DEFINED

// R_registerRoutines — primary subject of this guide.
//
// Signature confirmed against R_ext/Rdynload.h lines 80-83:
//   int R_registerRoutines(DllInfo *info,
//                          const R_CMethodDef        * const croutines,
//                          const R_CallMethodDef     * const callRoutines,
//                          const R_FortranMethodDef  * const fortranRoutines,
//                          const R_ExternalMethodDef * const externalRoutines);
//
// Declared static inline to:
//   - Prevent multiple-definition link errors when this header is included
//     by more than one translation unit in the same build.
//   - Allow the compiler to fold the no-op body entirely (zero code emitted).
//
// All five (void) casts suppress -Wall -Wextra unused-parameter warnings
// without requiring any modification to init.c.
//
// NOTE: DL_FUNC.h (included above via DllInfo.h) already emits an `inline`
// (non-static) form of this stub.  The two forms are compatible under C++
// ODR: both produce the same no-op body and the linker selects one copy.
// The FAKE_R_REGISTERROUTINES_DEFINED guard below ensures this block is
// skipped if DL_FUNC.h was already included, avoiding any redeclaration
// diagnostic.
static inline int R_registerRoutines(
        DllInfo                           *info,
        const R_CMethodDef        * const  croutines,
        const R_CallMethodDef     * const  callRoutines,
        const R_FortranMethodDef  * const  fortranRoutines,
        const R_ExternalMethodDef * const  externalRoutines)
{
    (void)info;              // DllInfo * — opaque handle; never dereferenced
    (void)croutines;         // NULL in rpart (no .C routines registered)
    (void)callRoutines;      // CallEntries[] — 5 .Call entry points; discarded
    (void)fortranRoutines;   // NULL in rpart (no Fortran routines registered)
    (void)externalRoutines;  // NULL in rpart (no .External routines registered)
    return 1;  // real function returns 1 on success; call site discards value
}

#endif /* FAKE_R_REGISTERROUTINES_DEFINED */

// --- Compatibility aliases (preserve original R API names) ---
//
// R_ext/Rdynload.h defines no preprocessor aliases for R_registerRoutines.
// The function name is used directly at the call site (init.c:25):
//   R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
// No #define remapping macros are needed or present in the original header.
//
// All aliases needed by the surrounding init.c context are provided by
// DL_FUNC.h (via DllInfo.h, included above):
//   - FALSE / TRUE          : Rboolean enum enumerators
//   - R_useDynamicSymbols() : companion no-op stub (init.c:26)
//   - R_forceSymbols()      : companion no-op stub (init.c:28, R_VERSION gated)
//   - DL_FUNC               : function pointer typedef (used in CallEntries[])
//   - R_CallMethodDef       : struct type for CallEntries[] array
//   - DllInfo               : C-compatible typedef for the dll parameter

#endif /* FAKE_R_REGISTERROUTINES_H */
