// =============================================================
// R_UnboundValue.h — Fake R API: R_UnboundValue
// Original R header: Rinternals.h
// Category: A — Type or Enum Constant (static global sentinel SEXP)
// Auto-generated by generate-r-extern-fake-header agent.
//
// R_UnboundValue is the canonical "symbol not found" sentinel in R's C API.
// It is declared in Rinternals.h line 413 as:
//
//   LibExtern SEXP  R_UnboundValue;     /* Unbound marker */
//
// LibExtern expands to `extern` in translation units that link against
// libR.so.  In a standalone (no-libR.so) build the extern declaration
// becomes an unresolved symbol at link time.  This header provides a
// self-contained definition so rpart source files build and run without
// libR.so.
//
// Contextual usage in rpart source (from CSV):
//
//   rpart_callback.c:23
//     if (val == R_UnboundValue)
//     Pattern: Global sentinel SEXP used as the right-hand side of a
//     pointer equality comparison inside the compat_getVar compatibility
//     shim (compiled when R_VERSION < R_Version(4, 5, 0)).
//     val is the return value of findVar(sym, rho) or
//     findVarInFrame(rho, sym).  Only the pointer address of
//     R_UnboundValue is ever inspected; no SEXP accessor (INTEGER, REAL,
//     TYPEOF, LENGTH, etc.) is applied to it.
//
// Co-occurring R API items in the context window (rpart_callback.c:18–28):
//   findVar(sym, rho)          line 22  — Category E, function-ptr bridge
//   findVarInFrame(rho, sym)   line 22  — Category E, function-ptr bridge
//   R_UnboundValue             line 23  — this sentinel (pointer equality)
//   error(...)                 line 24  — expands to Rf_error, throws RError
//   CHAR(PRINTNAME(sym))       line 24  — CHARSXP accessor chain
//
// Correctness invariant:
//   The fake findVar / findVarInFrame stubs must return R_UnboundValue
//   when the requested symbol is absent.  Because make_unbound_value()
//   uses a function-local static, the address is stable across all
//   translation units: every module-level `static SEXP R_UnboundValue`
//   points to the same SEXPREC.  The Python callback registered via
//   register_findVarInFrame_fn() must return get_R_UnboundValue() to
//   reproduce the same pointer on the failure path.
//
// NOTE: The primary definition of R_UnboundValue lives in SEXP.h under
// the FAKE_R_UNBOUNDVALUE_DEFINED guard (lines 374-384 of that file).
// This header is a lightweight focused wrapper that:
//   (a) pulls in SEXP.h so all types and the primary definition are present,
//   (b) provides a guarded fallback definition in case this header is
//       included standalone (without SEXP.h having been included first
//       in the same translation unit), and
//   (c) adds get_R_UnboundValue(), the exported C accessor that Python
//       must call to obtain the sentinel's pointer address for use inside
//       the py_findVarInFrame callback (see Python Interop Notes below).
//
// Integration Requirements (from R_UnboundValue.md Section 5):
//   SEXP.h / INTSXP.h  — provides SEXPREC struct, SEXP typedef, SYMSXP=1
//   R_NilValue.h        — establishes the make_nil_value() pattern followed
//                         here; R_NilValue must be defined before this header
//   Rboolean.h          — Rboolean required by compat_getVar parameter list
//   fake_Rversion.hpp   — must define R_VERSION < R_Version(4,5,0) as true
//                         so compat_getVar is compiled and R_getVar defined
//   findVar / findVarInFrame fake headers (Category E) — the stubs that
//                         produce the value compared against R_UnboundValue
//   error / Rf_error fake header (Category D) — triggered at line 24 when
//                         val == R_UnboundValue; must throw RError
//   fake_arena.h        — needed by .Call boundary wrappers (not by this
//                         header directly)
// =============================================================
#pragma once

#ifndef FAKE_R_UNBOUNDVALUE_H
#define FAKE_R_UNBOUNDVALUE_H

// --- Standard library includes ---
#include <stdlib.h>    // malloc, free, size_t
#include <stddef.h>    // NULL, size_t

// --- Fake R header dependencies ---
// (from Integration Requirements in R_UnboundValue.md, Section 5)
//
// SEXP.h provides (transitively via INTSXP.h and Rboolean.h):
//   - RError C++ exception struct (FAKE_R_RERROR_DEFINED)
//   - SEXPTYPE typedef + full SEXPTYPE constant block (FAKE_SEXPTYPE_DEFINED)
//     including SYMSXP = 1, NILSXP = 0, CHARSXP = 9, etc.
//   - struct SEXPREC { SEXPTYPE type; int length; int nrow; int ncol; void *data; }
//     (FAKE_SEXPREC_DEFINED)
//   - typedef SEXPREC *SEXP (FAKE_SEXPREC_DEFINED)
//   - allocVector, allocMatrix, INTEGER, REAL, PROTECT, UNPROTECT (INTSXP.h)
//   - Rboolean (Rboolean.h)
//   - R_NilValue singleton under FAKE_R_NILVALUE_DEFINED
//   - R_UnboundValue sentinel under FAKE_R_UNBOUNDVALUE_DEFINED (primary def.)
//   - R_NamesSymbol sentinel under FAKE_R_NAMESSYMBOL_DEFINED
//   - TYPEOF, CHAR, PRINTNAME, mkChar, VECTOR_ELT, SET_VECTOR_ELT,
//     setAttrib, getAttrib, isReal, isInteger, isNull, asInteger, asReal,
//     R_ProtectWithIndex, R_Reprotect, free_sexp_deep (SEXP.h)
//   - Rf_error, Rf_warning, Rf_errorcall (R_NilValue.h)
//   - error_return, errorcall_return compatibility macros (R_NilValue.h)
//
// WARNING: dependency fake_arena.h not found in output_folder.
// ArenaFrame is needed by .Call-entry wrappers (see ArenaFrame usage note
// at the bottom of this header).  Once fake_arena.h is available, add:
//   #include "fake_arena.h"
// to the wrapper source and declare `ArenaFrame _frame;` as the first
// statement of any .Call-entry function that invokes arena-backed functions.
//
// SEXP.h provides the primary definition of R_UnboundValue (SEXPREC struct,
// SEXP typedef, SYMSXP constant, make_unbound_value, static R_UnboundValue).
#include "SEXP.h"
//
// R_NilValue.h provides Rf_error (throws RError), the #define error alias,
// Rf_errorcall, Rf_warning, error_return, and errorcall_return.  These are
// needed for the `error(...)` call at rpart_callback.c:24 which fires when
// val == R_UnboundValue.  R_NilValue.h includes SEXP.h itself, so all SEXP
// definitions remain available and the include is idempotent.
#include "R_NilValue.h"

// ---------------------------------------------------------------------------
// R_UnboundValue — the "not found" sentinel (SYMSXP, type=1).
//
// Pattern: Global Sentinel SEXP for Pointer Equality Comparison
// Location: rpart_callback.c:23
//
// Original R API usage (rpart_callback.c:18–28):
//
//   #if R_VERSION < R_Version(4, 5, 0)
//   static SEXP compat_getVar(SEXP sym, SEXP rho, Rboolean inherits)
//   {
//     SEXP val = inherits ? findVar(sym, rho) : findVarInFrame(rho, sym);
//     if (val == R_UnboundValue)                  // <-- line 23
//       error(_("variable '%s' not found"), CHAR(PRINTNAME(sym)));
//     return val;
//   }
//   #define R_getVar(sym, rho, inherits) compat_getVar(sym, rho, inherits)
//   #endif
//
// Real declaration in Rinternals.h line 413:
//   LibExtern SEXP  R_UnboundValue;     /* Unbound marker */
//
// LibExtern expands to `extern` when linking against libR.so.
// In the fake build there is no libR.so, so the variable must be DEFINED
// (not merely declared) in the fake header.
//
// Fake mechanism: a function-local static SEXPREC with type=SYMSXP.
// The make_unbound_value() factory guarantees that:
//   - The SEXPREC is initialized exactly once per process.
//   - Every module-level `static SEXP R_UnboundValue` across all translation
//     units that include this header resolves to the same pointer address.
//   - The address differs from nil_rec (R_NilValue), from names_sym
//     (R_NamesSymbol), and from any heap allocation produced by allocVector /
//     allocMatrix / mkChar (which use std::malloc and therefore never alias
//     a function-local static).
//
// Observable properties (verified against rpart_callback.c usage):
//   R_UnboundValue != nullptr              (safe to hold in a SEXP variable)
//   R_UnboundValue != R_NilValue           (distinct from the nil sentinel)
//   R_UnboundValue != R_NamesSymbol        (distinct from the names symbol)
//   R_UnboundValue != any allocVector()    (heap vs. BSS — always distinct)
//   TYPEOF(R_UnboundValue) == SYMSXP (1)  (consistent with a symbol node)
//
// No accessor (INTEGER, REAL, CHAR, LENGTH, etc.) is ever applied to
// R_UnboundValue in the rpart source.  The `==` comparison at line 23 is
// the only operation performed on it.
//
// Invariant applicability:
//   Invariant 1 (C++ exception errors): triggered at line 24 (error()), not
//     by R_UnboundValue itself.  When val == R_UnboundValue, the code calls
//     error(...) which expands to Rf_error(...) which throws RError.
//   Invariant 2 (arena memory): not triggered.  R_UnboundValue is a
//     function-static SEXPREC in the BSS segment; no arena allocation occurs.
//   Invariant 3 (R Interpreter Items): partially applicable.  The sentinel
//     itself needs no function-pointer bridge; the bridge requirement belongs
//     to findVar and findVarInFrame, which produce the val that is compared
//     against R_UnboundValue.
//
// The primary definition lives in SEXP.h (included above) under the guard
// FAKE_R_UNBOUNDVALUE_DEFINED.  The block below is a guarded fallback for
// the case where this header is included into a translation unit that did
// not previously include SEXP.h.
// ---------------------------------------------------------------------------
#ifndef FAKE_R_UNBOUNDVALUE_DEFINED
#define FAKE_R_UNBOUNDVALUE_DEFINED

inline SEXP make_unbound_value() {
    static SEXPREC unbound_rec = { SYMSXP, 0, 0, 0, NULL };
    return &unbound_rec;
}

/* Every translation unit that includes this header gets its own static
   SEXP R_UnboundValue variable; all point to the same SEXPREC because
   make_unbound_value() uses a function-local static (initialized once,
   process-wide, on first call). */
static SEXP R_UnboundValue = make_unbound_value();

#endif // FAKE_R_UNBOUNDVALUE_DEFINED

// ---------------------------------------------------------------------------
// get_R_UnboundValue — exported C accessor for Python interop.
//
// Python must read the sentinel's pointer address before registering its
// findVarInFrame callback, so that the callback can return the same address
// on lookup failure.  The module-level `static SEXP R_UnboundValue` above is
// not directly visible to Python (it has internal linkage); this extern "C"
// accessor bridges the gap.
//
// Usage in the Python glue layer:
//
//   lib.get_R_UnboundValue.restype  = ctypes.c_void_p
//   lib.get_R_UnboundValue.argtypes = []
//   R_UNBOUND = lib.get_R_UnboundValue()   # integer address of unbound_rec
//
// The Python findVarInFrame callback returns R_UNBOUND on failure; on the C
// side, compat_getVar compares val against R_UnboundValue using pointer ==,
// which succeeds because both sides hold the same address.
//
// This function is guarded by FAKE_GET_R_UNBOUNDVALUE_DEFINED to prevent
// a redefinition error if another fake header (e.g., a future combined
// fake_Rinternals.hpp) also provides it.
// ---------------------------------------------------------------------------
#ifndef FAKE_GET_R_UNBOUNDVALUE_DEFINED
#define FAKE_GET_R_UNBOUNDVALUE_DEFINED

extern "C" inline SEXP get_R_UnboundValue() {
    return R_UnboundValue;
}

#endif // FAKE_GET_R_UNBOUNDVALUE_DEFINED

// --- Compatibility aliases (preserve original R API names) ---
//
// The real Rinternals.h declares R_UnboundValue as:
//   LibExtern SEXP R_UnboundValue;
// with no #define alias.  The variable name is used directly in rpart source.
// No macro alias is required.
//
// The `error` alias (#define error Rf_error) that makes line 24 compile is
// provided by R_NilValue.h (included transitively via SEXP.h above) and by
// the dedicated error/Rf_error fake guide.  It is not reproduced here.
//
// Summary of what this header adds beyond what SEXP.h already provides:
//   - Guarded fallback definition of make_unbound_value() + R_UnboundValue
//     (active only when SEXP.h was not included first)
//   - get_R_UnboundValue() C-linkage accessor for Python ctypes interop

// ---------------------------------------------------------------------------
// *** R INTERPRETER ITEM (partial) — findVar / findVarInFrame ***
//
// R_UnboundValue itself requires no Python callback registration.
// However, the two Category E stubs that produce values compared against it —
// findVar and findVarInFrame — do require Python-side registration.
//
// Call chain for init_rpcallback() (rpart_callback.c lines 59-68):
//
//   R_getVar("yback", rho, FALSE)
//     -> compat_getVar(sym, rho, FALSE)          [compat shim, R < 4.5.0]
//       -> findVarInFrame(rho, sym)               [Category E stub]
//       -> if (val == R_UnboundValue)             [sentinel comparison here]
//         -> error("variable '%s' not found")     [throws RError, Invariant 1]
//
// For standard rpart() calls (method != 4), init_rpcallback() is never
// invoked and neither findVar nor findVarInFrame are called; R_UnboundValue
// is never compared against anything.  Registration is only required for
// user-defined split methods (method=4).
//
// Python Interop Notes — full ctypes registration snippet:
//
//   import ctypes
//
//   # Load the shared library built from the fake-header rpart source.
//   lib = ctypes.CDLL("./librpart_fake.so")
//
//   # SEXP is an opaque pointer in Python; use c_void_p.
//   SEXP = ctypes.c_void_p
//
//   # Step 1: retrieve the R_UnboundValue sentinel pointer from the fake lib.
//   # The C-side accessor get_R_UnboundValue() (defined in this header) is
//   # exported with C linkage and is therefore directly callable via ctypes.
//   lib.get_R_UnboundValue.restype  = SEXP
//   lib.get_R_UnboundValue.argtypes = []
//   R_UNBOUND = lib.get_R_UnboundValue()   # int address of unbound_rec
//
//   # Step 2: build a symbol registry.
//   # Maps symbol-SEXP pointer -> value-SEXP pointer.
//   # Populated before each .Call invocation by the Python glue layer.
//   _symbol_registry: dict = {}  # {sym_ptr: val_ptr}
//
//   # Step 3: define and register the findVarInFrame Python callback.
//   # compat_getVar always calls findVarInFrame (inherits=FALSE at all sites).
//   FindVarInFrameFnType = ctypes.CFUNCTYPE(SEXP, SEXP, SEXP)
//
//   def py_findVarInFrame(rho: int, sym: int) -> int:
//       """
//       Look up sym in rho.  Return the registered value SEXP, or
//       R_UnboundValue (== R_UNBOUND) if sym is absent from the registry.
//       Key invariant: returning R_UNBOUND causes compat_getVar to call
//       error(), which throws RError (Invariant 1).
//       """
//       val = _symbol_registry.get(sym)
//       if val is None:
//           return R_UNBOUND   # == R_UnboundValue on the C side
//       return val
//
//   _findVarInFrame_cb = FindVarInFrameFnType(py_findVarInFrame)
//
//   lib.register_findVarInFrame_fn.restype  = None
//   lib.register_findVarInFrame_fn.argtypes = [FindVarInFrameFnType]
//   lib.register_findVarInFrame_fn(_findVarInFrame_cb)
//
//   # The findVar callback (inherits=TRUE path) is registered identically:
//   FindVarFnType = ctypes.CFUNCTYPE(SEXP, SEXP, SEXP)
//
//   def py_findVar(sym: int, rho: int) -> int:
//       val = _symbol_registry.get(sym)
//       if val is None:
//           return R_UNBOUND
//       return val
//
//   _findVar_cb = FindVarFnType(py_findVar)
//
//   lib.register_findVar_fn.restype  = None
//   lib.register_findVar_fn.argtypes = [FindVarFnType]
//   lib.register_findVar_fn(_findVar_cb)
// ---------------------------------------------------------------------------

// --- ArenaFrame usage ---
//
// R_UnboundValue itself has no arena dependency.
// However, the init_rpcallback() .Call-entry wrapper that exercises the
// compat_getVar -> R_UnboundValue code path must declare:
//
//   ArenaFrame _frame;
//
// as its first statement, because init_rpcallback internally calls R_alloc /
// ALLOC scratch allocators (arena-backed).  Once fake_arena.h is available:
//
//   #include "fake_arena.h"
//   extern "C" SEXP init_rpcallback_wrapper(
//           SEXP rhox, SEXP ny, SEXP nr, SEXP expr1x, SEXP expr2x) {
//       ArenaFrame _frame;   // frees all R_alloc/ALLOC scratch on exit
//       try {
//           return init_rpcallback(rhox, ny, nr, expr1x, expr2x);
//       } catch (const RError &e) {
//           // store e.what() for Python, then return sentinel
//           return R_NilValue;
//       }
//   }
//
// Static SEXP singletons (R_UnboundValue, R_NilValue, R_NamesSymbol) survive
// ArenaFrame destruction — they live in the BSS segment, not on the arena.

#endif // FAKE_R_UNBOUNDVALUE_H
