// =============================================================
// R_VERSION.h — Fake R API: R_VERSION
// Original R header: Rversion.h
// Category: A — Macro constant (compile-time preprocessor integer)
// Auto-generated by generate-r-extern-fake-header agent.
// =============================================================
//
// Design note:
//   R_VERSION and R_Version(v,p,s) are pure preprocessor constructs.
//   They appear exclusively in #if / #elif directives and have no
//   runtime existence.  The entire fake therefore consists of
//   #define directives; no C++ code is emitted.
//
//   Two guard expressions appear in rpart/src/:
//
//     init.c:27:
//       #if defined(R_VERSION) && R_VERSION >= R_Version(2, 16, 0)
//       -> must be TRUE  so that R_forceSymbols() is compiled (no-op stub).
//
//     rpart_callback.c:19:
//       #if R_VERSION < R_Version(4, 5, 0)
//       -> must be TRUE  so that compat_getVar / R_getVar are compiled;
//          otherwise the build would require the native R_getVar symbol
//          from libR.so, which is absent in the standalone fake build.
//
//   The guide (R_VERSION.md §3) mandates R_Version(4, 4, 0) = 263168.
//   That value satisfies both guards:
//     263168 >= R_Version(2,16,0)=131584   -> TRUE  (pattern 1)
//     263168  < R_Version(4,5,0) =263424   -> TRUE  (pattern 2)
//
//   CONFLICT NOTE: R_CallMethodDef.h already defines R_Version and
//   R_VERSION (as R_Version(4,3,0)=262912) under #ifndef guards.
//   262912 also satisfies both constraints.  All definitions here use
//   #ifndef so that whichever header is included first prevails and
//   no redefinition warning or error is emitted.

#pragma once

#ifndef FAKE_R_VERSION_H
#define FAKE_R_VERSION_H

// --- Standard library includes ---
// (none required — this header is purely preprocessor)

// --- Fake R header dependencies ---
// R_VERSION is a standalone preprocessor constant; it has no C-type
// dependencies.  No other fake headers need to be included here.
// (Downstream items that rely on the code paths R_VERSION enables —
//  Rboolean, SEXP, R_UnboundValue, error, findVar, findVarInFrame —
//  are included by their own guides and by fake_R.h.)

// =============================================================
// Core fake implementation
// =============================================================

// --- Pattern 1: Feature-presence guard (init.c:27) ---
// #if defined(R_VERSION) && R_VERSION >= R_Version(2, 16, 0)
// The guard must evaluate to TRUE so that R_forceSymbols(dll, TRUE)
// is compiled.  R_forceSymbols is a no-op stub defined in DllInfo.h.

// --- Pattern 2: Backward-compatibility shim guard (rpart_callback.c:19) ---
// #if R_VERSION < R_Version(4, 5, 0)
// The guard must evaluate to TRUE so that compat_getVar and the
// R_getVar macro are compiled instead of expecting the native
// R_getVar symbol from libR.so.

// Core version encoding formula — byte-for-byte identical to real Rversion.h.
// Guarded so R_CallMethodDef.h (which defines the same macro) does not
// cause a redefinition error regardless of include order.
#ifndef R_Version
#define R_Version(v, p, s)  (((v) * 65536) + ((p) * 256) + (s))
#endif

// Faked R version: 4.4.0  =>  4*65536 + 4*256 + 0  =  263168
//   >= R_Version(2,16,0) = 131584  ->  TRUE  (R_forceSymbols path compiled)
//    < R_Version(4,5,0)  = 263424  ->  TRUE  (compat_getVar path compiled)
// Guarded for the same reason as R_Version above.
#ifndef R_VERSION
#define R_VERSION           R_Version(4, 4, 0)   /* 263168 */
#endif

// --- Supplementary macros from the real Rversion.h ---
// Included to prevent compile errors from any transitively included header
// or code path outside the CSV that references these names.
// Values are plausible placeholders for R 4.4.0.
#ifndef R_NICK
#define R_NICK          "Pile of Leaves"
#endif
#ifndef R_MAJOR
#define R_MAJOR         "4"
#endif
#ifndef R_MINOR
#define R_MINOR         "4.0"
#endif
#ifndef R_STATUS
#define R_STATUS        ""
#endif
#ifndef R_YEAR
#define R_YEAR          "2024"
#endif
#ifndef R_MONTH
#define R_MONTH         "04"
#endif
#ifndef R_DAY
#define R_DAY           "24"
#endif
#ifndef R_SVN_REVISION
#define R_SVN_REVISION  86474
#endif

// --- Compatibility aliases (preserve original R API names) ---
// The real Rversion.h defines no #define aliases for R_VERSION or
// R_Version — they are the canonical names.  No remapping macros
// are needed.  The real header also wraps its content in:
//   #ifdef __cplusplus
//   extern "C" { ... }
//   #endif
// but since all definitions above are preprocessor macros (not
// declarations), the extern "C" linkage block is unnecessary here.

// --- ArenaFrame usage ---
// Not applicable.  R_VERSION and R_Version are compile-time preprocessor
// constants; they perform no memory allocation and require no ArenaFrame.
// However, the code path that R_VERSION < R_Version(4,5,0) enables
// (compat_getVar in rpart_callback.c) is called from .Call entry points
// that must declare ArenaFrame at their boundary.  See fake_arena.h.

#endif /* FAKE_R_VERSION_H */
