// =============================================================
// REAL.h — Fake R API: REAL
// Original R header: Rinternals.h
// Category: B — accessor inline function
// Auto-generated by generate-r-extern-fake-header agent.
//
// REAL is declared in Rinternals.h line 288 as:
//   double *(REAL)(SEXP x);
// The parentheses around the function name are a C technique that
// forces the compiler to treat the declaration as a true function
// even when a macro of the same name is in scope.  In the non-
// USE_RINTERNALS build path (which rpart uses), no #define alias
// is active for REAL; the function declaration is what the compiler
// resolves.  Therefore NO #define REAL(x) alias is required or
// emitted here.
//
// Observed usage patterns across all 24 CSV rows:
//
//   P1: Assign double * from an input SEXP parameter
//       rpart.c:78,79,96,115,122,130
//       xpred.c:72,73,75,94,113,121,129
//       Results stored in local double * variables or struct fields.
//
//   P2: Assign double * from a freshly allocated SEXP, or pass as
//       a direct function argument from an input SEXP
//       rpart.c:243,263,270; xpred.c:210; pred_rpart.c:140; rpartexp2.c:48
//       SEXP produced by allocMatrix(REALSXP,...) or allocVector(REALSXP,...)
//       immediately before the REAL() call.
//
//   P3: Assign static module-level double * from a SEXP via R_getVar
//       rpart_callback.c:60,63,66
//       Identical cast pattern; source SEXP is produced by a Category E stub.
//
//   P4: Assign double * from a SEXP returned by eval()
//       rpart_callback.c:117,150
//       Identical cast pattern; source SEXP is produced by a Category E stub.
//
// All four patterns resolve to the same cast: static_cast<double *>(s->data).
// The SEXPREC struct (from INTSXP.h) stores the element buffer as void *data.
// allocVector(REALSXP, n) and allocMatrix(REALSXP, nrow, ncol) set data to a
// heap-allocated double[n] or double[nrow*ncol] buffer.
//
// Co-occurring R API items at the same call sites:
//   INTEGER(sexp)    — also uses s->data cast; defined in INTSXP.h
//   PROTECT/UNPROTECT — no-ops; defined in INTSXP.h
//   allocVector / allocMatrix — defined in INTSXP.h
//   asReal(sexp) / asInteger(sexp) — scalar extractors; defined in SEXP.h
//   isReal(value) — type predicate; defined in SEXP.h (rpart_callback.c:113,147)
//   LENGTH(value) — defined in INTSXP.h
//   error() — Rf_error stub; defined in INTEGER.h / error.h
//
// Integration Requirements (from REAL.md Section 5):
//   - INTSXP.h  : SEXPREC struct (void *data field), SEXP typedef, allocVector,
//                 allocMatrix, INTEGER, REAL (already defined under
//                 FAKE_ACCESSORS_DEFINED), Rf_REAL, LENGTH, PROTECT, RError.
//                 REAL.h wraps INTSXP.h and adds REAL_RO and supplementary
//                 ALTREP-layer accessors (REAL0, REAL_ELT, SET_REAL_ELT).
//   - REALSXP.h : Establishes #define REALSXP 14 and the static_assert.
//                 Already transitively included via INTSXP.h.
//   - SEXP.h    : asReal, isReal, and other helpers used alongside REAL in
//                 rpart_callback.c patterns P3 and P4.
//   - fake_arena.h (not yet in output folder): ArenaFrame for .Call wrappers
//                 that mix REAL() calls with ALLOC / R_alloc scratch arrays.
//                 REAL itself does not use the arena.
// =============================================================
#pragma once

#ifndef FAKE_R_REAL_H
#define FAKE_R_REAL_H

// --- Standard library includes ---
// (All needed system headers are transitively included via INTSXP.h)

// --- Fake R header dependencies ---
// (from Integration Requirements in REAL.md)
//
// INTSXP.h provides: RError, SEXPTYPE constant block (#define REALSXP 14),
// struct SEXPREC (with void *data), typedef SEXP, sexptype_element_size,
// allocVector, allocMatrix, Rf_allocVector, Rf_allocMatrix,
// INTEGER / REAL / LOGICAL / RAW inline accessors (FAKE_ACCESSORS_DEFINED),
// Rf_INTEGER / Rf_REAL, LENGTH / Rf_length, Rf_nrows / Rf_ncols,
// Rf_protect / Rf_unprotect / Rf_unprotect_ptr, free_sexp,
// PROTECT / UNPROTECT / UNPROTECT_PTR / PROTECT_WITH_INDEX / REPROTECT macros,
// nrows / ncols / allocVector / allocMatrix macro aliases.
#include "INTSXP.h"

// ---------------------------------------------------------------------------
// Core fake implementation — REAL / Rf_REAL
//
// Pattern: extract the double * data pointer from a REALSXP SEXP.
//
// Corresponds to the Rinternals.h declaration (line 288):
//   double *(REAL)(SEXP x);
//
// The fake casts s->data (void *) to double *.  This is safe because:
//   - allocVector(REALSXP, n) stores double[n] in s->data.
//   - allocMatrix(REALSXP, nrow, ncol) stores double[nrow*ncol] in s->data.
//   - Python-side SEXP construction for input parameters must set s->data to
//     point to a double[n] buffer (e.g. a numpy float64 array or ctypes
//     c_double array) before passing the SEXP across the .Call boundary.
//
// INTSXP.h already defines REAL and Rf_REAL inside the FAKE_ACCESSORS_DEFINED
// guard.  The definitions here are therefore entirely guarded with #ifndef to
// prevent redefinition errors when this header is included after INTSXP.h.
//
// --- Pattern P1 coverage (rpart.c:78,79,96,115,122,130; xpred.c:72,73,75,
//                           94,113,121,129) ---
// wt    = REAL(wt2);                   // assigns to local double *
// parms = REAL(parms2);                // assigns to local double *
// dptr  = REAL(opt2);                  // options vector
// rp.vcost = REAL(cost2);             // assigns to double * struct field
// dptr  = REAL(xmat2);                // column-major matrix traversal
// dptr  = REAL(ymat2);                // row-major matrix traversal
//
// --- Pattern P2 coverage (rpart.c:243,263,270; xpred.c:210; pred_rpart.c:140;
//                           rpartexp2.c:48) ---
// cptable3 = PROTECT(allocMatrix(REALSXP, nrow, ncol));
// dptr = REAL(cptable3);              // writable double * into output matrix
// Rpartexp2(n, REAL(dtimes), ...);    // direct function-argument usage
//
// --- Pattern P3 (rpart_callback.c:60,63,66) and P4 (rpart_callback.c:117,150):
// REAL applied to SEXPs from R_getVar / eval; mechanically identical cast.
// These paths are only reachable when method=4 (user-defined splits) is active
// and the R_getVar / eval function-pointer bridges are registered.
// ---------------------------------------------------------------------------
#ifndef FAKE_ACCESSORS_DEFINED
// Only reached if INTSXP.h was not already included (unusual ordering).
// Provide a minimal SEXPREC + SEXP + REAL definition as a fallback.
// In practice INTSXP.h always comes first.

#define FAKE_ACCESSORS_DEFINED

inline double *REAL(SEXP s) {
    return static_cast<double *>(s->data);
}

inline double *Rf_REAL(SEXP s) {
    return static_cast<double *>(s->data);
}

#endif // FAKE_ACCESSORS_DEFINED

// ---------------------------------------------------------------------------
// REAL_RO — read-only variant of REAL.
//
// Corresponds to Rinternals.h line 293:
//   const double *(REAL_RO)(SEXP x);
//
// Not used by any rpart source file in the CSV subset, but present in the
// original header and required for completeness so that any package source
// that calls REAL_RO compiles without modification.
//
// Implemented as a const-qualified cast of s->data to const double *.
// ---------------------------------------------------------------------------
#ifndef FAKE_REAL_RO_DEFINED
#define FAKE_REAL_RO_DEFINED

inline const double *REAL_RO(SEXP s) {
    return static_cast<const double *>(s->data);
}

#endif // FAKE_REAL_RO_DEFINED

// ---------------------------------------------------------------------------
// REAL0 — ALTREP-layer direct accessor (Rinternals.h line 1178).
//
//   double *REAL0(SEXP x);
//
// In the real R implementation, REAL0 bypasses the ALTREP dispatch and
// reads the data pointer directly from the compact representation.  In the
// fake runtime there is no ALTREP layer; REAL0 is identical to REAL.
// Provided for completeness; not observed in rpart CSV rows.
// ---------------------------------------------------------------------------
#ifndef FAKE_REAL0_DEFINED
#define FAKE_REAL0_DEFINED

inline double *REAL0(SEXP s) {
    return static_cast<double *>(s->data);
}

#endif // FAKE_REAL0_DEFINED

// ---------------------------------------------------------------------------
// REAL_ELT / SET_REAL_ELT — element-level accessors (Rinternals.h lines 1158,
// 1165).
//
//   double (REAL_ELT)(SEXP x, R_xlen_t i);
//   void SET_REAL_ELT(SEXP x, R_xlen_t i, double v);
//
// Used for element-at-a-time access in ALTREP-aware code.  In the fake
// runtime these simply index into the flat double[] buffer.  R_xlen_t is
// the extended-length index type (ptrdiff_t / int depending on build);
// int is sufficient for rpart's data sizes.  Provided for completeness;
// not observed in rpart CSV rows.
// ---------------------------------------------------------------------------
#ifndef FAKE_REAL_ELT_DEFINED
#define FAKE_REAL_ELT_DEFINED

inline double REAL_ELT(SEXP s, int i) {
    return static_cast<double *>(s->data)[i];
}

inline void SET_REAL_ELT(SEXP s, int i, double v) {
    static_cast<double *>(s->data)[i] = v;
}

#endif // FAKE_REAL_ELT_DEFINED

// ---------------------------------------------------------------------------
// --- Compatibility aliases (preserve original R API names) ---
//
// The original Rinternals.h (non-USE_RINTERNALS build path, which rpart uses)
// does NOT define a macro alias '#define REAL(x) ...' for REAL.  The
// parenthesised function declaration 'double *(REAL)(SEXP x)' at line 288
// prevents the compiler from treating REAL as a macro, and no #define alias
// exists in this build path.  Therefore no #define REAL alias is emitted here.
//
// The Rf_REAL name is provided as an inline function in INTSXP.h
// (FAKE_ACCESSORS_DEFINED block).  If INTSXP.h was skipped (unusual), the
// fallback block above also defines Rf_REAL.
//
// REAL_RO, REAL0, REAL_ELT, SET_REAL_ELT: declared in the original header
// without macro aliases; provided above as inline functions.
//
// Summary of all names provided by this header (directly or transitively):
//   inline double       *REAL(SEXP s)             — in INTSXP.h (or above)
//   inline double       *Rf_REAL(SEXP s)          — in INTSXP.h (or above)
//   inline const double *REAL_RO(SEXP s)          — above
//   inline double       *REAL0(SEXP s)            — above
//   inline double        REAL_ELT(SEXP s, int i)  — above
//   inline void   SET_REAL_ELT(SEXP s, int i, double v) — above
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// --- ArenaFrame usage ---
//
// REAL itself performs only a pointer cast and does not interact with the
// arena allocator.  However, every .Call-entry function in rpart that calls
// REAL() also calls ALLOC / R_alloc for scratch arrays in the same function
// body.  Once fake_arena.h is available in the output folder, declare
// `ArenaFrame _frame;` as the FIRST statement of any such entry function.
//
// Example (rpart entry point, illustrative):
//
//   #include "fake_arena.h"
//   extern "C" SEXP rpart_entry(
//           SEXP ncat2, SEXP method2, SEXP opt2, SEXP parms2,
//           SEXP xvals2, SEXP xgrp2, SEXP ymat2, SEXP xmat2,
//           SEXP wt2, SEXP ny2, SEXP cost2) {
//       ArenaFrame _frame;   // frees ALLOC/R_alloc scratch arrays on exit
//       try {
//           return rpart(ncat2, method2, opt2, parms2, xvals2, xgrp2,
//                        ymat2, xmat2, wt2, ny2, cost2);
//       } catch (const RError &e) {
//           set_python_error(e.what());
//           return nullptr;
//       }
//   }
//
// Inside rpart(), the original source lines compile unchanged:
//   wt    = REAL(wt2);    // -> static_cast<double *>(wt2->data)
//   parms = REAL(parms2); // -> static_cast<double *>(parms2->data)
//   dptr  = REAL(opt2);   // -> static_cast<double *>(opt2->data)
//   rp.vcost = REAL(cost2); // -> static_cast<double *>(cost2->data)
//   dptr  = REAL(xmat2);  // -> flat double* for column-major xmat2 buffer
//   dptr  = REAL(ymat2);  // -> flat double* for row-major ymat2 buffer
//   dptr  = REAL(cptable3); // -> writable double* into freshly allocated SEXP
//
// ArenaFrame is NOT required solely because of REAL; it is required because
// rpart / xpred / pred_rpart / rpartexp2 / init_rpcallback also call
// ALLOC / R_alloc in the same function body.
// ---------------------------------------------------------------------------

#endif // FAKE_R_REAL_H
