// =============================================================
// REALSXP.h — Fake R API: REALSXP
// Original R header: Rinternals.h
// Category: A — Type or Enum Constant
// Auto-generated by generate-r-extern-fake-header agent.
//
// REALSXP is the SEXPTYPE tag (value 14) that identifies real
// (double-precision floating-point) vector and matrix objects in
// R's C API.  It is used as the first argument to allocVector and
// allocMatrix in four locations across the rpart package source:
//
//   rpart.c:241  cptable3 = PROTECT(allocMatrix(REALSXP, xvals > 1 ? 5 : 3, rp.num_unique_cp));
//   rpart.c:261  dnode3   = PROTECT(allocMatrix(REALSXP, nodecount, (3 + rp.num_resp)));
//   rpart.c:269  dsplit3  = PROTECT(allocMatrix(REALSXP, splitcount, 3));
//   xpred.c:209  predict2 = PROTECT(allocVector(REALSXP, n * ncp * nresp));
//
// Original R header definition (Rinternals.h, non-enum_SEXPTYPE branch,
// line 124):
//   #define REALSXP  14   /* real variables */
//
// In the enum_SEXPTYPE branch (Rinternals.h line 162):
//   REALSXP = 14,   /* real variables */
//
// This header pulls in INTSXP.h, which defines the complete SEXPTYPE
// block (including #define REALSXP 14), the SEXPREC struct, SEXP typedef,
// allocVector, allocMatrix, REAL, INTEGER, PROTECT/UNPROTECT, LENGTH,
// nrows/ncols, free_sexp, and RError.  No symbols are redefined here;
// all additions are guarded with #ifndef to prevent conflicts.
//
// Integration Requirements (from REALSXP.md Section 5):
//   - INTSXP.h      : provides SEXPTYPE block (#define REALSXP 14),
//                     SEXPREC/SEXP, allocVector, allocMatrix, REAL,
//                     PROTECT/UNPROTECT, RError — all needed here.
//   - fake_arena.h  : ArenaFrame RAII guard for R_alloc/ALLOC scratch
//                     arrays used in rpart() and xpred() alongside the
//                     REALSXP allocations.  REALSXP itself does not use
//                     the arena; the arena requirement belongs to ALLOC.
// =============================================================

#pragma once

#ifndef FAKE_REALSXP_H
#define FAKE_REALSXP_H

// --- Standard library includes ---
// (All needed system headers are transitively included via INTSXP.h)
#include <stdlib.h>    // malloc, free, size_t
#include <string.h>    // memset
#include <stddef.h>    // NULL, size_t
#include <stdexcept>   // std::runtime_error
#include <string>      // std::string

// --- Fake R header dependencies ---
// (from Integration Requirements in REALSXP.md)
//
// INTSXP.h defines the complete SEXPTYPE constant block, SEXPREC, SEXP,
// allocVector, allocMatrix, REAL, INTEGER, PROTECT, UNPROTECT, LENGTH,
// nrows, ncols, free_sexp, and RError.  It already contains:
//   #define REALSXP 14   (inside the FAKE_SEXPTYPE_DEFINED guard)
//   inline double *REAL(SEXP s) { ... }   (inside FAKE_ACCESSORS_DEFINED)
// Including INTSXP.h is therefore sufficient to satisfy all compile-time
// requirements of every REALSXP usage site in the rpart source.
#include "INTSXP.h"

// ---------------------------------------------------------------------------
// REALSXP — real (double) vector / matrix type tag.
//
// Value: 14  (non-enum_SEXPTYPE branch of Rinternals.h, line 124)
//
// This constant is already defined by the FAKE_SEXPTYPE_DEFINED block inside
// INTSXP.h:
//   #define REALSXP  14   // real (double) variables
//
// No redefinition is needed here.  The block below is provided for
// documentation and as a compile-time assertion that the definition is live.
// ---------------------------------------------------------------------------

// Verify that REALSXP resolved to 14 at compile time.
// If the static_assert fires, INTSXP.h was not included or was stripped.
#ifdef __cplusplus
static_assert(REALSXP == 14,
    "REALSXP must equal 14 — check that INTSXP.h was included before REALSXP.h");
#endif

// ---------------------------------------------------------------------------
// REAL accessor — already defined in INTSXP.h (FAKE_ACCESSORS_DEFINED guard).
//
//   inline double *REAL(SEXP s) { return (double *) s->data; }
//   inline double *Rf_REAL(SEXP s) { return REAL(s); }
//
// Used in every REALSXP context in the rpart source:
//   rpart.c:243   dptr = REAL(cptable3);        // cp table, column-major
//   rpart.c:263   dptr = REAL(dnode3);           // node table
//   rpart.c:270   dptr = REAL(dsplit3);          // split table
//   xpred.c:210   predict = REAL(predict2);      // flat prediction vector
//
// The accessor casts sexp->data to double * regardless of nrow/ncol; callers
// use pointer arithmetic (dptr += nrow) for column-major traversal.
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// allocMatrix usage with REALSXP — Pattern: 2-D real matrix allocation
//
// Locations: rpart.c:241, rpart.c:261, rpart.c:269
//
//   cptable3 = PROTECT(allocMatrix(REALSXP, xvals > 1 ? 5 : 3, rp.num_unique_cp));
//   dnode3   = PROTECT(allocMatrix(REALSXP, nodecount, (3 + rp.num_resp)));
//   dsplit3  = PROTECT(allocMatrix(REALSXP, splitcount, 3));
//
// allocMatrix(REALSXP, nrow, ncol) produces a SEXPREC with:
//   s->type   = REALSXP (14)
//   s->length = nrow * ncol
//   s->nrow   = nrow
//   s->ncol   = ncol
//   s->data   = double[nrow * ncol], zero-initialized, column-major layout
//
// Column j starts at REAL(s) + j * nrow.  The rpart source advances dptr
// by nrow per column: for (i = 0; i < ncol; i++) { col[i] = dptr; dptr += nrow; }
//
// Memory: SEXPREC node and data buffer are heap-allocated via malloc().
// They are NOT arena-managed: the returned SEXPs are part of the .Call
// return list and must outlive the function frame.  Python extracts data
// into numpy arrays and calls free_sexp() to release both allocations.
// On allocation failure, allocVector (called by allocMatrix) throws RError.
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// allocVector usage with REALSXP — Pattern: 1-D real vector allocation
//
// Location: xpred.c:209
//
//   predict2 = PROTECT(allocVector(REALSXP, n * ncp * nresp));
//   predict  = REAL(predict2);
//
// allocVector(REALSXP, n) produces a SEXPREC with:
//   s->type   = REALSXP (14)
//   s->length = n
//   s->nrow   = n   (treated as a 1-D vector; ncol = 1)
//   s->ncol   = 1
//   s->data   = double[n], zero-initialized
//
// predict is then indexed directly: predict[k++] = value;
// The same allocVector / REAL pair that handles INTSXP vectors handles
// REALSXP vectors — only the element size differs (double vs int), which
// sexptype_element_size(REALSXP) returns as sizeof(double).
//
// Memory: same as the matrix pattern above — heap-allocated, not arena.
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// --- Compatibility aliases (preserve original R API names) ---
//
// The original Rinternals.h defines (line 124, non-enum_SEXPTYPE branch):
//   #define REALSXP  14   /* real variables */
//
// This alias is already emitted by the FAKE_SEXPTYPE_DEFINED block in
// INTSXP.h.  The compatibility block below re-documents it for clarity
// and guards additional REAL-related aliases.
//
// REAL / Rf_REAL:
//   The original Rinternals.h (line ~260) declares:
//     SEXP (REAL)(SEXP x);   -- function form that R_REAL macro may shadow
//   and downstream headers may define:
//     #define REAL(x) ((double *) DATAPTR(x))
//   In the fake runtime REAL is an inline function provided by INTSXP.h.
//   No further alias is needed, but we provide the Rf_REAL name guard below
//   in case source files use it explicitly.
// ---------------------------------------------------------------------------

/* REALSXP tag: #define REALSXP 14 — defined in INTSXP.h; listed here for
   documentation.  Not redefined to avoid preprocessor warnings. */

/* REAL / Rf_REAL — both provided as inline functions in INTSXP.h. */
/* If a source file explicitly references Rf_REAL, it resolves to the
   inline double *Rf_REAL(SEXP s) defined in INTSXP.h (FAKE_ACCESSORS_DEFINED). */

// ---------------------------------------------------------------------------
// --- ArenaFrame usage (Category A with arena-adjacent context) ---
//
// REALSXP itself is a compile-time integer constant and allocates nothing.
// However, every function that calls allocMatrix(REALSXP,...) or
// allocVector(REALSXP,...) in the rpart source also calls ALLOC / R_alloc
// for scratch arrays (double **, sorting arrays, node arrays, etc.) in the
// same function body.  Those scratch allocations are arena-managed.
//
// Once fake_arena.h is available in the output folder, declare
// `ArenaFrame _frame;` as the FIRST statement of every .Call-entry wrapper
// that enters rpart() or xpred():
//
//   extern "C" SEXP rpart_entry(SEXP ncat, SEXP method, ...) {
//       ArenaFrame _frame;    // frees all R_alloc/ALLOC scratch on exit
//       try {
//           return rpart(ncat, method, ...);
//       } catch (const RError &e) {
//           set_python_error(e.what());
//           return nullptr;
//       }
//   }
//
//   extern "C" SEXP xpred_entry(SEXP ncat, SEXP method, ...) {
//       ArenaFrame _frame;    // frees rp.csplit, sort scratch, etc.
//       try {
//           return xpred(ncat, method, ...);
//       } catch (const RError &e) {
//           set_python_error(e.what());
//           return nullptr;
//       }
//   }
//
// The SEXP return values (cptable3, dnode3, dsplit3, predict2) are
// heap-allocated and survive ArenaFrame destruction.  Python calls
// free_sexp() on each after copying data into numpy arrays.
// ---------------------------------------------------------------------------

#endif // FAKE_REALSXP_H
