// =============================================================
// SET_VECTOR_ELT.h — Fake R API: SET_VECTOR_ELT
// Original R header: Rinternals.h
// Category: B — Accessor/Mutator Inline Function
// Auto-generated by generate-r-extern-fake-header agent.
//
// SET_VECTOR_ELT is a write mutator declared in Rinternals.h at line 298 as:
//
//   SEXP SET_VECTOR_ELT(SEXP x, R_xlen_t i, SEXP v);
//
// It writes a child SEXP value v into slot i of a generic vector (list)
// object x of type VECSXP.  It is the write counterpart of the read
// accessor VECTOR_ELT(x, i).  The function returns v (the written value),
// matching the real R implementation.
//
// Internally, a VECSXP stores its elements as a flat SEXP[length] array —
// each slot holds a pointer to a child SEXPREC of any type.  SET_VECTOR_ELT
// is therefore equivalent to assigning into that pointer array at index i.
//
// The companion read accessor is:
//
//   SEXP (VECTOR_ELT)(SEXP x, R_xlen_t i);    // Rinternals.h line 296
//
// (The parenthesised form in the real header exists to block potential
// macro substitution of the name; no #define alias for VECTOR_ELT exists
// in Rinternals.h.  The inline function in the fake uses the plain name.)
//
// Neither SET_VECTOR_ELT nor VECTOR_ELT has a #define alias in
// Rinternals.h; both are declared by their exact canonical names.
//
// Observed usage in rpart source (all seven CSV rows, rpart.c:330-343):
//
//   Pattern: Write Pre-Allocated Child SEXP into a VECSXP Slot
//   ----------------------------------------------------------
//   int nout = catcount > 0 ? 7 : 6;
//   SEXP rlist = PROTECT(allocVector(VECSXP, nout));   // rpart.c:327
//   SEXP rname = allocVector(STRSXP, nout);             // rpart.c:328
//   setAttrib(rlist, R_NamesSymbol, rname);             // rpart.c:329
//   SET_VECTOR_ELT(rlist, 0, which3);                  // rpart.c:330 — CSV row 1
//   SET_STRING_ELT(rname, 0, mkChar("which"));
//   SET_VECTOR_ELT(rlist, 1, cptable3);                // rpart.c:332 — CSV row 2
//   SET_STRING_ELT(rname, 1, mkChar("cptable"));
//   SET_VECTOR_ELT(rlist, 2, dsplit3);                 // rpart.c:334 — CSV row 3
//   SET_STRING_ELT(rname, 2, mkChar("dsplit"));
//   SET_VECTOR_ELT(rlist, 3, isplit3);                 // rpart.c:336 — CSV row 4
//   SET_STRING_ELT(rname, 3, mkChar("isplit"));
//   SET_VECTOR_ELT(rlist, 4, dnode3);                  // rpart.c:338 — CSV row 5
//   SET_STRING_ELT(rname, 4, mkChar("dnode"));
//   SET_VECTOR_ELT(rlist, 5, inode3);                  // rpart.c:340 — CSV row 6
//   SET_STRING_ELT(rname, 5, mkChar("inode"));
//   if (catcount > 0) {
//       SET_VECTOR_ELT(rlist, 6, csplit3);             // rpart.c:343 — CSV row 7
//       SET_STRING_ELT(rname, 6, mkChar("csplit"));
//   }
//   UNPROTECT(1 + nout);
//   return rlist;
//
// Child SEXP types written into rlist:
//   Slot 0: which3    — INTSXP 1-D vector   (allocVector,  rpart.c:194)
//   Slot 1: cptable3  — REALSXP 2-D matrix  (allocMatrix,  rpart.c:241)
//   Slot 2: dsplit3   — REALSXP 2-D matrix  (allocMatrix,  rpart.c:269)
//   Slot 3: isplit3   — INTSXP 2-D matrix   (allocMatrix,  rpart.c:285)
//   Slot 4: dnode3    — REALSXP 2-D matrix  (allocMatrix,  rpart.c:261)
//   Slot 5: inode3    — INTSXP 2-D matrix   (allocMatrix,  rpart.c:278)
//   Slot 6: csplit3   — INTSXP 2-D matrix   (allocMatrix,  rpart.c:293)
//              or NILSXP (R_NilValue) when catcount == 0; slot 6 is left
//              as nullptr (from allocVector zero-init) in that case.
//
// Argument and return types (confirmed against Rinternals.h line 298):
//   x      — SEXP pointing to a VECSXP object (the target generic list rlist)
//   i      — R_xlen_t (typedef int R_xlen_t in the 32-bit-safe fake per SEXP.h);
//             all rpart call sites pass integer literals 0–6.
//   v      — SEXP of any type (the child object to store; may be R_NilValue).
//   return — SEXP: the written value v.  None of the seven rpart call sites
//             use the return value, but the correct return type is required for
//             any client code that does.
//
// Invariant applicability:
//   Invariant 1 (C++ error): not triggered by SET_VECTOR_ELT itself.
//     The function performs no allocation and no error checking.  If x is
//     null or i is out of bounds the result is undefined behaviour —
//     consistent with the real R API under USE_RINTERNALS.  Allocation errors
//     from allocVector / allocMatrix calls that produced the child SEXPs
//     propagate (as RError) before SET_VECTOR_ELT is reached.
//   Invariant 2 (arena memory): not triggered.  SET_VECTOR_ELT performs no
//     allocation of any kind; it is a single pointer-array write.
//   Invariant 3 (R interpreter): not applicable.  SET_VECTOR_ELT is a pure
//     in-memory pointer-array write with no interpreter dependency.
//
// Symbol conflict analysis:
//   Both VECTOR_ELT and SET_VECTOR_ELT are already defined in SEXP.h at
//   lines 274-281 inside the FAKE_VECTORELT_DEFINED guard block, alongside
//   STRING_ELT and SET_STRING_ELT.  This header therefore MUST NOT emit
//   competing inline definitions; it delegates entirely to SEXP.h and
//   provides safety-net definitions only when FAKE_VECTORELT_DEFINED is
//   absent (i.e., when this header is included without SEXP.h, which should
//   not occur in correct builds but is handled defensively).
//
// This is structurally parallel to SET_STRING_ELT.h, which follows the
// same delegation strategy for its companion STRSXP mutator.
//
// Integration Requirements (from SET_VECTOR_ELT.md Section 5):
//   - SEXP.h         : Primary prerequisite.  Provides SEXPREC struct layout
//                      (type, length, nrow, ncol, data fields), SEXP typedef,
//                      R_xlen_t typedef (int), VECTOR_ELT and SET_VECTOR_ELT
//                      inline functions (FAKE_VECTORELT_DEFINED block),
//                      STRING_ELT / SET_STRING_ELT (same block), mkChar /
//                      Rf_mkChar, PROTECT / UNPROTECT no-ops (via INTSXP.h),
//                      R_NilValue, R_NamesSymbol, setAttrib (no-op), and
//                      free_sexp_deep (recurses into VECSXP children).
//   - VECSXP.h       : Establishes #define VECSXP 19 (via INTSXP.h chain)
//                      and documents allocVector(VECSXP, nout) that creates
//                      rlist.  Confirms sexptype_element_size(VECSXP) ==
//                      sizeof(SEXP), so slot array is SEXP[nout].
//   - SET_STRING_ELT.h : Documents the structurally parallel STRSXP mutator
//                      whose calls interleave with SET_VECTOR_ELT in
//                      rpart.c:330-344.  Both must be present for the output-
//                      construction block to compile as a unit.
//   - PROTECT.h      : Documents PROTECT / UNPROTECT no-ops; rlist is wrapped
//                      in PROTECT at rpart.c:327 immediately before the first
//                      SET_VECTOR_ELT call, and UNPROTECT(1 + nout) appears
//                      at line 347 after the last call.
//   - R_NamesSymbol.h : Documents R_NamesSymbol and the no-op setAttrib at
//                      rpart.c:329 (immediately before the first
//                      SET_VECTOR_ELT call).
//   - fake_arena.h   : Required by the rpart_wrapper .Call boundary wrapper
//                      for ArenaFrame RAII.  SET_VECTOR_ELT itself has no
//                      arena dependency; include fake_arena.h at the .Call
//                      entry point, not here.
// =============================================================
#pragma once

#ifndef FAKE_R_SET_VECTOR_ELT_H
#define FAKE_R_SET_VECTOR_ELT_H

// --- Standard library includes ---
// All necessary standard headers are transitively supplied by SEXP.h
// (stdlib.h, string.h, stddef.h, stdarg.h, stdio.h, stdexcept, string).
// No additional system includes are required by SET_VECTOR_ELT itself.

// --- Fake R header dependencies ---
// (from Integration Requirements in SET_VECTOR_ELT.md, Section 5)
//
// SEXP.h is the complete prerequisite.  It transitively provides (via its
// own include of INTSXP.h and Rboolean.h):
//   - struct SEXPREC (type, length, nrow, ncol, data fields)
//   - typedef SEXPREC *SEXP
//   - typedef int R_xlen_t  (32-bit-safe; matches real Rinternals.h on
//     rpart's target platforms)
//   - SEXPTYPE constant block: NILSXP=0, INTSXP=13, REALSXP=14,
//     STRSXP=16, VECSXP=19, CHARSXP=9, SYMSXP=1, EXPRSXP=20, etc.
//   - VECTOR_ELT / SET_VECTOR_ELT inline functions (FAKE_VECTORELT_DEFINED)
//   - STRING_ELT / SET_STRING_ELT inline functions (same guard)
//   - mkChar / Rf_mkChar (FAKE_MKCHAR_DEFINED)
//   - PROTECT / UNPROTECT no-ops (INTSXP.h via SEXP.h)
//   - R_NilValue, R_NamesSymbol, setAttrib (no-ops)
//   - free_sexp_deep (recurses into VECSXP/EXPRSXP/STRSXP children,
//     freeing each non-null child SEXP stored by SET_VECTOR_ELT)
//   - RError (C++ exception type replacing Rf_error for error propagation)
#include "SEXP.h"

// VECSXP.h documents allocVector(VECSXP, nout) and confirms that
// sexptype_element_size(VECSXP) == sizeof(SEXP), so the slot array
// allocated by allocVector is a SEXP[nout] array (zero-initialized).
// VECSXP.h is transitively consistent with SEXP.h since VECSXP.h itself
// includes STRSXP.h -> SEXP.h -> INTSXP.h; all guards prevent redefinition.
#include "VECSXP.h"

// SET_STRING_ELT.h is the structurally parallel mutator for STRSXP objects.
// The SET_STRING_ELT(rname, i, mkChar(...)) calls appear at every alternate
// line in the same rpart.c:330-344 block as SET_VECTOR_ELT.  Both must be
// present for the entire output-construction block to compile as a unit.
// SET_STRING_ELT.h includes SEXP.h and STRSXP.h; no redefinition conflicts
// arise due to header guards throughout the dependency chain.
#include "SET_STRING_ELT.h"

// R_NamesSymbol.h documents and (as a safety net) re-provides the
// R_NamesSymbol sentinel and the setAttrib/getAttrib no-ops used at
// rpart.c:329 (immediately before the first SET_VECTOR_ELT call).
// The actual definitions come from SEXP.h; R_NamesSymbol.h guards prevent
// redefinition.
#include "R_NamesSymbol.h"

// PROTECT.h adds PROTECT_INDEX typedef and corrected two-argument
// PROTECT_WITH_INDEX / REPROTECT aliases matching the real Rinternals.h
// signatures.  PROTECT itself is already a no-op identity inline from
// INTSXP.h.  rpart.c:327 wraps allocVector(VECSXP, nout) in PROTECT and
// calls UNPROTECT(1 + nout) at line 347; both must compile correctly.
#include "PROTECT.h"

// --- Core fake implementation ---
//
// Pattern: Write Pre-Allocated Child SEXP into a VECSXP Slot
// Locations: rpart.c:330, rpart.c:332, rpart.c:334, rpart.c:336,
//            rpart.c:338, rpart.c:340, rpart.c:343
//
// The implementation is provided by SEXP.h inside the FAKE_VECTORELT_DEFINED
// guard (SEXP.h lines 271-291, confirmed by reading SEXP.h).
// The definitions there read:
//
//   inline SEXP VECTOR_ELT(SEXP s, int i) {
//       return static_cast<SEXP *>(s->data)[i];
//   }
//
//   inline SEXP SET_VECTOR_ELT(SEXP s, int i, SEXP v) {
//       static_cast<SEXP *>(s->data)[i] = v;
//       return v;
//   }
//
// Correctness rationale:
//   1. allocVector(VECSXP, n) stores a SEXP[n] array in s->data, zeroed
//      (all child pointer slots initialized to nullptr by calloc inside
//      allocVector's implementation in INTSXP.h).
//   2. The cast static_cast<SEXP *>(x->data) is valid in C++ because data
//      is void* pointing to a SEXP[] array heap-allocated by allocVector.
//   3. The index i is an int literal (0-6) at all rpart call sites.
//      R_xlen_t is typedef int in the fake, so no narrowing occurs.
//   4. v may be any SEXP type: INTSXP (slots 0,3,5,6), REALSXP (slots 1,2,4),
//      or NILSXP / nullptr (slot 6 left as nullptr when catcount == 0 and
//      SET_VECTOR_ELT(rlist, 6, ...) is skipped by the if-branch).
//   5. Returning v matches the real Rinternals.h signature (SEXP return type).
//      No rpart call site uses the return value, but the correct return type
//      is required for any client code that does.
//   6. No allocation is performed by SET_VECTOR_ELT itself.  Any OOM
//      error in the allocVector / allocMatrix calls that produced the child
//      SEXPs has already propagated as RError before SET_VECTOR_ELT is reached.
//   7. No #define alias for SET_VECTOR_ELT or VECTOR_ELT exists in the real
//      Rinternals.h; the inline functions use the exact original names, so
//      rpart.c compiles unchanged.
//
// Memory lifecycle for rlist (VECSXP):
//   1. allocVector(VECSXP, nout) — std::malloc for the SEXPREC node plus
//      std::malloc (zeroed) for the SEXP[nout] slot array.
//   2. SET_VECTOR_ELT(rlist, i, child_sexp) — pointer copy into slot array;
//      O(1), no allocation.  Slot 6 remains nullptr when catcount == 0.
//   3. Python receives rlist as the .Call return value.  Each element is
//      read by positional index via VECTOR_ELT(rlist, i), then the element's
//      data buffer is accessed via INTEGER() or REAL().
//   4. Python calls free_sexp_deep(rlist) which recurses into all non-null
//      child slots and frees each child SEXP, then frees the slot array and
//      the rlist SEXPREC node itself.  The nullptr in slot 6 (catcount == 0
//      case) is safely handled by free_sexp_deep's `if (!s) return;` guard.
//   5. Python calls free_sexp_deep(rname) separately because setAttrib is a
//      no-op and rname is not owned by rlist.
//
// Safety-net definitions: if SEXP.h was somehow not included first (which
// should never occur in a correct build), the block below provides the
// minimal definitions to allow compilation.  The FAKE_VECTORELT_DEFINED
// guard ensures no redefinition conflict with SEXP.h's block.

#ifndef FAKE_VECTORELT_DEFINED
#define FAKE_VECTORELT_DEFINED
// WARNING: SEXP.h was not included before SET_VECTOR_ELT.h.
// The definitions below are safety-net fallbacks only.  In correct builds,
// these are already provided by SEXP.h under FAKE_VECTORELT_DEFINED.
// SEXPREC and SEXP must be defined by INTSXP.h (transitively via SEXP.h)
// for these to compile.

// VECTOR_ELT — read accessor for VECSXP elements.
// Real declaration in Rinternals.h line 296:
//   SEXP (VECTOR_ELT)(SEXP x, R_xlen_t i);
// The parenthesised form blocks macro substitution; no #define alias exists.
// Fake: cast x->data to SEXP * and return the child pointer at index i.
// x must be a VECSXP; x->data is a SEXP[x->length] array of child SEXP
// pointers allocated by allocVector(VECSXP, n) and zero-initialized.
inline SEXP VECTOR_ELT(SEXP s, int i) {
    return static_cast<SEXP *>(s->data)[i];
}

// SET_VECTOR_ELT — write mutator for VECSXP elements.
// Real declaration in Rinternals.h line 298:
//   SEXP SET_VECTOR_ELT(SEXP x, R_xlen_t i, SEXP v);
// No #define alias exists in Rinternals.h; callers use the exact name.
// Fake: cast x->data to SEXP * and assign v at index i, then return v.
// v may be any SEXP type (INTSXP, REALSXP, NILSXP, etc.); no allocation
// is performed and no arena is touched.
inline SEXP SET_VECTOR_ELT(SEXP s, int i, SEXP v) {
    static_cast<SEXP *>(s->data)[i] = v;
    return v;
}

// STRING_ELT and SET_STRING_ELT are also in this guard block (per SEXP.h
// layout) to ensure the guard covers all four VECSXP/STRSXP accessors.
inline SEXP STRING_ELT(SEXP s, int i) {
    return static_cast<SEXP *>(s->data)[i];
}

inline void SET_STRING_ELT(SEXP s, int i, SEXP v) {
    static_cast<SEXP *>(s->data)[i] = v;
}

#endif // FAKE_VECTORELT_DEFINED

// --- Compatibility aliases (preserve original R API names) ---
//
// Original Rinternals.h declarations for SET_VECTOR_ELT and VECTOR_ELT:
//
//   SEXP (VECTOR_ELT)(SEXP x, R_xlen_t i);    // line 296 — no #define alias
//   SEXP SET_VECTOR_ELT(SEXP x, R_xlen_t i, SEXP v);  // line 298 — no alias
//
// Neither SET_VECTOR_ELT nor VECTOR_ELT has a #define alias (e.g., no
// Rf_SET_VECTOR_ELT or similar remapping) in the original Rinternals.h.
// The inline functions above use the exact original names, so the rpart
// source files compile without any textual modification.
//
// No additional #define aliases are required for SET_VECTOR_ELT or
// VECTOR_ELT.
//
// Adjacent aliases required at rpart.c:327-347 call sites:
//
//   allocVector — used at rpart.c:327 (allocVector(VECSXP, nout)).
//     Provided by INTSXP.h (via SEXP.h).  No alias needed; inline function
//     uses the exact original name.
//
//   PROTECT / UNPROTECT — used at rpart.c:327 and rpart.c:347.
//     Real aliases: #define PROTECT(s) Rf_protect(s), etc.  Provided by
//     INTSXP.h (FAKE_PROTECT_DEFINED block) and augmented by PROTECT.h.
//
//   setAttrib — used at rpart.c:329 (immediately before the first
//     SET_VECTOR_ELT call).  No-op provided by SEXP.h / R_NamesSymbol.h.
//     Real alias: #define setAttrib Rf_setAttrib (Rinternals.h line 1048).
//     Provided as an inline short-name function in SEXP.h (FAKE_ATTRIB_DEFINED).
//
//   R_NamesSymbol — passed to setAttrib at rpart.c:329.
//     Static SYMSXP sentinel provided by SEXP.h (FAKE_R_NAMESSYMBOL_DEFINED).
//     No alias needed; the name is the canonical one from Rinternals.h.
//
//   SET_STRING_ELT / mkChar — used at rpart.c:331-344 (alternating with
//     SET_VECTOR_ELT).  Provided by SEXP.h / SET_STRING_ELT.h above.
//
// Summary: no new #define aliases are required for SET_VECTOR_ELT or
// VECTOR_ELT because the real Rinternals.h declares them by their exact
// canonical names and the fake inline functions use those same names.

// --- ArenaFrame usage (not applicable to SET_VECTOR_ELT directly) ---
//
// SET_VECTOR_ELT performs no arena allocation.  The SEXP objects it
// writes (the child SEXPs produced by allocVector / allocMatrix) are
// heap-allocated via std::malloc and are independent of the arena.
// The target VECSXP (rlist) is also heap-allocated.
//
// However, the enclosing rpart() function uses R_alloc / ALLOC extensively
// for scratch arrays during tree construction.  Those scratch allocations
// ARE arena-backed.  The .Call-entry wrapper for rpart() must therefore
// declare `ArenaFrame _frame;` as its very first statement to ensure the
// arena is freed on function exit even if RError is thrown.
//
// Declare `ArenaFrame _frame;` as the first statement of any .Call-entry
// function that invokes arena-backed functions from fake_arena.h.  Example:
//
//   SEXP rpart_entry(
//           SEXP ncat2, SEXP method2, SEXP opt2,
//           SEXP parms2, SEXP xvals2, SEXP xgrp2,
//           SEXP ymat2, SEXP xmat2, SEXP wt2, SEXP ny2, SEXP cost2) {
//       ArenaFrame _frame;   // frees R_alloc/ALLOC scratch at function exit
//       try {
//           return rpart(ncat2, method2, opt2, parms2, xvals2, xgrp2,
//                        ymat2, xmat2, wt2, ny2, cost2);
//       } catch (const RError &e) {
//           set_python_error(e.what());
//           return R_NilValue;
//       }
//   }
//
// The VECSXP rlist and all its child SEXPs are heap-allocated and survive
// ArenaFrame destruction.  Python extracts element data via VECTOR_ELT /
// REAL / INTEGER, then calls free_sexp_deep(rlist) after copying data into
// numpy arrays.  Python calls free_sexp_deep(rname) separately.

#endif // FAKE_R_SET_VECTOR_ELT_H
