// =============================================================
// setAttrib.h — Fake R API: setAttrib / Rf_setAttrib
// Original R header: Rinternals.h
// Category: B — Accessor / Inline Function (attribute stub, no-op)
// Auto-generated by generate-r-extern-fake-header agent.
//
// setAttrib(SEXP x, SEXP name, SEXP val) attaches attribute val to object x
// under the key name.  getAttrib(SEXP x, SEXP name) retrieves the attribute.
// Original R declarations:
//   SEXP Rf_setAttrib(SEXP, SEXP, SEXP);   (Rinternals.h line 582)
//   SEXP Rf_getAttrib(SEXP, SEXP);          (Rinternals.h line 583)
//   #define setAttrib Rf_setAttrib          (Rinternals.h line 1048)
//   #define getAttrib Rf_getAttrib          (Rinternals.h line 1049)
//
// Source usage context:
//   rpart.c:329  setAttrib(rlist, R_NamesSymbol, rname);
//   — Attaches rname (a STRSXP of field names) to rlist (the output VECSXP)
//     as the names attribute.  Called once, immediately after allocating both
//     SEXPs and before populating them with SET_VECTOR_ELT / SET_STRING_ELT.
//
// Implementation strategy (from setAttrib.md):
//   In the fake runtime, SEXPREC nodes have no attribute pairlist.  Python
//   reads rpart output by querying named list slots using positional indexing
//   (VECTOR_ELT) and a separately tracked name vector (rname).  The names
//   attribute does not need to be stored ON rlist itself.  Both setAttrib and
//   getAttrib are therefore safe no-ops:
//     Rf_setAttrib(x, name, val) → void (discards all arguments)
//     Rf_getAttrib(x, name) → R_NilValue (attribute not stored)
//
// Delegation: the authoritative no-op implementations are in SEXP.h under
// FAKE_ATTRIB_DEFINED (Rf_setAttrib, Rf_getAttrib, setAttrib, getAttrib).
// R_NamesSymbol (required at the call site) is also provided by SEXP.h.
// =============================================================
#pragma once

#ifndef FAKE_R_SETATTRIB_H
#define FAKE_R_SETATTRIB_H

// --- Fake R header dependencies ---
//
// SEXP.h provides:
//   - Rf_setAttrib / setAttrib (no-op) under FAKE_ATTRIB_DEFINED
//   - Rf_getAttrib / getAttrib (returns R_NilValue) under FAKE_ATTRIB_DEFINED
//   - R_NamesSymbol sentinel (static SYMSXP) for the call at rpart.c:329
//   - R_NilValue sentinel (returned by Rf_getAttrib)
//   - SEXPREC struct, SEXP typedef, all SEXPTYPE constants
#include "SEXP.h"

// --- Safety-net fallback: Rf_setAttrib / Rf_getAttrib ---
//
// Skipped when SEXP.h is already included (common case) because
// SEXP.h sets FAKE_ATTRIB_DEFINED.  Present for standalone use.
#ifndef FAKE_ATTRIB_DEFINED
#define FAKE_ATTRIB_DEFINED

inline void Rf_setAttrib(SEXP /*x*/, SEXP /*name*/, SEXP /*val*/) {}
inline SEXP Rf_getAttrib(SEXP /*x*/, SEXP /*name*/)               { return R_NilValue; }

// Short-form aliases: Rinternals.h lines 1048-1049.
// Provided as inline functions (not #define macros) for consistency with the
// pattern used throughout these fake headers.
inline void setAttrib(SEXP x, SEXP name, SEXP val) { Rf_setAttrib(x, name, val); }
inline SEXP getAttrib(SEXP x, SEXP name)           { return Rf_getAttrib(x, name); }

#endif // FAKE_ATTRIB_DEFINED

// --- Compatibility aliases (from Rinternals.h) ---
//
// Whether provided by SEXP.h or the fallback above, the following aliases
// are available:
//
//   Rinternals.h line 1048: #define setAttrib Rf_setAttrib
//   Rinternals.h line 1049: #define getAttrib Rf_getAttrib
//
// Provided as inline wrapper functions; no additional #define macros emitted.

// --- Design note ---
//
// The real setAttrib(rlist, R_NamesSymbol, rname) at rpart.c:329 protects
// rname by attaching it to rlist (which is PROTECT-ed at line 327).  In the
// fake runtime:
//   - PROTECT / UNPROTECT are no-ops (INTSXP.h).
//   - setAttrib is a no-op (does not store rname inside rlist).
//   - rname is not garbage-collected because the fake runtime has no GC;
//     Python is responsible for calling free_sexp(rname) after reading it.
//
// Python reads the named output fields via positional VECTOR_ELT(rlist, i)
// calls and independently traverses rname via STRING_ELT(rname, i).
// The absence of a stored attribute link between rlist and rname is not
// observable to Python as long as the caller keeps both pointers alive.

#endif // FAKE_R_SETATTRIB_H
