// =============================================================
// SEXP.h — Fake R API: SEXP
// Original R header: Rinternals.h
// Category: A — Type or Enum Constant
// Auto-generated by generate-r-extern-fake-header agent.
//
// SEXP is the foundational pointer type of R's C API, defined in
// Rinternals.h as:
//   typedef struct SEXPREC *SEXP;
// Every R object — integer vectors, real matrices, character strings,
// generic lists, language expressions, environments, and NULL — is
// represented at the C level as a SEXP, which is a pointer to a SEXPREC
// node managed by R's garbage collector (absent in the fake runtime).
//
// Observed usage roles in rpart source (all CSV rows):
//
//   P1: .Call entry-point parameter and return type
//       init.c:6-8, pred_rpart.c:133, rpart.c:40, rpart_callback.c:47,
//       rpartexp2.c:43, rpartproto.h:39, rpartproto.h:57, xpred.c:33
//
//   P2: Local SEXP variable for allocVector / allocMatrix result
//       pred_rpart.c:139, rpart.c:64, rpart.c:327-328, rpartexp2.c:47,
//       xpred.c:63
//
//   P3: Static module-level SEXP global for R interpreter objects
//       rpart_callback.c:33, rpart_callback.c:34, rpart_callback.c:35
//
//   P4: Local SEXP temporary for eval() result
//       rpart_callback.c:51, rpart_callback.c:92, rpart_callback.c:131
//
// Original R header: Rinternals.h
// Original declaration (inaccessible — permission denied on conda path):
//   typedef struct SEXPREC *SEXP;
//   (SEXPREC fields are opaque to package code when USE_RINTERNALS is not
//    defined; the fake defines a visible, minimal layout instead.)
//
// Integration Requirements (from SEXP.md Section 5):
//   - INTSXP.h      : SEXPTYPE block, SEXPREC, SEXP typedef, allocVector,
//                     allocMatrix, INTEGER/REAL/LOGICAL/RAW accessors,
//                     LENGTH, nrows/ncols, PROTECT/UNPROTECT, free_sexp,
//                     sexptype_element_size, RError — all provided there.
//   - Rboolean.h    : Rboolean (FALSE/TRUE) needed for compat_getVar in
//                     rpart_callback.c:20.  Included after INTSXP.h.
//   - fake_arena.h  : ArenaFrame RAII guard; used by .Call entry-point
//                     wrappers that mix SEXP allocations with R_alloc/ALLOC
//                     scratch arrays.  SEXP itself does not use the arena.
//
// Items added by this header (not present in INTSXP.h):
//   - XLENGTH / Rf_xlength
//   - TYPEOF inline
//   - isReal / isInteger / isNull / Rf_isReal / Rf_isInteger / Rf_isNull
//   - asInteger / asReal / asLogical / Rf_asInteger / Rf_asReal
//   - CHAR / R_CHAR (CHARSXP accessor)
//   - mkChar / Rf_mkChar (CHARSXP constructor)
//   - VECTOR_ELT / SET_VECTOR_ELT (VECSXP element access)
//   - STRING_ELT / SET_STRING_ELT (STRSXP element access)
//   - setAttrib / getAttrib (no-op stubs)
//   - R_NilValue singleton (NILSXP)
//   - R_UnboundValue sentinel (SYMSXP, for compat_getVar in rpart_callback.c)
//   - R_NamesSymbol sentinel (SYMSXP, for setAttrib in rpart.c)
//   - PRINTNAME (SYMSXP -> CHARSXP accessor, for rpart_callback.c:24)
//   - R_ProtectWithIndex / R_Reprotect no-ops
//   - free_sexp with recursive VECSXP/EXPRSXP child freeing
//   - .Call boundary wrapper pattern (ArenaFrame usage comment)
// =============================================================
#pragma once

#ifndef FAKE_SEXP_H
#define FAKE_SEXP_H

// --- Standard library includes ---
#include <stdlib.h>    // malloc, free, size_t
#include <string.h>    // memset, strlen, strcpy
#include <stddef.h>    // NULL, size_t
#include <stdarg.h>    // va_list, vsnprintf
#include <stdio.h>     // fprintf, stderr
#include <stdexcept>   // std::runtime_error
#include <string>      // std::string

// --- Fake R header dependencies ---
// (from Integration Requirements in SEXP.md)
//
// INTSXP.h provides: RError, SEXPTYPE constant block (all XxSXP macros),
// struct SEXPREC, typedef SEXP, sexptype_element_size, allocVector,
// allocMatrix, Rf_allocVector, Rf_allocMatrix, INTEGER, REAL, LOGICAL, RAW,
// Rf_INTEGER, Rf_REAL, Rf_LOGICAL, LENGTH, Rf_length, Rf_nrows, Rf_ncols,
// Rf_protect, Rf_unprotect, Rf_unprotect_ptr, free_sexp (basic form),
// PROTECT / UNPROTECT / UNPROTECT_PTR / PROTECT_WITH_INDEX / REPROTECT
// macros, nrows / ncols macro aliases, allocVector / allocMatrix aliases.
#include "INTSXP.h"

// Rboolean.h provides: typedef enum { FALSE = 0, TRUE = 1 } Rboolean;
// Required by rpart_callback.c:20:
//   static SEXP compat_getVar(SEXP sym, SEXP rho, Rboolean inherits)
// and by R_getVar(install("yback"), rho, FALSE) at lines 59–68.
#include "Rboolean.h"

// WARNING: dependency fake_arena.h not found in output_folder.
// ArenaFrame is required by the .Call-entry wrapper pattern shown at the
// bottom of this header.  Every rpart entry point (rpart, xpred, pred_rpart,
// rpartexp2, init_rpcallback) uses ALLOC / R_alloc scratch allocations in
// the same function body as SEXP allocations.  Once fake_arena.h is
// available, declare `ArenaFrame _frame;` as the first statement of every
// .Call-entry wrapper.  See the ArenaFrame usage block below.
//
// #include "fake_arena.h"

// ---------------------------------------------------------------------------
// XLENGTH / Rf_xlength — extended-length accessor.
//
// The real Rinternals.h uses R_xlen_t (ptrdiff_t in 64-bit builds) for
// lengths exceeding 2^31-1.  rpart uses only 32-bit lengths; the int form
// is sufficient.  XLENGTH is guarded in case INTSXP.h or a future header
// already defines it.
//
// Usage in rpart_callback.c line 115:
//   if (LENGTH(value) != (1 + rsave)) ...   (LENGTH is already in INTSXP.h)
// XLENGTH is provided for completeness matching the real Rinternals.h API.
// ---------------------------------------------------------------------------
#ifndef FAKE_XLENGTH_DEFINED
#define FAKE_XLENGTH_DEFINED

inline int Rf_xlength(SEXP s) { return s->length; }

/* XLENGTH — the real Rinternals.h maps this to a static inline that calls
   XLENGTH with the R_xlen_t return type.  In the fake, int is sufficient. */
#ifndef XLENGTH
#define XLENGTH(x) Rf_xlength(x)
#endif

#endif // FAKE_XLENGTH_DEFINED

// ---------------------------------------------------------------------------
// TYPEOF — returns the SEXPTYPE tag of a SEXP node.
//
// Usage pattern: rpart_callback.c uses isReal(value) (which checks the tag)
// rather than TYPEOF directly.  TYPEOF is provided for completeness and for
// any downstream header that constructs a switch on type tags.
// ---------------------------------------------------------------------------
#ifndef FAKE_TYPEOF_DEFINED
#define FAKE_TYPEOF_DEFINED

inline int TYPEOF(SEXP s) { return (int) s->type; }

#endif // FAKE_TYPEOF_DEFINED

// ---------------------------------------------------------------------------
// Scalar coercion — reads element [0] of the data buffer.
//
// asInteger(s): used in pred_rpart.c:138 (asInteger(dimx)),
//               rpartexp2.c:48 (asReal(eps)), rpart.c:77 (asInteger(xvals2)),
//               init_rpcallback at rpart_callback.c:54-55 (asInteger(ny),
//               asInteger(nr)).
// asReal(s):    used in rpartexp2.c:48 (asReal(eps)).
// asLogical(s): provided for completeness; not observed in rpart CSV subset.
//
// All three read the first element of the data buffer, cast to the target
// scalar type.  This matches the real R API for simple 1-element vectors.
// ---------------------------------------------------------------------------
#ifndef FAKE_ASINTEGER_DEFINED
#define FAKE_ASINTEGER_DEFINED

inline int    Rf_asInteger(SEXP s) { return ((int *)    s->data)[0]; }
inline double Rf_asReal(SEXP s)    { return ((double *) s->data)[0]; }
inline int    Rf_asLogical(SEXP s) { return ((int *)    s->data)[0]; }

/* The real Rinternals.h maps these names to Rf_asInteger etc. via #define.
   Provide both names as inline functions to avoid macro / inline conflicts. */
inline int    asInteger(SEXP s) { return Rf_asInteger(s); }
inline double asReal(SEXP s)    { return Rf_asReal(s);    }
inline int    asLogical(SEXP s) { return Rf_asLogical(s); }

#endif // FAKE_ASINTEGER_DEFINED

// ---------------------------------------------------------------------------
// CHAR / R_CHAR — return the char * stored in a CHARSXP node.
//
// Usage: rpart_callback.c:24
//   error(_("variable '%s' not found"), CHAR(PRINTNAME(sym)));
//
// The real Rinternals.h defines:
//   #define CHAR(x) R_CHAR(x)
//   const char *(R_CHAR)(SEXP x);
//
// In the fake, CHARSXP nodes are created by mkChar(); their data field
// holds a char * to a null-terminated string allocated via malloc.
// ---------------------------------------------------------------------------
#ifndef FAKE_CHAR_DEFINED
#define FAKE_CHAR_DEFINED

inline const char *R_CHAR(SEXP s) {
    return static_cast<const char *>(s->data);
}

/* Preserve the original Rinternals.h alias: #define CHAR(x) R_CHAR(x) */
#ifndef CHAR
#define CHAR(x) R_CHAR(x)
#endif

#endif // FAKE_CHAR_DEFINED

// ---------------------------------------------------------------------------
// mkChar / Rf_mkChar — create a CHARSXP from a null-terminated C string.
//
// Usage: rpart.c:331-344, one mkChar call per named slot of the output list:
//   SET_STRING_ELT(rname, 0, mkChar("which"));
//   SET_STRING_ELT(rname, 1, mkChar("cptable"));
//   ... (up to 7 slots)
//
// The CHARSXP node layout:
//   s->type   = CHARSXP (9)
//   s->length = strlen(str)
//   s->nrow   = strlen(str)
//   s->ncol   = 1
//   s->data   = malloc(strlen(str) + 1)   // null-terminated copy of str
//
// On allocation failure, RError is thrown (Invariant 1).
// The CHARSXP node is heap-allocated; Python-side cleanup must call
// free_sexp() on the STRSXP that holds it (which frees children).
// ---------------------------------------------------------------------------
#ifndef FAKE_MKCHAR_DEFINED
#define FAKE_MKCHAR_DEFINED

inline SEXP Rf_mkChar(const char *str) {
    size_t len = strlen(str);
    SEXPREC *s = (SEXPREC *) malloc(sizeof(SEXPREC));
    if (!s) throw RError("mkChar: out of memory allocating SEXPREC node");
    s->type   = CHARSXP;
    s->length = (int) len;
    s->nrow   = (int) len;
    s->ncol   = 1;
    s->data   = malloc(len + 1);
    if (!s->data) {
        free(s);
        throw RError("mkChar: out of memory allocating string buffer");
    }
    strcpy((char *) s->data, str);
    return s;
}

/* The real Rinternals.h maps mkChar -> Rf_mkChar via #define in many builds.
   Provide the short name as an inline to avoid double-expansion issues. */
inline SEXP mkChar(const char *str) { return Rf_mkChar(str); }

#endif // FAKE_MKCHAR_DEFINED

// ---------------------------------------------------------------------------
// VECSXP / STRSXP element accessors.
//
// VECTOR_ELT(x, i)       — read element i from a VECSXP (generic list).
// SET_VECTOR_ELT(x, i, v) — write element i; returns v (per real API).
// STRING_ELT(x, i)        — read element i from a STRSXP (string vector).
// SET_STRING_ELT(x, i, v) — write element i (no return value in real API).
//
// Usage: rpart.c:329-345
//   SEXP rlist = PROTECT(allocVector(VECSXP, nout));
//   SEXP rname = allocVector(STRSXP, nout);
//   setAttrib(rlist, R_NamesSymbol, rname);
//   SET_VECTOR_ELT(rlist, 0, which3);
//   SET_STRING_ELT(rname, 0, mkChar("which"));
//   ...
//
// For VECSXP and STRSXP, allocVector stores a SEXP[length] array in data.
// SEXP[i] is either a child SEXP (VECSXP) or a CHARSXP (STRSXP).
// After allocVector, all slots are zeroed (nullptr); they are populated by
// SET_VECTOR_ELT / SET_STRING_ELT before the list is returned.
//
// The real Rinternals.h (non-STRICT_R_HEADERS builds) defines these as
// static inline functions.  The fake uses the same pattern.
// ---------------------------------------------------------------------------
#ifndef FAKE_VECTORELT_DEFINED
#define FAKE_VECTORELT_DEFINED

inline SEXP VECTOR_ELT(SEXP s, int i) {
    return static_cast<SEXP *>(s->data)[i];
}

inline SEXP SET_VECTOR_ELT(SEXP s, int i, SEXP v) {
    static_cast<SEXP *>(s->data)[i] = v;
    return v;
}

inline SEXP STRING_ELT(SEXP s, int i) {
    return static_cast<SEXP *>(s->data)[i];
}

inline void SET_STRING_ELT(SEXP s, int i, SEXP v) {
    static_cast<SEXP *>(s->data)[i] = v;
}

#endif // FAKE_VECTORELT_DEFINED

// ---------------------------------------------------------------------------
// Type predicate helpers.
//
// isReal(s):    used in rpart_callback.c:113 (if (!isReal(value)) error(...))
//               and rpart_callback.c:147 (if (!isReal(goodness)) error(...))
// isInteger(s): provided for completeness.
// isNull(s):    provided for completeness (csplit3 == R_NilValue check paths).
//
// The real Rinternals.h declares these as:
//   int (Rf_isReal)(SEXP);
//   int (Rf_isInteger)(SEXP);
//   int (Rf_isNull)(SEXP);
// with #define aliases dropping the Rf_ prefix.
// ---------------------------------------------------------------------------
#ifndef FAKE_ISPREDICATES_DEFINED
#define FAKE_ISPREDICATES_DEFINED

inline int Rf_isReal(SEXP s)    { return s->type == REALSXP; }
inline int Rf_isInteger(SEXP s) { return s->type == INTSXP;  }
inline int Rf_isNull(SEXP s)    { return s->type == NILSXP;  }

/* Short-form aliases matching original Rinternals.h #define remapping. */
inline int isReal(SEXP s)    { return Rf_isReal(s);    }
inline int isInteger(SEXP s) { return Rf_isInteger(s); }
inline int isNull(SEXP s)    { return Rf_isNull(s);    }

#endif // FAKE_ISPREDICATES_DEFINED

// ---------------------------------------------------------------------------
// R_NilValue — the NULL singleton (NILSXP).
//
// Usage: rpart.c:64
//   SEXP which3, ..., csplit3 = R_NilValue, ...;
// Usage: rpart_callback.c:71
//   return R_NilValue;
// Usage: rpart.c:329 (via setAttrib / getAttrib stubs that return it)
//
// The real Rinternals.h declares:
//   LibExtern SEXP R_NilValue;
// (a single instance in libR.so).
//
// Fake strategy: a static SEXPREC with type=NILSXP, length=0, data=NULL.
// The make_nil_value() factory guarantees a single address per translation
// unit.  Because the static local is zero-initialized before first use,
// this is safe across all include orders.
//
// NOTE: INTSXP.h does not define R_NilValue; this is the sole definition.
// The FAKE_R_NILVALUE_DEFINED guard prevents redefinition if a future
// header or master fake_R.h also defines it.
// ---------------------------------------------------------------------------
#ifndef FAKE_R_NILVALUE_DEFINED
#define FAKE_R_NILVALUE_DEFINED

inline SEXP make_nil_value() {
    static SEXPREC nil_rec = { NILSXP, 0, 0, 0, NULL };
    return &nil_rec;
}

/* R_NilValue is a static file-scope SEXP; every translation unit that
   includes this header gets a pointer to the same singleton address
   (because the static local in make_nil_value() is initialized once). */
static SEXP R_NilValue = make_nil_value();

#endif // FAKE_R_NILVALUE_DEFINED

// ---------------------------------------------------------------------------
// R_UnboundValue — the "not found" sentinel (SYMSXP).
//
// Usage: rpart_callback.c:23 (inside compat_getVar, compiled when
//   R_VERSION < R_Version(4, 5, 0)):
//   if (val == R_UnboundValue)
//       error(_("variable '%s' not found"), CHAR(PRINTNAME(sym)));
//
// The real Rinternals.h declares:
//   LibExtern SEXP R_UnboundValue;
//
// Fake strategy: a static SEXPREC with type=SYMSXP, distinct address from
// R_NilValue, data=NULL (no print name; PRINTNAME on this sentinel returns
// the sentinel itself, which R_CHAR returns as an empty string rather than
// crashing).
// ---------------------------------------------------------------------------
#ifndef FAKE_R_UNBOUNDVALUE_DEFINED
#define FAKE_R_UNBOUNDVALUE_DEFINED

inline SEXP make_unbound_value() {
    static SEXPREC unbound_rec = { SYMSXP, 0, 0, 0, NULL };
    return &unbound_rec;
}

static SEXP R_UnboundValue = make_unbound_value();

#endif // FAKE_R_UNBOUNDVALUE_DEFINED

// ---------------------------------------------------------------------------
// R_NamesSymbol — the "names" attribute symbol (SYMSXP).
//
// Usage: rpart.c:329
//   setAttrib(rlist, R_NamesSymbol, rname);
//
// The real Rinternals.h declares:
//   LibExtern SEXP R_NamesSymbol;
//
// Fake strategy: a static SEXPREC with type=SYMSXP.  Its specific address is
// irrelevant because setAttrib is a no-op in the fake runtime; rlist slots
// are read by position (VECTOR_ELT), not by name lookup, on the Python side.
// ---------------------------------------------------------------------------
#ifndef FAKE_R_NAMESSYMBOL_DEFINED
#define FAKE_R_NAMESSYMBOL_DEFINED

inline SEXP make_names_symbol() {
    static SEXPREC names_sym = { SYMSXP, 0, 0, 0, NULL };
    return &names_sym;
}

static SEXP R_NamesSymbol = make_names_symbol();

#endif // FAKE_R_NAMESSYMBOL_DEFINED

// ---------------------------------------------------------------------------
// PRINTNAME — returns the name SEXP (CHARSXP) for a SYMSXP.
//
// Usage: rpart_callback.c:24
//   error(_("variable '%s' not found"), CHAR(PRINTNAME(sym)));
//
// The real Rinternals.h (USE_RINTERNALS branch) accesses the symsxp.pname
// field.  In the fake, a symbol created by install() stores a CHARSXP* in
// its data field (see the 'install' fake guide).  For correctly constructed
// fake symbols, PRINTNAME(s) returns that CHARSXP*.
//
// Safety fallback: if data is NULL (e.g., for R_UnboundValue), return s
// itself.  R_CHAR on a SYMSXP with data=NULL returns "" (casting NULL to
// const char * and printing it is undefined, but R_CHAR is only called in
// the error path, so the message may be garbled — acceptable for a fatal
// diagnostic).  To avoid UB, the fallback returns R_NilValue (NILSXP,
// data=NULL).  R_CHAR on NILSXP would still be NULL; callers should treat
// the error path as best-effort only.
// ---------------------------------------------------------------------------
#ifndef FAKE_PRINTNAME_DEFINED
#define FAKE_PRINTNAME_DEFINED

inline SEXP PRINTNAME(SEXP s) {
    if (s && s->type == SYMSXP && s->data)
        return static_cast<SEXP>(s->data);
    return R_NilValue;
}

#endif // FAKE_PRINTNAME_DEFINED

// ---------------------------------------------------------------------------
// setAttrib / getAttrib — attribute manipulation stubs.
//
// Usage: rpart.c:329
//   setAttrib(rlist, R_NamesSymbol, rname);
//
// In the real R API, setAttrib(x, R_NamesSymbol, val) attaches val as the
// "names" attribute of x.  Python reads named output by position
// (VECTOR_ELT(rlist, i)), not by name lookup, so the attribute is
// irrelevant at runtime.  Both functions are no-ops.
//
// The real Rinternals.h declares:
//   void Rf_setAttrib(SEXP, SEXP, SEXP);
//   SEXP Rf_getAttrib(SEXP, SEXP);
// with #define aliases setAttrib -> Rf_setAttrib etc.
// ---------------------------------------------------------------------------
#ifndef FAKE_ATTRIB_DEFINED
#define FAKE_ATTRIB_DEFINED

inline void Rf_setAttrib(SEXP /*x*/, SEXP /*name*/, SEXP /*val*/) {}
inline SEXP Rf_getAttrib(SEXP /*x*/, SEXP /*name*/)               { return R_NilValue; }

/* Preserve the original Rinternals.h alias block. */
inline void setAttrib(SEXP x, SEXP name, SEXP val) { Rf_setAttrib(x, name, val); }
inline SEXP getAttrib(SEXP x, SEXP name)           { return Rf_getAttrib(x, name); }

#endif // FAKE_ATTRIB_DEFINED

// ---------------------------------------------------------------------------
// R_ProtectWithIndex / R_Reprotect — additional PROTECT-family stubs.
//
// The real Rinternals.h defines:
//   #define PROTECT_WITH_INDEX(x,i) R_ProtectWithIndex(x,i)
//   #define REPROTECT(x,i)          R_Reprotect(x,i)
//
// INTSXP.h already provides these macros (mapped to Rf_protect no-ops).
// The underlying functions are added here for completeness and in case a
// source file calls them by their canonical Rf_* / R_* name directly.
// ---------------------------------------------------------------------------
#ifndef FAKE_R_PROTECTWITHINDEX_DEFINED
#define FAKE_R_PROTECTWITHINDEX_DEFINED

inline void R_ProtectWithIndex(SEXP /*s*/, int * /*i*/) {}
inline void R_Reprotect(SEXP /*s*/, int /*i*/)          {}

#endif // FAKE_R_PROTECTWITHINDEX_DEFINED

// ---------------------------------------------------------------------------
// free_sexp — extended version with recursive VECSXP/EXPRSXP child freeing.
//
// INTSXP.h defines a basic free_sexp(SEXP) under FAKE_FREE_SEXP_DEFINED that
// frees s->data and s without recursing into children.  That is sufficient
// for the INTSXP/REALSXP cases handled there.
//
// SEXP.h replaces that definition (if the INTSXP.h version has not yet been
// used in a way that would cause a conflict) or provides a companion named
// free_sexp_deep() for VECSXP / STRSXP trees returned from rpart().
//
// Pattern: rpart.c:327-349 builds:
//   VECSXP rlist[nout]  — contains child SEXPs: which3, cptable3, ...
//   STRSXP rname[nout]  — contains CHARSXP children created by mkChar().
// Python extracts element data via VECTOR_ELT / REAL / INTEGER, then must
// free the entire tree.  free_sexp_deep() handles the recursive case.
//
// For VECSXP / EXPRSXP: data holds SEXP[length]; recurse into each child.
// For STRSXP: data holds SEXP[length] (each is a CHARSXP); recurse.
// For all others (INTSXP, REALSXP, etc.): free data buffer + node directly.
// For NILSXP: no-op (R_NilValue is a static sentinel; must not be freed).
// ---------------------------------------------------------------------------
#ifndef FAKE_FREE_SEXP_DEEP_DEFINED
#define FAKE_FREE_SEXP_DEEP_DEFINED

inline void free_sexp_deep(SEXP s) {
    if (!s) return;
    // Never free static singletons.
    if (s == R_NilValue || s == R_UnboundValue || s == R_NamesSymbol) return;
    if (s->type == VECSXP || s->type == EXPRSXP || s->type == STRSXP) {
        SEXP *children = static_cast<SEXP *>(s->data);
        for (int i = 0; i < s->length; i++) {
            if (children[i] && children[i] != R_NilValue)
                free_sexp_deep(children[i]);
        }
    }
    free(s->data);
    free(s);
}

// Redefine free_sexp to the recursive form.
// If INTSXP.h's basic free_sexp is already defined (FAKE_FREE_SEXP_DEFINED),
// we cannot redefine the inline function, but we can redirect the macro.
// Since INTSXP.h defines free_sexp as an inline (not a macro), the redirection
// below shadows it within any translation unit that includes SEXP.h after
// INTSXP.h.  Both the shallow and deep forms remain available by their explicit
// names.  Callers that need deep freeing (returning VECSXP from rpart()) must
// call free_sexp_deep() explicitly on the top-level SEXP, or use the macro
// redirect below.
//
// Note: the #undef + #define approach is used here rather than re-declaring
// the inline, which would cause a redefinition error in C++.
#undef free_sexp
#define free_sexp(s) free_sexp_deep(s)

#endif // FAKE_FREE_SEXP_DEEP_DEFINED

// ---------------------------------------------------------------------------
// --- Compatibility aliases (preserve original R API names) ---
//
// The real Rinternals.h defines these aliases for the items added in this
// header.  Aliases already provided by INTSXP.h (PROTECT, UNPROTECT, etc.)
// are not repeated here.
// ---------------------------------------------------------------------------

// CHAR / R_CHAR — already in FAKE_CHAR_DEFINED block above.
// #define CHAR(x)  R_CHAR(x)    (already emitted above)

// NA_STRING — the R missing string sentinel.
// The real Rinternals.h declares: LibExtern SEXP R_NaString;
// In the fake runtime, NA_STRING is needed only if source code tests for it;
// rpart does not test for NA strings in the CSV usage set.  Provide a safe
// static stub.
#ifndef FAKE_NA_STRING_DEFINED
#define FAKE_NA_STRING_DEFINED

inline SEXP make_na_string() {
    static SEXPREC na_str_rec = { CHARSXP, 2, 2, 1, (void *) "NA" };
    return &na_str_rec;
}

static SEXP R_NaString = make_na_string();

/* Original Rinternals.h alias: #define NA_STRING R_NaString */
#ifndef NA_STRING
#define NA_STRING R_NaString
#endif

#endif // FAKE_NA_STRING_DEFINED

// XLENGTH macro already emitted in FAKE_XLENGTH_DEFINED block above.
// nrows / ncols macros already emitted by INTSXP.h.
// asInteger / asReal / asLogical — both inline and Rf_ forms above.
// setAttrib / getAttrib — short names as inline functions above (not macros,
// so they work with any argument types without macro expansion issues).

// --- Compatibility aliases (preserve original R API names) ---
// Original Rinternals.h aliases reproduced here for completeness:
//
//   #define PROTECT(s)              Rf_protect(s)          -- in INTSXP.h
//   #define UNPROTECT(n)            Rf_unprotect(n)        -- in INTSXP.h
//   #define UNPROTECT_PTR(s)        Rf_unprotect_ptr(s)   -- in INTSXP.h
//   #define PROTECT_WITH_INDEX(x,i) R_ProtectWithIndex(x,i) -- in INTSXP.h
//   #define REPROTECT(x,i)          R_Reprotect(x,i)      -- in INTSXP.h
//   #define CHAR(x)                 R_CHAR(x)             -- above
//   #define NA_STRING               R_NaString            -- above
//   #define nrows(x)                Rf_nrows(x)           -- in INTSXP.h
//   #define ncols(x)                Rf_ncols(x)           -- in INTSXP.h

// ---------------------------------------------------------------------------
// --- ArenaFrame usage ---
//
// Every .Call-entry wrapper that calls rpart, xpred, pred_rpart, rpartexp2,
// or init_rpcallback must declare `ArenaFrame _frame;` as its first statement.
// These functions mix SEXP allocations (heap, not arena) with ALLOC / R_alloc
// scratch allocations (arena, freed at frame exit).
//
// Example wrapper (pred_rpart as representative):
//
//   #include "fake_arena.h"
//   extern "C" SEXP pred_rpart_entry(
//           SEXP dimx, SEXP nnode, SEXP nsplit, SEXP dimc,
//           SEXP nnum, SEXP nodes2, SEXP vnum, SEXP split2,
//           SEXP csplit2, SEXP usesur, SEXP xdata2, SEXP xmiss2) {
//       ArenaFrame _frame;   // frees all R_alloc/ALLOC scratch on exit
//       try {
//           return pred_rpart(dimx, nnode, nsplit, dimc, nnum, nodes2,
//                             vnum, split2, csplit2, usesur, xdata2, xmiss2);
//       } catch (const RError &e) {
//           // store e.what() for Python, then return sentinel
//           return R_NilValue;
//       }
//   }
//
// SEXP return values (where, rlist, predict2, keep) are heap-allocated via
// malloc() inside allocVector / allocMatrix and survive ArenaFrame
// destruction.  Python extracts data and calls free_sexp() (or
// free_sexp_deep() for VECSXP trees) after copying data into numpy arrays.
//
// Static SEXP globals (expr1, expr2, rho in rpart_callback.c) are set by
// init_rpcallback() and consumed by eval() / findVar() stubs (Category E
// items; see the 'eval', 'findVar', and 'install' fake guides).  The SEXP
// type definition here enables compilation; the interpreter paths require
// function-pointer bridges registered from Python before calling rpart()
// with method=4 (user-defined splits).
// ---------------------------------------------------------------------------

#endif // FAKE_SEXP_H
