// =============================================================
// TRUE.h — Fake R API: TRUE
// Original R header: R_ext/Boolean.h
// Category: A — Type or Enum Constant (enumerator of Rboolean)
// Auto-generated by generate-r-extern-fake-header agent.
//
// NOTE: The original R header at
//   ~/.conda/envs/r-to-python/lib/R/include/R_ext/Boolean.h
// could not be found at that path. The definition below is
// reproduced from the authoritative Markdown guide (TRUE.md).
//
// `TRUE` is enumerator `1` of the `Rboolean` typedef enum defined in
// R_ext/Boolean.h.  Its integer value is 1.  The real R header issues
// `#undef TRUE` before the enum declaration so that any prior macro
// definition (e.g., from <stdbool.h> or <cstdbool>) is replaced by
// the enumerator.  TRUE is NOT a macro in the compiled program; it is
// a named constant of type Rboolean.
//
// Observed usage in rpart source:
//
//   init.c:28
//     R_forceSymbols(dll, TRUE);
//       -- second argument type: Rboolean
//          (no-op in the fake build; TRUE must be integer-compatible
//           and the call is guarded by:
//             #if defined(R_VERSION) && R_VERSION >= R_Version(2, 16, 0)
//           which is satisfied by R_VERSION.h defining R_VERSION = 4.4.0)
//
// Implementation strategy (TRUE.md Section 3):
//   TRUE is produced as a side effect of the Rboolean enum declaration.
//   This guide does not introduce a new enum; it delegates entirely to
//   Rboolean.h (already present in the output folder), which issues
//   `#undef FALSE`, `#undef TRUE`, and then:
//     typedef enum { FALSE = 0, TRUE = 1 } Rboolean;
//   Including Rboolean.h is therefore sufficient to make TRUE visible
//   as an integer-compatible constant of type Rboolean, satisfying the
//   R_forceSymbols(dll, TRUE) call site in init.c.
//
// Integration Requirements satisfied here (TRUE.md Section 5):
//   - Rboolean.h : present in output folder — provides the enum definition
//                  that places TRUE = 1 in enclosing (file/global) scope.
//   - FALSE.h    : present in output folder — establishes that FALSE and TRUE
//                  share the same enum and must not be split across separate
//                  definitions. Rboolean.h (included here) covers both.
//   - DllInfo.h  : provides DllInfo typedef and the R_forceSymbols no-op stub
//                  that consumes TRUE; included by fake_R.h, not here.
//   - DL_FUNC.h, R_CallMethodDef.h : required by the CallEntries table in
//                  init.c (same translation unit), NOT by TRUE itself.
//   - R_VERSION.h : present in output folder — defines R_VERSION = 4.4.0,
//                  which satisfies the #if guard at init.c:27 that controls
//                  whether the R_forceSymbols(dll, TRUE) call is compiled.
//                  R_VERSION.h is included by fake_R.h, not here.
//   - SEXP.h / INTSXP.h / REALSXP.h : required by rpart.h (included by
//                  init.c), NOT by TRUE itself.
//   - fake_arena.h : required at .Call entry points in the same build,
//                  NOT by TRUE itself.
// =============================================================
#pragma once

#ifndef FAKE_R_TRUE_H
#define FAKE_R_TRUE_H

// --- Standard library includes ---
// None required: TRUE is a plain enum enumerator with no runtime
// dependencies.

// --- Fake R header dependencies ---
// (from Integration Requirements in TRUE.md Section 5)
//
// Rboolean.h is the sole dependency: it declares
//   typedef enum { FALSE = 0, TRUE = 1 } Rboolean;
// after issuing #undef FALSE / #undef TRUE.  Including it here
// makes the enumerator TRUE available to every translation unit
// that includes TRUE.h (or fake_R.h, which includes this file).
#include "Rboolean.h"

// --- Core fake implementation ---
//
// Pattern: No-op Registration Argument (init.c:28)
// -------------------------------------------------------
// R_forceSymbols(dll, TRUE) passes TRUE as the second argument
// of type Rboolean.  In the standalone fake build R_forceSymbols
// is a no-op inline function (provided by DllInfo.h).  TRUE needs
// only to exist as an integer-compatible constant of type Rboolean
// — satisfied by the Rboolean enum from Rboolean.h included above.
// No additional definition is required here.
//
// The call site is guarded at the preprocessor level by:
//
//   #if defined(R_VERSION) && R_VERSION >= R_Version(2, 16, 0)
//       R_forceSymbols(dll, TRUE);
//   #endif
//
// R_VERSION.h (present in the output folder) defines:
//   #define R_VERSION  R_Version(4, 4, 0)   // = 263168
// which satisfies R_VERSION >= R_Version(2, 16, 0) (= 131584), so
// the compiler does see this line and TRUE must be a valid expression
// of type Rboolean.  The Rboolean enum from Rboolean.h satisfies that
// requirement fully.
//
// Usage pattern summary:
//   - TRUE is enumerator 1 of Rboolean.
//   - It is passed to R_forceSymbols, a no-op stub; no arithmetic or
//     comparison is performed on it at the call site.
//   - No allocation, error, warning, or interpreter interaction occurs.
//
// Invariant applicability:
//   - Invariant 1 (C++ exception-based errors): not triggered by TRUE itself.
//   - Invariant 2 (arena memory): not triggered; TRUE is a scalar constant.
//   - Invariant 3 (R Interpreter Items): not triggered by TRUE itself.
//     R_forceSymbols is a no-op registration function, not an R interpreter
//     item; TRUE requires no Python callback registration.

// --- Compatibility aliases (preserve original R API names) ---
//
// R_ext/Boolean.h introduces no #define aliases for TRUE.  The only
// preprocessor directive the original header uses for TRUE is `#undef TRUE`
// before the enum declaration — that #undef is already issued inside
// Rboolean.h (included above).  After the enum declaration, TRUE is an
// enumerator, not a macro.  No additional #define wrapper is required
// or present in the original header.

#endif // FAKE_R_TRUE_H
